-- VER 0.4 TRACKER NO:817 COMMENT #35 STARTDATE:07/05/2014 ENDDATE:07/05/2014 DESC: CHANGED TEMP TABLE FOR DYNAMIC PURPOSE DONE BY:RAJA 
-- VER 0.2 ISSUE NO:595 COMMENT #34 STARTDATE:13/01/2014 ENDDATE:13/01/2014 DESC:SP FOR SP CHARTS STAFF EXPENSE, INCREASED COLUMN PRECISION OF TEMP TABLE. DONE BY:MANIKANDAN.S
-- VER 0.3 ISSUE NO:595 COMMENT # STARTDATE:24/01/2014 ENDDATE:24/01/2014 DESC:CALLED SUB PROCEDURE FOR DATE CALCULATION. DONE BY:MANIKANDAN.S
DROP PROCEDURE IF EXISTS SP_CHARTS_STAFF_EXPENSE;
CREATE PROCEDURE SP_CHARTS_STAFF_EXPENSE(IN FROM_DATE VARCHAR(20), IN TO_DATE VARCHAR(20),IN USERSTAMP VARCHAR(50), OUT TEMP_CHARTS_STAFF_EXPENSE TEXT)
BEGIN
DECLARE FINAL_FROM_DATE VARCHAR(20);
DECLARE FINAL_TO_DATE VARCHAR(20);

DECLARE USERSTAMP_ID INT;
DECLARE CHARTS_STAFF_EXPENSE TEXT;
DECLARE INTERMEDIATE_CHARTS_STAFF_TMPTBL TEXT;
DECLARE INTERMEDIATE_CHARTS_STAFF TEXT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
 ROLLBACK;
END;     
  
  -- Format the input date into proper date format.
  CALL SP_FORMAT_DATE(FROM_DATE,TO_DATE,@fd,@td);
  SELECT @fd INTO FINAL_FROM_DATE;
  SELECT @td INTO FINAL_TO_DATE;
 
  --  TEMP TABLE NAME START
  CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
  SET USERSTAMP_ID=(SELECT @ULDID);
  SET CHARTS_STAFF_EXPENSE=(SELECT CONCAT('TEMP_CHARTS_STAFF_EXPENSE',SYSDATE()));
  --  TEMP TABLE NAME
  SET CHARTS_STAFF_EXPENSE=(SELECT REPLACE(CHARTS_STAFF_EXPENSE,' ',''));
  SET CHARTS_STAFF_EXPENSE=(SELECT REPLACE(CHARTS_STAFF_EXPENSE,'-',''));
  SET CHARTS_STAFF_EXPENSE=(SELECT REPLACE(CHARTS_STAFF_EXPENSE,':',''));
  SET TEMP_CHARTS_STAFF_EXPENSE=(SELECT CONCAT(CHARTS_STAFF_EXPENSE,'_',USERSTAMP_ID));   
 
  -- CREATING MAIN TEMP TABLE FOR FINAL OUTPUT
  -- DROP TABLE IF EXISTS TEMP_CHARTS_STAFF_EXPENSE;
  SET @CREATE_TEMP_CHARTS_STAFF_EXPENSE=(SELECT CONCAT('CREATE TABLE ',TEMP_CHARTS_STAFF_EXPENSE,' (MONTH_YEAR VARCHAR(20),AGENT_COMMISSION DECIMAL(20, 2),SALARY_ENTRY DECIMAL(20, 2),STAFF_EXPENSE DECIMAL(20, 2))'));
  PREPARE CREATE_TEMP_CHARTS_STAFF_EXPENSE_STMT FROM @CREATE_TEMP_CHARTS_STAFF_EXPENSE;
  EXECUTE CREATE_TEMP_CHARTS_STAFF_EXPENSE_STMT;
  
  --  TEMP TABLE NAME START
    SET INTERMEDIATE_CHARTS_STAFF=(SELECT CONCAT('INTERMEDIATE_CHARTS_STAFF_TMPTBL',SYSDATE()));
  --  TEMP TABLE NAME
  SET INTERMEDIATE_CHARTS_STAFF=(SELECT REPLACE(INTERMEDIATE_CHARTS_STAFF,' ',''));
  SET INTERMEDIATE_CHARTS_STAFF=(SELECT REPLACE(INTERMEDIATE_CHARTS_STAFF,'-',''));
  SET INTERMEDIATE_CHARTS_STAFF=(SELECT REPLACE(INTERMEDIATE_CHARTS_STAFF,':',''));
  SET INTERMEDIATE_CHARTS_STAFF_TMPTBL=(SELECT CONCAT(INTERMEDIATE_CHARTS_STAFF,'_',USERSTAMP_ID));   
 
  -- CREATING INTERMEDIATE TEMP TABLE
  -- DROP TABLE IF EXISTS TEMP_INTERMEDIATE_CHARTS_STAFF;
  SET @CREATE_INTERMEDIATE_CHARTS_STAFF_TMPTBL=(SELECT CONCAT('CREATE TABLE ',INTERMEDIATE_CHARTS_STAFF_TMPTBL,' (MONTH_YEAR VARCHAR(20),AGENT_COMMISSION DECIMAL(7, 2),SALARY_ENTRY DECIMAL(7, 2),STAFF_EXPENSE DECIMAL(7, 2), DATE DATE)'));
  PREPARE CREATE_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT FROM @CREATE_INTERMEDIATE_CHARTS_STAFF_TMPTBL;
  EXECUTE CREATE_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT;
  
  SET @INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_CHARTS_STAFF_TMPTBL,' (MONTH_YEAR, AGENT_COMMISSION, DATE) SELECT DATE_FORMAT(EA_DATE,"%M-%Y"),EA_COMM_AMOUNT, EA_DATE FROM EXPENSE_AGENT WHERE EA_DATE BETWEEN ','"',FINAL_FROM_DATE,'"',' AND ','"',FINAL_TO_DATE,'"',''));
  PREPARE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT FROM @INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL;
  EXECUTE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT;

  SET @INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_CHARTS_STAFF_TMPTBL,' (MONTH_YEAR, SALARY_ENTRY, DATE) SELECT DATE_FORMAT(ESS_INVOICE_DATE,"%M-%Y"),ESS_SALARY_AMOUNT, ESS_INVOICE_DATE FROM EXPENSE_STAFF_SALARY WHERE ESS_INVOICE_DATE BETWEEN ','"',FINAL_FROM_DATE,'"',' AND ','"',FINAL_TO_DATE,'"',''));
  PREPARE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT FROM @INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL;
  EXECUTE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT;

  SET @INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_CHARTS_STAFF_TMPTBL,' (MONTH_YEAR, STAFF_EXPENSE, DATE) SELECT DATE_FORMAT(ES_INVOICE_DATE,"%M-%Y"),ES_INVOICE_AMOUNT, ES_INVOICE_DATE FROM EXPENSE_STAFF WHERE ES_INVOICE_DATE BETWEEN ','"',FINAL_FROM_DATE,'"',' AND ','"',FINAL_TO_DATE,'"',''));  
  PREPARE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT FROM @INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL;
  EXECUTE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT;   
      
  -- INSERTING INTO FINAL TEMP TABLE GROUPING BY MONTH AND YEAR
  SET @INSERT_TEMP_CHARTS_STAFF_EXPENSE=(SELECT CONCAT('INSERT INTO ',TEMP_CHARTS_STAFF_EXPENSE,' (MONTH_YEAR, AGENT_COMMISSION,SALARY_ENTRY, STAFF_EXPENSE) (SELECT MONTH_YEAR,SUM(COALESCE(AGENT_COMMISSION,"0")),SUM(COALESCE(SALARY_ENTRY,"0")), SUM(COALESCE(STAFF_EXPENSE,"0")) FROM ',INTERMEDIATE_CHARTS_STAFF_TMPTBL,' GROUP BY MONTH_YEAR ORDER BY DATE)'));
  PREPARE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT FROM @INSERT_TEMP_CHARTS_STAFF_EXPENSE;
  EXECUTE INSERT_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT;   
    
  SET@DROP_INTERMEDIATE_CHARTS_STAFF_TMPTBL=(SELECT CONCAT('DROP TABLE ',INTERMEDIATE_CHARTS_STAFF_TMPTBL));
  PREPARE DROP_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT FROM @DROP_INTERMEDIATE_CHARTS_STAFF_TMPTBL;
  EXECUTE DROP_INTERMEDIATE_CHARTS_STAFF_TMPTBL_STMT;
  
 COMMIT;
END;  
/* 
  CALL SP_CHARTS_STAFF_EXPENSE('January-2007' , 'January-2014','admin@expatsint.com',@TEMP_CHARTS_STAFF_EXPENSE);
  SELECT @TEMP_CHARTS_STAFF_EXPENSE;
  SELECT * FROM TEMP_CHARTS_STAFF_EXPENSE20140510175941_1;
*/