-- VER 0.2 TRACKER NO:817 COMMENT #35 STARTDATE:08/05/2014 ENDDATE:08/05/2014 DESC:CHANGE THE SP CHARTS GROSS REVENUE AND NET REVENUE FOR DYNAMIC PURPOSE. DONE BY:RAJA
-- VER 0.1 TRACKER NO:595 COMMENT # STARTDATE:27/01/2014 ENDDATE:27/01/2014 DESC:SP FOR CHARTS GROSS REVENUE AND NET REVENUE. DONE BY:MANIKANDAN.S
DROP PROCEDURE IF EXISTS SP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE;
CREATE PROCEDURE SP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE(IN FROM_DATE VARCHAR(20), IN TO_DATE VARCHAR(20),IN USERSTAMP VARCHAR(50),OUT TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE TEXT)
BEGIN
DECLARE FINAL_FROM_DATE VARCHAR(20);
DECLARE FINAL_TO_DATE VARCHAR(20);

DECLARE USERSTAMP_ID INT;
DECLARE CHARTS_GROSS_REVENUE_AND_NET_REVENUE TEXT;
DECLARE INTERMEDIATE_GROSS_AND_NET_REVENUE TEXT;
DECLARE INTERMEDIATE_GROSS_NET_REVENUE TEXT;

DECLARE CHARTS_GROSS_REVENUE TEXT;
DECLARE GET_UNIT_RENTAL TEXT;
DECLARE CHARTS_BIZ_EXPENSE TEXT;
DECLARE CHARTS_STAFF_EXPENSE TEXT;
DECLARE CHARTS_PERSONAL_EXPENSE TEXT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
 ROLLBACK;
END;     
  -- Format the input date into proper date format.
  CALL SP_FORMAT_DATE(FROM_DATE,TO_DATE,@fd,@td);
  SELECT @fd INTO FINAL_FROM_DATE;
  SELECT @td INTO FINAL_TO_DATE;
  
  -- GROSS REVENUE
  
  CALL SP_CHARTS_GROSS_REVENUE(FROM_DATE, TO_DATE,USERSTAMP,@CHARTS_GROSS_REVENUE_TMPTBL);
  SET CHARTS_GROSS_REVENUE=(SELECT @CHARTS_GROSS_REVENUE_TMPTBL);
  
  SET @VW_GROSS=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_CHARTS_GROSS_REVENUE AS SELECT MONTH_YEAR, GROSS_REVENUE FROM ',CHARTS_GROSS_REVENUE));
  PREPARE CREATE_VIEW_CHARTS_GROSS_REVENUE_STMT FROM @VW_GROSS;
  EXECUTE CREATE_VIEW_CHARTS_GROSS_REVENUE_STMT;
  
  -- UNIT RENTAL 
  
  CALL SP_GET_UNIT_RENTAL(FINAL_FROM_DATE, FINAL_TO_DATE,USERSTAMP,@TEMP_UNIT_RENTAL);
  SET GET_UNIT_RENTAL=(SELECT @TEMP_UNIT_RENTAL);
  
  SET @VW_UNIT=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_PERSONAL_UNIT_RENTAL AS SELECT MONTH_YEAR, UD_PAYMENT AS UNIT_RENTAL FROM ',GET_UNIT_RENTAL));
  PREPARE CREATE_VIEW_PERSONAL_UNIT_RENTAL_STMT FROM @VW_UNIT;
  EXECUTE CREATE_VIEW_PERSONAL_UNIT_RENTAL_STMT;
  
  -- GETTING TOTAL BIZ EXPENSE
  
  CALL SP_CHARTS_BIZ_EXPENSE(FROM_DATE , TO_DATE,USERSTAMP,@TEMP_MAIN_CHARTS_BIZ_EXPENSE);
  SET CHARTS_BIZ_EXPENSE=(SELECT @TEMP_MAIN_CHARTS_BIZ_EXPENSE);
  
  SET @VW_BIZ=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_CHARTS_TOTAL_BIZ_EXPENSE AS SELECT MONTH_YEAR, (ELECTRICITY + STARHUB + UNIT_EXPENSE) AS TOTAL_BIZ_EXP FROM ',CHARTS_BIZ_EXPENSE));  
  PREPARE CREATE_VIEW_CHARTS_TOTAL_BIZ_EXPENSE_STMT FROM @VW_BIZ;
  EXECUTE CREATE_VIEW_CHARTS_TOTAL_BIZ_EXPENSE_STMT;
   
  -- TOTAL STAFF EXPENSE
  
  CALL SP_CHARTS_STAFF_EXPENSE(FROM_DATE , TO_DATE,USERSTAMP,@TEMP_CHARTS_STAFF_EXPENSE );
  SET CHARTS_STAFF_EXPENSE=(SELECT @TEMP_CHARTS_STAFF_EXPENSE);
 
  SET @VW_STAFF=(SELECT CONCAT ('CREATE OR REPLACE VIEW VIEW_CHARTS_TOTAL_STAFF_EXPENSE AS SELECT MONTH_YEAR, (AGENT_COMMISSION + SALARY_ENTRY + STAFF_EXPENSE) AS TOTAL_STAFF_EXP FROM ',CHARTS_STAFF_EXPENSE));
  PREPARE CREATE_VIEW_CHARTS_TOTAL_STAFF_EXPENSE_STMT FROM @VW_STAFF;
  EXECUTE CREATE_VIEW_CHARTS_TOTAL_STAFF_EXPENSE_STMT;
   
  -- TOTAL PERSONAL EXPENSE
  
  CALL SP_CHARTS_PERSONAL_EXPENSE(FROM_DATE , TO_DATE,USERSTAMP,@CHARTS_PERSONAL_EXPENSE_TEMPTBL);
  SET CHARTS_PERSONAL_EXPENSE=(SELECT @CHARTS_PERSONAL_EXPENSE_TEMPTBL);
  
  SET @VW_PERSONAL=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_CHARTS_TOTAL_PERSONAL_EXPENSE AS SELECT MONTH_YEAR, (BABY_EXPENSES + CAR_EXPENSES + CAR_LOAN + PERSONAL_EXPENSES) AS TOTAL_PERSONAL_EXP FROM ',CHARTS_PERSONAL_EXPENSE));
  PREPARE CREATE_VIEW_CHARTS_TOTAL_PERSONAL_EXPENSE_STMT FROM @VW_PERSONAL;
  EXECUTE CREATE_VIEW_CHARTS_TOTAL_PERSONAL_EXPENSE_STMT;
   
    -- UNIT RENTAL + PERSONAL EXPENSE
    CREATE OR REPLACE VIEW VIEW_UNIT_RENTAL_PLUS_TOT_PER_EXP AS
    SELECT t1.MONTH_YEAR, (t1.UNIT_RENTAL + ifnull(t2.TOTAL_PERSONAL_EXP,0)) AS EXPENSE FROM VIEW_PERSONAL_UNIT_RENTAL t1
    LEFT JOIN VIEW_CHARTS_TOTAL_PERSONAL_EXPENSE t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR
    UNION
    SELECT t2.MONTH_YEAR, (ifnull(t1.UNIT_RENTAL,0)+t2.TOTAL_PERSONAL_EXP) AS EXPENSE FROM VIEW_PERSONAL_UNIT_RENTAL t1
    RIGHT JOIN VIEW_CHARTS_TOTAL_PERSONAL_EXPENSE t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR;
    
    -- STAFF EXPENSE + BIZ EXPENSE
    CREATE OR REPLACE VIEW VIEW_STAFF_EXP_PLUS_TOT_BIZ_EXP AS
    SELECT t1.MONTH_YEAR, (t1.TOTAL_STAFF_EXP + ifnull(t2.TOTAL_BIZ_EXP,0)) AS EXPENSE FROM VIEW_CHARTS_TOTAL_STAFF_EXPENSE t1
    LEFT JOIN VIEW_CHARTS_TOTAL_BIZ_EXPENSE t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR
    UNION
    SELECT t2.MONTH_YEAR, (ifnull(t1.TOTAL_STAFF_EXP,0)+t2.TOTAL_BIZ_EXP) AS EXPENSE FROM VIEW_CHARTS_TOTAL_STAFF_EXPENSE t1
    RIGHT JOIN VIEW_CHARTS_TOTAL_BIZ_EXPENSE t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR;
    
    -- TOTAL RENTAL EXPENSE = ( UNIT RENTAL + PERSONAL EXPENSE   +   STAFF EXPENSE + BIZ EXPENSE )
    CREATE OR REPLACE VIEW VIEW_TOTAL_RENTAL_EXPENSE AS
    SELECT t1.MONTH_YEAR, (t1.EXPENSE + ifnull(t2.EXPENSE,0)) AS EXPENSE FROM VIEW_UNIT_RENTAL_PLUS_TOT_PER_EXP t1
    LEFT JOIN VIEW_STAFF_EXP_PLUS_TOT_BIZ_EXP t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR
    UNION
    SELECT t2.MONTH_YEAR, (ifnull(t1.EXPENSE,0)+t2.EXPENSE) AS EXPENSE FROM VIEW_UNIT_RENTAL_PLUS_TOT_PER_EXP t1
    RIGHT JOIN VIEW_STAFF_EXP_PLUS_TOT_BIZ_EXP t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR;
    
    -- NET REVENUE = GROSS REVENUE - TOTAL RENTAL EXPENSE
    CREATE OR REPLACE VIEW VIEW_NET_REVENUE AS
    SELECT t1.MONTH_YEAR, (t1.GROSS_REVENUE - ifnull(t2.EXPENSE,0)) AS NET_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE t1
    LEFT JOIN VIEW_TOTAL_RENTAL_EXPENSE t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR
    UNION
    SELECT t2.MONTH_YEAR, (ifnull(t1.GROSS_REVENUE,0) - t2.EXPENSE) AS NET_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE t1
    RIGHT JOIN VIEW_TOTAL_RENTAL_EXPENSE t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR;    
    
    --   TEMP TABLE NAME START
    CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
    SET USERSTAMP_ID=(SELECT @ULDID);
    SET INTERMEDIATE_GROSS_NET_REVENUE=(SELECT CONCAT('INTERMEDIATE_GROSS_AND_NET_REVENUE',SYSDATE()));
    --   TEMP TABLE NAME
    SET INTERMEDIATE_GROSS_NET_REVENUE=(SELECT REPLACE(INTERMEDIATE_GROSS_NET_REVENUE,' ',''));
    SET INTERMEDIATE_GROSS_NET_REVENUE =(SELECT REPLACE(INTERMEDIATE_GROSS_NET_REVENUE,'-',''));
    SET INTERMEDIATE_GROSS_NET_REVENUE =(SELECT REPLACE(INTERMEDIATE_GROSS_NET_REVENUE,':',''));
    SET INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT(INTERMEDIATE_GROSS_NET_REVENUE,'_',USERSTAMP_ID)); 
    
    -- DROP TABLE IF EXISTS TEMP_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    SET @CREATE_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('CREATE TABLE ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR VARCHAR(20), GROSS_REVENUE DECIMAL(20,2) DEFAULT 0,TOT_RENTAL_EXPENSE DECIMAL(20,2) DEFAULT 0,NET_REVENUE DECIMAL(20,2) DEFAULT 0, UNIT_RENTAL INT DEFAULT 0, TOT_BIZ_EXPENSE DECIMAL(20,2) DEFAULT 0, TOT_STAFF_EXPENSE DECIMAL(20,2) DEFAULT 0, TOT_PERSONAL_EXPENSE DECIMAL(20,2) DEFAULT 0, SORT_DATE DATE)'));
    PREPARE CREATE_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @CREATE_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE CREATE_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, GROSS_REVENUE, SORT_DATE) (SELECT MONTH_YEAR, GROSS_REVENUE, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_CHARTS_GROSS_REVENUE)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, TOT_RENTAL_EXPENSE, SORT_DATE) (SELECT MONTH_YEAR, EXPENSE, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_TOTAL_RENTAL_EXPENSE)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, NET_REVENUE, SORT_DATE) (SELECT MONTH_YEAR,NET_REVENUE, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_NET_REVENUE)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, UNIT_RENTAL, SORT_DATE) (SELECT MONTH_YEAR, UNIT_RENTAL, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_PERSONAL_UNIT_RENTAL)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, TOT_BIZ_EXPENSE, SORT_DATE) (SELECT MONTH_YEAR,TOTAL_BIZ_EXP, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_CHARTS_TOTAL_BIZ_EXPENSE)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, TOT_STAFF_EXPENSE, SORT_DATE) (SELECT MONTH_YEAR,TOTAL_STAFF_EXP, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_CHARTS_TOTAL_STAFF_EXPENSE)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' (MONTH_YEAR, TOT_PERSONAL_EXPENSE, SORT_DATE) (SELECT MONTH_YEAR,TOTAL_PERSONAL_EXP, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_CHARTS_TOTAL_PERSONAL_EXPENSE)'));
    PREPARE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE INSERT_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
    SET CHARTS_GROSS_REVENUE_AND_NET_REVENUE=(SELECT CONCAT('TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE',SYSDATE()));
    --   TEMP TABLE NAME
    SET CHARTS_GROSS_REVENUE_AND_NET_REVENUE=(SELECT REPLACE(CHARTS_GROSS_REVENUE_AND_NET_REVENUE,' ',''));
    SET CHARTS_GROSS_REVENUE_AND_NET_REVENUE =(SELECT REPLACE(CHARTS_GROSS_REVENUE_AND_NET_REVENUE,'-',''));
    SET CHARTS_GROSS_REVENUE_AND_NET_REVENUE =(SELECT REPLACE(CHARTS_GROSS_REVENUE_AND_NET_REVENUE,':',''));
    SET TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE=(SELECT CONCAT(CHARTS_GROSS_REVENUE_AND_NET_REVENUE,'_',USERSTAMP_ID)); 
        
    -- DROP TABLE IF EXISTS TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE;
    SET @CREATE_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE=(SELECT CONCAT('CREATE TABLE ',TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE,' (MONTH_YEAR VARCHAR(20), GROSS_REVENUE DECIMAL(30,2),TOT_RENTAL_EXPENSE DECIMAL(30,2),NET_REVENUE DECIMAL(30,2), UNIT_RENTAL INT, TOT_BIZ_EXPENSE DECIMAL(30,2), TOT_STAFF_EXPENSE DECIMAL(30,2), TOT_PERSONAL_EXPENSE DECIMAL(30,2))'));
    PREPARE CREATE_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE_STMT FROM @CREATE_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE;
    EXECUTE CREATE_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE_STMT;
    
    SET @INSERT_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE=(SELECT CONCAT('INSERT INTO ',TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE,' (MONTH_YEAR, GROSS_REVENUE, TOT_RENTAL_EXPENSE, NET_REVENUE, UNIT_RENTAL, TOT_BIZ_EXPENSE, TOT_STAFF_EXPENSE , TOT_PERSONAL_EXPENSE) (SELECT MONTH_YEAR, SUM(GROSS_REVENUE), SUM(TOT_RENTAL_EXPENSE),SUM(NET_REVENUE), SUM(UNIT_RENTAL), SUM(TOT_BIZ_EXPENSE), SUM(TOT_STAFF_EXPENSE) , SUM(TOT_PERSONAL_EXPENSE) FROM ',INTERMEDIATE_GROSS_AND_NET_REVENUE,' GROUP BY MONTH_YEAR ORDER BY SORT_DATE ASC)'));
    PREPARE INSERT_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE_STMT FROM @INSERT_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE;
    EXECUTE INSERT_TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE_STMT;
    
    -- DROP THE INTERMEDIATE_GROSS_AND_NET_REVENUE
    SET @DROP_INTERMEDIATE_GROSS_AND_NET_REVENUE=(SELECT CONCAT('DROP TABLE ',INTERMEDIATE_GROSS_AND_NET_REVENUE));
    PREPARE DROP_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT FROM @DROP_INTERMEDIATE_GROSS_AND_NET_REVENUE;
    EXECUTE DROP_INTERMEDIATE_GROSS_AND_NET_REVENUE_STMT;
    
 COMMIT;
END;  
/* 
  CALL SP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE('April-2013','January-2014','admin@expatsint.com',@TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE);
  SELECT @TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE;
  SELECT * FROM TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE20140510180346_1;  
*/