-- VER 0.2 TRACKER NO:817 COMMENT #35 STARTDATE:07/05/2014 ENDDATE:07/05/2014 DESC: CHANGED THE SP CHARTS UNIT GROSS AND NET REVENUE PERUNIT FOR DYNAMIC PURPOSE. DONE BY: RAJA
-- VER 0.1 TRACKER NO:595 COMMENT # STARTDATE:29/01/2014 ENDDATE:29/01/2014 DESC:SP FOR CHARTS UNIT GROSS AND NET REVENUE. DONE BY:MANIKANDAN.S
DROP PROCEDURE IF EXISTS SP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT;
CREATE PROCEDURE SP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT
(IN INPUT_UNIT_NO INT, 
IN FROM_DATE VARCHAR(20), 
IN TO_DATE VARCHAR(20),
IN USERSTAMP VARCHAR(50),
OUT TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT TEXT)
BEGIN
DECLARE FINAL_FROM_DATE VARCHAR(20);
DECLARE FINAL_TO_DATE VARCHAR(20);

DECLARE CHARTS_GROSS_REVENUE_PERUNIT TEXT;
DECLARE UNIT_RENTAL_PERUNIT TEXT;
DECLARE CHARTS_BIZ_EXPENSE_PERUNIT TEXT;

DECLARE USERSTAMP_ID INT;
DECLARE CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT TEXT;
DECLARE INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT TEXT;
DECLARE INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT TEXT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
 ROLLBACK;
END;
  -- Format the input date into proper date format.
  CALL SP_FORMAT_DATE(FROM_DATE,TO_DATE,@fd,@td);
  SELECT @fd INTO FINAL_FROM_DATE;
  SELECT @td INTO FINAL_TO_DATE;

  -- GROSS REVENUE PER UNIT

  CALL SP_CHARTS_GROSS_REVENUE_PERUNIT(INPUT_UNIT_NO, FROM_DATE, TO_DATE,USERSTAMP,@TEMP_CHARTS_GROSS_REVENUE_PERUNIT);
  SET CHARTS_GROSS_REVENUE_PERUNIT= (SELECT @TEMP_CHARTS_GROSS_REVENUE_PERUNIT);
  
  SET @VW_REVENUE=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_CHARTS_GROSS_REVENUE_PERUNIT AS SELECT MONTH_YEAR, GROSS_REVENUE FROM ',CHARTS_GROSS_REVENUE_PERUNIT));
  PREPARE CREATE_VIEW_CHARTS_GROSS_REVENUE_PERUNIT_STMT FROM @VW_REVENUE;
  EXECUTE CREATE_VIEW_CHARTS_GROSS_REVENUE_PERUNIT_STMT;
  
  -- UNIT RENTAL PER UNIT

  CALL SP_GET_UNIT_RENTAL_PERUNIT(INPUT_UNIT_NO, FINAL_FROM_DATE, FINAL_TO_DATE,USERSTAMP,@TEMP_UNIT_RENTAL_PERUNIT);
  SET UNIT_RENTAL_PERUNIT=(SELECT @TEMP_UNIT_RENTAL_PERUNIT);
  
  SET @VW_RENTAL=(SELECT CONCAT ('CREATE OR REPLACE VIEW VIEW_UNIT_RENTAL_PERUNIT AS SELECT MONTH_YEAR, UD_PAYMENT AS UNIT_RENTAL FROM ',UNIT_RENTAL_PERUNIT));
  PREPARE CREATE_VIEW_UNIT_RENTAL_PERUNIT_STMT FROM @VW_RENTAL;
  EXECUTE CREATE_VIEW_UNIT_RENTAL_PERUNIT_STMT;
  
  -- GETTING TOTAL BIZ EXPENSE PER UNIT

  CALL SP_CHARTS_BIZ_EXPENSE_PERUNIT(INPUT_UNIT_NO, FROM_DATE, TO_DATE,USERSTAMP,@MAIN_TEMPTBL_CHARTS_BIZ_EXPENSE_PERUNIT);
  SET CHARTS_BIZ_EXPENSE_PERUNIT=(SELECT @MAIN_TEMPTBL_CHARTS_BIZ_EXPENSE_PERUNIT);
  
  SET @VW_BIZ_EXPENSE=(SELECT CONCAT ('CREATE OR REPLACE VIEW VIEW_TOTAL_BIZ_EXPENSE_PERUNIT AS SELECT MONTH_YEAR, (ELECTRICITY + STARHUB + UNIT_EXPENSE) AS TOTAL_BIZ_EXP  FROM ',CHARTS_BIZ_EXPENSE_PERUNIT));
  PREPARE CREATE_VIEW_TOTAL_BIZ_EXPENSE_PERUNIT_STMT FROM @VW_BIZ_EXPENSE;
  EXECUTE CREATE_VIEW_TOTAL_BIZ_EXPENSE_PERUNIT_STMT;
  
    -- UNIT RENTAL + BIZ EXPENSE
    CREATE OR REPLACE VIEW VIEW_TOTAL_RENTAL_EXPENSE_PERUNIT AS
    SELECT t1.MONTH_YEAR, (t1.UNIT_RENTAL + ifnull(t2.TOTAL_BIZ_EXP,0)) AS EXPENSE FROM VIEW_UNIT_RENTAL_PERUNIT t1
    LEFT JOIN VIEW_TOTAL_BIZ_EXPENSE_PERUNIT t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR    
    UNION
    SELECT t2.MONTH_YEAR, (ifnull(t1.UNIT_RENTAL,0)+t2.TOTAL_BIZ_EXP) AS EXPENSE FROM VIEW_UNIT_RENTAL_PERUNIT t1
    RIGHT JOIN VIEW_TOTAL_BIZ_EXPENSE_PERUNIT t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR;

    -- NET REVENUE = GROSS REVENUE - TOTAL RENTAL EXPENSE
    CREATE OR REPLACE VIEW VIEW_NET_REVENUE_PERUNIT AS
    SELECT t1.MONTH_YEAR, (t1.GROSS_REVENUE - ifnull(t2.EXPENSE,0)) AS NET_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE_PERUNIT t1
    LEFT JOIN VIEW_TOTAL_RENTAL_EXPENSE_PERUNIT t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR
    UNION
    SELECT t2.MONTH_YEAR, (ifnull(t1.GROSS_REVENUE,0) - t2.EXPENSE) AS NET_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE_PERUNIT t1
    RIGHT JOIN VIEW_TOTAL_RENTAL_EXPENSE_PERUNIT t2 ON t1.MONTH_YEAR = t2.MONTH_YEAR;
    
    --   TEMP TABLE NAME START
    CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
    SET USERSTAMP_ID=(SELECT @ULDID);
    SET INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT CONCAT('INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT',SYSDATE()));
    --   TEMP TABLE NAME
    SET INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT REPLACE(INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,' ',''));
    SET INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT =(SELECT REPLACE(INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,'-',''));
    SET INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT =(SELECT REPLACE(INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,':',''));
    SET INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT(INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,'_',USERSTAMP_ID)); 

    -- DROP TABLE IF EXISTS TEMP_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
    SET @CREATE_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('CREATE TABLE ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' (MONTH_YEAR VARCHAR(20),GROSS_REVENUE DECIMAL(20,2) DEFAULT 0,TOT_RENTAL_EXPENSE DECIMAL(20,2) DEFAULT 0,NET_REVENUE DECIMAL(20,2) DEFAULT 0, UNIT_RENTAL INT DEFAULT 0, TOT_BIZ_EXPENSE DECIMAL(20,2) DEFAULT 0, SORT_DATE DATE)'));
    PREPARE CREATE_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @CREATE_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
		EXECUTE CREATE_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    SET @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' (MONTH_YEAR, GROSS_REVENUE, SORT_DATE) SELECT MONTH_YEAR, GROSS_REVENUE, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_CHARTS_GROSS_REVENUE_PERUNIT'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
    EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    SET @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' (MONTH_YEAR, TOT_RENTAL_EXPENSE, SORT_DATE) SELECT MONTH_YEAR, EXPENSE, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_TOTAL_RENTAL_EXPENSE_PERUNIT'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
    EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    SET @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' (MONTH_YEAR, NET_REVENUE, SORT_DATE) SELECT MONTH_YEAR,NET_REVENUE, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_NET_REVENUE_PERUNIT'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
    EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    SET @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' (MONTH_YEAR, UNIT_RENTAL, SORT_DATE) SELECT MONTH_YEAR, UNIT_RENTAL, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_UNIT_RENTAL_PERUNIT'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
    EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    SET @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' (MONTH_YEAR, TOT_BIZ_EXPENSE, SORT_DATE) SELECT MONTH_YEAR,TOTAL_BIZ_EXP, str_to_date(concat("1-", SUBSTRING(MONTH_YEAR,1,3) ,"-", SUBSTRING_INDEX(MONTH_YEAR,"-",-1)),  "%d-%b-%Y") FROM VIEW_TOTAL_BIZ_EXPENSE_PERUNIT'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
    EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    --   TEMP TABLE NAME START
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT CONCAT('TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT',SYSDATE()));
    --   TEMP TABLE NAME
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT REPLACE(CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,' ',''));
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT REPLACE(CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,'-',''));
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT REPLACE(CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,':',''));
    SET TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT CONCAT(CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,'_',USERSTAMP_ID)); 

    --  DROP TABLE IF EXISTS TEMP_CHARTS_UNIT_GROSS_NET_REVENUE_PERUNIT;
    SET @CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT CONCAT('CREATE TABLE ',TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,' (MONTH_YEAR VARCHAR(20), GROSS_REVENUE DECIMAL(30,2),TOT_RENTAL_EXPENSE DECIMAL(30,2),NET_REVENUE DECIMAL(30,2), UNIT_RENTAL INT, TOT_BIZ_EXPENSE DECIMAL(30,2))'));
    PREPARE CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT_STMT FROM @CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT;
		EXECUTE CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT_STMT;

    SET @INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT=(SELECT CONCAT('INSERT INTO ',TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT,' (MONTH_YEAR, GROSS_REVENUE, TOT_RENTAL_EXPENSE, NET_REVENUE, UNIT_RENTAL, TOT_BIZ_EXPENSE) (SELECT MONTH_YEAR,SUM(GROSS_REVENUE), SUM(TOT_RENTAL_EXPENSE),SUM(NET_REVENUE), SUM(UNIT_RENTAL), SUM(TOT_BIZ_EXPENSE) FROM ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT,' GROUP BY MONTH_YEAR ORDER BY SORT_DATE ASC)'));
    PREPARE INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT_STMT FROM @INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT;
    EXECUTE INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT_STMT;
    
    -- DROP THE INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT
    SET @DROP_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT));
  	PREPARE DROP_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT FROM @DROP_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT;
  	EXECUTE DROP_INTERMEDIATE_UNIT_GROSS_NET_REVENUE_PERUNIT_STMT;

    -- DROP TABLE IF EXISTS INTERMEDIATE_UNIT_GROSS_REVENUE_PERUNIT;

 COMMIT;
END;
/*
CALL SP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT(422,'January-2014','January-2014','admin@expatsint.com',@TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT);  
SELECT @TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT;
SELECT *FROM TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT20140510175901_1;
*/