DROP PROCEDURE IF EXISTS SP_DD_ELECTRICITY_EXCESS_CALCULATION;
CREATE PROCEDURE SP_DD_ELECTRICITY_EXCESS_CALCULATION(
	IN DD_UNIT_NO INTEGER(4),
	IN DD_CUSTOMER_ID INTEGER,
	IN DD_REC_VER INTEGER,
	IN DD_STARTDATE DATE,
	IN DD_ENDDATE DATE)
BEGIN
DECLARE NO_OF_DIV INTEGER;
DECLARE ELECTRICITY_CAP DECIMAL(7,2) DEFAULT NULL;
DECLARE DD_EEID INTEGER;
DECLARE DD_INVOICE_DATE DATE;
DECLARE DD_FROM_PERIOD DATE;
DECLARE DD_TO_PERIOD DATE;
DECLARE DD_AMOUNT DECIMAL(7,2);
DECLARE DD_DIVAMOUNT DECIMAL(7,2);
DECLARE DONE INT DEFAULT FALSE;
DECLARE DDINVDATESTR TEXT;
DECLARE ELECTRICITY_CURSOR CURSOR FOR SELECT EE.EE_ID,EE.EE_INVOICE_DATE,EE.EE_FROM_PERIOD,EE.EE_TO_PERIOD,EE.EE_AMOUNT FROM UNIT U,EXPENSE_DETAIL_ELECTRICITY EDE,EXPENSE_ELECTRICITY EE WHERE (U.UNIT_ID=EDE.UNIT_ID) AND (U.UNIT_NO=DD_UNIT_NO) AND (EDE.EDE_ID=EE.EDE_ID) AND (EE.EE_INVOICE_DATE BETWEEN DD_STARTDATE AND DD_ENDDATE) ORDER BY EE.EE_INVOICE_DATE ASC;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
END;
START TRANSACTION;
OPEN ELECTRICITY_CURSOR;
ELECTRICITY_LOOP: LOOP
	FETCH ELECTRICITY_CURSOR INTO DD_EEID,DD_INVOICE_DATE,DD_FROM_PERIOD,DD_TO_PERIOD,DD_AMOUNT;
	IF DONE THEN
		LEAVE ELECTRICITY_LOOP;
	END IF;
	IF NOT EXISTS(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS CFD WHERE CFD.CUSTOMER_ID=DD_CUSTOMER_ID AND CFD.CED_REC_VER=DD_REC_VER AND CFD.CPP_ID=5) THEN
		SET ELECTRICITY_CAP=0;
	ELSE
		SET ELECTRICITY_CAP=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS CFD WHERE CFD.CUSTOMER_ID=DD_CUSTOMER_ID AND CFD.CED_REC_VER=DD_REC_VER AND CFD.CPP_ID=5);
	END IF;
	IF DD_AMOUNT > ELECTRICITY_CAP AND ELECTRICITY_CAP >0 THEN
		IF(SELECT DDNOOFDIVISION FROM TEMP_DD_CALCULATION WHERE DDCUSTOMERID=DD_CUSTOMER_ID AND DDRECVER=DD_REC_VER) IS NOT NULL THEN
			SET NO_OF_DIV=(SELECT DDNOOFDIVISION FROM TEMP_DD_CALCULATION WHERE DDCUSTOMERID=DD_CUSTOMER_ID AND DDRECVER=DD_REC_VER);
		ELSE
			SET NO_OF_DIV=(SELECT DDNOOFDIVISION FROM TEMP_DD_CALCULATION WHERE DDNOOFDIVISION IS NOT NULL);
		END IF;
		IF NO_OF_DIV IS NOT NULL AND NO_OF_DIV!=0 THEN
			SET DD_DIVAMOUNT=((DD_AMOUNT-ELECTRICITY_CAP)/NO_OF_DIV);
		END IF;
	ELSE
		SET DD_DIVAMOUNT=DD_AMOUNT;
	END IF;
	SET DDINVDATESTR = CONCAT((SELECT DATE_FORMAT(DD_INVOICE_DATE,'%b - %Y')),'  (',(SELECT DATE_FORMAT(DD_FROM_PERIOD,'%b %d')),' - ',(SELECT DATE_FORMAT(DD_TO_PERIOD,'%b %d')),')');
	INSERT INTO TEMP_DD_CALCULATION(DDRECVER, DDEEAMOUNT, DDEEDIVAMOUNT, DDEEINVOICEDATE) VALUES(DD_REC_VER,DD_AMOUNT,DD_DIVAMOUNT,DDINVDATESTR);
	SET ELECTRICITY_CAP=NULL;
END LOOP;
CLOSE ELECTRICITY_CURSOR;
IF NOT EXISTS(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS CFD WHERE CFD.CUSTOMER_ID=DD_CUSTOMER_ID AND CFD.CED_REC_VER=DD_REC_VER AND CFD.CPP_ID=5) THEN
	SET ELECTRICITY_CAP=0;
ELSE
	SET ELECTRICITY_CAP=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS CFD WHERE CFD.CUSTOMER_ID=DD_CUSTOMER_ID AND CFD.CED_REC_VER=DD_REC_VER AND CFD.CPP_ID=5);
END IF;
INSERT INTO TEMP_DD_CALCULATION(DDRECVER, DDEECAP) VALUES(DD_REC_VER,ELECTRICITY_CAP);
COMMIT;
END;