DROP PROCEDURE IF EXISTS SP_CUSTOMER_ACCESS_CARD_TICKLER_NEWVALUE;
CREATE PROCEDURE SP_CUSTOMER_ACCESS_CARD_TICKLER_NEWVALUE (IN CUSTOMERID INTEGER,IN CACDID INTEGER,IN USERSTAMP VARCHAR(50),OUT NEWVALUE_ACCESS TEXT)
BEGIN
-- DECLARING VARIABLES
DECLARE NEWUASDID INTEGER;
--  QUERY FOR ROLLBACK COMMAND
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN 
		ROLLBACK;
	END;
	START TRANSACTION;
	SET NEWVALUE_ACCESS='';
	SET NEWUASDID = (SELECT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CUSTOMER_ID = CUSTOMERID AND CACD_ID = CACDID);
	SET NEWVALUE_ACCESS = (SELECT CONCAT (NEWVALUE_ACCESS,'UASD_ID = ',NEWUASDID));
	COMMIT;
END;
CALL SP_CUSTOMER_ACCESS_CARD_TICKLER_NEWVALUE(402,2,USERSTAMP,@NEWVALUE_ACCESS);
select @NEWVALUE_ACCESS;