DROP PROCEDURE IF EXISTS SP_TS_POST_MIGRATION_INITIAL_TABLE;
CREATE PROCEDURE SP_TS_POST_MIGRATION_INITIAL_TABLE()
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
END;
START TRANSACTION;
DROP TABLE IF EXISTS POST_MIGRATION_MODULE;
CREATE TABLE POST_MIGRATION_MODULE(
PMM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PMM_MODULE_NAME VARCHAR(50)NOT NULL,
PMM_FOLDER_ID VARCHAR(60));
INSERT INTO POST_MIGRATION_MODULE(PMM_MODULE_NAME,PMM_FOLDER_ID) VALUES
('AUDIT','0B_f0d7mdbV_UMF9tQURTdXptSEk'),
('CONFIGURATION','0B_f0d7mdbV_UaGFtdldUdDd2bTA'),
('USER RIGHTS','0B_f0d7mdbV_UT3lJYXFReVJRbU0'),
('REPORTPART1','0B_f0d7mdbV_USndFM2hCZlVHR3c'),
('REPORTPART2','0Bwv4Rd7ZecjPZkI0b0lnYUViR0U'),
('REPORTPART3','0Bwv4Rd7ZecjPYUNtMDJSLTdaemc'),
('REPORTPART4','0Bwv4Rd7ZecjPbmQ5Nlh3MC1pemc'),
('REPORTPART5','0Bwv4Rd7ZecjPOUgwU0E1eWoyTWs'),
('REPORTPART6','0Bwv4Rd7ZecjPSXBURlo4dndmMnc'),
('REPORTPART7','0Bwv4Rd7ZecjPeXpQU1FITVZyWWc'),
('REPORTPART8','0B_HhNbyfe3oQVjRnN3RpSkVzRjg'),
('BANDWIDTH','0Bwv4Rd7ZecjPWm9VZmFvWkdScW8');
COMMIT;
END;
CALL SP_TS_POST_MIGRATION_INITIAL_TABLE()