DROP PROCEDURE IF EXISTS SP_GET_UNIT_RENTAL;
CREATE PROCEDURE SP_GET_UNIT_RENTAL(IN FROM_DATE DATE, IN TO_DATE DATE,IN USERSTAMP VARCHAR(50),OUT TEMP_UNIT_RENTAL TEXT)
BEGIN
DECLARE startdate VARCHAR(3);
DECLARE year      VARCHAR(10);
DECLARE numbmonths INT;
DECLARE V_COUNT INT DEFAULT 0;
DECLARE li_ud_payment INT DEFAULT 0;
DECLARE unit_start_date DATE;
DECLARE unit_end_date DATE;
DECLARE i INT DEFAULT 0;
DECLARE unit_rental INT DEFAULT 0;
DECLARE mon INT DEFAULT 0;
DECLARE Rsdate DATE;
DECLARE Date DATE;
DECLARE USERSTAMP_ID INT;
DECLARE UNIT_RENTAL_TBL TEXT;
DECLARE TEMPTBL_UNIT_DETAILS TEXT;
DECLARE UNIT_DETAILS_TBL TEXT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
 ROLLBACK;
END;
  CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
  SET USERSTAMP_ID=(SELECT @ULDID);
  SET UNIT_RENTAL_TBL=(SELECT CONCAT('TEMP_UNIT_RENTAL',SYSDATE()));
  SET UNIT_RENTAL_TBL=(SELECT REPLACE(UNIT_RENTAL_TBL,' ',''));
  SET UNIT_RENTAL_TBL=(SELECT REPLACE(UNIT_RENTAL_TBL,'-',''));
  SET UNIT_RENTAL_TBL=(SELECT REPLACE(UNIT_RENTAL_TBL,':',''));
  SET TEMP_UNIT_RENTAL=(SELECT CONCAT(UNIT_RENTAL_TBL,'_',USERSTAMP_ID));   
  SET @CREATE_TEMP_UNIT_RENTAL=(SELECT CONCAT('CREATE TABLE ',TEMP_UNIT_RENTAL,' (MONTH_YEAR VARCHAR(20), UD_PAYMENT INT)'));
  PREPARE CREATE_TEMP_UNIT_RENTAL_STMT FROM @CREATE_TEMP_UNIT_RENTAL;
  EXECUTE CREATE_TEMP_UNIT_RENTAL_STMT;
  SET UNIT_DETAILS_TBL=(SELECT CONCAT('TEMPTBL_UNIT_DETAILS',SYSDATE()));
  SET UNIT_DETAILS_TBL=(SELECT REPLACE(UNIT_DETAILS_TBL,' ',''));
  SET UNIT_DETAILS_TBL=(SELECT REPLACE(UNIT_DETAILS_TBL,'-',''));
  SET UNIT_DETAILS_TBL=(SELECT REPLACE(UNIT_DETAILS_TBL,':',''));
  SET TEMPTBL_UNIT_DETAILS=(SELECT CONCAT(UNIT_DETAILS_TBL,'_',USERSTAMP_ID));   
  SET @CREATE_TEMPTBL_UNIT_DETAILS=(SELECT CONCAT ('CREATE TABLE ',TEMPTBL_UNIT_DETAILS,' (ID INT NOT NULL AUTO_INCREMENT,UD_PAYMENT INT,UD_START_DATE DATE,UD_END_DATE DATE,PRIMARY KEY(ID))'));
  PREPARE CREATE_TEMPTBL_UNIT_DETAILS_STMT FROM @CREATE_TEMPTBL_UNIT_DETAILS;
  EXECUTE CREATE_TEMPTBL_UNIT_DETAILS_STMT;
  SET @INSERT_TEMPTBL_UNIT_DETAILS=(SELECT CONCAT('INSERT INTO ',TEMPTBL_UNIT_DETAILS,' (UD_PAYMENT, UD_START_DATE, UD_END_DATE) SELECT UD_PAYMENT, UD.UD_START_DATE, UD.UD_END_DATE FROM UNIT_DETAILS UD WHERE UD.UD_OBSOLETE IS NULL AND UD.UD_NON_EI IS NULL AND UD.UD_END_DATE > CURDATE() AND ((','"',FROM_DATE,'"',' BETWEEN UD.UD_START_DATE AND UD.UD_END_DATE) OR (','"',FROM_DATE,'"',' <= UD.UD_END_DATE)) AND ((','"',TO_DATE,'"',' BETWEEN UD.UD_START_DATE AND UD.UD_END_DATE) OR (','"',TO_DATE,'"',' >= UD.UD_START_DATE))'));
  PREPARE INSERT_TEMPTBL_UNIT_DETAILS_STMT FROM @INSERT_TEMPTBL_UNIT_DETAILS;
  EXECUTE INSERT_TEMPTBL_UNIT_DETAILS_STMT;
SET numbmonths =MONTH(TO_DATE) - MONTH(FROM_DATE) + (12 * ( YEAR(TO_DATE) - YEAR(FROM_DATE)))+1;
SET startdate = 01;
SET year = YEAR(FROM_DATE);
SET mon = MONTH(FROM_DATE);
SET Date= concat(year,'-',mon,'-',startdate); 
 L1:
 LOOP
  SET unit_rental=0;
  SET Rsdate = DATE_ADD(Date, INTERVAL i MONTH);
  SET @SELECT_V_COUNT=(SELECT CONCAT('SELECT COUNT(*) INTO @VCOUNT FROM ',TEMPTBL_UNIT_DETAILS));
  PREPARE SELECT_V_COUNT_STMT FROM @SELECT_V_COUNT;
  EXECUTE SELECT_V_COUNT_STMT;
  SET V_COUNT=(SELECT @VCOUNT);
        L2: LOOP
          SET @SELECT=(SELECT CONCAT('SELECT UD_PAYMENT,UD_START_DATE,UD_END_DATE INTO @LIUDPAYMENT,@UNIT_SDATE,@UNIT_EDATE FROM ',TEMPTBL_UNIT_DETAILS,' WHERE ID = ',V_COUNT));
          PREPARE SELECT_STMT FROM @SELECT;
          EXECUTE SELECT_STMT;
          SET li_ud_payment =(SELECT @LIUDPAYMENT);
          SET unit_start_date =(SELECT @UNIT_SDATE);
          SET unit_end_date =(SELECT @UNIT_EDATE);
            IF(Rsdate BETWEEN DATE_FORMAT(unit_start_date,'%Y-%m-%01') AND DATE_FORMAT(unit_end_date,'%Y-%m-%31')) THEN
              SET unit_rental = unit_rental+li_ud_payment;
            END IF;
            SET V_COUNT = V_COUNT - 1;
            IF (V_COUNT = 0) THEN
              LEAVE L2;
            END IF;  
        END LOOP L2;
  SET @INSERT_TEMP_UNIT_RENTAL=(SELECT CONCAT('INSERT INTO ',TEMP_UNIT_RENTAL,' VALUES (date_format(','"',Rsdate,'"',',"%M-%Y"), ',unit_rental,')'));
  PREPARE INSERT_TEMP_UNIT_RENTAL_STMT FROM @INSERT_TEMP_UNIT_RENTAL;
  EXECUTE INSERT_TEMP_UNIT_RENTAL_STMT;
    SET i = i+1;
    IF(i >= numbmonths) THEN
      LEAVE L1;
    END IF;  
 END LOOP L1;
  SET @DROP_TEMPTBL_UNIT_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMPTBL_UNIT_DETAILS));
  PREPARE DROP_TEMPTBL_UNIT_DETAILS_STMT FROM @DROP_TEMPTBL_UNIT_DETAILS;
  EXECUTE DROP_TEMPTBL_UNIT_DETAILS_STMT;
COMMIT;
END;