-- version:0.9 -- sdate:09/06/2014 -- edate:09/06/2014 -- issue:566 --COMMENT NO: 12--desc:IMPLEMENTED ROLL BACK AND COMMIT --doneby:RAJA
-- version:0.8 -- sdate:22/04/2014 -- edate:22/04/2014 -- issue:765 --desc:updating timestamp --doneby:Bhavani.R
-- version:0.7 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
--version:0.6--sdate:22/02/2014 --edate:22/02/2014 --issue:750 -desc:changes source timestamp and userstamp as uld_id done by:dhivya
--version:0.5--sdate:22/02/2014 --edate:22/02/2014 --issue:750 -desc:added preaudit and post audit queries done by:dhivya
--version:0.4 --sdate:04/02/2014 --edate:04/02/2014 --desc:removed source table updation sp  --done by:RL
--version:0.3 --sdate:01/02/2014 --edate:01/02/2014 --desc:looping changed as cursor --done by:RL & DHIVYA


DROP PROCEDURE IF EXISTS SP_TEMP_PERSONAL_SCDB_FORMAT;
CREATE PROCEDURE SP_TEMP_PERSONAL_SCDB_FORMAT()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
--QUERY FOR CREATE TEMP_PERSONAL_SCDB_FORMAT TABLE
	DROP TABLE IF EXISTS TEMP_PERSONAL_SCDB_FORMAT;
	CREATE TABLE TEMP_PERSONAL_SCDB_FORMAT LIKE PERSONAL_SCDB_FORMAT;
--QUERY FOR INSERT VALUES TEMP_PERSONAL_SCDB_FORMAT TABLE	
	INSERT INTO TEMP_PERSONAL_SCDB_FORMAT SELECT * FROM PERSONAL_SCDB_FORMAT;
--QUERY FOR UPDATE VALUES TEMP_PERSONAL_SCDB_FORMAT TABLE	
	UPDATE TEMP_PERSONAL_SCDB_FORMAT SET PE_CAR_EXP_TYPE = 'CASH CARD' WHERE PE_CAR_EXP_TYPE = 'Cash Card/Coupon';
	UPDATE TEMP_PERSONAL_SCDB_FORMAT SET PE_BABY_EXPENSE = 'HEALTH CARE/HOSPITAL EXPENSES' WHERE PE_BABY_EXPENSE = 'HEALTH CARE/HOSPITAL EXPENSE';
	DELETE FROM TEMP_PERSONAL_SCDB_FORMAT WHERE PE_ID IN(2225,3154);
-- Query for Updating Timestamp
	UPDATE TEMP_PERSONAL_SCDB_FORMAT SET TIMESTAMP=(SELECT CONVERT_TZ(TIMESTAMP, "+08:00","+0:00"));
COMMIT;
END;	