-- version:0.6 -- sdate:09/06/2014 -- edate:09/06/2014 -- issue:566 --COMMENT NO: 12--desc:IMPLEMENTED ROLL BACK AND COMMIT --doneby:RAJA
-- version:0.5 -- sdate:02/04/2014 -- edate:02/04/2014 -- issue:765 COMMENT #58--desc: SPLITTED EXPENSE PERSONAL  --doneby:DHIVYA
-- version:0.4 -- sdate:28/03/2014 -- edate:28/03/2014 -- issue:765 --desc: SOURCE ND DESTINATION SCHEMA GET DYNAMICALLY --doneby:RL
-- version:0.3 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
--version:0.2--sdate:22/02/2014 --edate:22/02/2014 --issue:750 -desc:added preaudit and post audit queries done by:dhivya
--version:0.1--sdate:22/02/2014 --edate:22/02/2014 --issue:750 -desc:added preaudit and post audit queries done by:dhivya

DROP PROCEDURE IF EXISTS SP_EXPENSE_PERSONAL_INSERT;
CREATE PROCEDURE SP_EXPENSE_PERSONAL_INSERT(IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;

	CALL SP_TEMP_PERSONAL_SCDB_FORMAT();

	--EXPENSE PERSONAL
	SET START_TIME=(SELECT CURTIME());

	CALL SP_MIG_EXP_PERSONAL_TRIBLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
--VIEW FOR REMAINING COMMENTS
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_ALL_COMMENTS AS SELECT PE_ID,PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='PERSONAL' AND PE_PERSONAL_COMMENTS IS NOT NULL AND (PE_PERSONAL_INVOICE_ITEMS IS NULL OR PE_PERSONAL_INVOICE_FROM IS NULL);

	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_PERSONAL_ALL_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_TRIBLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
	WHERE t2.PE_ID IS NULL;

	CALL SP_MIG_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();

--VIEW FOR REMAINING COMMENTS
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_PERSONAL_REMAINING_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
	WHERE t2.PE_ID IS NULL;

	CALL SP_MIG_EXP_PERSONAL_SINGLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();

--VIEW FOR REMAINING COMMENTS
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_SINGLE_SLASHN_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_REMAINING_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_SINGLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
	WHERE t2.PE_ID IS NULL;

	CALL SP_MIG_EXP_PERSONAL_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();

--VIEW FOR REMAINING COMMENTS
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_SLASHN_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_PERSONAL_SINGLE_SLASHN_REMAINING_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
	WHERE t2.PE_ID IS NULL;

	CALL SP_MIG_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM_SPLIT_INSERT();

--VIEW FOR REMAINING COMMENTS
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_PERSONAL_SLASHN_REMAINING_COMMENTS t1
	LEFT JOIN TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM t2 ON t2.PE_ID = t1.PE_ID
	WHERE t2.PE_ID IS NULL;

	CALL SP_MIG_EXP_PERSONAL_SINGLE_SLASHN_INVOICE_ITEM_SPLIT_INSERT();
	
	CALL SP_PERSONAL_INVOICE_ITEM_FROM_SPLITTING(DESTINATIONSCHEMA);
	
	CALL SP_MIG_EXPENSE_PERSONAL_INSERT(DESTINATIONSCHEMA);

	DROP TABLE IF EXISTS TEMP_PERSONAL_INVOICE_ITEM_FROM_SPLITTED_TABLE;

	SET END_TIME=(SELECT CURTIME());
		
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

	SET @COUNT_SCDB_PERSONAL=(SELECT COUNT(*) FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='PERSONAL');

	SET @COUNT_SPLITTED_PERSONAL=(SELECT CONCAT('SELECT COUNT(*) INTO @SPLITEDPERSONAL FROM ',DESTINATIONSCHEMA,'.EXPENSE_PERSONAL'));
	PREPARE COUNT_SPLITTED_PERSONALSTMT FROM @COUNT_SPLITTED_PERSONAL;
	EXECUTE COUNT_SPLITTED_PERSONALSTMT;
	
	SET @REJECTION_COUNT=(@COUNT_SCDB_PERSONAL-@SPLITEDPERSONAL);
	
	SET FOREIGN_KEY_CHECKS = 0;

	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_PERSONAL WHERE PREASP_DATA='EXPENSE_PERSONAL';

	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
	VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_PERSONAL'),@SPLITEDPERSONAL,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_PERSONAL'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='PERSONAL'),DURATION,@REJECTION_COUNT,@ULDID);
	
	DROP TABLE IF EXISTS TEMP_PERSONAL_SCDB_FORMAT;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_ALL_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_SINGLE_SLASHN_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_SLASHN_REMAINING_COMMENTS;
COMMIT;
END;	

CALL SP_EXPENSE_PERSONAL_INSERT(DESTINATIONSCHEMA,MIGUSERSTAMP);



