DROP PROCEDURE IF EXISTS SP_TS_ROLE_CREATION_UPDATE;
CREATE PROCEDURE SP_TS_ROLE_CREATION_UPDATE(
IN CUSTOM_ROLE VARCHAR(15),
IN BASIC_ROLE TEXT,
IN MENUID TEXT,
IN USERSTAMP VARCHAR(50),
IN DB_NAME VARCHAR(20),
OUT RC_FLAG INTEGER)
BEGIN
	DECLARE MENU_LENGTH INTEGER;
	DECLARE TEMP_MENU TEXT;
	DECLARE MENU INTEGER;
	DECLARE MENU_POSITION INTEGER;
	DECLARE REMOVE_MP_ID TEXT DEFAULT "'";
	DECLARE GRANT_MP_ID TEXT DEFAULT "'";
	DECLARE USERSTAMP_ID INTEGER(2);
	DECLARE TEMP_INSERT_MENU TEXT;
	DECLARE INSERT_MENU TEXT;
	DECLARE TEMP_REMOVE_MENU TEXT;
	DECLARE REMOVE_MENU TEXT;
	DECLARE RM_COUNT INT;
	DECLARE RM_MPID INT;
	DECLARE IM_COUNT INT;
	DECLARE IM_MPID INT;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		SET RC_FLAG=0;
		IF (TEMP_INSERT_MENU IS NOT NULL) THEN
		  SET @DROP_TEMP_INSERT_MENU=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_INSERT_MENU));
		  PREPARE DROP_TEMP_INSERT_MENU_STMT FROM @DROP_TEMP_INSERT_MENU;
		  EXECUTE DROP_TEMP_INSERT_MENU_STMT;
		END IF;
		IF (TEMP_REMOVE_MENU IS NOT NULL) THEN
		  SET @DROP_TEMP_REMOVE_MENU=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_REMOVE_MENU));
		  PREPARE DROP_TEMP_REMOVE_MENU_STMT FROM @DROP_TEMP_REMOVE_MENU;
		  EXECUTE DROP_TEMP_REMOVE_MENU_STMT;
		END IF;
	END;
	SET AUTOCOMMIT = 0;
	START TRANSACTION;
	SET RC_FLAG=0;
	CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
	SET USERSTAMP_ID = (SELECT @ULDID);
	SET INSERT_MENU=(SELECT CONCAT('TEMP_INSERT_MENU',SYSDATE()));
	SET INSERT_MENU=(SELECT REPLACE(INSERT_MENU,' ',''));
	SET INSERT_MENU=(SELECT REPLACE(INSERT_MENU,'-',''));
	SET INSERT_MENU=(SELECT REPLACE(INSERT_MENU,':',''));
	SET TEMP_INSERT_MENU=(SELECT CONCAT(INSERT_MENU,'_',USERSTAMP_ID));
	SET REMOVE_MENU=(SELECT CONCAT('TEMP_REMOVE_MENU',SYSDATE()));
	SET REMOVE_MENU=(SELECT REPLACE(REMOVE_MENU,' ',''));
	SET REMOVE_MENU=(SELECT REPLACE(REMOVE_MENU,'-',''));
	SET REMOVE_MENU=(SELECT REPLACE(REMOVE_MENU,':',''));
	SET TEMP_REMOVE_MENU=(SELECT CONCAT(REMOVE_MENU,'_',USERSTAMP_ID));
	IF (CUSTOM_ROLE IS NOT NULL AND BASIC_ROLE IS NOT NULL) THEN
		UPDATE ROLE_CREATION SET URC_ID=(SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA=BASIC_ROLE)WHERE RC_NAME=CUSTOM_ROLE;
		SET RC_FLAG=1;
	END IF;
	SET @CREATE_TEMP_INSERT_MENU=(SELECT CONCAT('CREATE TABLE ',TEMP_INSERT_MENU,'(ID INT NOT NULL AUTO_INCREMENT, RC_ID INTEGER,MP_ID INTEGER, PRIMARY KEY (ID))'));
	PREPARE CREATE_TEMP_INSERT_MENU_STMT FROM @CREATE_TEMP_INSERT_MENU;
	EXECUTE CREATE_TEMP_INSERT_MENU_STMT;
	SET @CREATE_TEMP_REMOVE_MENU=(SELECT CONCAT('CREATE TABLE ',TEMP_REMOVE_MENU,'(ID INT NOT NULL AUTO_INCREMENT, RC_ID INTEGER,MP_ID INTEGER, PRIMARY KEY (ID))'));
	PREPARE CREATE_TEMP_REMOVE_MENU_STMT FROM @CREATE_TEMP_REMOVE_MENU;
	EXECUTE CREATE_TEMP_REMOVE_MENU_STMT;
	IF (MENUID IS NOT NULL) THEN
		SET TEMP_MENU = MENUID;
		SET MENU_LENGTH = 1;
		loop_label : LOOP
			SET MENU_POSITION = (SELECT LOCATE(',', TEMP_MENU,MENU_LENGTH));
			IF MENU_POSITION<=0 THEN
				SET MENU = TEMP_MENU;
			ELSE
				SELECT SUBSTRING(TEMP_MENU,MENU_LENGTH,MENU_POSITION-1) INTO MENU;
				SET TEMP_MENU=(SELECT SUBSTRING(TEMP_MENU,MENU_POSITION+1));
			END IF;		
			IF NOT EXISTS(SELECT MP_ID FROM USER_MENU_DETAILS WHERE MP_ID=MENU AND RC_ID=(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE))THEN
				SET FOREIGN_KEY_CHECKS=0;
				INSERT INTO USER_MENU_DETAILS(MP_ID,RC_ID,ULD_ID)VALUES(MENU,(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),USERSTAMP_ID);
				SET RC_FLAG=1;
			END IF;		
			SET @INSERT_TEMP_INSERT_MENU=(SELECT CONCAT('INSERT INTO ',TEMP_INSERT_MENU,'(RC_ID,MP_ID)VALUES((SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=','"',CUSTOM_ROLE,'"','),',MENU,')'));
			PREPARE INSERT_TEMP_INSERT_MENU_STMT FROM @INSERT_TEMP_INSERT_MENU;
			EXECUTE INSERT_TEMP_INSERT_MENU_STMT;
			IF MENU_POSITION<=0 THEN
				LEAVE  loop_label;
			END IF;
		END LOOP;
	END IF;
	SET @INSERT_TEMP_REMOVE_MENU=(SELECT CONCAT('INSERT INTO ',TEMP_REMOVE_MENU,'(RC_ID, MP_ID)SELECT U.RC_ID,U.MP_ID FROM USER_MENU_DETAILS U LEFT JOIN ',TEMP_INSERT_MENU,' T ON U.MP_ID=T.MP_ID WHERE T.MP_ID IS NULL AND U.RC_ID=(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=','"',CUSTOM_ROLE,'"',')'));
	PREPARE INSERT_TEMP_REMOVE_MENU_STMT FROM @INSERT_TEMP_REMOVE_MENU;
	EXECUTE INSERT_TEMP_REMOVE_MENU_STMT;
	SET @RM_COUNT=NULL;
	SET @SELECT_RM_COUNT = (SELECT CONCAT('SELECT COUNT(*) INTO @RM_COUNT FROM ',TEMP_REMOVE_MENU));
	PREPARE SELECT_RM_COUNT_STMT FROM @SELECT_RM_COUNT;
	EXECUTE SELECT_RM_COUNT_STMT;
	SET RM_COUNT=(SELECT @RM_COUNT);
	WHILE (RM_COUNT > 0) DO
		SET @RM_MPID=NULL;
		SET @SELECT_RM_MPID = (SELECT CONCAT('SELECT MP_ID INTO @RM_MPID FROM ',TEMP_REMOVE_MENU,' WHERE ID = ',RM_COUNT));
		PREPARE SELECT_RM_MPID_STMT FROM @SELECT_RM_MPID;
		EXECUTE SELECT_RM_MPID_STMT;
		SET RM_MPID=(SELECT @RM_MPID);
		SET REMOVE_MP_ID = CONCAT (REMOVE_MP_ID,RM_MPID,''',''');
		SET RM_COUNT = RM_COUNT - 1;
	END WHILE;
	SET REMOVE_MP_ID = SUBSTRING(REMOVE_MP_ID,1,CHAR_LENGTH(REMOVE_MP_ID)-2);
	SET @IM_COUNT=NULL;
	SET @SELECT_IM_COUNT = (SELECT CONCAT('SELECT COUNT(*) INTO @IM_COUNT FROM ',TEMP_INSERT_MENU));
	PREPARE SELECT_IM_COUNT_STMT FROM @SELECT_IM_COUNT;
	EXECUTE SELECT_IM_COUNT_STMT;
	SET IM_COUNT=(SELECT @IM_COUNT);
	WHILE (IM_COUNT > 0) DO
		SET @IM_MPID=NULL;
		SET @SELECT_RM_MPID = (SELECT CONCAT('SELECT MP_ID INTO @IM_MPID FROM ',TEMP_INSERT_MENU,' WHERE ID = ',IM_COUNT));
		PREPARE SELECT_RM_MPID_STMT FROM @SELECT_RM_MPID;
		EXECUTE SELECT_RM_MPID_STMT;
		SET IM_MPID=(SELECT @IM_MPID);
		SET GRANT_MP_ID = CONCAT (GRANT_MP_ID,IM_MPID,''',''');
		SET IM_COUNT = IM_COUNT - 1;
	END WHILE;
	SET GRANT_MP_ID = SUBSTRING(GRANT_MP_ID,1,CHAR_LENGTH(GRANT_MP_ID)-2);
	SET @DELETE_MENU=(SELECT CONCAT ('DELETE FROM USER_MENU_DETAILS WHERE MP_ID IN (SELECT MP_ID FROM ',TEMP_REMOVE_MENU,')AND RC_ID IN(SELECT RC_ID FROM ',TEMP_REMOVE_MENU,')'));
	PREPARE DELETE_MENU_STMT FROM @DELETE_MENU;
	EXECUTE DELETE_MENU_STMT;
	SET @DROP_TEMP_INSERT_MENU=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_INSERT_MENU));
	PREPARE DROP_TEMP_INSERT_MENU_STMT FROM @DROP_TEMP_INSERT_MENU;
	EXECUTE DROP_TEMP_INSERT_MENU_STMT;
	SET @DROP_TEMP_REMOVE_MENU=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_REMOVE_MENU));
	PREPARE DROP_TEMP_REMOVE_MENU_STMT FROM @DROP_TEMP_REMOVE_MENU;
	EXECUTE DROP_TEMP_REMOVE_MENU_STMT;
	COMMIT;
END;
CALL SP_TS_ROLE_CREATION_UPDATE(CUSTOM_ROLE,BASIC_ROLE,MENUID,USERSTAMP,DB_NAME,RC_FLAG);