DROP PROCEDURE IF EXISTS SP_TS_USER_RIGHTS_BASIC_PROFILE_SAVE;
CREATE PROCEDURE SP_TS_USER_RIGHTS_BASIC_PROFILE_SAVE (
IN USERSTAMP VARCHAR(50),
IN ROLE VARCHAR(255),
IN BASIC_ROLES VARCHAR(255),
IN MENUS VARCHAR(255),
OUT UR_FLAG INTEGER) 
BEGIN
	DECLARE URCID INT;
	DECLARE STR_LEN INT DEFAULT 0;
	DECLARE SUBSTR_LEN INT DEFAULT 0;
	DECLARE MENUID INT;
	DECLARE BASICROLES_ID INT;
	DECLARE BASICROLE VARCHAR(255);
	DECLARE USERSTAMP_ID INTEGER(2);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	SET AUTOCOMMIT = 0;
	START TRANSACTION;
	SET URCID = (SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA = ROLE);
	CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
	SET USERSTAMP_ID = (SELECT @ULDID);
	SET UR_FLAG=0;
	IF (BASIC_ROLES IS NULL) THEN
		SET BASIC_ROLES = '';
	END IF;  
	DO_THIS_FIRST:
	LOOP
		SET STR_LEN = CHAR_LENGTH(BASIC_ROLES); 
		SET BASICROLE = SUBSTRING_INDEX(BASIC_ROLES,',',1); 
		SET BASICROLES_ID = (SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA = BASICROLE);
		INSERT INTO BASIC_ROLE_PROFILE (URC_ID, BRP_BR_ID, ULD_ID) VALUES (URCID, BASICROLES_ID, USERSTAMP_ID);
		SET UR_FLAG=1;
		SET SUBSTR_LEN = CHAR_LENGTH(SUBSTRING_INDEX(BASIC_ROLES,',',1)) + 2;
		SET BASIC_ROLES = MID(BASIC_ROLES, SUBSTR_LEN, STR_LEN);    
		IF BASIC_ROLES = '' THEN
			LEAVE DO_THIS_FIRST;
		END IF;
	END LOOP DO_THIS_FIRST;
	IF MENUS IS NULL THEN
		SET MENUS = '';
	END IF;
	DO_THIS:
	LOOP
		SET STR_LEN = CHAR_LENGTH(MENUS);
		SET MENUID = SUBSTRING_INDEX(MENUS,',',1);
		INSERT INTO BASIC_MENU_PROFILE (URC_ID, MP_ID, ULD_ID) VALUES (URCID, MENUID, USERSTAMP_ID);   
		SET UR_FLAG=1;
		SET SUBSTR_LEN = CHAR_LENGTH(SUBSTRING_INDEX(MENUS,',',1)) + 2;
		SET MENUS = MID(MENUS, SUBSTR_LEN, STR_LEN);
		IF MENUS = '' THEN
		  LEAVE DO_THIS;
		END IF;
	END LOOP DO_THIS;
	COMMIT;
END;
CALL SP_TS_USER_RIGHTS_BASIC_PROFILE_SAVE(USERSTAMP,ROLE,BASIC_ROLES,MENUS,UR_FLAG);