DROP TRIGGER IF EXISTS TRG_STAFFDTL_SALARY_UPDATE_VALIDATION;
CREATE TRIGGER TRG_STAFFDTL_SALARY_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_DETAIL_STAFF_SALARY
FOR EACH ROW
BEGIN
	CALL SP_TRG_STAFFDTL_SALARY_VALIDATION (NEW.EDSS_CPF_NUMBER,NEW.EDSS_CPF_AMOUNT,NEW.EDSS_LEVY_AMOUNT,NEW.EDSS_SALARY_AMOUNT,'UPDATE');
END;