DROP PROCEDURE IF EXISTS SP_TS_MIG_TABLE_CREATION;
CREATE PROCEDURE SP_TS_MIG_TABLE_CREATION(
IN DESTINATIONSCHEMA VARCHAR(40))
BEGIN 
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;
	SET @DROP_CONFIGURATION_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CONFIGURATION_PROFILE'));
	PREPARE DROP_CONFIGURATION_PROFILE_STMT FROM @DROP_CONFIGURATION_PROFILE;
	EXECUTE DROP_CONFIGURATION_PROFILE_STMT; 
	SET @CREATE_CONFIGURATION_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CONFIGURATION_PROFILE(     
	CNP_ID INTEGER NOT NULL AUTO_INCREMENT,
	CNP_DATA VARCHAR(25) NOT NULL,
	PRIMARY KEY(CNP_ID),
	UNIQUE(CNP_DATA))'));    
	PREPARE CREATE_CONFIGURATION_PROFILE_STMT FROM @CREATE_CONFIGURATION_PROFILE;
	EXECUTE CREATE_CONFIGURATION_PROFILE_STMT;
	SET @DROP_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CONFIGURATION'));
	PREPARE DROP_CONFIGURATION_STMT FROM @DROP_CONFIGURATION;
	EXECUTE DROP_CONFIGURATION_STMT;
	SET @CREATE_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CONFIGURATION( 
	CGN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CNP_ID INTEGER NOT NULL, 
	CGN_TYPE VARCHAR(50) NOT NULL, 
	PRIMARY KEY(CGN_ID),
	FOREIGN KEY(CNP_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION_PROFILE (CNP_ID),
	UNIQUE(CGN_TYPE))'));
	PREPARE CREATE_CONFIGURATION_STMT FROM @CREATE_CONFIGURATION;
	EXECUTE CREATE_CONFIGURATION_STMT;
	SET @DROP_ERROR_MESSAGE_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.ERROR_MESSAGE_CONFIGURATION'));
	PREPARE DROP_ERROR_MESSAGE_CONFIGURATION_STMT FROM @DROP_ERROR_MESSAGE_CONFIGURATION;
	EXECUTE DROP_ERROR_MESSAGE_CONFIGURATION_STMT;
	SET @CREATE_ERROR_MESSAGE_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.ERROR_MESSAGE_CONFIGURATION( 
	EMC_ID INTEGER NOT NULL AUTO_INCREMENT,
	CNP_ID INTEGER NOT NULL,
	EMC_CODE INTEGER NOT NULL, 
	EMC_DATA TEXT NOT NULL, 
	ULD_ID INTEGER(2) NOT NULL,
	EMC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EMC_ID),
	FOREIGN KEY(CNP_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION_PROFILE (CNP_ID), 
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_ERROR_MESSAGE_CONFIGURATION_STMT FROM @CREATE_ERROR_MESSAGE_CONFIGURATION;
	EXECUTE CREATE_ERROR_MESSAGE_CONFIGURATION_STMT;
	SET @DROP_REPORT_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.REPORT_CONFIGURATION'));
	PREPARE DROP_REPORT_CONFIGURATION_STMT FROM @DROP_REPORT_CONFIGURATION;
	EXECUTE DROP_REPORT_CONFIGURATION_STMT;
	SET @CREATE_REPORT_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.REPORT_CONFIGURATION( 
	RC_ID INTEGER(2) NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL, 
	RC_DATA TEXT NOT NULL,
	ULD_ID INTEGER(2) NOT NULL, 
	RC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY(RC_ID), 
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID), 
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_REPORTCONFIGURATION_STMT FROM @CREATE_REPORT_CONFIGURATION;
	EXECUTE CREATE_REPORTCONFIGURATION_STMT; 
	SET @DROP_USER_RIGHTS_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION'));
	PREPARE DROP_USER_RIGHTS_CONFIGURATION_STMT FROM @DROP_USER_RIGHTS_CONFIGURATION;
	EXECUTE DROP_USER_RIGHTS_CONFIGURATION_STMT;
	SET @CREATE_USER_RIGHTS_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION(
	URC_ID INTEGER(2) NOT NULL AUTO_INCREMENT, 
	CGN_ID INTEGER NOT NULL, 
	URC_DATA TEXT NOT NULL, 
	URC_USERSTAMP VARCHAR(50) NOT NULL,
	URC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(URC_ID), 
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID))'));
	PREPARE CREATE_USER_RIGHTS_CONFIGURATION_STMT FROM @CREATE_USER_RIGHTS_CONFIGURATION;
	EXECUTE CREATE_USER_RIGHTS_CONFIGURATION_STMT;
	SET @DROP_ATTENDANCE_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION'));
	PREPARE DROP_ATTENDANCE_CONFIGURATION_STMT FROM @DROP_ATTENDANCE_CONFIGURATION;
	EXECUTE DROP_ATTENDANCE_CONFIGURATION_STMT;
	SET @CREATE_ATTENDANCE_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION(
	AC_ID INTEGER(2) NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	AC_DATA TEXT NOT NULL, 
	ULD_ID INTEGER(2) NOT NULL, 
	AC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(AC_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_CREATE_ATTENDANCE_CONFIGURATION_STMT FROM @CREATE_ATTENDANCE_CONFIGURATION;
	EXECUTE CREATE_CREATE_ATTENDANCE_CONFIGURATION_STMT;
	SET @DROP_PROJECT_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.PROJECT_CONFIGURATION'));
	PREPARE DROP_PROJECT_CONFIGURATION_STMT FROM @DROP_PROJECT_CONFIGURATION;
	EXECUTE DROP_PROJECT_CONFIGURATION_STMT;
	SET @CREATE_PROJECT_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.PROJECT_CONFIGURATION( 
	PC_ID INTEGER(2) NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL, 
	PC_DATA TEXT NOT NULL,
	ULD_ID INTEGER(2) NOT NULL, 
	PC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY(PC_ID), 
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID), 
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_PROJECT_CONFIGURATION_STMT FROM @CREATE_PROJECT_CONFIGURATION;
	EXECUTE CREATE_PROJECT_CONFIGURATION_STMT;
	SET @DROP_TICKLER_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TICKLER_PROFILE'));
	PREPARE DROP_TICKLER_PROFILE_STMT FROM @DROP_TICKLER_PROFILE;
	EXECUTE DROP_TICKLER_PROFILE_STMT;
	SET @CREATE_TICKLER_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TICKLER_PROFILE(
	TP_ID INTEGER NOT NULL AUTO_INCREMENT,
	TP_TYPE CHAR(10) NOT NULL,
	PRIMARY KEY(TP_ID))'));
	PREPARE CREATE_TICKLER_PROFILE_STMT FROM @CREATE_TICKLER_PROFILE;
	EXECUTE CREATE_TICKLER_PROFILE_STMT;
	SET @DROP_TICKLER_HISTORY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TICKLER_HISTORY'));
	PREPARE DROP_TICKLER_HISTORY_STMT FROM @DROP_TICKLER_HISTORY;
	EXECUTE DROP_TICKLER_HISTORY_STMT;
	SET @CREATE_TICKLER_HISTORY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TICKLER_HISTORY(
	TH_ID INTEGER NOT NULL AUTO_INCREMENT,
	TP_ID INTEGER NOT NULL,
	ULD_ID INTEGER NULL,
	TTIP_ID INTEGER NOT NULL,
	TH_OLD_VALUE TEXT NOT NULL,    
	TH_NEW_VALUE TEXT NULL,    
	TH_USERSTAMP_ID INTEGER(2) NOT NULL,
	TH_TIMESTAMP  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(TH_ID),
	FOREIGN KEY(TP_ID) REFERENCES ',DESTINATIONSCHEMA,'.TICKLER_PROFILE(TP_ID),
	FOREIGN KEY(TTIP_ID) REFERENCES ',DESTINATIONSCHEMA,'.TICKLER_TABID_PROFILE(TTIP_ID),
	FOREIGN KEY(TH_USERSTAMP_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_TICKLER_HISTORY_STMT FROM @CREATE_TICKLER_HISTORY;
	EXECUTE CREATE_TICKLER_HISTORY_STMT;
	SET @DROP_TICKLER_TABLE_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TICKLER_TABID_PROFILE'));
	PREPARE DROP_TICKLER_TABLE_PROFILE_STMT FROM @DROP_TICKLER_TABLE_PROFILE;
	EXECUTE DROP_TICKLER_TABLE_PROFILE_STMT;
	SET @CREATE_TICKLER_TABLE_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TICKLER_TABID_PROFILE(
	TTIP_ID INTEGER NOT NULL AUTO_INCREMENT,
	TTIP_DATA   VARCHAR(50) NOT NULL,
	PRIMARY KEY(TTIP_ID))'));
	PREPARE CREATE_TICKLER_TABLE_PROFILE_STMT FROM @CREATE_TICKLER_TABLE_PROFILE;
	EXECUTE CREATE_TICKLER_TABLE_PROFILE_STMT;
	SET @DROP_BASIC_MENU_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.BASIC_MENU_PROFILE'));
	PREPARE DROP_BASIC_MENU_PROFILE_STMT FROM @DROP_BASIC_MENU_PROFILE;
	EXECUTE DROP_BASIC_MENU_PROFILE_STMT;
	SET @CREATE_BASIC_MENU_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.BASIC_MENU_PROFILE( 
	BMP_ID INTEGER NOT NULL AUTO_INCREMENT,
	URC_ID INTEGER(2) NOT NULL, 
	MP_ID INTEGER(2) NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	BMP_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(BMP_ID),
	FOREIGN KEY(URC_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION (URC_ID),
	FOREIGN KEY(MP_ID) REFERENCES ',DESTINATIONSCHEMA,'.MENU_PROFILE (MP_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_BASIC_MENU_PROFILE_STMT FROM @CREATE_BASIC_MENU_PROFILE;
	EXECUTE CREATE_BASIC_MENU_PROFILE_STMT;
	SET @DROP_BASIC_ROLE_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.BASIC_ROLE_PROFILE'));
	PREPARE DROP_BASIC_ROLE_PROFILE_STMT FROM @DROP_BASIC_ROLE_PROFILE;
	EXECUTE DROP_BASIC_ROLE_PROFILE_STMT;
	SET @CREATE_BASIC_ROLE_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.BASIC_ROLE_PROFILE( 
	BRP_ID INTEGER NOT NULL AUTO_INCREMENT, 
	URC_ID INTEGER(2) NOT NULL, 
	BRP_BR_ID INTEGER NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	BRP_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(BRP_ID), 
	FOREIGN KEY(URC_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION (URC_ID),
	FOREIGN KEY(BRP_BR_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION (URC_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_BASIC_ROLE_PROFILE_STMT FROM @CREATE_BASIC_ROLE_PROFILE;
	EXECUTE CREATE_BASIC_ROLE_PROFILE_STMT;
	SET @DROP_MENU_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.MENU_PROFILE'));
	PREPARE DROP_MENUPROFILE FROM @DROP_MENU_PROFILE;
	EXECUTE DROP_MENUPROFILE;
	SET @CREATE_MENU_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.MENU_PROFILE( 
	MP_ID INTEGER(2) NOT NULL AUTO_INCREMENT,
	MP_MNAME VARCHAR(25) NOT NULL, 
	MP_MSUB VARCHAR(30) NOT NULL,
	MP_MSUBMENU VARCHAR(60) NULL,
	MP_MFILENAME VARCHAR(100) NOT NULL,
	MP_SCRIPT_FLAG VARCHAR(1) NULL,
	PRIMARY KEY(MP_ID))'));
	PREPARE CREATE_MENUPROFILE FROM @CREATE_MENU_PROFILE;
	EXECUTE CREATE_MENUPROFILE;
	SET @DROP_ROLE_CREATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.ROLE_CREATION'));
	PREPARE DROP_ROLECREATION FROM @DROP_ROLE_CREATION;
	EXECUTE DROP_ROLECREATION;
	SET @CREATE_ROLE_CREATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.ROLE_CREATION( 
	RC_ID INT(2) NOT NULL AUTO_INCREMENT,
	URC_ID INTEGER(2) NOT NULL, 
	RC_NAME VARCHAR(15) NOT NULL, 
	RC_USERSTAMP VARCHAR(50) NOT NULL, 
	RC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(RC_ID),
	FOREIGN KEY(URC_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION (URC_ID),
	UNIQUE (RC_NAME))'));
	PREPARE CREATE_ROLECREATION FROM @CREATE_ROLE_CREATION;
	EXECUTE CREATE_ROLECREATION;
	SET @DROP_ADMIN_WEEKLY_REPORT_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.ADMIN_WEEKLY_REPORT_DETAILS'));
	PREPARE DROP_ADMIN_WEEKLY_REPORT_DETAILS_STMT FROM @DROP_ADMIN_WEEKLY_REPORT_DETAILS;
	EXECUTE DROP_ADMIN_WEEKLY_REPORT_DETAILS_STMT;    
	SET @CREATE_ADMIN_WEEKLY_REPORT_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.ADMIN_WEEKLY_REPORT_DETAILS(
	AWRD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
	AWRD_REPORT	TEXT NOT NULL,
	AWRD_DATE	DATE NOT NULL,
	ULD_ID INTEGER NOT NULL,
	AWRD_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(AWRD_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_ADMIN_WEEKLY_REPORT_DETAILS_STMT FROM @CREATE_ADMIN_WEEKLY_REPORT_DETAILS;
	EXECUTE CREATE_ADMIN_WEEKLY_REPORT_DETAILS_STMT;
	SET @DROP_COMPANY_PROPERTIES_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.COMPANY_PROPERTIES_DETAILS'));
	PREPARE DROP_COMPANY_PROPERTIES_DETAILS_STMT FROM @DROP_COMPANY_PROPERTIES_DETAILS;
	EXECUTE DROP_COMPANY_PROPERTIES_DETAILS_STMT;    
	SET @CREATE_COMPANY_PROPERTIES_DETAILS_STMT=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.COMPANY_PROPERTIES_DETAILS(
	CPD_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMP_ID INTEGER	NOT NULL,
	CPD_LAPTOP_NUMBER	VARCHAR(25)	NULL,
	CPD_CHARGER_NUMBER	VARCHAR(25)	NULL,
	CPD_LAPTOP_BAG CHAR(1) NULL,
	CPD_MOUSE	CHAR(1)	NULL,
	CPD_DOOR_ACCESS	CHAR(1) NULL,
	CPD_ID_CARD	CHAR(1) NULL,
	CPD_HEADSET	CHAR(1) NULL,
	ULD_ID INTEGER NOT NULL,
	CPD_TIMESTAMP	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(CPD_ID),
	FOREIGN KEY(EMP_ID) REFERENCES ',DESTINATIONSCHEMA,'.EMPLOYEE_DETAILS (EMP_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_COMPANY_PROPERTIES_DETAILS_STMT FROM @CREATE_COMPANY_PROPERTIES_DETAILS_STMT;
	EXECUTE CREATE_COMPANY_PROPERTIES_DETAILS_STMT;  
	SET @DROP_ONDUTY_ENTRY_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.ONDUTY_ENTRY_DETAILS'));
	PREPARE DROP_ONDUTY_ENTRY_DETAILS_STMT FROM @DROP_ONDUTY_ENTRY_DETAILS;
	EXECUTE DROP_ONDUTY_ENTRY_DETAILS_STMT;    
	SET @CREATE_ONDUTY_ENTRY_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.ONDUTY_ENTRY_DETAILS(
	OED_ID INTEGER NOT NULL AUTO_INCREMENT,
	OED_DATE DATE	NOT NULL,
	OED_DESCRIPTION	TEXT NOT NULL,
	ULD_ID INTEGER NOT NULL,
	OED_TIMESTAMP	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(OED_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_ONDUTY_ENTRY_DETAILS_STMT FROM @CREATE_ONDUTY_ENTRY_DETAILS;
	EXECUTE CREATE_ONDUTY_ENTRY_DETAILS_STMT;
	SET @DROP_EMPLOYEE_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EMPLOYEE_DETAILS'));
	PREPARE DROP_EMPLOYEE_DETAILS_STMT FROM @DROP_EMPLOYEE_DETAILS;
	EXECUTE DROP_EMPLOYEE_DETAILS_STMT;    
	SET @CREATE_EMPLOYEE_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EMPLOYEE_DETAILS(
	EMP_ID INTEGER NOT NULL AUTO_INCREMENT,
	ULD_ID INTEGER NOT NULL,
	EMP_FIRST_NAME CHAR(30) NOT NULL,
	EMP_LAST_NAME	CHAR(30) NOT NULL,
	EMP_DOB	DATE NOT NULL,
	EMP_DESIGNATION	VARCHAR(50)	NOT NULL,
	EMP_MOBILE_NUMBER VARCHAR(10) NOT NULL,
	EMP_NEXT_KIN_NAME	CHAR(30) NOT NULL,
	EMP_RELATIONHOOD CHAR(30) NOT NULL,
	EMP_ALT_MOBILE_NO	VARCHAR(10) NOT NULL,
	EMP_USERSTAMP_ID INTEGER NOT NULL,
	EMP_TIMESTAMP	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EMP_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID),
	FOREIGN KEY(EMP_USERSTAMP_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_EMPLOYEE_DETAILS_STMT FROM @CREATE_EMPLOYEE_DETAILS;
	EXECUTE CREATE_EMPLOYEE_DETAILS_STMT;
	SET @DROP_PROJECTDTLS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.PROJECT_DETAILS'));
	PREPARE DROP_PROJECT_DETAILS_STMT FROM @DROP_PROJECTDTLS;
	EXECUTE DROP_PROJECT_DETAILS_STMT;    
	SET @CREATE_PROJECT_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.PROJECT_DETAILS(
	PD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
	PD_PROJECT_NAME	VARCHAR(50)	NOT NULL,
	PD_PROJECT_DESCRIPTION	VARCHAR(100)	NOT NULL,
	ULD_ID INTEGER(2)	NOT NULL,
	PD_TIMESTAMP TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (PD_ID),
	UNIQUE (PD_PROJECT_NAME),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_PROJECT_DETAILS_STMT FROM @CREATE_PROJECT_DETAILS;
	EXECUTE CREATE_PROJECT_DETAILS_STMT;
	SET @DROP_PROJECT_STATUS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.PROJECT_STATUS'));
	PREPARE DROP_PROJECT_STATUS_STMT FROM @DROP_PROJECT_STATUS;
	EXECUTE DROP_PROJECT_STATUS_STMT;    
	SET @CREATE_PROJECT_STATUS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.PROJECT_STATUS(
	PS_ID INTEGER NOT NULL AUTO_INCREMENT,
	PD_ID INTEGER NOT NULL,
	PC_ID INTEGER NOT NULL,
	PS_REC_VER INTEGER NOT NULL,
	PS_START_DATE DATE NOT NULL,
	PS_END_DATE	DATE NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	PS_TIMESTAMP TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(PS_ID),
	FOREIGN KEY(PD_ID) REFERENCES ',DESTINATIONSCHEMA,'.PROJECT_DETAILS (PD_ID),
	FOREIGN KEY(PC_ID) REFERENCES ',DESTINATIONSCHEMA,'.PROJECT_CONFIGURATION (PC_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_PROJECT_STATUS_STMT FROM @CREATE_PROJECT_STATUS;
	EXECUTE CREATE_PROJECT_STATUS_STMT;
	SET @DROP_PUBLIC_HOLIDAY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.PUBLIC_HOLIDAY'));
	PREPARE DROP_PUBLICHOLIDAY FROM @DROP_PUBLIC_HOLIDAY;
	EXECUTE DROP_PUBLICHOLIDAY;
	SET @CREATE_PUBLIC_HOLIDAY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.PUBLIC_HOLIDAY(
	PH_ID INTEGER(2) NOT NULL AUTO_INCREMENT,
	PH_DESCRIPTION VARCHAR(50) NOT NULL,
	PH_DATE DATE NOT NULL,
	PRIMARY KEY(PH_ID))'));
	PREPARE CREATE_PUBLICHOLIDAY FROM @CREATE_PUBLIC_HOLIDAY;
	EXECUTE CREATE_PUBLICHOLIDAY;
	SET @DROP_USER_ACCESS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.USER_ACCESS'));
	PREPARE DROP_USERACCESS FROM @DROP_USER_ACCESS;
	EXECUTE DROP_USERACCESS;
	SET @CREATE_USER_ACCESS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.USER_ACCESS (
	UA_ID INTEGER NOT NULL AUTO_INCREMENT,
	RC_ID INTEGER(2) NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	UA_REC_VER INTEGER NOT NULL,
	UA_JOIN_DATE DATE NOT NULL,
	UA_JOIN CHAR(1) NULL,
	UA_END_DATE DATE NULL,
	UA_TERMINATE CHAR(1) NULL, 
	UA_REASON TEXT NULL, 
	UA_EMP_TYPE	INT	NOT NULL,
	UA_USERSTAMP VARCHAR(50) NOT NULL,
	UA_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(UA_ID),
	FOREIGN KEY(RC_ID) REFERENCES ',DESTINATIONSCHEMA,'.ROLE_CREATION (RC_ID),
	FOREIGN KEY(UA_EMP_TYPE) REFERENCES ',DESTINATIONSCHEMA,'.USER_RIGHTS_CONFIGURATION (CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_USERACCESS FROM @CREATE_USER_ACCESS;
	EXECUTE CREATE_USERACCESS;
	SET @DROP_USER_MENU_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.USER_MENU_DETAILS'));
	PREPARE DROP_USERMENUDETAILS FROM @DROP_USER_MENU_DETAILS;
	EXECUTE DROP_USERMENUDETAILS;
	SET @CREATE_USER_MENU_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.USER_MENU_DETAILS( 
	UMD_ID INTEGER NOT NULL AUTO_INCREMENT,
	MP_ID INTEGER(2) NOT NULL, 
	RC_ID INTEGER(2) NOT NULL, 
	ULD_ID INTEGER(2) NOT NULL,
	UMD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(UMD_ID), 
	FOREIGN KEY(MP_ID) REFERENCES ',DESTINATIONSCHEMA,'.MENU_PROFILE (MP_ID),
	FOREIGN KEY(RC_ID) REFERENCES ',DESTINATIONSCHEMA,'.ROLE_CREATION (RC_ID), 
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_USERMENUDETAILS FROM @CREATE_USER_MENU_DETAILS;
	EXECUTE CREATE_USERMENUDETAILS;
	SET @DROP_USER_LOGIN_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS'));
	PREPARE DROP_USERLOGINDETAILS FROM @DROP_USER_LOGIN_DETAILS;
	EXECUTE DROP_USERLOGINDETAILS;
	SET @CREATE_USER_LOGIN_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS( 
	ULD_ID INT(2) NOT NULL AUTO_INCREMENT, 
	ULD_LOGINID VARCHAR(40) NOT NULL, 
	ULD_USERSTAMP VARCHAR(50) NOT NULL,
	ULD_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ULD_ID),
	UNIQUE (ULD_LOGINID))'));
	PREPARE CREATE_USERLOGINDETAILS FROM @CREATE_USER_LOGIN_DETAILS;
	EXECUTE CREATE_USERLOGINDETAILS;  
	SET @DROP_USERADMINREPORTDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS'));
	PREPARE DROP_USER_ADMIN_REPORT_DETAILS_STMT FROM @DROP_USERADMINREPORTDETAILS;
	EXECUTE DROP_USER_ADMIN_REPORT_DETAILS_STMT;
	SET @CREATE_USERADMINREPORTDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS(
	UARD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
	UARD_REPORT	TEXT NULL,
	UARD_REASON	TEXT NULL,
	UARD_DATE	DATE NOT NULL,
	URC_ID INTEGER(2) NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	UARD_PERMISSION	INTEGER	NULL,
	UARD_ATTENDANCE	INTEGER	NOT NULL,
	UARD_PDID	TEXT NULL,
	UARD_AM_SESSION	INTEGER NOT NULL,
	UARD_PM_SESSION	INTEGER	NOT NULL,
	UARD_BANDWIDTH DECIMAL(6,2) NOT NULL,
	UARD_USERSTAMP_ID	INTEGER	NOT NULL,
	UARD_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	ABSENT_FLAG	CHAR(1) NULL,
	PRIMARY KEY(UARD_ID),
	FOREIGN KEY(URC_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID),
	FOREIGN KEY(UARD_USERSTAMP_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_USER_ADMIN_REPORT_DETAILS_STMT FROM @CREATE_USERADMINREPORTDETAILS;
	EXECUTE CREATE_USER_ADMIN_REPORT_DETAILS_STMT;
	SET FOREIGN_KEY_CHECKS=1;
	COMMIT;
END;
