DROP TRIGGER IF EXISTS TRG_CUSTOMER_PERSONAL_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_CUSTOMER_PERSONAL_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON CUSTOMER_PERSONAL_DETAILS
FOR EACH ROW
BEGIN
    CALL  SP_TRG_CUSTOMER_PERSONAL_DETAILS_VALIDATION(NEW.CUSTOMER_ID,NEW.CPD_MOBILE,NEW.CPD_INTL_MOBILE,NEW.CPD_PASSPORT_NO,NEW.CPD_PASSPORT_DATE,NEW.CPD_EP_NO,NEW.CPD_EP_DATE,'INSERT');
END;