-- VERSION 0.4 STARTDATE:11/10/2014 ENDDATE:11/10/2014 ISSUE NO:78 COMMENT NO:148 DESC:SPLITTED FROM HALFDAY LEAVE SP. DONE BY :RAJA
-- VERSION 0.3 STARTDATE:08/10/2014 ENDDATE:09/10/2014 ISSUE NO:78 COMMENT NO:129 DESC:ADDED NEW KEYWORDS FOR THE NEW REPORTS SCDB MIG. DONE BY :RAJA
-- VERSION 0.2 STARTDATE:05/08/2014 ENDDATE:06/08/2014 ISSUE NO:78 COMMENT NO:45 DESC:ADDED NEW KEY WORDS FOR THE NEW MIG REPORT. DONE BY :RAJA
-- VERSION 0.1 STARTDATE:26/08/2014 ENDDATE:27/08/2014 ISSUE NO:78 COMMENT NO:33 DESC:SP FOR INSERT THE HALF DAY LEAVE REPORTS. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TS_MIG_REPORT_DETAILS_MRNG_ABSENT_INSERT;
CREATE PROCEDURE SP_TS_MIG_REPORT_DETAILS_MRNG_ABSENT_INSERT(
IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	DECLARE MRNG_UREPORT TEXT;
	DECLARE MRNG_TIMESTAMP TIMESTAMP;
	DECLARE MRNG_USERSTAMP VARCHAR(50);
	DECLARE MRNG_MIN_ID INT;
	DECLARE MRNG_MAX_ID INT;
	DECLARE STR_REASON TEXT;
	DECLARE STR_REPORT TEXT;
	DECLARE STR_LOCATION INTEGER;
	DECLARE STR_MID TEXT; 
	DECLARE UARDMAX_ID INTEGER;
	DECLARE LOCATION INTEGER;
	DECLARE MAX_ID INT;   
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
	-- TEMP TABLE FOR HALF DAY LEAVE
	SET START_TIME = (SELECT CURTIME());
	SET @DROP_TEMP_HALF_DAY_LEAVE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE'));
	PREPARE DROP_TEMP_HALF_DAY_LEAVE_STMT FROM @DROP_TEMP_HALF_DAY_LEAVE;
	EXECUTE DROP_TEMP_HALF_DAY_LEAVE_STMT;
	SET @CREATE_TEMP_HALF_DAY_LEAVE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UID INT(11) NOT NULL,
	UNAME VARCHAR(255) DEFAULT NULL,
	UDATE VARCHAR(255) DEFAULT NULL,
	UREPORT TEXT,
	USERSTAMP VARCHAR(255) DEFAULT NULL,
	TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
	PREPARE CREATE_TEMP_ABSENT_STMT FROM @CREATE_TEMP_HALF_DAY_LEAVE;
	EXECUTE CREATE_TEMP_ABSENT_STMT;
	SET @INSERT_TEMPHALFDAYLEAVE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
	(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%half%day%absent%" OR UREPORT LIKE "%worked upto 2.20 pm%"
	OR UREPORT LIKE "morning%absent%"  OR UREPORT LIKE "%half%leave%"  OR UREPORT LIKE "%morning%leave%" OR UREPORT LIKE "%AFTERNOON%LEAVE%" OR UREPORT LIKE "%Permission: 2.30pm%" OR UREPORT LIKE "Came at  8.30am%" 
	OR UREPORT LIKE "%Permission 3 pm - 7 p%" OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Came to office at 11 and%" 
	OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%" OR UREPORT LIKE "%AFT%ABSENT%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "1.came at 1.30%" 
	OR UREPORT LIKE "1.Came at 11 am n%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%" OR UREPORT LIKE "1.Came office at 4.20%" OR UREPORT LIKE "come to office at 1%" 
	OR UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%ABSENT%" OR UREPORT LIKE "%home 2 pm - to 4 pm%") AND UREPORT NOT LIKE "%after  half day%" AND UREPORT NOT LIKE "%half day but there%" 
	AND UREPORT NOT LIKE "%half day%full day%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%")'));
	PREPARE INSERT_TEMP_HALF_DAY_LEAVE_STMT FROM @INSERT_TEMPHALFDAYLEAVE;
	EXECUTE INSERT_TEMP_HALF_DAY_LEAVE_STMT;  
	SET @DELETE_TEMPHALFDAYLEAVE=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE)'));
	PREPARE DELETE_TEMPHALFDAYLEAVE_STMT FROM @DELETE_TEMPHALFDAYLEAVE;
	EXECUTE DELETE_TEMPHALFDAYLEAVE_STMT;
	-- TABLE FOR MORNG LEAVE
	SET @DROP_TEMP_HALF_DAY_MRNG=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE DROP_TEMP_HALF_DAY_MRNG_STMT FROM @DROP_TEMP_HALF_DAY_MRNG;
	EXECUTE DROP_TEMP_HALF_DAY_MRNG_STMT; 
	SET @CREATE_TEMP_HALF_DAY_MRNG=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UID INT(11) NOT NULL ,
	UNAME VARCHAR(255) DEFAULT NULL,
	UDATE VARCHAR(255) DEFAULT NULL,
	UREPORT TEXT,
	USERSTAMP VARCHAR(255) DEFAULT NULL,
	TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
	PREPARE CREATE_TEMP_ABSENT_STMT FROM @CREATE_TEMP_HALF_DAY_MRNG;
	EXECUTE CREATE_TEMP_ABSENT_STMT;
	SET @INSERT_TEMPHALFDAYMORNG=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
	(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" 
	OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Come to office at 1.%" OR UREPORT LIKE "%(half a day - AM)%" OR UREPORT LIKE "come to office at 1%" OR UREPORT LIKE "%OFFICE AT 1.15%" 
	OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "1.came at 1.30%" OR UREPORT LIKE "1.Came office at 4.20%")AND UREPORT NOT LIKE "%ernoon%" 
	AND UREPORT NOT LIKE "1.CAME TO OFFICE FOR MORNING%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%")'));
	PREPARE INSERT_TEMP_HALF_DAY_MRNG_STMT FROM @INSERT_TEMPHALFDAYMORNG;
	EXECUTE INSERT_TEMP_HALF_DAY_MRNG_STMT;  
	-- QUERY FOR ALTER AUTO_INCREMENT 
	SET @MAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @MRNG_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE MAX_ID_STMT FROM @MAXID;
	EXECUTE MAX_ID_STMT;
	SET MAX_ID=@MRNG_MAX_ID;
	IF (MAX_ID IS NOT NULL) THEN    
		SET @ALTER_TEMP_HALF_DAY_MRNG =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG AUTO_INCREMENT=',MAX_ID));
		PREPARE ALTER_TEMP_HALF_DAY_MRNG_STMT FROM @ALTER_TEMP_HALF_DAY_MRNG;
		EXECUTE ALTER_TEMP_HALF_DAY_MRNG_STMT;
	END IF;
	SET @INSERT_TEMPHALFDAYMORNG=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
	(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "%HALF%day%"  OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
	AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%" AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
	AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%" AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND TIME(TIMESTAMP)>"03:00:00")'));
	PREPARE INSERT_TEMP_HALF_DAY_MRNG_STMT FROM @INSERT_TEMPHALFDAYMORNG;
	EXECUTE INSERT_TEMP_HALF_DAY_MRNG_STMT;
	-- QUERY FOR ALTER AUTO_INCREMENT 
	SET @MAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @MRNG_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE MAX_ID_STMT FROM @MAXID;
	EXECUTE MAX_ID_STMT;
	SET MAX_ID=@MRNG_MAX_ID;
	IF (MAX_ID IS NOT NULL) THEN    
		SET @ALTER_TEMP_HALF_DAY_MRNG =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG AUTO_INCREMENT=',MAX_ID));
		PREPARE ALTER_TEMP_HALF_DAY_MRNG_STMT FROM @ALTER_TEMP_HALF_DAY_MRNG;
		EXECUTE ALTER_TEMP_HALF_DAY_MRNG_STMT;
	END IF;
	SET @INSERT_TEMPHALFDAYMORNG=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
	(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "%HALF%day%"  OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
	AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%" AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
	AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%" AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND TIMESTAMP IS NULL)'));
	PREPARE INSERT_TEMP_HALF_DAY_MRNG_STMT FROM @INSERT_TEMPHALFDAYMORNG;
	EXECUTE INSERT_TEMP_HALF_DAY_MRNG_STMT;
	-- QUERY FOR ALTER AUTO_INCREMENT 
	SET @MAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @MRNG_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE MAX_ID_STMT FROM @MAXID;
	EXECUTE MAX_ID_STMT;
	SET MAX_ID=@MRNG_MAX_ID;
	IF (MAX_ID IS NOT NULL) THEN    
		SET @ALTER_TEMP_HALF_DAY_MRNG =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG AUTO_INCREMENT=',MAX_ID));
		PREPARE ALTER_TEMP_HALF_DAY_MRNG_STMT FROM @ALTER_TEMP_HALF_DAY_MRNG;
		EXECUTE ALTER_TEMP_HALF_DAY_MRNG_STMT;
	END IF;
	SET @DELETE_TEMPHALFDAYLEAVEMRNG=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG)'));
	PREPARE DELETE_TEMPHALFDAYLEAVEMRNG_STMT FROM @DELETE_TEMPHALFDAYLEAVEMRNG;
	EXECUTE DELETE_TEMPHALFDAYLEAVEMRNG_STMT;

	-- FOR TEMP_HALF_DAY_MRNG
	SET @MRNGMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @MRNGMIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE MRNGMIN_ID_STMT FROM @MRNGMINID;
	EXECUTE MRNGMIN_ID_STMT;
	SET @MRNGMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @MRNGMAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE MRNGMAX_ID_STMT FROM @MRNGMAXID;
	EXECUTE MRNGMAX_ID_STMT;
	SET MRNG_MIN_ID = @MRNGMIN_ID;
	SET MRNG_MAX_ID = @MRNGMAX_ID;
	WHILE(MRNG_MIN_ID <= MRNG_MAX_ID)DO         
		SET @SELECT_MRNG_USERSTAMP_TIMESTAMP=(SELECT CONCAT('SELECT UREPORT, USERSTAMP, `TIMESTAMP` INTO @MUREPORT, @MUSERSTAMP, @MTIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID));
		PREPARE SELECT_MRNG_USERSTAMP_TIMESTAMP_STMT FROM @SELECT_MRNG_USERSTAMP_TIMESTAMP;
		EXECUTE SELECT_MRNG_USERSTAMP_TIMESTAMP_STMT;
		SET MRNG_UREPORT=@MUREPORT;
		SET MRNG_USERSTAMP=@MUSERSTAMP;
		SET MRNG_TIMESTAMP=@MTIMESTAMP;
		SET LOCATION=(SELECT LOCATE('Reason',MRNG_UREPORT));        
		IF (MRNG_UREPORT IS NOT NULL) THEN
			IF (LOCATION>0) THEN 
				SET STR_LOCATION=(SELECT LOCATE('Reason',MRNG_UREPORT)-1);
				SET STR_MID=(SELECT MID(MRNG_UREPORT,STR_LOCATION,6));
				SET STR_REPORT=(SELECT SUBSTRING_INDEX(MRNG_UREPORT,STR_MID,+1));
				SET STR_REASON=(SELECT SUBSTRING(MRNG_UREPORT,STR_LOCATION));
				SET STR_REPORT=(SELECT REPLACE(REPLACE(REPLACE(STR_REPORT,'(',''),'-',' '),')', ''));
				SET STR_REASON=(SELECT REPLACE(REPLACE(REPLACE(STR_REASON,'(',''),'-',' '),')', ''));
				IF (STR_REPORT IS NOT NULL OR STR_REASON IS NOT NULL) THEN
					IF (MRNG_USERSTAMP IS NOT NULL OR MRNG_TIMESTAMP IS NOT NULL) THEN
						SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
						(("',STR_REPORT,'"),("',STR_REASON,'"),    
						(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
						(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0.5" AND CGN_ID=5),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
						(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',MRNG_MIN_ID,'),
						(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
						(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
						(SELECT DISTINCT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'))'));      
						PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
						EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;     
						-- QUERY FOR ALTER AUTO_INCREMENT 
						SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
						PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
						EXECUTE UARD_MAX_ID_STMT;
						SET UARDMAX_ID=@UARD_MAX_ID;
						IF (UARDMAX_ID IS NOT NULL) THEN    
							SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
							PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
							EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
						END IF;
					END IF; 
					IF (MRNG_USERSTAMP IS NULL OR MRNG_TIMESTAMP IS NULL) THEN
						SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
						(("',STR_REPORT,'"),("',STR_REASON,'"),     
						(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
						(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0.5" AND CGN_ID=5),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
						(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',MRNG_MIN_ID,'),
						(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
						(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
						(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'))'));      
						PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
						EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;   
						-- QUERY FOR ALTER AUTO_INCREMENT 
						SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
						PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
						EXECUTE UARD_MAX_ID_STMT;
						SET UARDMAX_ID=@UARD_MAX_ID;
						IF (UARDMAX_ID IS NOT NULL) THEN    
							SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
							PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
							EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
						END IF;
					END IF; 
				END IF;
			END IF;
			IF(LOCATION=0) THEN
				IF (MRNG_USERSTAMP IS NOT NULL OR MRNG_TIMESTAMP IS NOT NULL) THEN            
					SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
					(("',MRNG_UREPORT,'"),("NO REASON"),    
					(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
					(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'),
					(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0.5" AND CGN_ID=5),
					(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
					(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
					(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',MRNG_MIN_ID,'),
					(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
					(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
					(SELECT DISTINCT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'))'));      
					PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
					EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT; 
					-- QUERY FOR ALTER AUTO_INCREMENT 
					SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
					PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
					EXECUTE UARD_MAX_ID_STMT;
					SET UARDMAX_ID=@UARD_MAX_ID;
					IF (UARDMAX_ID IS NOT NULL) THEN    
						SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
						PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
						EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
					END IF;
				END IF; 
				IF (MRNG_USERSTAMP IS NULL OR MRNG_TIMESTAMP IS NULL) THEN
					SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
					(("',MRNG_UREPORT,'"),("NO REASON"),    
					(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
					(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'),
					(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0.5" AND CGN_ID=5),
					(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
					(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
					(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',MRNG_MIN_ID,'),
					(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
					(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,')),
					(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG WHERE ID=',MRNG_MIN_ID,'))'));      
					PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
					EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;   
					-- QUERY FOR ALTER AUTO_INCREMENT 
					SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
					PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
					EXECUTE UARD_MAX_ID_STMT;
					SET UARDMAX_ID=@UARD_MAX_ID;
					IF (UARDMAX_ID IS NOT NULL) THEN    
						SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
						PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
						EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
					END IF;             
				END IF;
			END IF;
		END IF;
		SET MRNG_MIN_ID=MRNG_MIN_ID+1;
	END WHILE;         
	SET @DROP_TEMP_HALF_DAY_MRNG=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MRNG'));
	PREPARE DROP_TEMP_HALF_DAY_MRNG_STMT FROM @DROP_TEMP_HALF_DAY_MRNG;
	EXECUTE DROP_TEMP_HALF_DAY_MRNG_STMT; 
	SET END_TIME = (SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @INSERT_TEMP_DURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_DURATION(DURATION)VALUES(','"',DURATION,'"',')'));
	PREPARE INSERT_TEMP_DURATION_STMT FROM @INSERT_TEMP_DURATION;
	EXECUTE INSERT_TEMP_DURATION_STMT;
	COMMIT;
END;
/*
CALL SP_TS_MIG_REPORT_DETAILS_MRNG_ABSENT_INSERT('TS_DEST');
*/