INSERT INTO raja_dest.admin_weekly_report_details
(AWRD_REPORT, AWRD_DATE, ULD_ID, AWRD_TIMESTAMP) 
VALUES ('AWRD_REPORT', 'AWRD_DATE', ULD_ID, 'AWRD_TIMESTAMP');
INSERT INTO raja_dest.attendance_configuration
(CGN_ID, AC_DATA, ULD_ID, AC_TIMESTAMP) 
VALUES (CGN_ID, 'AC_DATA', ULD_ID, 'AC_TIMESTAMP');
INSERT INTO raja_dest.basic_menu_profile
(URC_ID, MP_ID, ULD_ID, BMP_TIMESTAMP) 
VALUES (URC_ID, MP_ID, ULD_ID, 'BMP_TIMESTAMP');
INSERT INTO raja_dest.basic_role_profile
(URC_ID, BRP_BR_ID, ULD_ID, BRP_TIMESTAMP) 
VALUES (URC_ID, BRP_BR_ID, ULD_ID, 'BRP_TIMESTAMP');
INSERT INTO raja_dest.company_properties_details
(EMP_ID, CPD_LAPTOP_NUMBER, CPD_CHARGER_NUMBER, CPD_LAPTOP_BAG, CPD_MOUSE, CPD_DOOR_ACCESS, CPD_ID_CARD, CPD_HEADSET, ULD_ID, CPD_TIMESTAMP) 
VALUES (EMP_ID, 'CPD_LAPTOP_NUMBER', 'CPD_CHARGER_NUMBER', 'CPD_LAPTOP_BAG', 'CPD_MOUSE', 'CPD_DOOR_ACCESS', 'CPD_ID_CARD', 'CPD_HEADSET', ULD_ID, 'CPD_TIMESTAMP');
INSERT INTO raja_dest.configuration
(CNP_ID, CGN_TYPE) 
VALUES (CNP_ID, 'CGN_TYPE');
INSERT INTO raja_dest.configuration_profile
(CNP_DATA) 
VALUES ('CNP_DATA');
INSERT INTO raja_dest.employee_details
(ULD_ID, EMP_FIRST_NAME, EMP_LAST_NAME, EMP_DOB, EMP_DESIGNATION, EMP_MOBILE_NUMBER, EMP_NEXT_KIN_NAME, EMP_RELATIONHOOD, EMP_ALT_MOBILE_NO, EMP_USERSTAMP_ID, EMP_TIMESTAMP) 
VALUES (ULD_ID, 'EMP_FIRST_NAME', 'EMP_LAST_NAME', 'EMP_DOB', 'EMP_DESIGNATION', 'EMP_MOBILE_NUMBER', 'EMP_NEXT_KIN_NAME', 'EMP_RELATIONHOOD', 'EMP_ALT_MOBILE_NO', EMP_USERSTAMP_ID, 'EMP_TIMESTAMP');
INSERT INTO raja_dest.error_message_configuration
(CNP_ID, EMC_CODE, EMC_DATA, ULD_ID, EMC_TIMESTAMP) 
VALUES (CNP_ID, EMC_CODE, 'EMC_DATA', ULD_ID, 'EMC_TIMESTAMP');
INSERT INTO raja_dest.menu_profile
(MP_MNAME, MP_MSUB, MP_MSUBMENU, MP_MFILENAME, MP_SCRIPT_FLAG) 
VALUES ('MP_MNAME', 'MP_MSUB', 'MP_MSUBMENU', 'MP_MFILENAME', 'MP_SCRIPT_FLAG');
INSERT INTO raja_dest.onduty_entry_details
(OED_DATE, OED_DESCRIPTION, ULD_ID, OED_TIMESTAMP) 
VALUES ('OED_DATE', 'OED_DESCRIPTION', ULD_ID, 'OED_TIMESTAMP');
INSERT INTO raja_dest.project_configuration
(CGN_ID, PC_DATA, ULD_ID, PC_TIMESTAMP) 
VALUES (CGN_ID, 'PC_DATA', ULD_ID, 'PC_TIMESTAMP');
INSERT INTO raja_dest.project_details
(PD_PROJECT_NAME, PD_PROJECT_DESCRIPTION, ULD_ID, PD_TIMESTAMP) 
VALUES ('PD_PROJECT_NAME', 'PD_PROJECT_DESCRIPTION', ULD_ID, 'PD_TIMESTAMP');
INSERT INTO raja_dest.project_status
(PD_ID, PC_ID, PS_REC_VER, PS_START_DATE, PS_END_DATE, ULD_ID, PS_TIMESTAMP) 
VALUES (PD_ID, PC_ID, PS_REC_VER, 'PS_START_DATE', 'PS_END_DATE', ULD_ID, 'PS_TIMESTAMP');
INSERT INTO raja_dest.public_holiday
(PH_DESCRIPTION, PH_DATE) 
VALUES ('PH_DESCRIPTION', 'PH_DATE');
INSERT INTO raja_dest.report_configuration
(CGN_ID, RC_DATA, ULD_ID, RC_TIMESTAMP) 
VALUES (CGN_ID, 'RC_DATA', ULD_ID, 'RC_TIMESTAMP');
INSERT INTO raja_dest.role_creation
(URC_ID, RC_NAME, RC_USERSTAMP, RC_TIMESTAMP) 
VALUES (URC_ID, 'RC_NAME', 'RC_USERSTAMP', 'RC_TIMESTAMP');
INSERT INTO raja_dest.temp_bandwidth_calculation20141016133034_1
(LOGINID, BANDWIDTH_MB) 
VALUES ('LOGINID', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016133108_1
(REPORT_DATE, BANDWIDTH_MB) 
VALUES ('REPORT_DATE', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016133141_1
(LOGINID, BANDWIDTH_MB) 
VALUES ('LOGINID', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016133205_1
(REPORT_DATE, BANDWIDTH_MB) 
VALUES ('REPORT_DATE', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016133232_1
(REPORT_DATE, BANDWIDTH_MB) 
VALUES ('REPORT_DATE', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016133252_1
(LOGINID, BANDWIDTH_MB) 
VALUES ('LOGINID', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016152904_1
(LOGINID, BANDWIDTH_MB) 
VALUES ('LOGINID', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016153045_1
(LOGINID, BANDWIDTH_MB) 
VALUES ('LOGINID', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_bandwidth_calculation20141016153844_1
(LOGINID, BANDWIDTH_MB) 
VALUES ('LOGINID', BANDWIDTH_MB);
INSERT INTO raja_dest.temp_dynamic
(UID, UNAME, UDATE, UREPORT, USERSTAMP, `TIMESTAMP`) 
VALUES (UID, 'UNAME', 'UDATE', 'UREPORT', 'USERSTAMP', 'TIMESTAMP');
INSERT INTO raja_dest.temp_half_day_aftn
(UID, UNAME, UDATE, UREPORT, USERSTAMP, `TIMESTAMP`) 
VALUES (UID, 'UNAME', 'UDATE', 'UREPORT', 'USERSTAMP', 'TIMESTAMP');
INSERT INTO raja_dest.temp_half_day_mrng
(UID, UNAME, UDATE, UREPORT, USERSTAMP, `TIMESTAMP`) 
VALUES (UID, 'UNAME', 'UDATE', 'UREPORT', 'USERSTAMP', 'TIMESTAMP');
INSERT INTO raja_dest.temp_key
(HR, DATA) 
VALUES ('HR', 'DATA');
INSERT INTO raja_dest.temp_permission
(UID, UNAME, UDATE, UREPORT, USERSTAMP, `TIMESTAMP`) 
VALUES (UID, 'UNAME', 'UDATE', 'UREPORT', 'USERSTAMP', 'TIMESTAMP');
INSERT INTO raja_dest.temp_project_revenue_20141016162208_1
(USERNAME, TOT_NO_OF_DAYS) 
VALUES ('USERNAME', TOT_NO_OF_DAYS);
INSERT INTO raja_dest.temp_project_revenue_20141016162342_1
(USERNAME, TOT_NO_OF_DAYS) 
VALUES ('USERNAME', TOT_NO_OF_DAYS);
INSERT INTO raja_dest.temp_project_revenue_20141016162400_1
(USERNAME, TOT_NO_OF_DAYS) 
VALUES ('USERNAME', TOT_NO_OF_DAYS);
INSERT INTO raja_dest.temp_project_revenue_20141016162753_1
(USERNAME, TOT_NO_OF_DAYS) 
VALUES ('USERNAME', TOT_NO_OF_DAYS);
INSERT INTO raja_dest.temp_project_revenue_20141016163253_1
(USERNAME, TOT_NO_OF_DAYS) 
VALUES ('USERNAME', TOT_NO_OF_DAYS);
INSERT INTO raja_dest.temp_reports
(UID, UNAME, UDATE, UREPORT, USERSTAMP, `TIMESTAMP`) 
VALUES (UID, 'UNAME', 'UDATE', 'UREPORT', 'USERSTAMP', 'TIMESTAMP');
INSERT INTO raja_dest.temp_user_rights_scdb_format
(siloId, `timeStamp`, Uname, userStamp, URecVer, UTerminate, UEDate, Rid, roles, UJDate, UReason, UJoin, Udate, Ureport, Uid) 
VALUES ('siloId', 'timeStamp', 'Uname', 'userStamp', 'URecVer', 'UTerminate', 'UEDate', Rid, 'roles', 'UJDate', 'UReason', 'UJoin', 'Udate', 'Ureport', 'Uid');
INSERT INTO raja_dest.tickler_profile
(TP_TYPE) 
VALUES ('TP_TYPE');
INSERT INTO raja_dest.tickler_tabid_profile
(TTIP_DATA) 
VALUES ('TTIP_DATA');
INSERT INTO raja_dest.user_access
(RC_ID, ULD_ID, UA_REC_VER, UA_JOIN_DATE, UA_JOIN, UA_END_DATE, UA_TERMINATE, UA_REASON, UA_EMP_TYPE, UA_USERSTAMP, UA_TIMESTAMP) 
VALUES (RC_ID, ULD_ID, UA_REC_VER, 'UA_JOIN_DATE', 'UA_JOIN', 'UA_END_DATE', 'UA_TERMINATE', 'UA_REASON', UA_EMP_TYPE, 'UA_USERSTAMP', 'UA_TIMESTAMP');
INSERT INTO raja_dest.user_admin_report_details
(UARD_REPORT, UARD_REASON, UARD_DATE, URC_ID, ULD_ID, UARD_PERMISSION, UARD_ATTENDANCE, UARD_PDID, UARD_AM_SESSION, UARD_PM_SESSION, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP, ABSENT_FLAG) 
VALUES ('UARD_REPORT', 'UARD_REASON', 'UARD_DATE', URC_ID, ULD_ID, UARD_PERMISSION, UARD_ATTENDANCE, 'UARD_PDID', UARD_AM_SESSION, UARD_PM_SESSION, UARD_BANDWIDTH, UARD_USERSTAMP_ID, 'UARD_TIMESTAMP', 'ABSENT_FLAG');
INSERT INTO raja_dest.user_login_details
(ULD_LOGINID, ULD_USERSTAMP, ULD_TIMESTAMP) 
VALUES ('ULD_LOGINID', 'ULD_USERSTAMP', 'ULD_TIMESTAMP');
INSERT INTO raja_dest.user_menu_details
(MP_ID, RC_ID, ULD_ID, UMD_TIMESTAMP) 
VALUES (MP_ID, RC_ID, ULD_ID, 'UMD_TIMESTAMP');
INSERT INTO raja_dest.user_rights_configuration
(CGN_ID, URC_DATA, URC_USERSTAMP, URC_TIMESTAMP) 
VALUES (CGN_ID, 'URC_DATA', 'URC_USERSTAMP', 'URC_TIMESTAMP');
