DROP TRIGGER IF EXISTS TRG_EMPLOYEE_DETAILS_UPDATE_VALIDATION;
CREATE TRIGGER TRG_EMPLOYEE_DETAILS_UPDATE_VALIDATION
BEFORE UPDATE ON EMPLOYEE_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TRG_EMPLOYEE_DETAILS_VALIDATION (NEW.EMP_MOBILE,'UPDATE');
END;