DROP TRIGGER IF EXISTS TRG_EMPLOYEE_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_EMPLOYEE_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON EMPLOYEE_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TRG_EMPLOYEE_DETAILS_VALIDATION (NEW.EMP_MOBILE,'INSERT');
END;