DROP PROCEDURE IF EXISTS SP_TS_MIG_REPORT_DETAILS_PERMISSION_INSERT;
CREATE PROCEDURE SP_TS_MIG_REPORT_DETAILS_PERMISSION_INSERT(
IN DESTINATIONSCHEMA VARCHAR(40))
BEGIN
	DECLARE PER_UREPORT TEXT;
	DECLARE PER_TIMESTAMP TIMESTAMP;
	DECLARE PER_USERSTAMP VARCHAR(50);
	DECLARE PER_MIN_ID INT;
	DECLARE PER_MAX_ID INT;
	DECLARE KEY_MIN_ID INT;
	DECLARE KEY_MAX_ID INT;
	DECLARE UARDMAX_ID INTEGER;
	DECLARE MAX_ID INT;
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE STR_REASON TEXT;
	DECLARE STR_REPORT TEXT;
	DECLARE STR_LOCATION INTEGER;
	DECLARE STR_MID TEXT; 
	DECLARE LOCATION INTEGER;
	DECLARE HALF_LEAVE_PER INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;	
	SET START_TIME = (SELECT CURTIME());
	SET @DROP_TEMP_PERMISSION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_PERMISSION'));
	PREPARE DROP_TEMP_PERMISSION_STMT FROM @DROP_TEMP_PERMISSION;
	EXECUTE DROP_TEMP_PERMISSION_STMT;
	SET @CREATE_TEMP_PERMISSION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_PERMISSION (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UID INT(11) NOT NULL ,
	UNAME VARCHAR(255) DEFAULT NULL,
	UDATE VARCHAR(255) DEFAULT NULL,
	UREPORT TEXT,
	USERSTAMP VARCHAR(255) DEFAULT NULL,
	TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
	PREPARE CREATE_TEMP_PERMISSION_STMT FROM @CREATE_TEMP_PERMISSION;
	EXECUTE CREATE_TEMP_PERMISSION_STMT;
	SET @INSERT_TEMPPERMISSION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_PERMISSION(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
	(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%PERMISSION%" OR UREPORT LIKE "%PERSMISSION%" OR UREPORT LIKE "%HR PERMISSON%" 
	OR UREPORT LIKE "%LEFT OFFICE AT 4.15 P.M%" OR UREPORT LIKE "Came at 12%" OR UREPORT LIKE "Came to office at 1%" OR UREPORT LIKE "come to office by 12%" OR UREPORT LIKE "went out at%" OR UREPORT LIKE "worked till 3.30 pm%" 
	OR UREPORT LIKE "1.Came to office at 10.%" OR UREPORT LIKE "1.came at 12%o clock%" OR UREPORT LIKE "1.came at 11.%") AND UREPORT NOT LIKE "%Half day permission%" AND UREPORT NOT LIKE "%the permission%" 
	AND UREPORT NOT LIKE "%provide permission%" AND UREPORT NOT LIKE "%Select permission%" AND UREPORT NOT LIKE "%GRANT%permission%" AND UREPORT NOT LIKE "%Revoke permissioin%" AND UREPORT NOT LIKE "%Access permission%" 
	AND UREPORT NOT LIKE "%view permission%" AND UREPORT NOT LIKE "%need permission%" AND UREPORT NOT LIKE "%GIVE PERMISSION%" AND UREPORT NOT LIKE "%GIVEn PERMISSION%" AND UREPORT NOT LIKE "%employee permission%" 
	AND UREPORT NOT LIKE "%CHECKING PERMISSION%" AND UREPORT NOT LIKE "%edit PERMISSION%" AND UREPORT NOT LIKE "%permission cant%" AND UREPORT NOT LIKE "%an permission%" AND UREPORT NOT LIKE "%& permission%"
	AND UREPORT NOT LIKE "%Permission: 2.30pm%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing permission%" AND UREPORT NOT LIKE "%table permission%" AND UREPORT NOT LIKE "%Left office at 2p%"
	AND UREPORT NOT LIKE "%Permission 3 pm - 7 p%" )'));
	PREPARE INSERT_TEMP_PERMISSION_STMT FROM @INSERT_TEMPPERMISSION;
	EXECUTE INSERT_TEMP_PERMISSION_STMT;  
	SET @DELETE_TEMPPERMISSION=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_PERMISSION)'));
	PREPARE DELETE_TEMPPERMISSION_STMT FROM @DELETE_TEMPPERMISSION;
	EXECUTE DELETE_TEMPPERMISSION_STMT;
	SET @DROP_TEMP_DYNAMIC=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC'));
	PREPARE DROP_TEMP_DYNAMIC_STMT FROM @DROP_TEMP_DYNAMIC;
	EXECUTE DROP_TEMP_DYNAMIC_STMT;
	SET @CREATE_TEMP_DYNAMIC=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UID INT(11) NOT NULL ,
	UNAME VARCHAR(255) DEFAULT NULL,
	UDATE VARCHAR(255) DEFAULT NULL,
	UREPORT TEXT,
	USERSTAMP VARCHAR(255) DEFAULT NULL,
	TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
	PREPARE CREATE_DROP_TEMP_DYNAMIC_STMT FROM @CREATE_TEMP_DYNAMIC;
	EXECUTE CREATE_DROP_TEMP_DYNAMIC_STMT;
	SET @DROP_TEMP_DYNAMIC=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_KEY'));
	PREPARE DROP_TEMP_DYNAMIC_STMT FROM @DROP_TEMP_DYNAMIC;
	EXECUTE DROP_TEMP_DYNAMIC_STMT;
	SET @CREATE_TEMP_KEY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_KEY (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	HR TEXT NOT NULL ,
	DATA VARCHAR(255) DEFAULT NULL)'));
	PREPARE CREATE_DROP_TEMP_KEY_STMT FROM @CREATE_TEMP_KEY;
	EXECUTE CREATE_DROP_TEMP_KEY_STMT;
	SET @INSERT_TEMP_KEY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_KEY (HR,DATA) VALUES
	(1.5,"%1 1/2 h%"), (1.5, "%Permission% 1.30%"),(0.5, "%1/2 hour%"),(2.5, "%2 ND HALF%"),(1, "%1hr%"),(1, "%1 hr%"),(1, "%1 hour%"),(1, "%1hour%"),
	(2, "%2 hr%"),(2, "%2hr%"),(2, "%2 hour%"),(3, "%3 hour%"),(3, "%3 hr%"),(1, "%ONE HOUR%"),(1, "%ONE HR%"),(2, "%TWO%HOUR%"),(3, "%THREE%HOUR%"),
	(0.5, "%30 min%"),(3, "%came at 12%"),(2.5, "%came%11:30%"),(2, "%came%11.15%"),(2.5,"%2%30 hrs permission%"),(0.5,"% -5:30 TO 6:00%"),(0.5,"%18:20(FELT %"),
	(0.5,"%45 min%"),(1,"%at 4.30 to 5.30%"),(1,"%permission:5-6%"),(1,"% 6:15 pm to 7 p%"),(1.5,"%10.30 came back at 12.10pm%"),(1.5,"%:2.00 to 3.30%"),
	(1.5,"%(17:00 - 18:20)%"),(1.5,"%office at 10.30%"),(1.5,"%5.3%-%7%"),(2,"%5 pm - 7 pm%"),(2,"%from 5 clk.%"),(2,"%from 5.15 pm."),(2,"%4.45 pm to 7 pm%"),
	(2,"%from 5pm to 7pm%"),(2.5,"%3:10 PM TO 5:45%"),(2.5,"%cme at 11.30am%"),(2.5,"% at 3.30 till 6:00 pm%"),(2.5,"%( 3.30 to 6.00)%"),(2.5,"% - From  3.45P%"),
	(2.5,"%(9 to 11.45a.m)%"),(2.5,"%(9 to 11.45a.m)%"),(3,"%(permission 4.15pm to 7pm)%"),(3,"%permission-3 to 6p.m.%"),(3,"%2.45 to 6.00pm%"),(3,"%Came to office at 12%"),
	(3,"%3.45 PM  TO 7 P%"),(3,"%3.00pm to 6.0%"),(3,"%4 o%clock on%"),(3,"%till 3.30 pm %"),(3,"%(16:00 - 19:00)%"),(3,"% timing 9.50 - 1.10 %"),(3,"%LEFT OFFICE AT 4.15 P.M%")'));
	PREPARE INSERT_TEMP_KEY_STMT FROM @INSERT_TEMP_KEY;
	EXECUTE INSERT_TEMP_KEY_STMT;
	SET @KEYMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @KEYMIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_KEY'));
	PREPARE KEYMIN_ID_STMT FROM @KEYMINID;
	EXECUTE KEYMIN_ID_STMT;
	SET @KEYMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @KEYMAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_KEY'));
	PREPARE KEYMAX_ID_STMT FROM @KEYMAXID;
	EXECUTE KEYMAX_ID_STMT;
	SET KEY_MIN_ID = @KEYMIN_ID;
	SET KEY_MAX_ID = @KEYMAX_ID;
	WHILE(KEY_MIN_ID <= KEY_MAX_ID)DO      
		SET @TRUNCAT_TEMP_DYNAMIC=(SELECT CONCAT('TRUNCATE ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC'));
		PREPARE TRUNCAT_TEMP_DYNAMIC_STMT FROM @TRUNCAT_TEMP_DYNAMIC;
		EXECUTE TRUNCAT_TEMP_DYNAMIC_STMT;      
		SET @INSERT_TEMP_DYNAMIC=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC (UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
		(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_PERMISSION WHERE UREPORT LIKE (SELECT DATA FROM ',DESTINATIONSCHEMA,'.TEMP_KEY WHERE ID=',KEY_MIN_ID,'))'));
		PREPARE INSERT_TEMP_DYNAMIC_STMT FROM @INSERT_TEMP_DYNAMIC;
		EXECUTE INSERT_TEMP_DYNAMIC_STMT;
		SET @DELETE_TEMP_PERMISSION=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_PERMISSION WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC)'));
		PREPARE DELETE_TEMP_PERMISSION_STMT FROM @DELETE_TEMP_PERMISSION;
		EXECUTE DELETE_TEMP_PERMISSION_STMT;
		SET @PERMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @PERMIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC'));
		PREPARE PERMIN_ID_STMT FROM @PERMINID;
		EXECUTE PERMIN_ID_STMT;
		SET @PERMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @PERMAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC'));
		PREPARE PERMAX_ID_STMT FROM @PERMAXID;
		EXECUTE PERMAX_ID_STMT;
		SET PER_MIN_ID = @PERMIN_ID;
		SET PER_MAX_ID = @PERMAX_ID;
		WHILE(PER_MIN_ID <= PER_MAX_ID)DO         
			SET @SELECT_PER_USERSTAMP_TIMESTAMP=(SELECT CONCAT('SELECT UREPORT, USERSTAMP, `TIMESTAMP` INTO @MUREPORT, @MUSERSTAMP, @MTIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID));
			PREPARE SELECT_PER_USERSTAMP_TIMESTAMP_STMT FROM @SELECT_PER_USERSTAMP_TIMESTAMP;
			EXECUTE SELECT_PER_USERSTAMP_TIMESTAMP_STMT;
			SET PER_UREPORT=@MUREPORT;
			SET PER_USERSTAMP=@MUSERSTAMP;
			SET PER_TIMESTAMP=@MTIMESTAMP;   
			SET LOCATION=(SELECT LOCATE('Reason',PER_UREPORT));  
			SET HALF_LEAVE_PER=(SELECT LOCATE('Left the office 3 pm',PER_UREPORT));
			IF (PER_UREPORT IS NOT NULL) THEN
				IF (LOCATION>0) THEN 
					SET STR_LOCATION=(SELECT LOCATE('Reason',PER_UREPORT)-1);
					SET STR_MID=(SELECT MID(PER_UREPORT,STR_LOCATION,6));
					SET STR_REPORT=(SELECT SUBSTRING_INDEX(PER_UREPORT,STR_MID,+1));
					SET STR_REASON=(SELECT SUBSTRING(PER_UREPORT,STR_LOCATION));                
					IF (STR_REPORT IS NOT NULL OR STR_REASON IS NOT NULL) THEN
						IF (PER_USERSTAMP IS NOT NULL OR PER_TIMESTAMP IS NOT NULL) THEN            
							SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_PERMISSION,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
							(("',STR_REPORT,'"),("',STR_REASON,'"),        
							(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE CGN_ID=6 AND AC_DATA=(SELECT HR FROM ',DESTINATIONSCHEMA,'.TEMP_KEY WHERE ID=',KEY_MIN_ID,')),
							(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="1" AND CGN_ID=5),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_DYNAMIC RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',PER_MIN_ID,'),
							(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(SELECT DISTINCT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'))'));      
							PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
							EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT; 
							SET @MUREPORT=NULL;
							SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
							PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
							EXECUTE UARD_MAX_ID_STMT;
							SET UARDMAX_ID=@UARD_MAX_ID;
							IF (UARDMAX_ID IS NOT NULL) THEN    
								SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
								PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
								EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
							END IF;
						END IF; 
						IF (PER_USERSTAMP IS NULL OR PER_TIMESTAMP IS NULL) THEN
							SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_PERMISSION,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
							(("',STR_REPORT,'"),("',STR_REASON,'"),     
							(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE CGN_ID=6 AND AC_DATA=(SELECT HR FROM ',DESTINATIONSCHEMA,'.TEMP_KEY WHERE ID=',KEY_MIN_ID,')),
							(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="1" AND CGN_ID=5),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_DYNAMIC RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',PER_MIN_ID,'),
							(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'))'));      
							PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
							EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;  
							SET @MUREPORT=NULL;
							SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
							PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
							EXECUTE UARD_MAX_ID_STMT;
							SET UARDMAX_ID=@UARD_MAX_ID;
							IF (UARDMAX_ID IS NOT NULL) THEN    
								SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
								PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
								EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
							END IF;             
						END IF; 
					END IF;
				END IF;
				IF (LOCATION=0) THEN
					IF (HALF_LEAVE_PER>0) THEN
						SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_PERMISSION,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
						((@MUREPORT),("NO REASON"),        
						(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE CGN_ID=6 AND AC_DATA=(SELECT HR FROM ',DESTINATIONSCHEMA,'.TEMP_KEY WHERE ID=',KEY_MIN_ID,')),
						(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0.5" AND CGN_ID=5),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
						(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
						(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_DYNAMIC RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',PER_MIN_ID,'),
						(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
						(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
						(SELECT DISTINCT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'))'));      
						PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
						EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT; 
						SET @MUREPORT=NULL;
						SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
						PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
						EXECUTE UARD_MAX_ID_STMT;
						SET UARDMAX_ID=@UARD_MAX_ID;
						IF (UARDMAX_ID IS NOT NULL) THEN    
							SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
							PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
							EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
						END IF;
					END IF;
					IF (HALF_LEAVE_PER=0) THEN
						IF (PER_USERSTAMP IS NOT NULL OR PER_TIMESTAMP IS NOT NULL) THEN           
							SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_PERMISSION,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
							((@MUREPORT),("NO REASON"),    
							(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE CGN_ID=6 AND AC_DATA=(SELECT HR FROM ',DESTINATIONSCHEMA,'.TEMP_KEY WHERE ID=',KEY_MIN_ID,')),
							(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="1" AND CGN_ID=5),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_DYNAMIC RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',PER_MIN_ID,'),
							(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(SELECT DISTINCT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'))'));      
							PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
							EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT; 
							SET @MUREPORT=NULL;
							SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
							PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
							EXECUTE UARD_MAX_ID_STMT;
							SET UARDMAX_ID=@UARD_MAX_ID;
							IF (UARDMAX_ID IS NOT NULL) THEN    
								SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
								PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
								EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
							END IF;
						END IF; 
						IF (PER_USERSTAMP IS NULL OR PER_TIMESTAMP IS NULL) THEN
							SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_REASON,UARD_PDID,UARD_PERMISSION,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
							((@MUREPORT),("NO REASON"),    
							(SELECT DISTINCT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE CGN_ID=6 AND AC_DATA=(SELECT HR FROM ',DESTINATIONSCHEMA,'.TEMP_KEY WHERE ID=',KEY_MIN_ID,')),
							(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="1" AND CGN_ID=5),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
							(SELECT DISTINCT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_DYNAMIC RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',PER_MIN_ID,'),
							(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(0),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,')),
							(SELECT DISTINCT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC WHERE ID=',PER_MIN_ID,'))'));      
							PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
							EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;  
							SET @MUREPORT=NULL;
							SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
							PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
							EXECUTE UARD_MAX_ID_STMT;
							SET UARDMAX_ID=@UARD_MAX_ID;
							IF (UARDMAX_ID IS NOT NULL) THEN    
								SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
								PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
								EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
							END IF;             
						END IF;
					END IF;
				END IF;
			END IF;
			SET PER_MIN_ID=PER_MIN_ID+1;
		END WHILE;
		SET KEY_MIN_ID = KEY_MIN_ID+1;
	END WHILE;
	SET @DROP_TEMP_DYNAMIC=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_KEY'));
	PREPARE DROP_TEMP_DYNAMIC_STMT FROM @DROP_TEMP_DYNAMIC;
	EXECUTE DROP_TEMP_DYNAMIC_STMT;
	SET @DROP_TEMP_DYNAMIC=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_DYNAMIC'));
	PREPARE DROP_TEMP_DYNAMIC_STMT FROM @DROP_TEMP_DYNAMIC;
	EXECUTE DROP_TEMP_DYNAMIC_STMT;
	SET @DROP_TEMP_PERMISSION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_PERMISSION'));
	PREPARE DROP_TEMP_PERMISSION_STMT FROM @DROP_TEMP_PERMISSION;
	EXECUTE DROP_TEMP_PERMISSION_STMT;
	SET END_TIME = (SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @INSERT_TEMP_DURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_DURATION(DURATION)VALUES(','"',DURATION,'"',')'));
	PREPARE INSERT_TEMP_DURATION_STMT FROM @INSERT_TEMP_DURATION;
	EXECUTE INSERT_TEMP_DURATION_STMT;
	COMMIT;
END;
CALL SP_TS_MIG_REPORT_DETAILS_PERMISSION_INSERT(DESTINATIONSCHEMA);