-- VERSION 0.4 STARTDATE:04/08/2014 ENDDATE:04/08/2014 ISSUE NO: 836  DESC:IMPLEMENTED CHECK CONSTRAINTS TRIGGER ERROR MSG GET FROM CONFIG TABLE. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TRG_PAYMENT_DETAILS_VALIDATION;
CREATE PROCEDURE SP_TRG_PAYMENT_DETAILS_VALIDATION(
IN NEWPDID INTEGER,
IN UNITID INTEGER,
IN CUSTOMERID INTEGER,
IN PPID INTEGER,
IN RECVERSION INTEGER,
IN FORPERIOD TEXT,
IN PROCESS TEXT)
BEGIN
	DECLARE MESSAGE_TEXT VARCHAR(50);
	DECLARE STARTDATE DATE;
	DECLARE ENDDATE DATE;
	DECLARE FOR_PERIOD_DATE DATE;
	DECLARE STARTDATE_MONTH INTEGER;
	DECLARE STARTDATE_LENGTH INTEGER;
	DECLARE PRETERMINATEDATE DATE;
	DECLARE OLDFORPERIOD DATE;
	DECLARE OLDRECVER INTEGER;
	DECLARE OLDPPID INTEGER;
	DECLARE ERRORMSG TEXT;
	DECLARE CUSTOMERNAME VARCHAR(40);
	DECLARE CUSTOMER_FNAME VARCHAR(30);
	DECLARE CUSTOMER_LNAME VARCHAR(30);
	DECLARE MONTH_FORPERIOD INTEGER;
	DECLARE YEAR_FORPERIOD INTEGER;
	DECLARE MONTH_NAME VARCHAR(20);
	DECLARE MONTH_YEAR VARCHAR(30);
	SET OLDFORPERIOD=(SELECT PD_FOR_PERIOD FROM PAYMENT_DETAILS WHERE PD_ID=NEWPDID);
	SET OLDRECVER=(SELECT CED_REC_VER FROM PAYMENT_DETAILS WHERE PD_ID=NEWPDID);
	SET OLDPPID=(SELECT PP_ID FROM PAYMENT_DETAILS WHERE PD_ID=NEWPDID);
	IF(PROCESS = 'INSERT') THEN
		IF(FORPERIOD IS NOT NULL)THEN
			SET STARTDATE_MONTH=(SELECT MONTH(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL); 
			SET STARTDATE_LENGTH=(SELECT LENGTH(STARTDATE_MONTH));
			SET FOR_PERIOD_DATE=FORPERIOD;
			IF  (STARTDATE_LENGTH=1) THEN
				SET STARTDATE=(SELECT CONCAT((SELECT YEAR(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-','0',(SELECT MONTH(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-','01'));
			ELSE
				SET STARTDATE=(SELECT CONCAT((SELECT YEAR(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-',(SELECT MONTH(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-','01'));
			END IF;
			SET ENDDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);  
			SET PRETERMINATEDATE=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);
			IF PRETERMINATEDATE IS NOT NULL THEN
				SET ENDDATE=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);
			ELSE
				SET ENDDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);
			END IF;
			IF EXISTS(SELECT DISTINCT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_STARTDATE>CLP_PRETERMINATE_DATE ,CLP_STARTDATE>CLP_ENDDATE) AND (CLP_GUEST_CARD=' 'OR CLP_GUEST_CARD IS NULL))THEN
				SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=556);
				SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[RECVER]',RECVERSION));
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = ERRORMSG;
			END IF;
			IF FOR_PERIOD_DATE NOT BETWEEN STARTDATE AND ENDDATE THEN
				SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=557);
				SIGNAL SQLSTATE '45000'        
				SET MESSAGE_TEXT = ERRORMSG;
			END IF;
			IF (PPID=1 OR PPID=4) THEN
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=FOR_PERIOD_DATE AND PP_ID=PPID AND UNIT_ID=UNITID)THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=558);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'          
				  SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
			IF (PPID=5)THEN
				IF (FOR_PERIOD_DATE!=(SELECT ADDDATE(LAST_DAY(SUBDATE(ENDDATE, INTERVAL 1 MONTH)), 1))) THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=559);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'          
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=(SELECT ADDDATE(LAST_DAY(SUBDATE(ENDDATE, INTERVAL 1 MONTH)), 1)) AND PP_ID=PPID AND UNIT_ID=UNITID)THEN
					SET CUSTOMER_FNAME=(SELECT CUSTOMER_FIRST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMER_LNAME=(SELECT CUSTOMER_LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMERNAME=(SELECT CONCAT(CUSTOMER_FNAME,'_',CUSTOMER_LNAME));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=560);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[CUSTOMER]',CUSTOMERNAME));
					SIGNAL SQLSTATE '45000'          
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
			IF (PPID=2)THEN
				IF (FOR_PERIOD_DATE!=STARTDATE)THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=561);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'					
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=STARTDATE AND PP_ID=PPID AND UNIT_ID=UNITID)THEN 
					SET CUSTOMER_FNAME=(SELECT CUSTOMER_FIRST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMER_LNAME=(SELECT CUSTOMER_LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMERNAME=(SELECT CONCAT(CUSTOMER_FNAME,'_',CUSTOMER_LNAME));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=562);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[CUSTOMER]',CUSTOMERNAME));
					SIGNAL SQLSTATE '45000'          
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
			IF (PPID=3)THEN
				IF (FOR_PERIOD_DATE!=STARTDATE)THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=563);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'					
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;     
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=STARTDATE AND PP_ID=PPID AND UNIT_ID=UNITID)THEN
					SET CUSTOMER_FNAME=(SELECT CUSTOMER_FIRST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMER_LNAME=(SELECT CUSTOMER_LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMERNAME=(SELECT CONCAT(CUSTOMER_FNAME,'_',CUSTOMER_LNAME));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=564);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[CUSTOMER]',CUSTOMERNAME));
					SIGNAL SQLSTATE '45000'					
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
		END IF;
    END IF;
	IF(PROCESS = 'UPDATE') THEN
		IF((OLDFORPERIOD!=FORPERIOD) OR (OLDRECVER!=RECVERSION) OR (OLDPPID!=PPID))THEN
			IF NOT EXISTS (SELECT CED_REC_VER FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION) THEN
				SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=565);
				SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[REC VER]',RECVERSION));
				SIGNAL SQLSTATE '45000'						
				SET MESSAGE_TEXT = ERRORMSG;
			END IF;
			SET STARTDATE_MONTH=(SELECT MONTH(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL); 
			SET STARTDATE_LENGTH=(SELECT LENGTH(STARTDATE_MONTH));
			SET FOR_PERIOD_DATE=FORPERIOD;
			IF  (STARTDATE_LENGTH=1) THEN
				SET STARTDATE=(SELECT CONCAT((SELECT YEAR(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-','0',(SELECT MONTH(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-','01'));
			ELSE
				SET STARTDATE=(SELECT CONCAT((SELECT YEAR(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-',(SELECT MONTH(CLP_STARTDATE) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL),'-','01'));
			END IF;
			SET ENDDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);  
			SET PRETERMINATEDATE=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);
			IF PRETERMINATEDATE IS NOT NULL THEN
				SET ENDDATE=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);
			ELSE
				SET ENDDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND CLP_GUEST_CARD IS NULL);
			END IF;
			IF EXISTS(SELECT DISTINCT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_STARTDATE>CLP_PRETERMINATE_DATE ,CLP_STARTDATE>CLP_ENDDATE) AND (CLP_GUEST_CARD=' 'OR CLP_GUEST_CARD IS NULL))THEN
				SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=556);
				SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[RECVER]',RECVERSION));
				SIGNAL SQLSTATE '45000'					
				SET MESSAGE_TEXT = ERRORMSG;
			END IF;
			IF FOR_PERIOD_DATE NOT BETWEEN STARTDATE AND ENDDATE THEN
				SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=557);
				SIGNAL SQLSTATE '45000'					
				SET MESSAGE_TEXT = ERRORMSG;
			END IF;
			IF (PPID=1 OR PPID=4) THEN
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=FOR_PERIOD_DATE AND PP_ID=PPID AND UNIT_ID=UNITID)THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=558);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
			IF (PPID=5)THEN
				IF (FOR_PERIOD_DATE!=(SELECT ADDDATE(LAST_DAY(SUBDATE(ENDDATE, INTERVAL 1 MONTH)), 1))) THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=559);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=(SELECT ADDDATE(LAST_DAY(SUBDATE(ENDDATE, INTERVAL 1 MONTH)), 1)) AND PP_ID=PPID AND UNIT_ID=UNITID)THEN
					SET CUSTOMER_FNAME=(SELECT CUSTOMER_FIRST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMER_LNAME=(SELECT CUSTOMER_LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMERNAME=(SELECT CONCAT(CUSTOMER_FNAME,'_',CUSTOMER_LNAME));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=560);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[CUSTOMER]',CUSTOMERNAME));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
			IF (PPID=2)THEN
				IF (FOR_PERIOD_DATE!=STARTDATE)THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=561);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=STARTDATE AND PP_ID=PPID AND UNIT_ID=UNITID)THEN 
					SET CUSTOMER_FNAME=(SELECT CUSTOMER_FIRST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMER_LNAME=(SELECT CUSTOMER_LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMERNAME=(SELECT CONCAT(CUSTOMER_FNAME,'_',CUSTOMER_LNAME));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=562);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[CUSTOMER]',CUSTOMERNAME));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
			IF (PPID=3)THEN
				IF (FOR_PERIOD_DATE!=STARTDATE)THEN
					SET MONTH_FORPERIOD=(SELECT MONTH(FORPERIOD));
					SET YEAR_FORPERIOD=(SELECT YEAR(FORPERIOD));
					SET MONTH_NAME=(SELECT UCASE(MONTHNAME(STR_TO_DATE(MONTH_FORPERIOD, '%m'))));
					SET MONTH_YEAR=(SELECT CONCAT(MONTH_NAME,'-',YEAR_FORPERIOD));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=563);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[MONTH]',MONTH_YEAR));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;     
				IF EXISTS(SELECT * FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=CUSTOMERID AND CED_REC_VER=RECVERSION AND PD_FOR_PERIOD=STARTDATE AND PP_ID=PPID AND UNIT_ID=UNITID)THEN
					SET CUSTOMER_FNAME=(SELECT CUSTOMER_FIRST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMER_LNAME=(SELECT CUSTOMER_LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID=CUSTOMERID);
					SET CUSTOMERNAME=(SELECT CONCAT(CUSTOMER_FNAME,'_',CUSTOMER_LNAME));
					SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=564);
					SET ERRORMSG=(SELECT REPLACE(ERRORMSG,'[CUSTOMER]',CUSTOMERNAME));
					SIGNAL SQLSTATE '45000'						
					SET MESSAGE_TEXT = ERRORMSG;
				END IF;
			END IF;
		END IF;
	END IF;
END;