DROP TRIGGER IF EXISTS TRG_PAYMENT_DETAILS_UPDATE_VALIDATION;
CREATE TRIGGER TRG_PAYMENT_DETAILS_UPDATE_VALIDATION
BEFORE UPDATE ON PAYMENT_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TRG_PAYMENT_DETAILS_VALIDATION(NEW.PD_ID,NEW.UNIT_ID,NEW.CUSTOMER_ID,NEW.PP_ID,NEW.CED_REC_VER,NEW.PD_FOR_PERIOD,'UPDATE');
END;