DROP TRIGGER IF EXISTS TRG_PAYMENT_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_PAYMENT_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON PAYMENT_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TRG_PAYMENT_DETAILS_VALIDATION(NULL,NEW.UNIT_ID,NEW.CUSTOMER_ID,NEW.PP_ID,NEW.CED_REC_VER,NEW.PD_FOR_PERIOD,'INSERT');
END;