-- VERSION 0.1 STARTDATE:15/10/2014 ENDDATE:15/10/2014 ISSUE NO:88 COMMENT NO:19 DESC:SP FOR CALCULATE BANDWIDTH ON MONTH WISE. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TS_REPORT_BANDWIDTH_CALCULATION;
CREATE PROCEDURE SP_TS_REPORT_BANDWIDTH_CALCULATION(
IN MONTH_YEAR VARCHAR(20),
IN LOGIN_ID VARCHAR(50),
IN USERSTAMP VARCHAR(50),
OUT TEMP_BANDWIDTH_CALCULATION TEXT)
BEGIN
	DECLARE SHORTMONTH VARCHAR(10);
	DECLARE MONTH_STARTDATE DATE;
	DECLARE MONTH_ENDDATE DATE;
	DECLARE TEMP_BANDWIDTHCALCULATION TEXT;
	DECLARE USERSTAMP_ID INT(11);
	DECLARE ULDID INT(11);
	DECLARE N INT;
	DECLARE I INT;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
 	CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULD_ID);
	SET USERSTAMP_ID=@ULD_ID;
	IF(LOGIN_ID='')THEN
		SET LOGIN_ID=NULL;
	END IF;
	SET N=0;
	SET I=1;
	SET SHORTMONTH=(SELECT SUBSTRING(MONTH_YEAR,1,3));
	SET MONTH_STARTDATE=(SELECT CONCAT(SUBSTRING_INDEX(MONTH_YEAR,'-',-1),'-',(MONTH(STR_TO_DATE(SHORTMONTH,'%b'))),'-01'));
	SET MONTH_ENDDATE=(SELECT LAST_DAY(MONTH_STARTDATE));

	-- CALCULATE FOR SINGLE USER
	IF(LOGIN_ID IS NOT NULL)THEN
		CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID(LOGIN_ID,@ULD_ID);
		SET ULDID=@ULD_ID;    
		SET TEMP_BANDWIDTHCALCULATION=(SELECT CONCAT('TEMP_BANDWIDTH_CALCULATION',SYSDATE()));
		SET TEMP_BANDWIDTHCALCULATION=(SELECT REPLACE(TEMP_BANDWIDTHCALCULATION,':',''));
		SET TEMP_BANDWIDTHCALCULATION=(SELECT REPLACE(TEMP_BANDWIDTHCALCULATION,'-',''));
		SET TEMP_BANDWIDTHCALCULATION=(SELECT REPLACE(TEMP_BANDWIDTHCALCULATION,' ',''));
		SET TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT(TEMP_BANDWIDTHCALCULATION,'_',USERSTAMP_ID));  
		SET @CREATE_TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT('CREATE TABLE ',TEMP_BANDWIDTH_CALCULATION,' (
		ID INT NOT NULL AUTO_INCREMENT,
		REPORT_DATE VARCHAR(20),
		BANDWIDTH_MB DECIMAL(8,2),
		PRIMARY KEY(ID))'));
		PREPARE CREATE_TEMP_BANDWIDTH_CALCULATION_STMT FROM @CREATE_TEMP_BANDWIDTH_CALCULATION;
		EXECUTE CREATE_TEMP_BANDWIDTH_CALCULATION_STMT;
		SET @INSERT_TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT('INSERT INTO ',TEMP_BANDWIDTH_CALCULATION,' (REPORT_DATE,BANDWIDTH_MB)
		SELECT COALESCE(DATE_FORMAT(UARD_DATE,"%d-%m-%Y,%a"),"TOTAL"),SUM(UARD_BANDWIDTH) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=',ULDID,' 
		AND UARD_DATE BETWEEN ','"',MONTH_STARTDATE,'"',' AND ','"',MONTH_ENDDATE,'"',' GROUP BY UARD_DATE WITH ROLLUP'));
		PREPARE INSERT_TEMP_BANDWIDTH_CALCULATION_STMT FROM @INSERT_TEMP_BANDWIDTH_CALCULATION;
		EXECUTE INSERT_TEMP_BANDWIDTH_CALCULATION_STMT;
	END IF;

	-- CALCULATE FOR ALL USERS
	IF (LOGIN_ID IS NULL) THEN
		SET TEMP_BANDWIDTHCALCULATION=(SELECT CONCAT('TEMP_BANDWIDTH_CALCULATION',SYSDATE()));
		SET TEMP_BANDWIDTHCALCULATION=(SELECT REPLACE(TEMP_BANDWIDTHCALCULATION,':',''));
		SET TEMP_BANDWIDTHCALCULATION=(SELECT REPLACE(TEMP_BANDWIDTHCALCULATION,'-',''));
		SET TEMP_BANDWIDTHCALCULATION=(SELECT REPLACE(TEMP_BANDWIDTHCALCULATION,' ',''));
		SET TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT(TEMP_BANDWIDTHCALCULATION,'_',USERSTAMP_ID));  
		SET @CREATE_TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT('CREATE TABLE ',TEMP_BANDWIDTH_CALCULATION,' (
		ID INT NOT NULL AUTO_INCREMENT,
		LOGINID VARCHAR(50),
		BANDWIDTH_MB DECIMAL(8,2),
		PRIMARY KEY(ID))'));
		PREPARE CREATE_TEMP_BANDWIDTH_CALCULATION_STMT FROM @CREATE_TEMP_BANDWIDTH_CALCULATION;
		EXECUTE CREATE_TEMP_BANDWIDTH_CALCULATION_STMT;
		SET @USERSULDID=(SELECT CONCAT('SELECT COUNT(DISTINCT ULD_ID) INTO @UCOUNT FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_DATE BETWEEN ','"',MONTH_STARTDATE,'"',' AND ','"',MONTH_ENDDATE,'"'));
		PREPARE USERSULDID_STMT FROM @USERSULDID;
		EXECUTE USERSULDID_STMT;
		WHILE(@UCOUNT>=I)DO
			SET @SELECT_LOGINID_ULDID = (SELECT CONCAT('SELECT ULD_ID,ULD_LOGINID INTO @U_ID,@LOGID FROM USER_LOGIN_DETAILS WHERE ULD_ID=(SELECT DISTINCT ULD_ID FROM USER_ADMIN_REPORT_DETAILS
			WHERE UARD_DATE BETWEEN ','"',MONTH_STARTDATE,'"',' AND ','"',MONTH_ENDDATE,'"',' LIMIT ',N,',1)'));
			PREPARE SELECT_LOGINID_ULDID_STMT FROM @SELECT_LOGINID_ULDID;
			EXECUTE SELECT_LOGINID_ULDID_STMT;
			SET ULDID=@U_ID;
			SET LOGIN_ID=@LOGID;
			SET @INSERT_TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT('INSERT INTO ',TEMP_BANDWIDTH_CALCULATION,' (LOGINID,BANDWIDTH_MB)
			SELECT ','"',LOGIN_ID,'"',',SUM(UARD_BANDWIDTH) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=',ULDID,' AND UARD_DATE BETWEEN ','"',MONTH_STARTDATE,'"',' AND ','"',MONTH_ENDDATE,'"'));
			PREPARE INSERT_TEMP_BANDWIDTH_CALCULATION_STMT FROM @INSERT_TEMP_BANDWIDTH_CALCULATION;
			EXECUTE INSERT_TEMP_BANDWIDTH_CALCULATION_STMT;
			SET N=N+1;
			SET I=I+1;
		END WHILE;
		SET @INSERT_TEMP_BANDWIDTH_CALCULATION=(SELECT CONCAT('INSERT INTO ',TEMP_BANDWIDTH_CALCULATION,' (LOGINID,BANDWIDTH_MB) SELECT "TOTAL",SUM(BANDWIDTH_MB) FROM ',TEMP_BANDWIDTH_CALCULATION));
		PREPARE INSERT_TEMP_BANDWIDTH_CALCULATION_STMT FROM @INSERT_TEMP_BANDWIDTH_CALCULATION;
		EXECUTE INSERT_TEMP_BANDWIDTH_CALCULATION_STMT;
	END IF;
	COMMIT;
END;
/*
CALL SP_TS_REPORT_BANDWIDTH_CALCULATION('OCTOBER-2013','dhandapani.sattanathan@ssomens.com','dhandapani.sattanathan@ssomens.com',@TEMP_BANDWIDTH_CALCULATION);
*/