-- TOTAL 9277
SELECT*FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ATTENDANCE IN (4,6,7) OR UARD_PERMISSION IS NOT NULL;
SELECT*FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ATTENDANCE=5 AND UARD_REASON IS NULL GROUP BY UARD_ID;

-- ABSENT 
SELECT *FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ATTENDANCE=6;

SELECT UID,UREPORT FROM RAJA_SOURCE.REPORTS_SCDB_FORMAT  WHERE (UREPORT NOT LIKE "%Ha%day%Absent%" AND UREPORT NOT LIKE "%Absent not%"
AND UREPORT NOT LIKE "%ABSENT record del%" AND UREPORT NOT LIKE "%AFT%ABSENT%" AND UREPORT NOT LIKE "%present%absent%" AND UREPORT NOT LIKE "%absentee%" AND UREPORT NOT LIKE "%0.5%D%"  
AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%absent trigger%" AND UREPORT NOT LIKE "%Absent Radio%" AND UREPORT NOT LIKE "%Absent option%" AND UREPORT NOT LIKE "%Absent in%" 
AND UREPORT NOT LIKE "%Absent for%" AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%ABSENT(AFTERNOON)%" AND UREPORT NOT LIKE "%ABSENT record%" AND UREPORT NOT LIKE "%ABSENT%ON%DUTY%"
AND UREPORT NOT LIKE "%morning%Absent%" AND UREPORT NOT LIKE "%ABSENT: (half%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%" AND UREPORT NOT LIKE "%insert absent%" 
AND UREPORT NOT LIKE "%count all absent%" AND UREPORT NOT LIKE "%ADDED ABSENT FLAG%" AND UREPORT NOT LIKE "%ABSENT AND PRESENT%") AND (UREPORT LIKE "%went chennai%" OR UREPORT LIKE "off%"
OR UREPORT LIKE " off%" OR UREPORT LIKE "%took leave%" OR UREPORT LIKE "%ABSENT%" OR UREPORT LIKE "%today%leave%" OR UREPORT LIKE "leave%");

SELECT UID,UREPORT FROM RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT  WHERE (UREPORT NOT LIKE "%Ha%day%Absent%" AND UREPORT NOT LIKE "%Absent not%"
AND UREPORT NOT LIKE "%ABSENT record del%" AND UREPORT NOT LIKE "%AFT%ABSENT%" AND UREPORT NOT LIKE "%present%absent%" AND UREPORT NOT LIKE "%absentee%" AND UREPORT NOT LIKE "%0.5%D%"  
AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%absent trigger%" AND UREPORT NOT LIKE "%Absent Radio%" AND UREPORT NOT LIKE "%Absent option%" AND UREPORT NOT LIKE "%Absent in%" 
AND UREPORT NOT LIKE "%Absent for%" AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%ABSENT(AFTERNOON)%" AND UREPORT NOT LIKE "%ABSENT record%" AND UREPORT NOT LIKE "%ABSENT%ON%DUTY%"
AND UREPORT NOT LIKE "%morning%Absent%" AND UREPORT NOT LIKE "%ABSENT: (half%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%" AND UREPORT NOT LIKE "%insert absent%" 
AND UREPORT NOT LIKE "%count all absent%" AND UREPORT NOT LIKE "%ADDED ABSENT FLAG%" AND UREPORT NOT LIKE "%ABSENT AND PRESENT%") AND (UREPORT LIKE "%went chennai%" OR UREPORT LIKE "off%"
OR UREPORT LIKE " off%" OR UREPORT LIKE "%took leave%" OR UREPORT LIKE "%ABSENT%" OR UREPORT LIKE "%today%leave%" OR UREPORT LIKE "leave%");

SELECT B.UREPORT,C.UREPORT,A.*FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REASON=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REASON=C.UREPORT
WHERE A.UARD_ATTENDANCE=6 GROUP BY A.UARD_ID;

-- ONDUTY
SELECT *FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ATTENDANCE=7;

SELECT UID,UREPORT FROM RAJA_SOURCE.REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%on-duty%" OR UREPORT LIKE "%onduty%" OR UREPORT LIKE "%on duty%" OR UREPORT LIKE "%worked in new year%" OR UREPORT LIKE "holiday" OR UREPORT LIKE "BAKRID HOLIDAY"
OR UREPORT LIKE "%on_duty%" OR  UREPORT LIKE "OD" OR  UREPORT LIKE "%We went%" OR  UREPORT LIKE "Worked in Christmas%" OR UREPORT LIKE "on leave%") AND UREPORT NOT LIKE "%ONDUTY%SEARCH%UPDATE%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%"
AND UREPORT NOT LIKE "%ABSENT & ONDUTY%" AND UREPORT NOT LIKE "%absent and onduty%" AND UREPORT NOT LIKE "%calculate%present, onduty%" AND UREPORT NOT LIKE "%onduty entry%" AND UREPORT NOT LIKE "%onduty_levae_dtls%";

SELECT UID,UREPORT FROM RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT  WHERE (UREPORT LIKE "%on-duty%" OR UREPORT LIKE "%onduty%" OR UREPORT LIKE "%on duty%" OR UREPORT LIKE "%worked in new year%" OR UREPORT LIKE "holiday" OR UREPORT LIKE "BAKRID HOLIDAY"
OR UREPORT LIKE "%on_duty%" OR  UREPORT LIKE "OD" OR  UREPORT LIKE "%We went%" OR  UREPORT LIKE "Worked in Christmas%" OR UREPORT LIKE "on leave%") AND UREPORT NOT LIKE "%ONDUTY%SEARCH%UPDATE%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%"
AND UREPORT NOT LIKE "%ABSENT & ONDUTY%" AND UREPORT NOT LIKE "%absent and onduty%" AND UREPORT NOT LIKE "%calculate%present, onduty%" AND UREPORT NOT LIKE "%onduty entry%" AND UREPORT NOT LIKE "%onduty_levae_dtls%";

SELECT B.UREPORT,C.UREPORT,A.*FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REASON=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REASON=C.UREPORT
WHERE A.UARD_ATTENDANCE=7 GROUP BY A.UARD_ID;

-- HALFDAY LEAVE
SELECT *FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ATTENDANCE=4;

SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM RAJA_SOURCE.REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%half%day%absent%" OR UREPORT LIKE "%worked upto 2.20 pm%"
OR UREPORT LIKE "morning%absent%"  OR UREPORT LIKE "%half%leave%"  OR UREPORT LIKE "%morning%leave%" OR UREPORT LIKE "%AFTERNOON%LEAVE%" OR UREPORT LIKE "%Permission: 2.30pm%" OR UREPORT LIKE "Came at  8.30am%" 
OR UREPORT LIKE "%Permission 3 pm - 7 p%" OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Came to office at 11 and%" 
OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%" OR UREPORT LIKE "%AFT%ABSENT%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "1.came at 1.30%" 
OR UREPORT LIKE "1.Came at 11 am n%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%" OR UREPORT LIKE "1.Came office at 4.20%" OR UREPORT LIKE "come to office at 1%" 
OR UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%ABSENT%" OR UREPORT LIKE "%home 2 pm - to 4 pm%" OR UREPORT LIKE "1.TOOK BACKUP%") AND UREPORT NOT LIKE "%after  half day%" AND UREPORT NOT LIKE "%half day but there%" 
AND UREPORT NOT LIKE "%half day%full day%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%";

SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%half%day%absent%" OR UREPORT LIKE "%worked upto 2.20 pm%"
OR UREPORT LIKE "morning%absent%"  OR UREPORT LIKE "%half%leave%"  OR UREPORT LIKE "%morning%leave%" OR UREPORT LIKE "%AFTERNOON%LEAVE%" OR UREPORT LIKE "%Permission: 2.30pm%" OR UREPORT LIKE "Came at  8.30am%" 
OR UREPORT LIKE "%Permission 3 pm - 7 p%" OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Came to office at 11 and%" 
OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%" OR UREPORT LIKE "%AFT%ABSENT%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "1.came at 1.30%" 
OR UREPORT LIKE "1.Came at 11 am n%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%" OR UREPORT LIKE "1.Came office at 4.20%" OR UREPORT LIKE "come to office at 1%" 
OR UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%ABSENT%" OR UREPORT LIKE "%home 2 pm - to 4 pm%") AND UREPORT NOT LIKE "%after  half day%" AND UREPORT NOT LIKE "%half day but there%" 
AND UREPORT NOT LIKE "%half day%full day%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%";

SELECT C.UREPORT,B.UREPORT,A.* FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REPORT=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REASON=C.UREPORT
WHERE A.UARD_ATTENDANCE=4 GROUP BY A.UARD_ID;

SELECT C.UREPORT,B.UREPORT,A.UARD_REPORT FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REPORT=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REASON=C.UREPORT
WHERE A.UARD_ATTENDANCE=4 GROUP BY A.UARD_ID;

-- PERMISSION
SELECT *FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_PERMISSION IS NOT NULL;

SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM RAJA_SOURCE.REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%PERMISSION%" OR UREPORT LIKE "%PERSMISSION%" OR UREPORT LIKE "%HR PERMISSON%" 
OR UREPORT LIKE "%LEFT OFFICE AT 4.15 P.M%" OR UREPORT LIKE "Came at 12%" OR UREPORT LIKE "Came to office at 1%" OR UREPORT LIKE "come to office by 12%" OR UREPORT LIKE "went out at%" OR UREPORT LIKE "worked till 3.30 pm%" 
OR UREPORT LIKE "1.Came to office at 10.%" OR UREPORT LIKE "1.came at 12%o clock%" OR UREPORT LIKE "1.came at 11.%") AND UREPORT NOT LIKE "%Half day permission%" AND UREPORT NOT LIKE "%the permission%" 
AND UREPORT NOT LIKE "%provide permission%" AND UREPORT NOT LIKE "%Select permission%" AND UREPORT NOT LIKE "%GRANT%permission%" AND UREPORT NOT LIKE "%Revoke permissioin%" AND UREPORT NOT LIKE "%Access permission%" 
AND UREPORT NOT LIKE "%view permission%" AND UREPORT NOT LIKE "%need permission%" AND UREPORT NOT LIKE "%GIVE PERMISSION%" AND UREPORT NOT LIKE "%GIVEn PERMISSION%" AND UREPORT NOT LIKE "%employee permission%" 
AND UREPORT NOT LIKE "%CHECKING PERMISSION%" AND UREPORT NOT LIKE "%edit PERMISSION%" AND UREPORT NOT LIKE "%permission cant%" AND UREPORT NOT LIKE "%an permission%" AND UREPORT NOT LIKE "%& permission%" AND UREPORT NOT LIKE "%IN PERMISSION MIG%"
AND UREPORT NOT LIKE "%Permission: 2.30pm%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing permission%" AND UREPORT NOT LIKE "%table permission%" AND UREPORT NOT LIKE "%Left office at 2p%"
AND UREPORT NOT LIKE "%Permission 3 pm - 7 p%" AND UREPORT NOT LIKE "%PERMISSION FOR FLEX%" AND UREPORT NOT LIKE "%PERMISSION LIST%" AND UREPORT NOT LIKE "%onduty and permission%" AND UREPORT NOT LIKE "%NO PERMISSION%";

SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT WHERE (UREPORT LIKE "%PERMISSION%" OR UREPORT LIKE "%PERSMISSION%" OR UREPORT LIKE "%HR PERMISSON%" 
OR UREPORT LIKE "%LEFT OFFICE AT 4.15 P.M%" OR UREPORT LIKE "Came at 12%" OR UREPORT LIKE "Came to office at 1%" OR UREPORT LIKE "come to office by 12%" OR UREPORT LIKE "went out at%" OR UREPORT LIKE "worked till 3.30 pm%" 
OR UREPORT LIKE "1.Came to office at 10.%" OR UREPORT LIKE "1.came at 12%o clock%" OR UREPORT LIKE "1.came at 11.%") AND UREPORT NOT LIKE "%Half day permission%" AND UREPORT NOT LIKE "%the permission%" 
AND UREPORT NOT LIKE "%provide permission%" AND UREPORT NOT LIKE "%Select permission%" AND UREPORT NOT LIKE "%GRANT%permission%" AND UREPORT NOT LIKE "%Revoke permissioin%" AND UREPORT NOT LIKE "%Access permission%" 
AND UREPORT NOT LIKE "%view permission%" AND UREPORT NOT LIKE "%need permission%" AND UREPORT NOT LIKE "%GIVE PERMISSION%" AND UREPORT NOT LIKE "%GIVEn PERMISSION%" AND UREPORT NOT LIKE "%employee permission%" 
AND UREPORT NOT LIKE "%CHECKING PERMISSION%" AND UREPORT NOT LIKE "%edit PERMISSION%" AND UREPORT NOT LIKE "%permission cant%" AND UREPORT NOT LIKE "%an permission%" AND UREPORT NOT LIKE "%& permission%" AND UREPORT NOT LIKE "%IN PERMISSION MIG%"
AND UREPORT NOT LIKE "%Permission: 2.30pm%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing permission%" AND UREPORT NOT LIKE "%table permission%" AND UREPORT NOT LIKE "%Left office at 2p%"
AND UREPORT NOT LIKE "%Permission 3 pm - 7 p%" AND UREPORT NOT LIKE "%PERMISSION FOR FLEX%" AND UREPORT NOT LIKE "%PERMISSION LIST%" AND UREPORT NOT LIKE "%onduty and permission%" AND UREPORT NOT LIKE "%NO PERMISSION%";

SELECT C.UREPORT,B.UREPORT,A.* FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REPORT=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REASON=C.UREPORT
WHERE A.UARD_PERMISSION IS NOT NULL GROUP BY A.UARD_ID;

SELECT C.UREPORT,B.UREPORT,A.UARD_REPORT FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REPORT=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REASON=C.UREPORT
WHERE A.UARD_PERMISSION IS NOT NULL GROUP BY A.UARD_ID;

-- REPORT
SELECT*FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ATTENDANCE=5 AND UARD_REASON IS NULL GROUP BY UARD_ID;

SELECT C.UID,B.UID,C.UREPORT,B.UREPORT,A.*FROM USER_ADMIN_REPORT_DETAILS A
LEFT JOIN RAJA_SOURCE.REPORTS_SCDB_FORMAT B ON A.UARD_REPORT=B.UREPORT 
LEFT JOIN RAJA_SOURCE.TEMP_EMP_REPORT_SCDB_FORMAT C ON A.UARD_REPORT=C.UREPORT
WHERE A.UARD_REASON IS NULL AND A.UARD_ATTENDANCE=5 GROUP BY A.UARD_ID;

-- BANDWIDTH
SELECT * FROM TS_SOURCE_27102014.BANDWIDTH_SEPTEMBER_2014;
SELECT * FROM VW_SINGLE_BANDWIDTH_USAGE WHERE BANDWIDTH_MB!=0 AND REPORT_DATE BETWEEN '2013-06-14' AND '2014-10-31';
SELECT * FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_BANDWIDTH!=0 AND UARD_DATE BETWEEN '2013-06-14' AND '2014-10-31';

-- EMAIL

SELECT *FROM RAJA_SOURCE.EMAIL_SQL_FORMAT;
SELECT*FROM EMAIL_TEMPLATE;
SELECT*FROM EMAIL_TEMPLATE_DETAILS;

SELECT AA.SCRIPT_NAME,BB.ET_EMAIL_SCRIPT,BB.ET_ID,CC.ET_ID,AA.SUBJECT,CC.ETD_EMAIL_SUBJECT,AA.BODY,CC.ETD_EMAIL_BODY,
CC.ETD_TIMESTAMP,AA.TIMESTAMP,CC.ULD_ID,AA.USER_STAMP FROM RAJA_SOURCE.EMAIL_SQL_FORMAT AA
INNER JOIN EMAIL_TEMPLATE BB ON AA.SCRIPT_NAME=BB.ET_EMAIL_SCRIPT
INNER JOIN EMAIL_TEMPLATE_DETAILS CC ON AA.SUBJECT=CC.ETD_EMAIL_SUBJECT AND AA.BODY=CC.ETD_EMAIL_BODY 
INNER JOIN user_login_details DD ON DD.ULD_LOGINID=AA.USER_STAMP AND DD.ULD_ID = CC.ULD_ID
WHERE BB.ET_ID = CC.ET_ID AND CC.ETD_TIMESTAMP=AA.TIMESTAMP;






