-- version 0.9 -- sdate:13/06/2014 -- edate:13/06/2014 -- issue:738 -- commentno:#27 -- desc:IMPLEMENTING TRIGGER CHANGES FOR NOT UPDATING ULD_ID,TIMESTAMP IN TICKLER_HISTORY BY: RAJA
-- version 0.8 -- sdate:12/06/2014 -- edate:12/06/2014 -- issue:738 -- commentno:#18 -- desc:IMPLEMENTING TRIGGER CHANGES FOR NOT UPDATING PRIMARY KEY IN TICKLER_HISTORY BY: RAJA
-- version 0.7 -- sdate:05/06/2014 -- edate:05/06/2014 -- issue:529 -- commentno:#196 -- desc:ADD ULD_ID AND TIMESTAMP TO UPDATE OLD VALUE DONE BY:BHAVANI.R
-- version 0.6 -- sdate:07/04/2014 -- edate:07/04/2014 -- issue:797 -- commentno:#28 -- desc:REPLACED TABLENAME AND HEADER NAME DONE BY:SASIKALA.D
-- version:0.5 -- sdate:26/02/2014 -- edate:26/02/2014 -- issue:529 -- commentno:132 -- done by:RL
-- version:0.4 -- sdate:10/02/2014 -- edate:10/02/2014 -- issue:529 -- desc:add comma after 1 header value is completed -- doneby:RL
-- version 0.3 -- sdate:07/02/2014 -- edate:07/02/2014 -- issue:738 -- commentno:#1 -- desc:ADDED ONE CONDITION FOR NOT CREATING NULL ROW IN TICKLER_HISTORY DONE BY:DHIVYA
-- version 0.2 -- sdate:10/11/2013 -- edate:10/11/2013 -- issue:636 commentno#47 -- desc:trigger name changed by rl
-- > version 0.1-- >start date:12/10/2013 end date:14/10/2013-- >issueno:529 -- >commentno:53 -- >desc:TRIGGER UPDATION QUERY FOR ERM_ENTRY_DETAILS TABLE
-- >doneby:dhivya

DROP TRIGGER IF EXISTS TRG_ERM_ENTRY_DETAILS_UPDATE;
CREATE TRIGGER TRG_ERM_ENTRY_DETAILS_UPDATE
AFTER UPDATE ON ERM_ENTRY_DETAILS
FOR EACH ROW
BEGIN 
--  declaration for old_value and new_value to store it in TICKLER_HISTORY table
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.ERM_CUST_NAME != NEW.ERM_CUST_NAME ) OR (OLD.ERM_RENT!= NEW.ERM_RENT) OR (OLD.ERM_MOVING_DATE!= NEW.ERM_MOVING_DATE) 
OR (OLD.ERM_MIN_STAY!= NEW.ERM_MIN_STAY) OR (OLD.ERMO_ID!= NEW.ERMO_ID) OR (OLD.NC_ID IS NULL AND NEW.NC_ID IS NOT NULL) OR (OLD.NC_ID IS NOT NULL AND NEW.NC_ID IS NULL) OR (OLD.NC_ID != NEW.NC_ID)
OR (OLD.ERM_NO_OF_GUESTS IS NULL AND NEW.ERM_NO_OF_GUESTS IS NOT NULL) OR (OLD.ERM_NO_OF_GUESTS IS NOT NULL AND NEW.ERM_NO_OF_GUESTS IS NULL) OR (OLD.ERM_NO_OF_GUESTS != NEW.ERM_NO_OF_GUESTS)
OR (OLD.ERM_AGE IS NULL AND NEW.ERM_AGE IS NOT NULL) OR (OLD.ERM_AGE IS NOT NULL AND NEW.ERM_AGE IS NULL) OR (OLD.ERM_AGE != NEW.ERM_AGE)
OR (OLD.ERM_CONTACT_NO IS NULL AND NEW.ERM_CONTACT_NO IS NOT NULL) OR (OLD.ERM_CONTACT_NO IS NOT NULL AND NEW.ERM_CONTACT_NO IS NULL) OR (OLD.ERM_CONTACT_NO !=NEW.ERM_CONTACT_NO) 
OR (OLD.ERM_EMAIL_ID IS NULL AND NEW.ERM_EMAIL_ID IS NOT NULL) OR (OLD.ERM_EMAIL_ID IS NOT NULL AND NEW.ERM_EMAIL_ID IS NULL) OR (OLD.ERM_EMAIL_ID != NEW.ERM_EMAIL_ID)
OR (OLD.ERM_COMMENTS!= NEW.ERM_COMMENTS)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ERM_ID=', OLD.ERM_ID,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_CUST_NAME  to store it in TICKLER_HISTORY table
IF (OLD.ERM_CUST_NAME != NEW.ERM_CUST_NAME ) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERM_CUST_NAME =', OLD.ERM_CUST_NAME ,','); 
END IF;
IF (OLD.ERM_CUST_NAME != NEW.ERM_CUST_NAME ) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ERM_CUST_NAME =', NEW.ERM_CUST_NAME ,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_RENT to store it in TICKLER_HISTORY table
IF (OLD.ERM_RENT!= NEW.ERM_RENT) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERM_RENT=', OLD.ERM_RENT,','); 
END IF;
IF (OLD.ERM_RENT!= NEW.ERM_RENT) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ERM_RENT=', NEW.ERM_RENT,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_MOVING_DATE to store it in TICKLER_HISTORY table
IF (OLD.ERM_MOVING_DATE!= NEW.ERM_MOVING_DATE) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERM_MOVING_DATE=', OLD.ERM_MOVING_DATE,','); 
END IF;
IF (OLD.ERM_MOVING_DATE!= NEW.ERM_MOVING_DATE) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ERM_MOVING_DATE=', NEW.ERM_MOVING_DATE,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_MIN_STAY to store it in TICKLER_HISTORY table
IF (OLD.ERM_MIN_STAY!= NEW.ERM_MIN_STAY) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERM_MIN_STAY=', OLD.ERM_MIN_STAY,','); 
END IF;
IF (OLD.ERM_MIN_STAY!= NEW.ERM_MIN_STAY) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ERM_MIN_STAY=', NEW.ERM_MIN_STAY,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERMO_ID to store it in TICKLER_HISTORY table
IF (OLD.ERMO_ID!= NEW.ERMO_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERMO_ID=', OLD.ERMO_ID,','); 
END IF;
IF (OLD.ERMO_ID!= NEW.ERMO_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ERMO_ID=', NEW.ERMO_ID,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for NC_ID to store it in TICKLER_HISTORY table
IF (OLD.NC_ID IS NULL AND NEW.NC_ID IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'NC_ID=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'NC_ID=',NEW.NC_ID,',');
ELSEIF (OLD.NC_ID IS NOT NULL AND NEW.NC_ID IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'NC_ID=',OLD.NC_ID,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'NC_ID=','<NULL>,');
ELSEIF (OLD.NC_ID!= NEW.NC_ID) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'NC_ID=', OLD.NC_ID,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'NC_ID=', NEW.NC_ID,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_NO_OF_GUESTS to store it in TICKLER_HISTORY table
IF (OLD.ERM_NO_OF_GUESTS IS NULL AND NEW.ERM_NO_OF_GUESTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_NO_OF_GUESTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_NO_OF_GUESTS=',NEW.ERM_NO_OF_GUESTS,',');
ELSEIF (OLD.ERM_NO_OF_GUESTS IS NOT NULL AND NEW.ERM_NO_OF_GUESTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_NO_OF_GUESTS=',OLD.ERM_NO_OF_GUESTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_NO_OF_GUESTS=','<NULL>,');
ELSEIF (OLD.ERM_NO_OF_GUESTS!= NEW.ERM_NO_OF_GUESTS) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'ERM_NO_OF_GUESTS=', OLD.ERM_NO_OF_GUESTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'ERM_NO_OF_GUESTS=', NEW.ERM_NO_OF_GUESTS,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_AGE to store it in TICKLER_HISTORY table
IF (OLD.ERM_AGE IS NULL AND NEW.ERM_AGE IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_AGE=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_AGE=',NEW.ERM_AGE,',');
ELSEIF (OLD.ERM_AGE IS NOT NULL AND NEW.ERM_AGE IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_AGE=',OLD.ERM_AGE,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_AGE=','<NULL>,');
ELSEIF (OLD.ERM_AGE!= NEW.ERM_AGE) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'ERM_AGE=', OLD.ERM_AGE,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'ERM_AGE=', NEW.ERM_AGE,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_CONTACT_NO to store it in TICKLER_HISTORY table
IF (OLD.ERM_CONTACT_NO IS NULL AND NEW.ERM_CONTACT_NO IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_CONTACT_NO=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_CONTACT_NO=',NEW.ERM_CONTACT_NO,',');
ELSEIF (OLD.ERM_CONTACT_NO IS NOT NULL AND NEW.ERM_CONTACT_NO IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_CONTACT_NO=',OLD.ERM_CONTACT_NO,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_CONTACT_NO=','<NULL>,');
ELSEIF (OLD.ERM_CONTACT_NO!= NEW.ERM_CONTACT_NO) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'ERM_CONTACT_NO=', OLD.ERM_CONTACT_NO,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'ERM_CONTACT_NO=', NEW.ERM_CONTACT_NO,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_EMAIL_ID to store it in TICKLER_HISTORY table
IF (OLD.ERM_EMAIL_ID IS NULL AND NEW.ERM_EMAIL_ID IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_EMAIL_ID=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_EMAIL_ID=',NEW.ERM_EMAIL_ID,',');
ELSEIF (OLD.ERM_EMAIL_ID IS NOT NULL AND NEW.ERM_EMAIL_ID IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ERM_EMAIL_ID=',OLD.ERM_EMAIL_ID,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ERM_EMAIL_ID=','<NULL>,');
ELSEIF (OLD.ERM_EMAIL_ID!= NEW.ERM_EMAIL_ID) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'ERM_EMAIL_ID=', OLD.ERM_EMAIL_ID,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'ERM_EMAIL_ID=', NEW.ERM_EMAIL_ID,','); 
END IF;
--  get the OLD VALUE & NEW_VALUE for ERM_COMMENTS to store it in TICKLER_HISTORY table
IF (OLD.ERM_COMMENTS!= NEW.ERM_COMMENTS) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERM_COMMENTS=', OLD.ERM_COMMENTS,','); 
END IF;
IF (OLD.ERM_COMMENTS!= NEW.ERM_COMMENTS) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ERM_COMMENTS=', NEW.ERM_COMMENTS,','); 
END IF;
IF ((OLD.ERM_CUST_NAME != NEW.ERM_CUST_NAME ) OR (OLD.ERM_RENT!= NEW.ERM_RENT) OR (OLD.ERM_MOVING_DATE!= NEW.ERM_MOVING_DATE) 
OR (OLD.ERM_MIN_STAY!= NEW.ERM_MIN_STAY) OR (OLD.ERMO_ID!= NEW.ERMO_ID) OR (OLD.NC_ID IS NULL AND NEW.NC_ID IS NOT NULL) OR (OLD.NC_ID IS NOT NULL AND NEW.NC_ID IS NULL) OR (OLD.NC_ID != NEW.NC_ID)
OR (OLD.ERM_NO_OF_GUESTS IS NULL AND NEW.ERM_NO_OF_GUESTS IS NOT NULL) OR (OLD.ERM_NO_OF_GUESTS IS NOT NULL AND NEW.ERM_NO_OF_GUESTS IS NULL) OR (OLD.ERM_NO_OF_GUESTS != NEW.ERM_NO_OF_GUESTS)
OR (OLD.ERM_AGE IS NULL AND NEW.ERM_AGE IS NOT NULL) OR (OLD.ERM_AGE IS NOT NULL AND NEW.ERM_AGE IS NULL) OR (OLD.ERM_AGE != NEW.ERM_AGE)
OR (OLD.ERM_CONTACT_NO IS NULL AND NEW.ERM_CONTACT_NO IS NOT NULL) OR (OLD.ERM_CONTACT_NO IS NOT NULL AND NEW.ERM_CONTACT_NO IS NULL) OR (OLD.ERM_CONTACT_NO !=NEW.ERM_CONTACT_NO) 
OR (OLD.ERM_EMAIL_ID IS NULL AND NEW.ERM_EMAIL_ID IS NOT NULL) OR (OLD.ERM_EMAIL_ID IS NOT NULL AND NEW.ERM_EMAIL_ID IS NULL) OR (OLD.ERM_EMAIL_ID != NEW.ERM_EMAIL_ID)
OR (OLD.ERM_COMMENTS!= NEW.ERM_COMMENTS)) THEN
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.ERM_TIMESTAMP!= NEW.ERM_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ERM_TIMESTAMP=', OLD.ERM_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE!=NEW_VALUE)THEN
SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
--  inserting old_values and new_values in the TICKLER_HISTORY table with their corresponding TTIP_ID in TICKLER_TABID_PROFILE
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM ERM_ENTRY_DETAILS  WHERE ERM_ID=NEW.ERM_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='ERM_ENTRY_DETAILS'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;
