
$.fn.dataTableExt.aTypes.unshift(function(sData){if(sData!==null&&sData.match(/^(0[1-9]|[12][0-9]|3[01])[\/-](0[1-9]|1[012])[\/-](19|20|21)\d\d$/)){return'uk-date';}
    return null;});$.extend($.fn.dataTableExt.oSort,{"uk-date-pre":function(a){console.log(a.match(/^(0[1-9]|[12][0-9]|3[01])[\/-](0[1-9]|1[012])[\/-](19|20|21)\d\d$/));return a.match(/^(0[1-9]|[12][0-9]|3[01])[\/-](0[1-9]|1[012])[\/-](19|20|21)\d\d$/)[0];},"uk-date-asc":function(a,b){var ukDatea=a.split(/[\/-]/),ukDateb=b.split(/[\/-]/),x=(ukDatea[2]+ ukDatea[1]+ ukDatea[0])*1,y=(ukDateb[2]+ ukDateb[1]+ ukDateb[0])*1;if(isNaN(x)){x=0;}
    if(isNaN(y)){y=0;}
    return((x<y)?-1:((x>y)?1:0));},"uk-date-desc":function(a,b){var ukDatea=a.split(/[\/-]/),ukDateb=b.split(/[\/-]/),x=(ukDatea[2]+ ukDatea[1]+ ukDatea[0])*1,y=(ukDateb[2]+ ukDateb[1]+ ukDateb[0])*1;if(isNaN(x)){x=0;}
    if(isNaN(y)){y=0;}
    return((x<y)?1:((x>y)?-1:0));}});$.extend(jQuery.fn.dataTableExt.oSort,{"dom-link-text-pre":function(a){return a.match(/<a(.*?)>(.*?)<\/a>/)[2].toLowerCase().trim();},"dom-link-text-asc":function(a,b){return((a<b)?-1:((a>b)?1:0));},"dom-link-text-desc":function(a,b){return((a<b)?1:((a>b)?-1:0));}});$.fn.dataTableExt.afnSortData['dom-select']=function(oSettings,iColumn){var aData=[];$('td:eq('+ iColumn+') select',oSettings.oApi._fnGetTrNodes(oSettings)).each(function(){aData.push($(this).val());});return aData;};$.fn.dataTableExt.afnSortData['dom-checkbox']=function(oSettings,iColumn){var aData=[];$('td:eq('+ iColumn+') input[type="checkbox"]',oSettings.oApi._fnGetTrNodes(oSettings)).each(function(){aData.push(this.checked==true?"1":"0");});return aData;};$.fn.dataTableExt.afnSortData['dom-text']=function(oSettings,iColumn){var aData=[];$('td:eq('+ iColumn+') textarea, td:eq('+ iColumn+') input[type="text"]',oSettings.oApi._fnGetTrNodes(oSettings)).each(function(){aData.push($(this).val());});return aData;};$.extend($.fn.dataTableExt.oSort,{"num-html-pre":function(a){var x=a.replace(/<.*?>/g,"");return parseFloat(x);},"num-html-asc":function(a,b){return((a<b)?-1:((a>b)?1:0));},"num-html-desc":function(a,b){return((a<b)?1:((a>b)?-1:0));}});$.fn.dataTableExt.aTypes.unshift(function(sData){sData=typeof sData.replace=='function'?sData.replace(/<.*?>/g,""):sData;sData=$.trim(sData);var sValidFirstChars="0123456789-";var sValidChars="0123456789.";var Char;var bDecimal=false;Char=sData.charAt(0);if(sValidFirstChars.indexOf(Char)==-1){return null;}
    for(var i=1;i<sData.length;i++){Char=sData.charAt(i);if(sValidChars.indexOf(Char)==-1){return null;}
        if(Char=="."){if(bDecimal){return null;}
            bDecimal=true;}}
    return'num-html';});