-- VER 0.1 ISSUE NO:83 COMMENT #5 STARTDATE:03/09/2014 ENDDATE:03/09/2014 DESC:SP FOR USER RIGHTS LOGIN UPDATE. DONE BY:RAJA
DROP PROCEDURE IF EXISTS SP_TS_LOGIN_UPDATE;
CREATE PROCEDURE SP_TS_LOGIN_UPDATE(
IN LOGINID VARCHAR(40),
IN ROLENAME VARCHAR(15),
IN JOINDATE DATE,
IN USERSTAMP VARCHAR(50),
OUT UR_FLAG INTEGER)
BEGIN
	DECLARE RECVER INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN 
		ROLLBACK;
		SET UR_FLAG=0;
	END;
	SET AUTOCOMMIT = 0;
	START TRANSACTION; 
	SET FOREIGN_KEY_CHECKS=0;
	SET RECVER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID));
	IF (LOGINID IS NOT NULL AND ROLENAME IS NOT NULL AND JOINDATE IS NOT NULL AND USERSTAMP IS NOT NULL)THEN
		UPDATE USER_ACCESS SET RC_ID=(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=ROLENAME),UA_JOIN_DATE=JOINDATE,UA_USERSTAMP=USERSTAMP WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID)AND UA_REC_VER=RECVER;
		SET UR_FLAG=1;
	END IF;
	SET FOREIGN_KEY_CHECKS=1;
	COMMIT;
END;
/*
CALL SP_TS_LOGIN_UPDATE('raja@gmail.com','USER','2014-04-02','dhandapani.sattanathan@ssomens.com',@UR_FLAG);
*/