-- VER 0.4 ISSUE NO:817 COMMENT #35 STARTDATE:20/05/2014 ENDDATE:20/05/2014 DESC: DROP THE TEMP TABLES AND VIEWS. DONE BY:RAJA
-- VER 0.3 TRACKER NO:595 COMMENT #68 STARTDATE:19/05/2014 ENDDATE:19/05/2014 DESC:ADDED UNSIGNED ZEROFILL DONE BY:DHIVYA.A
-- VER 0.2 TRACKER NO:817 COMMENT #35 STARTDATE:07/05/2014 ENDDATE:07/05/2014 DESC: CHANGED THE SP CHARTS UNIT GROSS NET REVENUE ALLUNIT FOR DYNAMIC PURPOSE. DONE BY: RAJA
-- VER 0.1 TRACKER NO:595 COMMENT # STARTDATE:30/01/2014 ENDDATE:30/01/2014 DESC:SP FOR CHARTS UNIT GROSS AND NET REVENUE FOR ALL UNIT. DONE BY:MANIKANDAN.S

DROP PROCEDURE IF EXISTS SP_CHARTS_UNIT_GROSS_NET_REVENUE_ALLUNIT;
CREATE PROCEDURE SP_CHARTS_UNIT_GROSS_NET_REVENUE_ALLUNIT(IN FROM_DATE VARCHAR(20), IN TO_DATE VARCHAR(20),IN USERSTAMP VARCHAR(50),OUT TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT TEXT)
BEGIN
DECLARE FINAL_FROM_DATE VARCHAR(20);
DECLARE FINAL_TO_DATE VARCHAR(20);

DECLARE CHARTS_GROSS_REVENUE_ALLUNIT TEXT;
DECLARE UNIT_RENTAL_ALLUNIT TEXT;
DECLARE CHARTS_BIZ_EXPENSE_ALLUNIT TEXT;

DECLARE USERSTAMP_ID INT;
DECLARE CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT TEXT;
DECLARE INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT TEXT;
DECLARE INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT TEXT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
 ROLLBACK;
END;       
  -- Format the input date into proper date format.
  CALL SP_FORMAT_DATE(FROM_DATE,TO_DATE,@fd,@td);
  SELECT @fd INTO FINAL_FROM_DATE;
  SELECT @td INTO FINAL_TO_DATE;
  
  -- GROSS REVENUE ALL UNIT

  CALL SP_CHARTS_GROSS_REVENUE_ALLUNIT(FROM_DATE, TO_DATE,USERSTAMP,@TEMP_CHARTS_GROSS_REVENUE_ALLUNIT);
  SET CHARTS_GROSS_REVENUE_ALLUNIT=(SELECT @TEMP_CHARTS_GROSS_REVENUE_ALLUNIT);

  SET @VW_REVENUE=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_CHARTS_GROSS_REVENUE_ALLUNIT AS SELECT UNIT_NUMBER, GROSS_REVENUE FROM ',CHARTS_GROSS_REVENUE_ALLUNIT));
  PREPARE CREATE_VIEW_CHARTS_GROSS_REVENUE_ALLUNIT_STMT FROM @VW_REVENUE;
  EXECUTE CREATE_VIEW_CHARTS_GROSS_REVENUE_ALLUNIT_STMT;
  
  -- GETTING TOTAL BIZ EXPENSE ALL UNIT
  
  CALL SP_CHARTS_BIZ_EXPENSE_ALLUNIT(FROM_DATE, TO_DATE,USERSTAMP,@CHARTS_BIZ_EXPENSE_ALLUNIT_TMPTBL);
  SET CHARTS_BIZ_EXPENSE_ALLUNIT=(SELECT @CHARTS_BIZ_EXPENSE_ALLUNIT_TMPTBL);
  
  SET @VW_BIZ_EXPENSE=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT AS SELECT UNIT_NUMBER, (ELECTRICITY + STARHUB + UNIT_EXPENSE) AS TOTAL_BIZ_EXP FROM ',CHARTS_BIZ_EXPENSE_ALLUNIT));
  PREPARE CREATE_VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT_STMT FROM @VW_BIZ_EXPENSE;
  EXECUTE CREATE_VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT_STMT;
  
  -- UNIT RENTAL ALL UNIT FOR ALL MONTHS BETWEEN FROM DATE AND TO DATE.VALUES WILL BE AVAILABLE IN TEMP_UNIT_RENTAL_ALLUNIT TABLE
  
  CALL SP_CHARTS_GET_UNIT_RENTAL_ALLUNIT(FINAL_FROM_DATE, FINAL_TO_DATE,USERSTAMP,@TEMPTBL_UNIT_RENTAL_ALLUNIT);
  SET UNIT_RENTAL_ALLUNIT=(SELECT @TEMPTBL_UNIT_RENTAL_ALLUNIT);
  
  SET @VW_UNIT=(SELECT CONCAT('CREATE OR REPLACE VIEW VIEW_UNIT_RENTAL_ALLUNIT AS SELECT UNIT_NO AS UNIT_NUMBER, UD_PAYMENT AS UNIT_RENTAL FROM ',UNIT_RENTAL_ALLUNIT));
  PREPARE CREATE_VIEW_UNIT_RENTAL_ALLUNIT_STMT FROM @VW_UNIT;
  EXECUTE CREATE_VIEW_UNIT_RENTAL_ALLUNIT_STMT;
  
     -- UNIT RENTAL + BIZ EXPENSE
    CREATE OR REPLACE VIEW VIEW_TOTAL_RENTAL_EXPENSE_ALLUNIT AS
    SELECT t1.UNIT_NUMBER, (t1.UNIT_RENTAL + ifnull(t2.TOTAL_BIZ_EXP,0)) AS EXPENSE FROM VIEW_UNIT_RENTAL_ALLUNIT t1
    LEFT JOIN VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT t2 ON t1.UNIT_NUMBER = t2.UNIT_NUMBER    
    UNION
    SELECT t2.UNIT_NUMBER, (ifnull(t1.UNIT_RENTAL,0)+t2.TOTAL_BIZ_EXP) AS EXPENSE FROM VIEW_UNIT_RENTAL_ALLUNIT t1
    RIGHT JOIN VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT t2 ON t1.UNIT_NUMBER = t2.UNIT_NUMBER;
 
    -- NET REVENUE = GROSS REVENUE - TOTAL RENTAL EXPENSE
    CREATE OR REPLACE VIEW VIEW_NET_REVENUE_ALLUNIT AS
    SELECT t1.UNIT_NUMBER, (t1.GROSS_REVENUE - ifnull(t2.EXPENSE,0)) AS NET_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE_ALLUNIT t1
    LEFT JOIN VIEW_TOTAL_RENTAL_EXPENSE_ALLUNIT t2 ON t1.UNIT_NUMBER = t2.UNIT_NUMBER
    UNION
    SELECT t2.UNIT_NUMBER, (ifnull(t1.GROSS_REVENUE,0) - t2.EXPENSE) AS NET_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE_ALLUNIT t1
    RIGHT JOIN VIEW_TOTAL_RENTAL_EXPENSE_ALLUNIT t2 ON t1.UNIT_NUMBER = t2.UNIT_NUMBER;
     
    --   TEMP TABLE NAME START
    CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
    SET USERSTAMP_ID=(SELECT @ULDID);
    SET INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT',SYSDATE()));
    --  TEMP TABLE NAME
    SET INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT=(SELECT REPLACE(INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT,' ',''));
    SET INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT=(SELECT REPLACE(INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT,'-',''));
    SET INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT=(SELECT REPLACE(INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT,':',''));
    SET INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT(INTERMEDIATE_UNIT_GROSS_NET_REVENUE_ALLUNIT,'_',USERSTAMP_ID)); 
 
    -- DROP TABLE IF EXISTS INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
    SET @CREATE_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('CREATE TABLE ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' (UNIT_NUMBER INT, GROSS_REVENUE DECIMAL(20,2) DEFAULT 0,TOT_RENTAL_EXPENSE DECIMAL(20,2) DEFAULT 0,NET_REVENUE DECIMAL(20,2) DEFAULT 0, UNIT_RENTAL INT DEFAULT 0, TOT_BIZ_EXPENSE DECIMAL(20,2) DEFAULT 0, SORT_DATE DATE)'));
    PREPARE CREATE_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @CREATE_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE CREATE_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' (UNIT_NUMBER, GROSS_REVENUE) (SELECT UNIT_NUMBER, GROSS_REVENUE FROM VIEW_CHARTS_GROSS_REVENUE_ALLUNIT)'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' (UNIT_NUMBER, TOT_RENTAL_EXPENSE) (SELECT UNIT_NUMBER, EXPENSE FROM VIEW_TOTAL_RENTAL_EXPENSE_ALLUNIT)'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' (UNIT_NUMBER, NET_REVENUE) (SELECT UNIT_NUMBER,NET_REVENUE FROM VIEW_NET_REVENUE_ALLUNIT)'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' (UNIT_NUMBER, UNIT_RENTAL) (SELECT UNIT_NUMBER, UNIT_RENTAL FROM VIEW_UNIT_RENTAL_ALLUNIT)'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INSERT INTO ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' (UNIT_NUMBER, TOT_BIZ_EXPENSE) (SELECT UNIT_NUMBER,TOTAL_BIZ_EXP FROM VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT)'));
    PREPARE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE INSERT_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    --  TEMP TABLE NAME START
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT',SYSDATE()));
    --  TEMP TABLE NAME
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT REPLACE(CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' ',''));
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT REPLACE(CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,'-',''));
    SET CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT REPLACE(CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,':',''));
    SET TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT(CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,'_',USERSTAMP_ID)); 
     
    -- DROP TABLE IF EXISTS TEMP_CHARTS_UNIT_GROSS_NET_REVENUE_ALLUNIT;
    SET @CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('CREATE TABLE ',TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,'(UNIT_NUMBER INT(4)UNSIGNED ZEROFILL, GROSS_REVENUE DECIMAL(30,2),TOT_RENTAL_EXPENSE DECIMAL(30,2),NET_REVENUE DECIMAL(30,2), UNIT_RENTAL INT, TOT_BIZ_EXPENSE DECIMAL(30,2))'));
    PREPARE CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE CREATE_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('INSERT INTO ',TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,'(UNIT_NUMBER, GROSS_REVENUE, TOT_RENTAL_EXPENSE,NET_REVENUE, UNIT_RENTAL, TOT_BIZ_EXPENSE) (SELECT UNIT_NUMBER, SUM(GROSS_REVENUE),SUM(TOT_RENTAL_EXPENSE),SUM(NET_REVENUE), SUM(UNIT_RENTAL),SUM(TOT_BIZ_EXPENSE) FROM ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT,' GROUP BY UNIT_NUMBER ORDER BY UNIT_NUMBER ASC)'));
    PREPARE INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
		EXECUTE INSERT_TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    
    -- DROP THE INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT
    SET @DROP_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT));
  	PREPARE DROP_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT FROM @DROP_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
  	EXECUTE DROP_INTERMEDIATE_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT_STMT;
    
    SET @DROP_CHARTS_GROSS_REVENUE_ALLUNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',CHARTS_GROSS_REVENUE_ALLUNIT));
  	PREPARE DROP_CHARTS_GROSS_REVENUE_ALLUNIT_STMT FROM @DROP_CHARTS_GROSS_REVENUE_ALLUNIT;
  	EXECUTE DROP_CHARTS_GROSS_REVENUE_ALLUNIT_STMT;
    
    SET @DROP_CHARTS_BIZ_EXPENSE_ALLUNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',CHARTS_BIZ_EXPENSE_ALLUNIT));
  	PREPARE DROP_CHARTS_BIZ_EXPENSE_ALLUNIT_STMT FROM @DROP_CHARTS_BIZ_EXPENSE_ALLUNIT;
  	EXECUTE DROP_CHARTS_BIZ_EXPENSE_ALLUNIT_STMT;
    
    SET @DROP_UNIT_RENTAL_ALLUNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',UNIT_RENTAL_ALLUNIT));
  	PREPARE DROP_UNIT_RENTAL_ALLUNIT_STMT FROM @DROP_UNIT_RENTAL_ALLUNIT;
  	EXECUTE DROP_UNIT_RENTAL_ALLUNIT_STMT;
    
    DROP VIEW IF EXISTS VIEW_CHARTS_GROSS_REVENUE_ALLUNIT;
    DROP VIEW IF EXISTS VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT;
    DROP VIEW IF EXISTS VIEW_UNIT_RENTAL_ALLUNIT;
    DROP VIEW IF EXISTS VIEW_TOTAL_RENTAL_EXPENSE_ALLUNIT;
    DROP VIEW IF EXISTS VIEW_NET_REVENUE_ALLUNIT;
    
  COMMIT;
END;  
/* 
  CALL SP_CHARTS_UNIT_GROSS_NET_REVENUE_ALLUNIT('January-2014','January-2014','admin@expatsint.com',@TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT);
  SELECT @TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT;
  select * from VIEW_TOTAL_BIZ_EXPENSE_ALLUNIT;
  SELECT * FROM TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT20140520165822_1;
*/