-- VERSION 0.1 STARTDATE:06/08/2014 ENDDATE:06/08/2014 ISSUE NO: 836  DESC:IMPLEMENTED CHECK CONSTRAINTS TRIGGER FOR DETAIL STAFF SALARY TABLE. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TRG_STAFFDTL_SALARY_VALIDATION;
CREATE PROCEDURE SP_TRG_STAFFDTL_SALARY_VALIDATION(
IN NEWCPFNUMBER VARCHAR(20),
IN PROCESS TEXT)
BEGIN
	DECLARE ERRORMSG TEXT;
	DECLARE MESSAGE_TEXT VARCHAR(50);
	IF ((PROCESS = 'INSERT') OR (PROCESS = 'UPDATE')) THEN  
		IF (NEWCPFNUMBER IS NOT NULL) THEN
			IF ((LENGTH(NEWCPFNUMBER) < 9)) THEN
				SET ERRORMSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=171);
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT=ERRORMSG;
			END IF;
		END IF;		
	END IF;
END;
