-- MIG
-- AUDIT
CALL SP_TS_MIG_TABLE_CREATION('RAJA_DEST');
CALL SP_TS_POST_AUDIT_CREATE_INSERT('RAJA_DEST');
CALL SP_TS_POST_AUDIT('RAJA_DEST');
-- CONFIG
CALL SP_TS_MIG_CONFIGURATION_INSERT_PART1('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_CONFIGURATION_INSERT_PART2('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');
-- USER RIGHTS
CALL SP_TS_MIG_USER_RIGHTS_INSERT_PART1('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_USER_RIGHTS_INSERT_PART2('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');
-- REPORTS
CALL SP_TS_MIG_REPORT_DETAILS_ABSENT_INSERT('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_ONDUTY_INSERT('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_MRNG_ABSENT_INSERT('RAJA_DEST');
CALL SP_TS_MIG_REPORT_DETAILS_AFTN_ABSENT_INSERT('RAJA_DEST');
CALL SP_TS_MIG_REPORT_DETAILS_PERMISSION_INSERT('RAJA_DEST');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('RAJA_SOURCE','RAJA_DEST',1,1,1500,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('RAJA_SOURCE','RAJA_DEST',2,1501,3000,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('RAJA_SOURCE','RAJA_DEST',3,3001,4500,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('RAJA_SOURCE','RAJA_DEST',4,4501,6000,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('RAJA_SOURCE','RAJA_DEST',5,6001,7500,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('RAJA_SOURCE','RAJA_DEST',6,7501,NULL,'dhandapani.sattanathan@ssomens.com');
-- EMAIL
CALL SP_TS_MIG_EMAIL_TEMPLATE_INSERT('RAJA_SOURCE','RAJA_DEST','dhandapani.sattanathan@ssomens.com');

-- FORM OBJ
-- REPORT
CALL SP_TS_DAILY_REPORT_INSERT('','ONDUTY','2014-09-16','2014-09-23','2','raja@gmail.com','','OD','','ONDUTY','ONDUTY',0.00,'raja@gmail.com',@SUCCESS_FLAG);
CALL SP_TS_DAILY_REPORT_SEARCH_UPDATE(7901,'testing','test','2014-09-02',1,'dhandapani.sattanathan@ssomens.com','2','1','1','PRESENT','PRESENT',250.00,'dhandapani.sattanathan@ssomens.com',@REPORT_UPDATE);
CALL SP_TS_USER_ADMIN_REPORT_DETAILS_TICKLER_DATA('dhandapani.sattanathan@ssomens.com',@TEMP_UARD_TICKLER_HISTORY);
CALL SP_TS_REPORT_AUTO_ABSENT_INSERT('safiyullah.mohideen@ssomens.com',@TEMP_ABSENT_USER);
CALL SP_TS_REPORT_COUNT_ABSENT_FLAG('SEPTEMBER-2014','dhandapani.sattanathan@ssomens.com',@TEMP_USER_ABSENT_COUNT);
CALL SP_TS_ATTENDANCE_CALCULATION('JULY-2014','','dhandapani.sattanathan@ssomens.com',@TEMP_ATTENDANCE_CALCULATION,@TOTAL_DAYS,@TOTAL_WORKINGDAYS);
CALL SP_TS_REPORT_BANDWIDTH_CALCULATION('DECEMBER-2013','','dhandapani.sattanathan@ssomens.com',@TEMP_BANDWIDTH_CALCULATION);
CALL TS_VW_REPORT_BANDWIDTH_CALCULATION();
-- USER RIGHTS
CALL SP_TS_LOGIN_CREATION_INSERT('DEEPANAIDU25@MAIL.COM','ADMIN','2014-09-07','EXPATSINTEGRATED@GMAIL.COM',@SUCCESS_FLAG);
CALL SP_TS_LOGIN_UPDATE('raja@gmail.com','USER','2014-04-02','dhandapani.sattanathan@ssomens.com',@UR_FLAG);
CALL SP_TS_LOGIN_TERMINATE_SAVE('DEEPANAIDU25@MAIL.COM','2014-05-03','NEW USER','EXPATSINTEGRATED@GMAIL.COM',@SUCCESS_FLAG);
CALL SP_TS_USER_RIGHTS_BASIC_PROFILE_SAVE('dhandapani.sattanathan@ssomens.com','ADMIN','USER,SUPER ADMIN','1,2,3,4,5,6',@UR_FLAG);
CALL SP_TS_USER_RIGHTS_BASIC_PROFILE_UPDATE('dhandapani.sattanathan@ssomens.com','ADMIN','ADMIN,USER','1,3,5,9',@UR_FLAG);
CALL SP_TS_ROLE_CREATION_UPDATE('USER1','ADMIN','2,48,81,59','dhandapani.sattanathan@ssomens.com','SQLTEAM',@RC_FLAG);
CALL SP_TS_ROLE_CREATION_INSERT('USER1','USER','1,2,3,4','dhandapani.sattanathan@ssomens.com','SQL_TEAM',@RC_FLAG);
CALL SP_ACCESS_RIGHTS_TERMINATE_REJOIN_LOGINID();
CALL SP_TS_ACCESS_RIGHTS_SITE_MAINTANENCE('1,2,3,4,5');
-- EMPLOYEE
CALL SP_TS_EMPLOYEE_DETAILS_INSERT('safiyullah.mohideen@ssomens.com','SAFIYULLAH','MOHIDEEN','1988-09-02','PROGRAMMER','7654443333','SAFI','STAFF','9324338799',
'56TRGHY5E6T4EWRW','23RWEFDSF3WREWF332','X','X','X','X','X','dhandapani.sattanathan@ssomens.com',@FLAG);
CALL SP_TS_EMPLOYEE_DETAILS_SEARCH_UPDATE(1,'SAFIYULLAH','MOHIDEEN','1988-09-02','PROGRAMMER','7654443333','SAFI','STAFF','9324338799',
'56TRGHY5E6T4EWRW','23RWEFDSF3WREWF332','X','X','X','X','X','dhandapani.sattanathan@ssomens.com',@FLAG);
-- COMMON
CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',','UARD_ID=1,2,4,3,UARD_TIMESTAMP=2014-09-17',@VALUE,@REMAINING_STRING);
CALL SP_TS_SINGLE_TABLE_ROW_DELETION(2,7961,'dhandapani.sattanathan@ssomens.com',@FLAG);
CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID('dhandapani.sattanathan@ssomens.com',@ULD_ID);
-- EMAIL
CALL SP_TS_EMAIL_TEMPLATE_INSERT('REPORT','REPORT FOR [REPORT NAME]','HELLO [MAILID_USERNAME] ,PLEASE FIND THE CURRENT ATTACHED REPORT:','dhandapani.sattanathan@ssomens.com',@FLAG);

