INSERT INTO TEMP_USER_ABSENT_COUNT20140917154918_1(ULD_ID,UNAME,ABSENT_COUNT) (SELECT ULD.ULD_ID,ULD.ULD_LOGINID,COUNT(UARD.ABSENT_FLAG) 
FROM USER_ADMIN_REPORT_DETAILS UARD,USER_LOGIN_DETAILS ULD WHERE UARD.ULD_ID=(SELECT ULD_ID FROM TEMP_ACTIVE_USER WHERE ID=11) AND (UARD.UARD_DATE BETWEEN "2014-09-01" AND "2014-09-30") 
AND UARD.ABSENT_FLAG="X" AND UARD.ULD_ID = ULD.ULD_ID AND ULD.ULD_ID=(SELECT ULD_ID FROM TEMP_ACTIVE_USER WHERE ID=11));

SELECT DISTINCT ULD_ID FROM USER_ADMIN_REPORT_DETAILS WHERE (UARD_DATE BETWEEN "2014-09-01" AND "2014-09-30") AND ABSENT_FLAG="X";

SELECT ULD.ULD_ID,ULD.ULD_LOGINID,COUNT(UARD.ABSENT_FLAG) FROM USER_ADMIN_REPORT_DETAILS UARD,USER_LOGIN_DETAILS ULD 
WHERE (UARD.UARD_DATE BETWEEN "2014-09-01" AND "2014-09-30") AND UARD.ABSENT_FLAG="X" AND UARD.ULD_ID = ULD.ULD_ID AND ULD.ULD_ID=8;

SELECT CHAR_LENGTH('USER,ADMIN'); 
SELECT SUBSTRING_INDEX('USER,ADMIN',',',1); 
(SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA = BASICROLE);
-- INSERTING EACH ROLES TABLE
INSERT INTO BASIC_ROLE_PROFILE (URC_ID, BRP_BR_ID, ULD_ID) VALUES (URCID, BASICROLES_ID, USERSTAMP_ID);
SELECT  CHAR_LENGTH(SUBSTRING_INDEX('USER,ADMIN',',',1)) + 2;
SELECT  MID('USER,ADMIN', 6, 10);    

SELECT CHAR_LENGTH('ADMIN'); 
SELECT SUBSTRING_INDEX('ADMIN', ',', 1); 
(SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA = BASICROLES_1);
SELECT CONCAT ('3,',"'",1,"',");
SELECT CHAR_LENGTH(SUBSTRING_INDEX('ADMIN', ',', 1)) + 2;
SELECT MID('ADMIN', 7, 5);
SELECT SUBSTRING('3,1,',1,(CHAR_LENGTH('3,1,')-1) );
--  DELETING BASIC ROLES WHICH IS NOT AVAILABLE IN THE INPUT DURING UPDATION
DELETE FROM BASIC_ROLE_PROFILE WHERE BRP_BR_ID NOT IN (3,1) AND URC_ID =1;

SELECT ADDDATE("2014-09-01",1);
SELECT DATE_FORMAT("2014-08-31",'%d-%m-%Y,%a');
SELECT DATE_FORMAT(UARD_DATE,'%d-%m-%Y,%a');
SELECT @A=(SELECT PH_DATE FROM PUBLIC_HOLIDAY WHERE PH_DATE='2014-10-0');

INSERT INTO ONDUTY_ENTRY_DETAILS(OED_DATE, OED_DESCRIPTION, ULD_ID)VALUES('2014-10-21','STICK',2);

SELECT UARD_DATE FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE='2014-10-01';

CALL SP_TS_DAILY_REPORT_INSERT(REPORT,REASON,FINALDATE,URCID,LOGIN_ID,URE_PERMISSION,URE_ATTENDANCE,URE_PDID,URE_MORNING_SESSION,URE_AFTERNOON_SESSION,BANDWIDTH,URE_ULD_ID,@REPORT_SUCCESS);

-- FOR CHECK CONSTRAINTS

INSERT INTO EMPLOYEE_DETAILS(ULD_ID, EMP_FIRST_NAME, EMP_LAST_NAME, EMP_DOB, EMP_DESIGNATION, EMP_MOBILE_NUMBER, EMP_NEXT_KIN_NAME, EMP_ALT_MOBILE_NO, EMP_USERSTAMP_ID)VALUES
(42,	'vasanth',	'g',	'1992-06-06'	,'TESTER'	,'86088524h7'	,'vasanth'	,	'8g87650981'	,1);

UPDATE EMPLOYEE_DETAILS  SET EMP_DOB='1999-08-03', EMP_DESIGNATION='DEVELOPER', EMP_MOBILE_NUMBER ='345U66n532', EMP_ALT_MOBILE_NO=	'8806298841' WHERE EMP_ID=6;

INSERT INTO project_details (PD_PROJECT_NAME, PD_PROJECT_DESCRIPTION, ULD_ID )VALUES('BHU','SFSDF',2);

UPDATE PROJECT_DETAILS SET PD_PROJECT_NAME='YHHN', PD_PROJECT_DESCRIPTION='DSFGD' WHERE PD_ID=6;

SELECT '2038-08-03'< DATE_ADD(CURDATE(),INTERVAL +18 YEAR);

SELECT LOCATE(',', '5,6,4,3');
SELECT SUBSTRING('5,6,4,3',1,2-1);
SELECT SUBSTRING('3GB',2,2);

CALL SP_TS_ACCESS_RIGHTS_SITE_MAINTANENCE(NULL);

SELECT TH_ID,ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,TH_USERSTAMP_ID,TH_TIMESTAMP 
FROM TEMP_TICKLER_HISTORY WHERE ID=1;

INSERT INTO TEMP_UARD_TICKLER_HISTORY20140919154236_1 VALUES(1,29,(SELECT ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@ULDID),
(SELECT TP_TYPE FROM TICKLER_PROFILE WHERE TP_ID = 1),(SELECT TTIP_DATA FROM TICKLER_TABID_PROFILE WHERE TTIP_ID=2),@TH_OLDVALUE,@TH_NEWVALUE,@THUSERSTAMP,@THTIMESTAMP);

CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',','UARD_ID=1,2,4,3,UARD_TIMESTAMP=2014-09-17',@VALUE,@REMAINING_STRING);
SELECT @VALUE;
SELECT @REMAINING_STRING;

CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=','UARD_ID=1',@COLUMN_NAME,@COLUMN_VALUE);
SELECT @COLUMN_NAME;
SELECT @COLUMN_VALUE;

SELECT '1' REGEXP BINARY '^[0-9]';
SELECT REPLACE('EI,2,UARD_TIMESTAMP=2014-09-17 18:10:31',',2',',YII');
SELECT REPLACE('EI,2,UARD_TIMESTAMP=2014-09-17 18:10:31',@VALUE,@REPLACE_STRING);

SELECT TH.TH_OLD_VALUE,T.TH_OLD_VALUE FROM temp_uard_tickler_history20140920163829_1 T, TICKLER_HISTORY TH WHERE T.TH_ID=TH.TH_ID;

SELECT TH.TH_NEW_VALUE,T.TH_NEW_VALUE FROM temp_uard_tickler_history20140920163829_1 T, TICKLER_HISTORY TH WHERE T.TH_ID=TH.TH_ID;

SELECT TH_OLD_VALUE,TH_NEW_VALUE FROM temp_uard_tickler_history20140920163829_1;

SELECT * FROM temp_uard_tickler_history20140920163829_1 WHERE ULD_LOGINID='safiyullah.mohideen@ssomens.com' AND EVENT_TYPE='UPDATION';

CALL SP_TS_USER_ADMIN_REPORT_DETAILS_TICKLER_DATA('dhandapani.sattanathan@ssomens.com',@TEMP_UARD_TICKLER_HISTORY);

SELECT * FROM USER_ADMIN_REPORT_DETAILS LIMIT 15;

UPDATE CONFIG_SQL_FORMAT SET `TIMESTAMP`='2014-08-01';

CALL SP_TS_POST_AUDIT_CREATE_INSERT('dest_04092014');
CALL SP_TS_MIG_USER_RIGHTS_INSERT('ts_source_20140901','dest_04092014','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_CONFIGURATION_INSERT ('ts_source_20140901','dest_04092014','dhandapani.sattanathan@ssomens.com');

SELECT (UARD_DATE) FROM user_admin_report_details WHERE ULD_ID=29 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=5;;

SELECT UARD.UARD_DATE,AC.AC_DATA FROM USER_ADMIN_REPORT_DETAILS UARD,ATTENDANCE_CONFIGURATION AC WHERE UARD.ULD_ID=36 
AND UARD.UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD.UARD_PERMISSION IS NOT NULL AND UARD.UARD_PERMISSION=AC.AC_ID;

SELECT COUNT(UARD_ATTENDANCE) FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=4;
SELECT COUNT(UARD_ATTENDANCE) FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=5;
SELECT COUNT(UARD_ATTENDANCE) FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=6;
SELECT COUNT(UARD_ATTENDANCE) FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=7;
SELECT COUNT(UARD_ATTENDANCE) FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=8;

CREATE TABLE TEMP_ATTENDANCE_COUNT20140925152318_29 (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
LOGINID VARCHAR(50) NOT NULL,
PERSENT DECIMAL(3,1) NOT NULL,
ABSENT DECIMAL(3,1) NOT NULL,
ONDUTY DECIMAL(3,1) NOT NULL,
PERMISSION INT NOT NULL);

INSERT INTO TEMP_ATTENDANCE_COUNT20140925152318_29(ULD_ID,PERSENT,ABSENT,ONDUTY,HALFDAY,HALFOD,PERMISSION) VALUES
((ULDID),(SELECT COUNT(UARD_ATTENDANCE) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=5),
(SELECT COUNT(UARD_ATTENDANCE) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=6),
(SELECT COUNT(UARD_ATTENDANCE) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=7),
(SELECT COUNT(UARD_ATTENDANCE) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=36 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=4 AND UARD_AM_SESSION IN (1,2) AND UARD_PM_SESSION IN (1,2)),
(SELECT COUNT(UARD_ATTENDANCE) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=8),
(SELECT COUNT(UARD_PERMISSION) FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31"));
INSERT INTO TEMP_ATTENDANCE_COUNT20140925133652_29(ULD_ID,ATTENDANCE,PERMISSION)
(SELECT ULD_ID,UARD_ATTENDANCE,UARD_PERMISSION FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=29 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31");

SELECT SUM(4+0.5);

SELECT PRESENT,ABSENT,ONDUTY,HALFDAY,HALFOD,PERMISSION INTO @PRSNT,@ABSNT,@OD,@HDL,@HOD,@PERMSN FROM TEMP_ATTENDANCE_COUNT20140925155807_29;
INSERT INTO TEMP_ATTENDANCE_CALCULATION20140925160520_29(LOGINID,PRESENT,ABSENT,ONDUTY,PERMISSION)VALUES ("safiyullah.mohideen@ssomens.com",22.5,1.5,1.0,2);

SELECT SUM(AC.AC_DATA) FROM USER_ADMIN_REPORT_DETAILS UARD,ATTENDANCE_CONFIGURATION AC 
WHERE UARD.ULD_ID=29 AND UARD.UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD.UARD_PERMISSION IS NOT NULL AND UARD.UARD_PERMISSION=AC.AC_ID;

SELECT DISTINCT ULD_ID FROM user_admin_report_details WHERE UARD_DATE BETWEEN '2014-09-01' AND '2014-09-31';

SELECT DAY('2014-09-01');
SELECT LAST_DAY('2014-09-01');

SELECT DAY(LAST_DAY('2014-09-01'));
SELECT DAYOFMONTH(LAST_DAY('2014-09-01'));
SET @E='2014-06-30';
SET @S='2014-06-01';

SELECT COUNT(*) FROM public_holiday WHERE DAYOFWEEK(PH_DATE) < 7 AND PH_DATE BETWEEN @S AND @E;

SELECT(ROW+1) AS SUNDAYS FROM
(SELECT @ROW := @ROW + 1 AS ROW FROM 
(SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) T1,
(SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) T2, 
(SELECT @ROW:=-1) T3 LIMIT 31) B
WHERE DATE_ADD(@S, INTERVAL ROW DAY) BETWEEN @S AND @E AND DAYOFWEEK(DATE_ADD(@S, INTERVAL ROW DAY))=1;

INSERT INTO TEMP_ATTENDANCE_CALCULATION20140927112906_1(REPORT_DATE,PRESENT)    
(SELECT DATE_FORMAT(UARD_DATE,'%d-%m-%Y,%a'),"X" FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=1 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=5);

UPDATE temp_attendance_calculation20140927151317_1 X INNER JOIN (SELECT UARD.UARD_DATE,AC.AC_DATA FROM USER_ADMIN_REPORT_DETAILS UARD,ATTENDANCE_CONFIGURATION AC 
WHERE UARD.ULD_ID=1 AND UARD.UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD.UARD_PERMISSION IS NOT NULL AND UARD.UARD_PERMISSION=AC.AC_ID) Y
ON X.REPORT_DATE=Y.UARD_DATE SET X.PERMISSION_HRS=Y.AC_DATA;

SELECT UARD_AM_SESSION,UARD_PM_SESSION FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=4 AND UARD_AM_SESSION IN (1,2) AND UARD_PM_SESSION IN (1,2);
SELECT UARD_AM_SESSION,UARD_PM_SESSION FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31' AND UARD_ATTENDANCE=8 AND UARD_AM_SESSION IN (1,2) AND UARD_PM_SESSION IN (1,2);

SELECT * FROM user_admin_report_details WHERE ULD_ID=36 AND UARD_DATE BETWEEN '2014-07-01' AND '2014-07-31';

SELECT DATE_FORMAT(UARD_DATE,'%d-%m-%Y,%a'),UARD_AM_SESSION,UARD_PM_SESSION  FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=36 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=4 AND UARD_AM_SESSION IN (1,2) AND UARD_PM_SESSION IN (1,2) LIMIT 0,1;

SELECT UARD_DATE,UARD_AM_SESSION,UARD_PM_SESSION  FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=36 AND UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" AND UARD_ATTENDANCE=4 AND UARD_AM_SESSION IN (1,2) AND UARD_PM_SESSION IN (1,2) LIMIT 1,1;

SET FOREIGN_KEY_CHECKS=0;
SET FOREIGN_KEY_CHECKS=1;
TRUNCATE EMPLOYEE_DETAILS;

UPDATE TEMP_ATTENDANCE20140930175008_1 X 
INNER JOIN (SELECT UARD.UARD_DATE,AC.AC_DATA FROM USER_ADMIN_REPORT_DETAILS UARD,ATTENDANCE_CONFIGURATION AC 
WHERE UARD.ULD_ID=1 AND UARD.UARD_DATE BETWEEN "2014-07-01" AND "2014-07-31" 
AND UARD.UARD_PERMISSION IS NOT NULL AND UARD.UARD_PERMISSION=AC.AC_ID) Y ON X.REPORT_DATE=Y.UARD_DATE SET X.PERMISSION_HRS=Y.AC_DATA;

SELECT DATE_FORMAT(UARD_DATE,"%d-%m-%Y,%a"),"X" FROM USER_ADMIN_REPORT_DETAILS;

SELECT DISTINCT COLUMN_NAME  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='USER_ADMIN_REPORT_DETAILS' AND COLUMN_KEY='PRI' AND TABLE_SCHEMA=(SELECT DATABASE());

INSERT INTO TEMP_2_COLUMN_NAMES_20141001161121_1(COLUMN_NAME) SELECT DISTINCT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='USER_ADMIN_REPORT_DETAILS' AND TABLE_SCHEMA=(SELECT DATABASE());

CALL SP_TS_SINGLE_TABLE_ROW_DELETION(2,7902,'dhandapani.sattanathan@ssomens.com',@FLAG);

CREATE OR REPLACE VIEW VW_TS_POST_AUDIT AS
SELECT PAMP.PREAMP_DATA AS DOMAIN_NAME,IF(PAH.PREAMP_ID=3,(SELECT SUM(PREAMP_SQL_REC) FROM PRE_AUDIT_HISTORY WHERE PREAMP_ID=3),PREAMP_SQL_REC) AS SCDB_NO_OF_RECORDS,
PASP.PREASP_DATA AS PREAUDIT_SPLITTED_TABLE,PASP.PREASP_NO_OF_REC AS PRE_AUDIT_NO_OF_REC,PAP.POSTAP_DATA AS POSTAUDIT_SPLITTED_TABLE,
PAH.POSTAH_NO_OF_REC AS POST_AUDIT_NO_OF_REC,PAH.POSTAH_NO_OF_REJ AS NO_OF_REJ,ULD.ULD_LOGINID AS USERSTAMP,PAH.POSTAH_TIMESTAMP AS TIMESTAMP 
FROM PRE_AUDIT_MAIN_PROFILE PAMP,PRE_AUDIT_HISTORY PAUH,PRE_AUDIT_SUB_PROFILE PASP,POST_AUDIT_PROFILE PAP,POST_AUDIT_HISTORY PAH,TS_DEST.USER_LOGIN_DETAILS ULD
WHERE PAMP.PREAMP_ID=PAUH.PREAMP_ID AND PAP.POSTAP_ID=PAH.POSTAP_ID AND PASP.PREASP_ID=PAH.PREASP_ID AND PAMP.PREAMP_ID=PAH.PREAMP_ID AND PASP.PREASP_DATA=PAP.POSTAP_DATA 
AND ULD.ULD_ID=PAH.ULD_ID GROUP BY PAP.POSTAP_DATA ORDER BY PAMP.PREAMP_DATA;

CALL SP_TS_POST_AUDIT('TS_DEST');

CALL SP_TS_EMPLOYEE_DETAILS_SEARCH_UPDATE(1,'SAFIYULLAH','MOHIDEEN','1988-09-02','PROGRAMMER','7654443333','SAFI','STAFF','9324338799',
'56TRGHY5E6T4EWRW','23RWEFDSF3WREWF332','X','X','X','X','','dhandapani.sattanathan@ssomens.com',@FLAG);

SELECT SUM(IF(WEEKDAY('2014-09-02') >= 5, 1, 0)) AS WeekendCount, SUM(IF(WEEKDAY('2014-09-02') < 5, 1, 0)) AS WeekdayCount;

SELECT (DATEDIFF(LAST_DAY('2014-08-02'),'2014-08-02') + 1) - 
((WEEK(LAST_DAY('2014-08-02')) - WEEK('2014-08-02')) * 2) -
(case when weekday('2014-08-02') = 6 then 1 else 0 end) - 
(case when weekday(LAST_DAY('2014-08-02')) = 5 then 1 else 0 end);

SET @S='2014-08-01';
SET @E='2014-08-30';
SET @ID=1;
SELECT UARD_DATE,UARD_BANDWIDTH FROM user_admin_report_details WHERE ULD_ID=@ID AND UARD_DATE BETWEEN @S AND @E;

SELECT SUBSTRING_INDEX('m.premkumar@ssomens.com','@',+1);

INSERT INTO temp_bandwidth_calculation20141016121552_1 (LOGINID,BANDWIDTH_MB) 
SELECT  'TOTAL' ,SUM(BANDWIDTH_MB)BANDWIDTH_MB FROM temp_bandwidth_calculation20141016121552_1 ;

CREATE OR REPLACE VIEW VW_TS_BANDWIDTH_CALCULATION  AS SELECT COALESCE(UARD_DATE,'TOTAL'), SUM(UARD_BANDWIDTH)
FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=1 AND UARD_DATE BETWEEN '2014-08-01' AND '2014-08-30' GROUP	BY UARD_DATE WITH ROLLUP;

SELECT ULD_ID,ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=(SELECT DISTINCT ULD_ID FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_DATE BETWEEN '2014-08-01' AND '2014-08-30' LIMIT 2,1);
SELECT COUNT(DISTINCT ULD_ID) FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_DATE BETWEEN "2013-12-01" AND "2013-12-31";

-- BANDWIDTH CALC
-- MULTIPLE
CREATE OR REPLACE VIEW VW_ULDID_MONTH AS SELECT DISTINCT ULD_ID,DATE_FORMAT(UARD_DATE,'%Y-%m-01')`MONTH` FROM USER_ADMIN_REPORT_DETAILS;

CREATE OR REPLACE VIEW VW_ALL_BANDWIDTH_USAGE AS SELECT VUM.ULD_ID AS ULD_ID,ULD.ULD_LOGINID AS LOGINID,VUM.`MONTH` AS REPORT_DATE,SUM(UARD_BANDWIDTH)AS BANDWIDTH_MB
FROM USER_ADMIN_REPORT_DETAILS UARD,USER_LOGIN_DETAILS ULD,VW_ULDID_MONTH VUM WHERE UARD.ULD_ID=VUM.ULD_ID AND ULD.ULD_ID = UARD.ULD_ID AND ULD.ULD_ID = VUM.ULD_ID 
AND (UARD.UARD_DATE BETWEEN VUM.`MONTH` AND LAST_DAY(VUM.`MONTH`))GROUP BY VUM.`MONTH`,VUM.ULD_ID;

CREATE OR REPLACE VIEW VW_ALL_BANDWIDTH_USAGE AS SELECT VUM.ULD_ID AS ULD_ID,ULD.ULD_LOGINID AS LOGINID,VUM.`MONTH` AS REPORT_DATE,SUM(UARD_BANDWIDTH)AS BANDWIDTH_MB
FROM USER_ADMIN_REPORT_DETAILS UARD JOIN USER_LOGIN_DETAILS ULD ON ULD.ULD_ID = UARD.ULD_ID JOIN VW_ULDID_MONTH VUM ON UARD.ULD_ID=VUM.ULD_ID AND ULD.ULD_ID = VUM.ULD_ID
WHERE UARD.UARD_DATE BETWEEN VUM.`MONTH` AND LAST_DAY(VUM.`MONTH`)GROUP BY VUM.`MONTH`,VUM.ULD_ID;

CREATE OR REPLACE VIEW VW_ALL_BANDWIDTH_USAGE AS SELECT VUM.ULD_ID AS ULD_ID,ULD.ULD_LOGINID AS LOGINID,VUM.`MONTH` AS REPORT_DATE,SUM(UARD_BANDWIDTH)AS BANDWIDTH_MB
FROM USER_ADMIN_REPORT_DETAILS UARD INNER JOIN USER_LOGIN_DETAILS ULD ON  ULD.ULD_ID = UARD.ULD_ID INNER JOIN VW_ULDID_MONTH VUM ON UARD.ULD_ID=VUM.ULD_ID AND ULD.ULD_ID = VUM.ULD_ID 
WHERE UARD.UARD_DATE BETWEEN VUM.`MONTH` AND LAST_DAY(VUM.`MONTH`)GROUP BY VUM.`MONTH`,VUM.ULD_ID;

SELECT COALESCE(LOGINID,'TOTAL')LOGINID,SUM(BANDWIDTH_MB)BANDWIDTH_MB FROM VW_ALL_BANDWIDTH_USAGE WHERE REPORT_DATE ='2013-10-01' GROUP BY LOGINID WITH ROLLUP;

-- SINGLE

CREATE OR REPLACE VIEW VW_SINGLE_BANDWIDTH_USAGE AS SELECT VUM.ULD_ID AS ULD_ID,UARD.UARD_DATE AS REPORT_DATE,UARD_BANDWIDTH AS BANDWIDTH_MB
FROM USER_ADMIN_REPORT_DETAILS UARD JOIN USER_LOGIN_DETAILS ULD ON UARD.ULD_ID=ULD.ULD_ID JOIN VW_ULDID_MONTH VUM ON UARD.ULD_ID=VUM.ULD_ID AND ULD.ULD_ID = VUM.ULD_ID 
WHERE UARD.UARD_DATE BETWEEN VUM.`MONTH` AND LAST_DAY(VUM.`MONTH`)GROUP BY UARD.UARD_ID ORDER BY UARD.ULD_ID;

SELECT COALESCE(DATE_FORMAT(REPORT_DATE,"%d-%m-%Y,%a"),'TOTAL')REPORT_DATE,SUM(BANDWIDTH_MB)BANDWIDTH_MB FROM VW_SINGLE_BANDWIDTH_USAGE 
WHERE ULD_ID=1 AND REPORT_DATE BETWEEN "2013-10-01" AND "2013-10-31" GROUP BY REPORT_DATE WITH ROLLUP;

-- ATTENDANCE PDF

DROP SCHEMA TS_TEST;
CREATE SCHEMA TS_TEST;

ALTER TABLE EMAIL_TEMPLATE_DETAILS AUTO_INCREMENT=11;
SELECT DATE_FORMAT('2014-11-28','%B-%Y') INTO @A;
CALL SP_TS_ATTENDANCE_CALCULATION ('NOVEMBER-2014','','RAJA.GUNASEKARAN@SSOMENS.COM',@TEMP_USER_ABSENT_COUNT,@TOTAL_DAYS, @WORKING_DAYS)


CALL SP_TS_REPORT_COUNT_ABSENT_FLAG('NOVEMBER-2014','RAJA.GUNASEKARAN@SSOMENS.COM',@TEMP_USER_ABSENT_COUNT)
SELECT * FROM TEMP_ATTENDANCE_CALCULATION20141128122442_44 A LEFT JOIN TEMP_USER_ABSENT_COUNT20141128125608_44 B ON B.UNAME=A.LOGINID ORDER BY LOGINID ASC
SELECT * FROM TEMP_USER_ABSENT_COUNT20141128125608_44
SELECT @TEMP_USER_ABSENT_COUNT


SELECT RC.RC_NAME,UA.UA_JOIN_DATE,URC1.URC_DATA 
FROM USER_LOGIN_DETAILS ULD,USER_ACCESS UA ,USER_RIGHTS_CONFIGURATION URC,USER_RIGHTS_CONFIGURATION URC1,ROLE_CREATION RC WHERE UA.UA_EMP_TYPE=URC1.URC_ID AND ULD.ULD_ID=UA.ULD_ID AND URC.URC_ID=RC.URC_ID AND RC.RC_ID=UA.RC_ID AND ULD_LOGINID='SASIKALA.DJEASANKAR@SSOMENS.COM' AND UA.UA_REC_VER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS UA,USER_LOGIN_DETAILS ULD WHERE ULD.ULD_ID=UA.ULD_ID AND ULD_LOGINID='SASIKALA.DJEASANKAR@SSOMENS.COM' AND UA_JOIN IS NOT NULL) ORDER BY RC_NAME;

SELECT DISTINCT RC.RC_NAME,UA.UA_JOIN_DATE,URC1.URC_DATA,EMP.EMP_ID,EMP.EMP_FIRST_NAME,EMP.EMP_LAST_NAME,DATE_FORMAT(EMP.EMP_DOB,'%D-%M-%Y') AS EMP_DOB,EMP.EMP_DESIGNATION,EMP.EMP_MOBILE_NUMBER,EMP.EMP_NEXT_KIN_NAME,EMP.EMP_RELATIONHOOD,EMP.EMP_ALT_MOBILE_NO,CPD.CPD_LAPTOP_NUMBER,CPD.CPD_CHARGER_NUMBER,CPD.CPD_LAPTOP_BAG,CPD.CPD_MOUSE,CPD.CPD_DOOR_ACCESS,CPD.CPD_ID_CARD,CPD.CPD_HEADSET,ULD.ULD_LOGINID,DATE_FORMAT(CONVERT_TZ(EMP.EMP_TIMESTAMP,'+00:00','+05:30'), '%D-%M-%Y %T') AS EMP_TIMESTAMP 
FROM USER_ACCESS UA ,USER_RIGHTS_CONFIGURATION URC,USER_RIGHTS_CONFIGURATION URC1,ROLE_CREATION RC,EMPLOYEE_DETAILS EMP,USER_LOGIN_DETAILS ULD ,COMPANY_PROPERTIES_DETAILS CPD WHERE EMP.EMP_ID=CPD.EMP_ID AND (EMP.EMP_FIRST_NAME ='SASIKALA' AND EMP.EMP_LAST_NAME ='DJEASANKAR') AND  EMP.ULD_ID=ULD.ULD_ID AND UA.UA_EMP_TYPE=URC1.URC_ID AND ULD.ULD_ID=UA.ULD_ID AND URC.URC_ID=RC.URC_ID AND RC.RC_ID=UA.RC_ID AND ULD_LOGINID='SASIKALA.DJEASANKAR@SSOMENS.COM' AND UA.UA_REC_VER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS UA,USER_LOGIN_DETAILS ULD WHERE ULD.ULD_ID=UA.ULD_ID AND ULD_LOGINID='SASIKALA.DJEASANKAR@SSOMENS.COM' AND UA_JOIN IS NOT NULL)ORDER BY EMP.EMP_FIRST_NAME,EMP.EMP_LAST_NAME

SELECT ROW+1 AS SUNDAYS  FROM	(SELECT @ROW := @ROW + 1 AS ROW FROM 
(SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) T1,
(SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6) T2, (SELECT @ROW:=-1) T3 LIMIT 31) B
WHERE DATE_ADD('2014-11-01', INTERVAL ROW DAY) BETWEEN '2014-11-01' AND '2014-11-30' AND DAYOFWEEK(DATE_ADD('2014-11-01', INTERVAL ROW DAY))=1;

SELECT DISTINCT RC.RC_NAME,UA.UA_JOIN_DATE,URC1.URC_DATA,EMP.EMP_ID,EMP.EMP_FIRST_NAME,EMP.EMP_LAST_NAME,DATE_FORMAT(EMP.EMP_DOB,'%D-%M-%Y') AS EMP_DOB,EMP.EMP_DESIGNATION,EMP.EMP_MOBILE_NUMBER,EMP.EMP_NEXT_KIN_NAME,EMP.EMP_RELATIONHOOD,EMP.EMP_ALT_MOBILE_NO,CPD.CPD_LAPTOP_NUMBER,CPD.CPD_CHARGER_NUMBER,CPD.CPD_LAPTOP_BAG,CPD.CPD_MOUSE,CPD.CPD_DOOR_ACCESS,CPD.CPD_ID_CARD,CPD.CPD_HEADSET,ULD.ULD_LOGINID,DATE_FORMAT(CONVERT_TZ(EMP.EMP_TIMESTAMP,'+00:00','+05:30'), '%D-%M-%Y %T') AS EMP_TIMESTAMP 
FROM EMPLOYEE_DETAILS EMP LEFT JOIN COMPANY_PROPERTIES_DETAILS CPD ON EMP.EMP_ID=CPD.EMP_ID,USER_LOGIN_DETAILS ULD,USER_ACCESS UA ,USER_RIGHTS_CONFIGURATION URC,USER_RIGHTS_CONFIGURATION URC1,ROLE_CREATION RC  WHERE  (EMP.EMP_FIRST_NAME ='RAJA' AND EMP.EMP_LAST_NAME ='GUNASEKARAN') AND  EMP.ULD_ID=ULD.ULD_ID AND UA.UA_EMP_TYPE=URC1.URC_ID AND ULD.ULD_ID=UA.ULD_ID AND URC.URC_ID=RC.URC_ID AND RC.RC_ID=UA.RC_ID AND ULD_LOGINID='RAJA.GUNASEKARAN@SSOMENS.COM' AND UA.UA_REC_VER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS UA,USER_LOGIN_DETAILS ULD WHERE ULD.ULD_ID=UA.ULD_ID AND ULD_LOGINID='RAJA.GUNASEKARAN@SSOMENS.COM' AND UA_JOIN IS NOT NULL) ORDER BY EMP.EMP_FIRST_NAME,EMP.EMP_LAST_NAME;

SELECT RC.RC_NAME,UA.UA_JOIN_DATE,URC1.URC_DATA FROM USER_LOGIN_DETAILS ULD,USER_ACCESS UA ,USER_RIGHTS_CONFIGURATION URC,USER_RIGHTS_CONFIGURATION URC1,ROLE_CREATION RC WHERE UA.UA_EMP_TYPE=URC1.URC_ID AND ULD.ULD_ID=UA.ULD_ID AND URC.URC_ID=RC.URC_ID AND RC.RC_ID=UA.RC_ID AND ULD_LOGINID='RAJA.GUNASEKARAN@SSOMENS.COM' AND UA.UA_REC_VER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS UA,USER_LOGIN_DETAILS ULD WHERE ULD.ULD_ID=UA.ULD_ID AND ULD_LOGINID='RAJA.GUNASEKARAN@SSOMENS.COM' AND UA_JOIN IS NOT NULL) ORDER BY RC_NAME

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_BANK_NAME VARCHAR(50) NOT NULL;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_BRANCH_NAME VARCHAR(50) NOT NULL;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_ACCOUNT_NAME VARCHAR(50) NOT NULL;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_ACCOUNT_NO VARCHAR(50) NOT NULL;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_IFSC_CODE VARCHAR(50) NOT NULL;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_ACCOUNT_TYPE VARCHAR(15) NOT NULL;
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN EMP_BRANCH_ADDRESS TEXT NOT NULL;




