SELECT LID.LID_ID,LID.LID_ITEM_NO,LCD.CLD_CONTRACT_NO,LID.LID_DESCRIPTION,LID.LID_COST,LID.LID_INTERNAL_COST,LID.LID_PERCENTAGE_LEVEL,LID.LID_COST_AFTER_DISCOUNT,LMU.LMU_UNIT,LID.LID_QTY_SOLD,LID.LID_TIMESTAMP
FROM LMC_INVENTORY_ITEM_DETAILS LID,LMC_CONTRACT_DETAILS LCD,LMC_MEASURE_UNIT LMU WHERE LID.CLD_ID = LCD.CLD_ID AND LID.LMU_ID = LMU.LMU_ID ORDER BY LID.LID_ITEM_NO


SELECT DISTINCT LMU_UNIT FROM LMC_MEASURE_UNIT ORDER BY LMU_UNIT;

CALL SP_INVENTORY_LIST_ENTRY_UPDATE(1,'123344','373737','TEST',888,999,10,860,'BL',33,'sasi',@SUCCESS_MESSAGE);

SELECT @SUCCESS_MESSAGE;
IN SEARCH_OPTION INTEGER,
IN CONTRACTNO VARCHAR(15),
IN ITEMNO  VARCHAR(10),
IN DESCRIPTION TEXT,
IN COST  DECIMAL(7,2),
IN INTERNAL_COST DECIMAL(7,2),
IN PERCENTAGE_LEVEL INTEGER,
IN COST_AFTER_DISCOUNT DECIMAL(7,2),
IN MEASURING_UNIT VARCHAR(10),
IN QUANTITY_SOLD INTEGER,
IN USERSTAMP VARCHAR(50),
OUT SUCCESS_MESSAGE INTEGER)

CALL SP_INVENTORY_LIST_ENTRY_UPDATE(2,'123344','3733338','TEST1234',8835,995,12,832,'DAY',35,'sasi',@SUCCESS_MESSAGE);
SELECT @SUCCESS_MESSAGE;

CALL SP_INVENTORY_LIST_ENTRY_UPDATE(1,'',CC/65677','35453','adjusting textbox height - HTML / CSS - Bytesbytes.com  topics  html / css  questionsOct 3, 200',2343.00,2342.00,23,1321.00,'ST',323,'raja',@SUCCESS_MESSAGE)CALL failed: (1064) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '','35453','adjusting textbox height - HTML / CSS - Bytesbytes.com  topics  html ' at line 1

SELECT ISS.LISD_ID,ISS.LISD_DATE,FUD.LID_ITEM_NO,FUD.LID_DESCRIPTION,ISS.LISD_WKLY_OPENING_BALANCE,ISS.LISD_ADD_NEW_STOCK,ISS.LISD_DRAWN,ISS.LISD_RETURNED,ISS.LISD_SITE_USED,ISS.LISD_SITE_STOCK,ISS.LISD_SOLD,ISS.LISD_BALANCE_STOCK 
FROM LMC_INVENTORY_SITE_STOCK_DETAILS ISS,LMC_INVENTORY_ITEM_DETAILS FUD WHERE ISS.LISD_DATE BETWEEN '2015-07-01' AND '2015-07-02'
AND ISS.LID_ID=FUD.LID_ID ORDER BY ISS.LISD_DATE,FUD.LID_ITEM_NO,FUD.LID_DESCRIPTION

SELECT ISS.LISD_ID,ISS.LISD_DATE,FUD.LID_ITEM_NO,FUD.LID_DESCRIPTION,ISS.LISD_WKLY_OPENING_BALANCE,ISS.LISD_ADD_NEW_STOCK,ISS.LISD_DRAWN,ISS.LISD_RETURNED,ISS.LISD_SITE_USED,ISS.LISD_SITE_STOCK,ISS.LISD_SOLD,ISS.LISD_BALANCE_STOCK 
FROM LMC_INVENTORY_SITE_STOCK_DETAILS ISS,LMC_INVENTORY_ITEM_DETAILS FUD WHERE FUD.LID_ITEM_NO='564656' AND ISS.LID_ID=FUD.LID_ID ORDER BY FUD.LID_ITEM_NO

SELECT ISS.LISD_ID,ISS.LISD_DATE,FUD.LID_ITEM_NO,FUD.LID_DESCRIPTION,ISS.LISD_WKLY_OPENING_BALANCE,ISS.LISD_ADD_NEW_STOCK,ISS.LISD_DRAWN,ISS.LISD_RETURNED,ISS.LISD_SITE_USED,ISS.LISD_SITE_STOCK,ISS.LISD_SOLD,ISS.LISD_BALANCE_STOCK 
FROM LMC_INVENTORY_SITE_STOCK_DETAILS ISS,LMC_INVENTORY_ITEM_DETAILS FUD WHERE FUD.LID_DESCRIPTION='TEST 1234' AND ISS.LID_ID=FUD.LID_ID ORDER BY FUD.LID_ITEM_NO

SELECT DATE_FORMAT(TRD_DATE,'%d-%m-%Y') AS TRD_DATE,TRD_LOCATION,CLD_CONTRACT_NO,TRD_CONTRACT_NO,T1.TEAM_NAME,DATE_FORMAT(TRD_REACH_SITE,'%H:%i' ) AS REACHSITE,DATE_FORMAT(TRD_LEAVE_SITE,'%H:%i' ) AS LEAVESITE,TOJ_ID,DATE_FORMAT(TRD_WEATHER_FROM_TIME,'%H:%i' ) AS WEATHERFROM,DATE_FORMAT(TRD_WEATHER_TO_TIME,'%H:%i' ) AS WEATHERTO,TRD_PIPE_TESTING,TRD_START_PRESSURE,TRD_END_PRESSURE,TRD_REMARK,TRD_WEATHER_REASON,TRD_IMG_FILE_NAME 
FROM LMC_TEAM_REPORT_DETAILS L,LMC_TEAM_CREATION T1,LMC_CONTRACT_DETAILS LCD WHERE L.TC_ID=T1.TC_ID AND L.TRD_CONTRACT_NO=LCD.CLD_ID AND TRD_ID=56

SELECT CLD_ID,CLD_CONTRACT_NO FROM LMC_CONTRACT_DETAILS WHERE LCS_ID = 1 AND TC_ID=(SELECT TC_ID FROM LMC_TEAM_CREATION WHERE TEAM_NAME='TEAM-1')

SELECT LID_ID,LID_ITEM_NO,LID_DESCRIPTION FROM LMC_INVENTORY_ITEM_DETAILS IID,LMC_CONTRACT_DETAILS LCD WHERE IID.CLD_ID=LCD.CLD_ID AND IID.CLD_ID=1 ORDER BY LID_ITEM_NO

SELECT LISU_ID,L2.LID_ITEM_NO,L2.LID_DESCRIPTION,L1.LISU_QUANTITY FROM LMC_INVENTORY_STOCK_USED L1,LMC_INVENTORY_ITEM_DETAILS L2 WHERE L1.LID_ID=L2.LID_ID AND L1.TRD_ID=60

INSERT INTO LMC_ERROR_MESSAGE_CONFIGURATION(EMC_ID,CNP_ID,EMC_CODE,EMC_DATA,ULD_ID,EMC_INITIALIZE_FLAG) VALUES ('167','2','167','PROJECT TIMELINE BETWEEN [SDATE] AND [EDATE]','1','X');
INSERT INTO LMC_ERROR_MESSAGE_CONFIGURATION(EMC_ID,CNP_ID,EMC_CODE,EMC_DATA,ULD_ID,EMC_INITIALIZE_FLAG) VALUES ('168','2','168','PROJECT TIMELINE FOR [MONTH]','1','X');

SELECT CLD_CUSTOMER_NAME, CLD_CONTRACT_NO, CLD_CREATED_DATE, CLD_END_DATE
FROM LMC_CONTRACT_DETAILS WHERE CLD_CREATED_DATE >='2015-06-01' 
AND (CLD_END_DATE <='2015-07-31' OR CLD_EXTENDED_DATE <='2015-07-31')

SELECT * FROM (SELECT CLDID,CONTRACT_NAME,STARTDATE,ENDDATE FROM TEMP_MAIN_REPORT_CHART_20150704120425_1 )AS A UNION ALL
SELECT * FROM (SELECT CLDID,CONTRACT_NAME,ENDDATE,EXTENDED_DATE FROM TEMP_MAIN_REPORT_CHART_20150704120425_1 ORDER BY CLDID) AS B ORDER BY CLDID,STARTDATE

SELECT * FROM (SELECT CLDID,CONTRACT_NAME,STARTDATE,ENDDATE,(SELECT CONCAT((SELECT DATE_FORMAT(STARTDATE,'%b-%d %Y')), '  -  ', (select DATE_FORMAT(ENDDATE,'%b-%d %Y')))) AS DATE_RANGE FROM TEMP_MAIN_REPORT_CHART_20150704102320_1 )AS A UNION ALL
SELECT * FROM (SELECT CLDID,CONTRACT_NAME,ENDDATE,EXTENDED_DATE,(SELECT CONCAT((SELECT DATE_FORMAT(ENDDATE,'%b-%d %Y')), '  -  ', (SELECT DATE_FORMAT(EXTENDED_DATE,'%b-%d %Y')))) AS DATE_RANGE FROM TEMP_MAIN_REPORT_CHART_20150704102320_1 ORDER BY CLDID) AS B ORDER BY CLDID,STARTDATE
    
SELECT * FROM
(select CLDID,CONTRACT_NAME,STARTDATE,ENDDATE,(SELECT CONCAT((SELECT DATE_FORMAT(STARTDATE,'%b-%d %Y')), '  -  ', (select DATE_FORMAT(ENDDATE,'%b-%d %Y')))) AS DATE_RANGE FROM TEMP_MAIN_REPORT_CHART_20150704102320_1 ) AS A
UNION ALL
SELECT * FROM (select CLDID,CONTRACT_NAME,ENDDATE,EXTENDED_DATE,(SELECT CONCAT((SELECT DATE_FORMAT(ENDDATE,'%b-%d %Y')), '  -  ', (SELECT DATE_FORMAT(EXTENDED_DATE,'%b-%d %Y')))) AS DATE_RANGE FROM TEMP_MAIN_REPORT_CHART_20150704102320_1 ORDER BY CLDID) AS B
ORDER BY CLDID,STARTDATE

