SELECT COUNT(TP_TYPE) INTO @COUNT_TICKLER_CONFIGURATION_SQL_FORMAT FROM SOURCE_RAJA.CONFIG_SQL_FORMAT WHERE TP_TYPE IS NOT NULL;

SELECT COUNT(*) INTO @COUNT_SPLITING_TICKLER_PROFILE FROM DEST_RAJA.TICKLER_PROFILE;

SET @INSERT = (SELECT CONCAT ('INSERT INTO ',SOURCESCHEMA,'.POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
VALUES (@POSTAPID,@COUNT_SPLITING_TICKLER_PROFILE,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID)'));
PREPARE INSERT_STMT FROM @INSERT;
EXECUTE INSERT_STMT;

DROP SCHEMA RAJA_DEST;
DROP SCHEMA RAJA_SOURCE;
CREATE SCHEMA RAJA_DEST;
CREATE SCHEMA RAJA_SOURCE;

INSERT INTO SOURCE_RAJA.POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID) VALUES (@POSTAPID,@COUNT_SPLITING_TICKLER_PROFILE,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);

SELECT CSQL.CGN_ID,CSQL.DATA,ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_RAJA.CONFIG_SQL_FORMAT CSQL, USER_LOGIN_DETAILS ULD WHERE CSQL.CGN_ID IN (1,2) AND CSQL.DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP;

CREATE TABLE temp_emp_user_rights_scdb_format (select * from ts_source.temp_emp_user_rights_scdb_format);

INSERT INTO CONFIG_SQL_FORMAT(SELECT *FROM DEST_RAJA.CONFIG_SQL_FORMAT);

SELECT CNP_DATA FROM CONFIG_SQL_FORMAT WHERE CNP_DATA IS NOT NULL AND CNP_ID IN (1,2,3,4) ORDER BY ID ASC;

INSERT INTO TICKLER_HISTORY VALUES (NULL,1,2,2,'RAJA',NULL,3,NULL);

INSERT INTO post_audit_profile(POSTAP_DATA)VALUES('POSTAP_DATA');
INSERT INTO pre_audit_main_profile (PREAMP_DATA) VALUES('POSTAP_DATA');
INSERT INTO pre_audit_sub_profile(PREAMP_ID, PREASP_DATA) VALUES(1,'POSTAP_DATA');
INSERT INTO RAJA.user_login_details(ULD_LOGINID, ULD_USERSTAMP) VALUES('DDSFS','FSD');

INSERT INTO DEST_RAJA.CONFIGURATION_PROFILE (CNP_DATA) (SELECT CNP_DATA FROM DEST_RAJA.TEMP_CONFIG_PROFILE20140819170833 WHERE CNP_DATA IS NOT NULL AND CNP_ID=4);

ALTER TABLE CONFIGURATION_PROFILE AUTO_INCREMENT = 5;
ALTER TABLE DEST_RAJA.CONFIGURATION_PROFILE AUTO_INCREMENT=4;

SET @ALTER_CONFIGURATION_PROFILE =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.CONFIGURATION_PROFILE AUTO_INCREMENT = 6'));
PREPARE ALTER_CONFIGURATION_PROFILE_STMT FROM @ALTER_CONFIGURATION_PROFILE;
EXECUTE ALTER_CONFIGURATION_PROFILE_STMT;

SELECT COUNT(EMC_ID)FROM error_message_configuration;

INSERT INTO configuration_profile( CNP_DATA) VALUES ('ADDRTIT');
INSERT INTO configuration( CNP_ID, CGN_TYPE) VALUES (3,'ADIDTRT');
INSERT INTO error_message_configuration ( CNP_ID, EMC_CODE, EMC_DATA, ULD_ID ) VALUES (3,1,'ATET',3);
INSERT INTO report_configuration ( CGN_ID, RC_DATA, ULD_ID ) VALUES (1,'A3TT',3);
INSERT INTO tickler_profile ( TP_TYPE ) VALUES ('III');
INSERT INTO tickler_tabid_profile ( TTIP_DATA) VALUES ('AITET');
INSERT INTO tickler_history ( TP_ID, TTIP_ID, TH_OLD_VALUE, TH_USERSTAMP_ID) VALUES (3,3,'ATET',3);
INSERT INTO user_rights_configuration ( CGN_ID, URC_DATA, URC_USERSTAMP ) VALUES (4,'AETT','dhandapani.sattanathan@ssomens.com');
INSERT INTO attendance_configuration ( CGN_ID, AC_DATA, ULD_ID ) VALUES (3,'AQTT',3);

SELECT MAX(CNP_ID) INTO @CONFIG_PROFILE_MAX_ID FROM DEST_RAJA.CONFIGURATION_PROFILE;
SELECT MAX(CGN_ID) INTO @CONFIG_MAX_ID FROM DEST_RAJA.CONFIGURATION;
ALTER TABLE DEST_RAJA.CONFIGURATION AUTO_INCREMENT=6;

-- USER_ADMIN_REPORT_DETAILS

CREATE TABLE REPORTS_SCDB_FORMAT LIKE TIMESHEET.REPORTS_SCDB_FORMAT;

CREATE TABLE TEMP_REPORTS_SCDB_FORMAT LIKE TS_PHP.TEMP_REPORTS_SCDB_FORMAT;

INSERT INTO REPORTS_SCDB_FORMAT(SELECT *FROM TIMESHEET.REPORTS_SCDB_FORMAT );

SELECT UNAME, UDATE, UREPORT, USERSTAMP, `TIMESTAMP` INTO @RUNAME, @RUDATE, @RUREPORT, @RUSERSTAMP, @RTIMESTAMP FROM REPORTS_SCDB_FORMAT WHERE UID=1;

SELECT MIN(Uid) INTO @MIN_UID FROM SOURCE_RAJA.REPORTS_SCDB_FORMAT;

CREATE TABLE `role_creation` (
  `RC_ID` int(2) NOT NULL AUTO_INCREMENT,
  `URC_ID` int(2) NOT NULL,
  `RC_NAME` varchar(15) NOT NULL,
  `RC_USERSTAMP` varchar(50) NOT NULL,
  `RC_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RC_ID`),
  UNIQUE KEY `RC_NAME` (`RC_NAME`),
  KEY `URC_ID` (`URC_ID`),
  CONSTRAINT `role_creation_ibfk_1` FOREIGN KEY (`URC_ID`) REFERENCES `user_rights_configuration` (`URC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
INSERT INTO role_creation SELECT* FROM bhavani_dest.role_creation;

INSERT INTO DEST_RAJA.user_admin_report_details(UARD_ID,UARD_REASON,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_USERSTAMP_ID, UARD_TIMESTAMP)VALUES
(3,(SELECT UREPORT FROM source_raja.REPORTS_SCDB_FORMAT WHERE UID=7793),
('EI'),
(SELECT UDATE FROM source_raja.REPORTS_SCDB_FORMAT WHERE UID=7793),
(SELECT AC_ID FROM ATTENDANCE_CONFIGURATION WHERE AC_DATA='ABSENT'),
(SELECT AC_DATA FROM ATTENDANCE_CONFIGURATION WHERE AC_DATA=2),
(SELECT AC_DATA FROM ATTENDANCE_CONFIGURATION WHERE AC_DATA=2),
(SELECT RC.URC_ID FROM USER_LOGIN_DETAILS ULD,ROLE_CREATION RC,USER_ACCESS UA,SOURCE_RAJA.REPORTS_SCDB_FORMAT RSF WHERE ULD.ULD_LOGINID= RSF.Uname AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.UID=7793),
(SELECT ULD_ID FROM user_login_details WHERE ULD_LOGINID=(SELECT UNAME FROM source_raja.REPORTS_SCDB_FORMAT WHERE UID=7793)),
(SELECT ULD_ID FROM user_login_details WHERE ULD_LOGINID=(SELECT USERSTAMP FROM source_raja.REPORTS_SCDB_FORMAT WHERE UID=7793)),
(SELECT TIMESTAMP FROM source_raja.REPORTS_SCDB_FORMAT WHERE UID=7793));

SELECT * FROM SOURCE_RAJA.REPORTS_SCDB_FORMAT RSF
inner join USER_LOGIN_DETAILS ULD on RSF.UNAME=ULD.ULD_LOGINID
inner join USER_ACCESS UA on ULD.ULD_ID = UA.ULD_ID
inner join ROLE_CREATION RC on UA.RC_ID = RC.RC_ID;

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE PROJECT_DETAILS;
DROP TABLE PROJECT_DETAILS;
DROP TABLE ADMIN_WEEKLY_REPORT_DETAILS;
DROP TABLE COMPANY_PROPERTIES_DETAILS;
DROP TABLE EMPLOYEE_DETAILS;
DROP TABLE ONDUTY_ENTRY_DETAILS;

DROP TABLE USER_LOGIN_DETAILS;
DROP TABLE USER_ADMIN_REPORT_DETAILS;
INSERT INTO DEST_RAJA.USER_LOGIN_DETAILS SELECT *FROM BHAVANI_DEST.USER_LOGIN_DETAILS;

CREATE TABLE PROJECT_DETAILS(
PD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
PD_PROJECT_NAME	VARCHAR(50)	NOT NULL,
PD_PROJECT_DESCRIPTION	VARCHAR(100)	NOT NULL,
ULD_ID INTEGER(2)	NOT NULL,
PD_TIMESTAMP TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (PD_ID),
UNIQUE (PD_PROJECT_NAME),
FOREIGN KEY(ULD_ID) REFERENCES USER_LOGIN_DETAILS (ULD_ID));

SET @SS = "ABSENT";
SELECT UID,UREPORT FROM SOURCE_RAJA.REPORTS_SCDB_FORMAT WHERE UREPORT LIKE @SS AND UID =7788;

SELECT RSF.UREPORT,AC.AC_ID,AC.AC_DATA,ULD.ULD_ID FROM SOURCE_RAJA.REPORTS_SCDB_FORMAT RSF,USER_LOGIN_DETAILS ULD,ATTENDANCE_CONFIGURATION AC
WHERE AC.AC_DATA=1 AND AC.AC_DATA='ABSENT' OR RSF.UNAME=ULD.ULD_LOGINID AND RSF.UID=7788;

SELECT * FROM SOURCE_RAJA.REPORTS_SCDB_FORMAT WHERE UID=905;

INSERT INTO TEMP_REPORTS_SCDB_FORMAT20140822152548( SILOID,TIMESTAMP,UNAME,UDATE,UREPORT,USERSTAMP) (SELECT SILOID , TIMESTAMP,    UNAME ,    UDATE,    UREPORT,    USERSTAMP FROM SOURCE_RAJA.REPORTS_SCDB_FORMAT);

SELECT *FROM REPORTS_SCDB_FORMAT WHERE UREPORT LIKE "%IN PERMISSION MIG%" AND UREPORT NOT LIKE "%OFFICE%";

SELECT MIN(UID) INTO @MIN_UID FROM DEST_RAJA.TEMP_REPORTS_SCDB_FORMAT;

-- 702
-- ABSENTIES-74
SELECT UID,UREPORT FROM REPORTS_SCDB_FORMAT  WHERE (UREPORT NOT LIKE "%Ha%day%Absent%" AND UREPORT NOT LIKE "%Absent not%"
AND UREPORT NOT LIKE "%ABSENT record del%" AND UREPORT NOT LIKE "%AFT%ABSENT%" AND UREPORT NOT LIKE "%present%absent%" AND UREPORT NOT LIKE "%absentee%" AND UREPORT NOT LIKE "%0.5%D%"  
AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%absent trigger%" AND UREPORT NOT LIKE "%Absent Radio%" AND UREPORT NOT LIKE "%Absent option%" AND UREPORT NOT LIKE "%Absent in%" 
AND UREPORT NOT LIKE "%Absent for%" AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%ABSENT(AFTERNOON)%" AND UREPORT NOT LIKE "%ABSENT record%" AND UREPORT NOT LIKE "%ABSENT%ON%DUTY%"
AND UREPORT NOT LIKE "%morning%Absent%" AND UREPORT NOT LIKE "%ABSENT: (half%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%" AND UREPORT NOT LIKE "%insert absent%" 
AND UREPORT NOT LIKE "%count all absent%" AND UREPORT NOT LIKE "%ADDED ABSENT FLAG%" AND UREPORT NOT LIKE "%ABSENT AND PRESENT%") AND (UREPORT LIKE "%went chennai%" OR UREPORT LIKE "off%"
OR UREPORT LIKE " off%" OR UREPORT LIKE "%took leave%" OR UREPORT LIKE "%ABSENT%" OR UREPORT LIKE "%today%leave%" OR UREPORT LIKE "leave%");
-- 620
SELECT UID,UREPORT FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT NOT LIKE "%Ha%day%Absent%" AND UREPORT NOT LIKE "%Absent not%"
AND UREPORT NOT LIKE "%ABSENT record del%" AND UREPORT NOT LIKE "%AFT%ABSENT%" AND UREPORT NOT LIKE "%present%absent%" AND UREPORT NOT LIKE "%absentee%" AND UREPORT NOT LIKE "%0.5%D%"  
AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%absent trigger%" AND UREPORT NOT LIKE "%Absent Radio%" AND UREPORT NOT LIKE "%Absent option%" AND UREPORT NOT LIKE "%Absent in%" 
AND UREPORT NOT LIKE "%Absent for%" AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%ABSENT(AFTERNOON)%" AND UREPORT NOT LIKE "%ABSENT record%" AND UREPORT NOT LIKE "%ABSENT%ON%DUTY%"
AND UREPORT NOT LIKE "%morning%Absent%" AND UREPORT NOT LIKE "%ABSENT: (half%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%") AND (UREPORT LIKE "%went chennai%" OR UREPORT LIKE "off%" 
OR UREPORT LIKE "%took leave%" OR UREPORT LIKE "%ABSENT%" OR UREPORT LIKE "%today%leave%" OR UREPORT LIKE "leave%");

-- 157
-- ONDUTY-26
SELECT UID,UREPORT FROM REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%on-duty%" OR UREPORT LIKE "%onduty%" OR UREPORT LIKE "%on duty%" OR UREPORT LIKE "%worked in new year%" OR UREPORT LIKE "holiday" OR UREPORT LIKE "BAKRID HOLIDAY"
OR UREPORT LIKE "%on_duty%" OR  UREPORT LIKE "OD" OR  UREPORT LIKE "%We went%" OR  UREPORT LIKE "Worked in Christmas%" OR UREPORT LIKE "on leave%") AND UREPORT NOT LIKE "%ONDUTY%SEARCH%UPDATE%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%"
AND UREPORT NOT LIKE "%ABSENT & ONDUTY%" AND UREPORT NOT LIKE "%absent and onduty%" AND UREPORT NOT LIKE "%calculate%present, onduty%" AND UREPORT NOT LIKE "%onduty entry%" AND UREPORT NOT LIKE "%onduty_levae_dtls%";
-- 122
SELECT UID,UREPORT FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "%on-duty%" OR UREPORT LIKE "%onduty%" OR UREPORT LIKE "%on duty%" OR UREPORT LIKE "%worked in new year%" 
OR UREPORT LIKE "%on_duty%" OR  UREPORT LIKE "OD" OR  UREPORT LIKE "%We went%" OR  UREPORT LIKE "Worked in Christmas%" OR UREPORT LIKE "on leave%") AND UREPORT NOT LIKE "%ONDUTY%SEARCH%UPDATE%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%";

-- HALF DAY LEAVE-89 + 11
insert into REPORTS_SCDB_FORMAT1 (UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP)
SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%half%day%absent%" OR UREPORT LIKE "%worked upto 2.20 pm%"
OR UREPORT LIKE "morning%absent%"  OR UREPORT LIKE "%half%leave%"  OR UREPORT LIKE "%morning%leave%" OR UREPORT LIKE "%AFTERNOON%LEAVE%" OR UREPORT LIKE "%Permission: 2.30pm%" OR UREPORT LIKE "Came at  8.30am%" 
OR UREPORT LIKE "%Permission 3 pm - 7 p%" OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Came to office at 11 and%" 
OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%" OR UREPORT LIKE "%AFT%ABSENT%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "1.came at 1.30%" 
OR UREPORT LIKE "1.Came at 11 am n%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%" OR UREPORT LIKE "1.Came office at 4.20%" OR UREPORT LIKE "come to office at 1%" 
OR UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%ABSENT%" OR UREPORT LIKE "%home 2 pm - to 4 pm%") AND UREPORT NOT LIKE "%after  half day%" AND UREPORT NOT LIKE "%half day but there%" 
AND UREPORT NOT LIKE "%half day%full day%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing onduty%absent%halfday%";

-- MORN
SELECT UID,UREPORT  FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" 
OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Come to office at 1.%" OR UREPORT LIKE "%(half a day - AM)%" OR UREPORT LIKE "come to office at 1%" OR UREPORT LIKE "%OFFICE AT 1.15%" 
OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "1.came at 1.30%" OR UREPORT LIKE "1.Came office at 4.20%")AND UREPORT NOT LIKE "%ernoon%" 
AND UREPORT NOT LIKE "1.CAME TO OFFICE FOR MORNING%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%";

SELECT UID,UREPORT,timestamp FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%" AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%" AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND TIME(TIMESTAMP)>"03:00:00";

SELECT UID,UREPORT,timestamp FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%" AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%" AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND TIMESTAMP IS NULL; 

-- AFTN
SELECT UID,UREPORT  FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "%AFTERN%" OR UREPORT LIKE "%leave%1%pm%" or UREPORT LIKE "Afternoon half day%" OR UREPORT LIKE "%AFTRN ABSENT%" 
OR UREPORT LIKE "%2 pm - to 4 pm%" OR UREPORT LIKE "%worked upto 2.20 pm%" OR UREPORT LIKE "Came at  8.30am%" OR UREPORT LIKE "%AN%session%" OR UREPORT LIKE "%After noon%" OR UREPORT LIKE "%Left at 1PM%" OR UREPORT LIKE "%LEFT%AT%1:30%"
OR UREPORT LIKE "%day Absent(AN)%" OR UREPORT LIKE "%Permission: 2.30pm%" OR UREPORT LIKE "%Came to office at 11 and%" OR UREPORT LIKE "%Permission 3 pm - 7 p%" OR UREPORT LIKE "1.Came at 11 am%" OR UREPORT LIKE "1.Came to office at 11 %" 
OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%" OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%") AND UREPORT NOT LIKE "%(Morning)%";

SELECT UID,UREPORT,timestamp FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "%HALF%day%"  OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%" AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%" AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND  TIME(TIMESTAMP)<"03:00:00";

-- 116
-- PERMISSION-15
insert into TEMP_REPORTS_SCDB_FORMAT (UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP)
SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%PERMISSION%" OR UREPORT LIKE "%PERSMISSION%" OR UREPORT LIKE "%HR PERMISSON%" 
OR UREPORT LIKE "%LEFT OFFICE AT 4.15 P.M%" OR UREPORT LIKE "Came at 12%" OR UREPORT LIKE "Came to office at 1%" OR UREPORT LIKE "come to office by 12%" OR UREPORT LIKE "went out at%" OR UREPORT LIKE "worked till 3.30 pm%" 
OR UREPORT LIKE "1.Came to office at 10.%" OR UREPORT LIKE "1.came at 12%o clock%" OR UREPORT LIKE "1.came at 11.%") AND UREPORT NOT LIKE "%Half day permission%" AND UREPORT NOT LIKE "%the permission%" 
AND UREPORT NOT LIKE "%provide permission%" AND UREPORT NOT LIKE "%Select permission%" AND UREPORT NOT LIKE "%GRANT%permission%" AND UREPORT NOT LIKE "%Revoke permissioin%" AND UREPORT NOT LIKE "%Access permission%" 
AND UREPORT NOT LIKE "%view permission%" AND UREPORT NOT LIKE "%need permission%" AND UREPORT NOT LIKE "%GIVE PERMISSION%" AND UREPORT NOT LIKE "%GIVEn PERMISSION%" AND UREPORT NOT LIKE "%employee permission%" 
AND UREPORT NOT LIKE "%CHECKING PERMISSION%" AND UREPORT NOT LIKE "%edit PERMISSION%" AND UREPORT NOT LIKE "%permission cant%" AND UREPORT NOT LIKE "%an permission%" AND UREPORT NOT LIKE "%& permission%" AND UREPORT NOT LIKE "%IN PERMISSION MIG%"
AND UREPORT NOT LIKE "%Permission: 2.30pm%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing permission%" AND UREPORT NOT LIKE "%table permission%" AND UREPORT NOT LIKE "%Left office at 2p%"
AND UREPORT NOT LIKE "%Permission 3 pm - 7 p%" AND UREPORT NOT LIKE "%PERMISSION FOR FLEX%" AND UREPORT NOT LIKE "%PERMISSION LIST%" AND UREPORT NOT LIKE "%onduty and permission%" AND UREPORT NOT LIKE "%NO PERMISSION%";
-- 98
insert into TEMP_REPORTS_SCDB_FORMAT (UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP)
SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM REPORTS_SCDB_FORMAT1 WHERE (UREPORT LIKE "%PERMISSION%" OR UREPORT LIKE "%PERSMISSION%" OR UREPORT LIKE "%HR PERMISSON%" 
OR UREPORT LIKE "%LEFT OFFICE AT 4.15 P.M%" OR UREPORT LIKE "Came at 12%" OR UREPORT LIKE "Came to office at 1%" OR UREPORT LIKE "come to office by 12%" OR UREPORT LIKE "went out at%" OR UREPORT LIKE "worked till 3.30 pm%" 
OR UREPORT LIKE "1.Came to office at 10.%" OR UREPORT LIKE "1.came at 12%o clock%" OR UREPORT LIKE "1.came at 11.%") AND UREPORT NOT LIKE "%Half day permission%" AND UREPORT NOT LIKE "%the permission%" 
AND UREPORT NOT LIKE "%provide permission%" AND UREPORT NOT LIKE "%Select permission%" AND UREPORT NOT LIKE "%GRANT%permission%" AND UREPORT NOT LIKE "%Revoke permissioin%" AND UREPORT NOT LIKE "%Access permission%" 
AND UREPORT NOT LIKE "%view permission%" AND UREPORT NOT LIKE "%need permission%" AND UREPORT NOT LIKE "%GIVE PERMISSION%" AND UREPORT NOT LIKE "%GIVEn PERMISSION%" AND UREPORT NOT LIKE "%employee permission%" 
AND UREPORT NOT LIKE "%CHECKING PERMISSION%" AND UREPORT NOT LIKE "%edit PERMISSION%" AND UREPORT NOT LIKE "%permission cant%" AND UREPORT NOT LIKE "%an permission%" AND UREPORT NOT LIKE "%& permission%" AND UREPORT NOT LIKE "%IN PERMISSION MIG%"
AND UREPORT NOT LIKE "%Permission: 2.30pm%" AND UREPORT NOT LIKE "%DAY LEAVE%PERMISSION%" AND UREPORT NOT LIKE "%testing permission%" AND UREPORT NOT LIKE "%table permission%" AND UREPORT NOT LIKE "%Left office at 2p%"
AND UREPORT NOT LIKE "%Permission 3 pm - 7 p%";

SELECT * FROM RAJA_DEST.temp_user_admin_report_details WHERE UARD_PERMISSION IS NOT NULL;

SELECT UID,UNAME,UDATE,UREPORT FROM temp_absent WHERE UREPORT LIKE "%afternoon absent%";
SELECT UID,UNAME,UDATE,UREPORT FROM source_raja.new_report WHERE UREPORT LIKE "%permission%hr%ABSENT%";

SELECT UARD_REPORT, UARD_REASON FROM TEMP_USER_ADMIN_REPORT_DETAILS LIMIT 111,15;

DELETE FROM new_report WHERE Uid= @U_ID;
SELECT TIME('2012-12-26 05:29:16')<'06:00:00';

SELECT SUBSTRING_INDEX('SFDSFDSFDSFABSENTFSDFSDFDSFDSFSF', 'Absent', 1);

SELECT DISTINCT A.UARD_REPORT,A.ULD_ID AS LOGINID,A.ULD_ID AS USERSTAMP,A.UARD_TIMESTAMP FROM USER_ADMIN_REPORT_DETAILS A
INNER JOIN USER_LOGIN_DETAILS B on A.ULD_ID=B.ULD_ID 
INNER JOIN USER_ACCESS C where B.ULD_ID=C.ULD_ID AND C.UA_TERMINATE=null;

SELECT * FROM DEST_RAJA.temp_REPORTS_SCDB_FORMAT20140822183141 WHERE UREPORT IN('ABSENT');

ALTER TABLE  DEST_RAJA.temp_REPORTS_SCDB_FORMAT20140822183141 ADD FULLTEXT(UREPORT);

SELECT uid, UREPORT FROM DEST_RAJA.temp_REPORTS_SCDB_FORMAT20140822183141 WHERE MATCH (UREPORT)  AGAINST ('absent') and uid=9;

SELECT LOCATE('ABSENT','1.Wrote name patch julien nd tested in uat, int in prod2.Tested card assign form nd opened defect.3.Half day Absent(AN)');

SELECT REPLACE(REPLACE(REPLACE('REASON-Due to-personal (reason)','(',''), '-', ' '),')', '');

INSERT INTO DEST_RAJA.TEMP_HALF_DAY_LEAVE(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
(SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM DEST_RAJA.TEMP_REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%half%day%absent%"
OR UREPORT LIKE "morning%absent%"  OR UREPORT LIKE "%half%leave%"  OR UREPORT LIKE "%morning%leave%" OR UREPORT LIKE "%AFTERNOON%LEAVE%"
OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "Came at  8.30am%" 
OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%" OR UREPORT LIKE "%AFT%ABSENT%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "Came office at 1%"
OR UREPORT LIKE "1.came at 1.30%" OR UREPORT LIKE "1.Came at 11 am n%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%"
OR UREPORT LIKE "1.Came office at 4.20%" OR UREPORT LIKE "come to office at 1%" OR UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%ABSENT%" OR UREPORT LIKE "%2 pm - to 4 pm%")
AND UREPORT NOT LIKE "%after  half day%" AND UREPORT NOT LIKE "%half day but there%" AND UREPORT NOT LIKE "%half day%full day%");

SELECT LOCATE(substr, (SELECT UREPORT FROM DEST_RAJA.temp_REPORTS_SCDB_FORMAT WHERE uID =6));
SELECT MID((SELECT UREPORT FROM UREPORT WHERE ID =1), pos, len);
SELECT SUBSTRING_INDEX(str, delim, count);
SELECT LOCATE('\n','Wrote name\npatch julien nd tested in uat');
SELECT SUBSTRING('Wrote name\n patch julien nd tested in uat',11+1);

-- spliting 
SELECT MID('1.Wrote name patch julien nd tested in uat, int in prod 2.Tested card assign form nd opened defect. 3.Half day Absent(AN)', 5, 87);

--
SELECT LENGTH ("HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections");
SELECT LOCATE('half day', 'HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections');
SELECT SUBSTRING('HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections',1);
SELECT LENGTH ("HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections")-1;
SELECT SUBSTRING('HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections',101);
SELECT SUBSTRING_INDEX('HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections','1',+1);

--
SELECT LOCATE('half ', 'HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections');
SELECT LOCATE('1', 'HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections');
SELECT SUBSTRING('HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections',26);
SELECT SUBSTRING_INDEX('HALF DAY ABSENT(MORNING) 1. come to office at 3.00 pm 2. check the ocbc for rejections','1',+1);

--
SELECT LOCATE('HALF ','1.Half day leave. 2.Worked in customer Search/update Form.');
SELECT LOCATE('2','1.Half day leave. 2.Worked in customer Search/update Form.');
SELECT SUBSTRING_INDEX('1.Half day leave. 2.Worked in customer Search/update Form.','2',+1);
SELECT SUBSTRING('1.Half day leave. 2.Worked in customer Search/update Form.',19);

--
SELECT LOCATE('HALF ','1.MORNING HALF DAY I GET AN LEAVE TODAY 2.MIGRATE THE REAL DATA  IN THE SHEET TODAY.');
SELECT LOCATE('2','1.MORNING HALF DAY I GET AN LEAVE TODAY 2.MIGRATE THE REAL DATA  IN THE SHEET TODAY.');
SELECT SUBSTRING_INDEX('1.MORNING HALF DAY I GET AN LEAVE TODAY 2.MIGRATE THE REAL DATA  IN THE SHEET TODAY.','2',+1);
SELECT SUBSTRING('1.MORNING HALF DAY I GET AN LEAVE TODAY 2.MIGRATE THE REAL DATA  IN THE SHEET TODAY.',41);

--
SELECT LOCATE('come ','COME TO OFFICE AT 1.15 1. delivered sp for unit_login_door update sp');
SELECT LOCATE('1','COME TO OFFICE AT 1.15 1. delivered sp for unit_login_door update sp')+5;
SELECT SUBSTRING_INDEX('COME TO OFFICE AT 1.15 1. delivered sp for unit_login_door update sp','1',+1);
SELECT SUBSTRING('COME TO OFFICE AT 1.15 1. delivered sp for unit_login_door update sp',24);

--
SELECT LOCATE('came ','1.Came office at 4.20 pm. 2.In home che');
SELECT LOCATE('2.','1.Came office at 4.20 pm. 2.In home che');
SELECT SUBSTRING_INDEX('1.Came office at 4.20 pm. 2.In home che','2.',+1);
SELECT SUBSTRING('1.Came office at 4.20 pm. 2.In home che',27);

--
SELECT LOCATE('came ','1.Came office at 4.20 pm. 2.In home che');
SELECT LOCATE('1.','1.Came office at 4.20 pm. 2.In home che');
SELECT SUBSTRING_INDEX('1.Came office at 4.20 pm. 2.In home che','1.',+1);
SELECT SUBSTRING('1.Came office at 4.20 pm. 2.In home che',27);

--
SELECT LOCATE('Reason ','half day leave reason: going for land registration');
SELECT MID('half day leave reason: going for land registration',16,6);
SELECT SUBSTRING_INDEX('half day leave reason: going for land registration','reason',+1);
SELECT SUBSTRING('half day leave reason: going for land registration',16);

SELECT LOCATE('Reason','half day leave reason: going for land registration');
SELECT MID('half day leave reason: going for land registration',16,6);
SELECT SUBSTRING_INDEX('half day leave Reason: going for land registration','Reason',+1);
SELECT SUBSTRING('half day leave reason: going for land registration',16);
--
SELECT LOCATE('(','AFTERNOON(ABSENT -PERSONAL WORK)1.discussed abt the css n informed the css format to all.');
SELECT SUBSTRING_INDEX('AFTERNOON(ABSENT -PERSONAL WORK)1.discussed abt the css n informed the css format to all.','(',+1);
SELECT SUBSTRING('AFTERNOON(ABSENT -PERSONAL WORK)1.discussed abt the css n informed the css format to all.',10);

SELECT LOCATE('-','1. Delivered with active and non active employees.2. Half day Leave-Going to Hospital');
SELECT SUBSTRING_INDEX('1. Delivered with active and non active employees.2. Half day Leave-Going to Hospital','-',+1);
SELECT SUBSTRING('1. Delivered with active and non active employees.2. Half day Leave-Going to Hospital',68);

INSERT INTO USER_ADMIN_REPORT_DETAILS (UARD_REPORT,UARD_REASON,UARD_DATE,URC_ID,ULD_ID,UARD_PERMISSION,UARD_ATTENDANCE,UARD_FULLDAY_PDID,UARD_AM_PDID,UARD_PM_PDID,UARD_AM_SESSION,UARD_PM_SESSION,UARD_BANDWIDTH,UARD_USERSTAMP_ID,UARD_TIMESTAMP)
SELECT UARD_REPORT,UARD_REASON,UARD_DATE,URC_ID,ULD_ID,UARD_PERMISSION,UARD_ATTENDANCE,UARD_FULLDAY_PDID,UARD_AM_PDID,UARD_PM_PDID,UARD_AM_SESSION,UARD_PM_SESSION,UARD_BANDWIDTH,UARD_USERSTAMP_ID,UARD_TIMESTAMP
FROM temp_user_admin_report_details20140826122656 ORDER BY UARD_DATE;

select Uid, UREPORT,
  replace(STRIP_NON_DIGIT(UREPORT),',','.')
  as final
from REPORTS_SCDB_FORMAT;

DROP FUNCTION IF EXISTS STRIP_NON_DIGIT;
CREATE FUNCTION STRIP_NON_DIGIT(input VARCHAR(255))
   RETURNS VARCHAR(255)
BEGIN
   DECLARE output VARCHAR(255) DEFAULT '';
   DECLARE iterator INT DEFAULT 1;
   WHILE iterator < (LENGTH(input) + 1) DO
      IF SUBSTRING(input, iterator, 1) IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ) THEN
         SET output = CONCAT(output, SUBSTRING(input, iterator, 1),',');
      END IF;
      SET iterator = iterator + 1;
   END WHILE;   
   RETURN output;
END;

select STRIP_NON_DIGIT("PERMISSION -5:30 TO 6:00 REASON:SEVERE HEADACHE");
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE (SELECT DATA FROM temp_key WHERE ID=1);

SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%2 ND%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%1 1/2 hour%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%1/2 hour%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%Permission% 1.30%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%1hr%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%1 hr%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%1 hour%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%1hour%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%2 hr%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%2hr%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%2 hour%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%3 hour%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%3 hr%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%ONE HOUR%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%ONE HR%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%2 HRS%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%2HRS%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%TWO%HOUR%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%THREE%HOUR%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%30 min%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%came at 12%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%came%11:30%";
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%came%11%";
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%2%30 hrs permission%";


DELETE FROM temp_permission WHERE UREPORT LIKE "%2 ND%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%1 1/2 hour%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%1/2 hour%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%Permission% 1.30%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%1hr%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%1 hr%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%1 hour%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%1hour%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%2 hr%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%2hr%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%2 hour%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%3 hour%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%3 hr%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%ONE HOUR%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%ONE HR%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%TWO%HOUR%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%THREE%HOUR%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%30 min%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%came at 12%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%came%11:30%";
DELETE FROM temp_permission WHERE UREPORT LIKE "%came%11%";
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%2%30 hrs permission%";

(1.5, "%1 1/2 h%"),
(1.5, "%Permission% 1.30%"),
(0.5, "%1/2 hour%"),
(2.5, "%2 ND%"),
(1, "%1hr%"),
(1, "%1 hr%"),
(1, "%1 hour%"),
(1, "%1hour%"),
(2, "%2 hr%"),
(2, "%2hr%"),
(2, "%2 hour%"),
(3, "%3 hour%"),
(3, "%3 hr%"),
(1, "%ONE HOUR%"),
(1, "%ONE HR%"),
(1, "%TWO%HOUR%"),
(3, "%THREE%HOUR%"),
(2.5, "%2.30 hrs%"),
(0.5, "%30 min%"),
(3, "%came at 12%"),
(2.5, "%came%11:30%"),
(2, "%came%11.15%"),
(2.5,"%2%30 hrs permission%"),
(0.5,"% -5:30 TO 6:00%"),(0.5,"%18:20(FELT %"),(0.5,"%45 min%"),
(1,"%at 4.30 to 5.30%"),(1,"%permission:5-6%"),(1,"% 6:15 pm to 7 p%"),
(1.5,"%10.30 came back at 12.10pm%"),(1.5,"%:2.00 to 3.30%"),(1.5,"%(17:00 - 18:20)%"),(1.5,"%office at 10.30%"),(1.5,"%5.3%-%7%"),
(2,"%5 pm - 7 pm%"),(2,"%from 5 clk.%"),(2,"%from 5.15 pm."),(2,"%4.45 pm to 7 pm%"),(2,"%from 5pm to 7pm%"),(2.5,"%LEFT OFFICE AT 4.15 P.M%"),
(2.5,"%3:10 PM TO 5:45%"),(2.5,"%cme at 11.30am%"),(2.5,"% at 3.30 till 6:00 pm%"),(2.5,"%( 3.30 to 6.00)%"),(2.5,"% - From  3.45P%"),(2.5,"%(9 to 11.45a.m)%"),(2.5,"%(9 to 11.45a.m)%"),(3,"%permission - 4 pm - 7 pm%"),
(3,"%(permission 4.15pm to 7pm)%"),(3,"%permission-3 to 6p.m.%"),(3,"%2.45 to 6.00pm%"),(3,"%Came to office at 12%"),(3,"%3.45 PM  TO 7 P%"),(3,"%3.00pm to 6.0%"),(3,"%4 o%clock on%"),(3,"%till 3.30 pm %"),(3,"%(16:00 - 19:00)%"),(3,"% timing 9.50 - 1.10 %")

"%came%11%30%"
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%came%11%"
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%5%-%7%"
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%permission 3%-%7%"
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%6%pm%7%"
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%4.4%pm%7%"
SELECT UREPORT FROM temp_permission WHERE UREPORT LIKE "%(17:00 - 18:20)%"

SELECT ureport FROM temp_permission ULD,ROLE_CREATION RC,USER_ACCESS UA,TEMP_DYNAMIC RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=13;

INSERT INTO TEMP_DYNAMIC SELECT*FROM DEST_RAJA.TEMP_PERMISSION WHERE UNAME='pradab.v@ssomens.com';

INSERT INTO user_access SELECT*FROM bhavani_dest.user_access;

INSERT INTO user_login_details SELECT*FROM bhavani_dest.user_login_details;

-- 2
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%5 pm - 7 pm%" OR UREPORT LIKE "%from 5 clk.%" OR UREPORT LIKE "%from 5.15 pm."
OR UREPORT LIKE "%4.45 pm to 7 pm%" OR UREPORT LIKE "%from 5pm to 7pm%";

-- 3
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%(permission 4.15pm to 7pm)%" OR UREPORT LIKE "%permission-3 to 6p.m.%" OR UREPORT LIKE "%2.45 to 6.00pm%"
OR UREPORT LIKE "%Came to office at 12%" OR UREPORT LIKE "%3.45 PM  TO 7 P%" OR UREPORT LIKE "%3.00pm to 6.0%" OR UREPORT LIKE "%4 o'clock on%" OR UREPORT LIKE "%till 3.30 pm %"
OR UREPORT LIKE "%(16:00 - 19:00)%" OR UREPORT LIKE "% timing 9.50 - 1.10 %";

-- 2.5
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%3:10 PM TO 5:45%" OR UREPORT LIKE "%cme at 11.30am%" OR UREPORT LIKE "% at 3.30 till 6:00 pm%"
OR UREPORT LIKE "%( 3.30 to 6.00)%" OR UREPORT LIKE "% - From  3.45P%" OR UREPORT LIKE "%(9 to 11.45a.m)%" OR UREPORT LIKE "%(9 to 11.45a.m)%";

-- 0.5
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "% -5:30 TO 6:00%" OR UREPORT LIKE "%18:20(FELT %" OR UREPORT LIKE "%45 min%";

-- 1.5
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE '%10.30 came back at 12.10pm%' OR UREPORT LIKE '%:2.00 to 3.30%' OR UREPORT LIKE '%(17:00 - 18:20)%'
OR UREPORT LIKE '%office at 10.30%' OR UREPORT LIKE '%5.3%-%7%';

-- 1
SELECT UID,UREPORT FROM temp_permission WHERE UREPORT LIKE "%at 4.30 to 5.30%" OR UREPORT LIKE "%permission:5-6%" OR UREPORT LIKE "% 6:15 pm to 7 p%";

-- 2
DELETE FROM temp_permission WHERE UREPORT LIKE "%5 pm - 7 pm%" OR UREPORT LIKE "%from 5 clk.%" OR UREPORT LIKE "%from 5.15 pm."
OR UREPORT LIKE "%4.45 pm to 7 pm%" OR UREPORT LIKE "%from 5pm to 7pm%";

-- 3
DELETE FROM temp_permission WHERE UREPORT LIKE "%(permission 4.15pm to 7pm)%" OR UREPORT LIKE "%permission-3 to 6p.m.%" OR UREPORT LIKE "%2.45 to 6.00pm%"
OR UREPORT LIKE "%Came to office at 12%" OR UREPORT LIKE "%3.45 PM  TO 7 P%" OR UREPORT LIKE "%3.00pm to 6.0%" OR UREPORT LIKE "%4 o'clock on%" OR UREPORT LIKE "%till 3.30 pm %"
OR UREPORT LIKE "%(16:00 - 19:00)%" OR UREPORT LIKE "% timing 9.50 - 1.10 %";

-- 2.5
DELETE FROM temp_permission WHERE UREPORT LIKE "%3:10 PM TO 5:45%" OR UREPORT LIKE "%cme at 11.30am%" OR UREPORT LIKE "% at 3.30 till 6:00 pm%"
OR UREPORT LIKE "%( 3.30 to 6.00)%" OR UREPORT LIKE "% - From  3.45P%" OR UREPORT LIKE "%(9 to 11.45a.m)%" OR UREPORT LIKE "%(9 to 11.45a.m)%";

-- 0.5
DELETE FROM temp_permission WHERE UREPORT LIKE "% -5:30 TO 6:00%" OR UREPORT LIKE "%18:20(FELT %" OR UREPORT LIKE "%45 min%";

-- 1.5
DELETE FROM temp_permission WHERE UREPORT LIKE '%10.30 came back at 12.10pm%' OR UREPORT LIKE '%:2.00 to 3.30%' OR UREPORT LIKE '%(17:00 - 18:20)%'
OR UREPORT LIKE '%office at 10.30%' OR UREPORT LIKE '%5.3%-%7%';

-- 1
DELETE FROM temp_permission WHERE UREPORT LIKE "%at 4.30 to 5.30%" OR UREPORT LIKE "%permission:5-6%" OR UREPORT LIKE "% 6:15 pm to 7 p%";

INSERT INTO USER_ADMIN_REPORT_DETAILS (UARD_REPORT,UARD_REASON,UARD_DATE,URC_ID,ULD_ID,UARD_PERMISSION,UARD_ATTENDANCE,UARD_PDID,UARD_AM_SESSION,UARD_PM_SESSION,UARD_BANDWIDTH,UARD_USERSTAMP_ID,UARD_TIMESTAMP)
SELECT UARD_REPORT,UARD_REASON,UARD_DATE,URC_ID,ULD_ID,UARD_PERMISSION,UARD_ATTENDANCE,UARD_PDID,UARD_AM_SESSION,UARD_PM_SESSION,UARD_BANDWIDTH,UARD_USERSTAMP_ID,UARD_TIMESTAMP
FROM TEMP_USER_ADMIN_REPORT_DETAILS ORDER BY UARD_DATE;

CALL SP_TS_MIG_REPORT_DETAILS_ABSENT_INSERT('ts_source_20140901','ts_sqlteam','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_ONDUTY_INSERT('ts_source_20140901','ts_sqlteam','dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_MRNG_ABSENT_INSERT('ts_sqlteam');
CALL SP_TS_MIG_REPORT_DETAILS_AFTN_ABSENT_INSERT('ts_sqlteam');
CALL SP_TS_MIG_REPORT_DETAILS_PERMISSION_INSERT('ts_sqlteam');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('ts_source_20140901','ts_sqlteam',1,1,1500,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('ts_source_20140901','ts_sqlteam',2,1501,3000,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('ts_source_20140901','ts_sqlteam',3,3001,4500,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('ts_source_20140901','ts_sqlteam',4,4501,6000,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('ts_source_20140901','ts_sqlteam',5,6001,7500,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('ts_source_20140901','ts_sqlteam',6,7501,NULL,'dhandapani.sattanathan@ssomens.com');
-- old
CALL SP_TS_MIG_REPORT_DETAILS_HALFDAY_LEAVE_INSERT('TS_PHP');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('TS_SOURCE','TS_PHP',1,1,1746,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('TS_SOURCE','TS_PHP',2,1747,3492,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('TS_SOURCE','TS_PHP',3,3493,5238,'dhandapani.sattanathan@ssomens.com');
CALL SP_TS_MIG_REPORT_DETAILS_REPORT_INSERT('TS_SOURCE','TS_PHP',4,5239,6984,'dhandapani.sattanathan@ssomens.com');

INSERT INTO DEST_RAJA.PROJECT_DETAILS(PD_PROJECT_NAME,PD_PROJECT_DESCRIPTION,ULD_ID,PD_TIMESTAMP)  
(SELECT UCASE(CSQL.PD_DATA),UCASE(CSQL.PD_DESCRIPTION),ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_RAJA.CONFIG_SQL_FORMAT CSQL,USER_LOGIN_DETAILS ULD WHERE CSQL.PD_DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP);

UPDATE CONFIG_SQL_FORMAT SET pd_data='ei',pd_description='expatsintegrated' WHERE ID=63;

UPDATE  PROJECT_DETAILS SET PD_PROJECT_NAME=UPPER(PD_PROJECT_NAME),PD_PROJECT_DESCRIPTION=UPPER(PD_PROJECT_DESCRIPTION);

SELECT COUNT(PD_DATA) INTO @COUNT_PROJECT_DETAILS_SQL_FORMAT FROM SOURCE_RAJA.CONFIG_SQL_FORMAT WHERE PD_DATA IS NOT NULL;

INSERT INTO DEST_RAJA.TEMP_DURATION(DURATION)VALUES('00:01:13');
SELECT DURATION FROM temp_duration;
SELECT SEC_TO_TIME(SUM(TIME_TO_SEC(duration))) FROM temp_duration;

CREATE TABLE `REPORTS_SCDB_FORMAT` (
  `siloId` varchar(50) DEFAULT NULL,
  `timeStamp` varchar(50) DEFAULT NULL,
  `Uname` varchar(70) DEFAULT NULL,
  `Udate` datetime DEFAULT NULL,
  `Ureport` text,
  `Uid` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `userStamp` varchar(65) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SELECT MAX(UID) INTO @MAXUID FROM REPORTS_SCDB_FORMAT1;

SELECT @MAXUID;
SELECT A.UREPORT, B.Ureport FROM REPORTS_SCDB_FORMAT A, REPORTS_SCDB_FORMAT1 B WHERE A.UREPORT!=B.Ureport GROUP BY A.UID;

UPDATE CONFIG_SQL_FORMAT SET CGN_ID=NULL WHERE CGN_ID='';
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE PROJECT_CONFIGURATION;
CALL SP_TS_MIG_CONFIGURATION_INSERT('TS_SOURCE','TS_DEST','dhandapani.sattanathan@ssomens.com');

RENAME TABLE TEMP_REPORTS_SCDB_FORMAT TO TEMP_EMP_REPORT_SCDB_FORMAT;

SELECT DISTINCT UNAME,'dhandapani.sattanathan@ssomens.com' FROM TEMP_EMP_REPORT_SCDB_FORMAT;

ALTER TABLE USER_LOGIN_DETAILS AUTO_INCREMENT=45;
SELECT * FROM USER_LOGIN_DETAILS;
SELECT * FROM POST_AUDIT_HISTORY;

SELECT SUM(PREASP_NO_OF_REC) FROM pre_audit_sub_profile WHERE PREAMP_ID=1;
SELECT SUM(PREASP_NO_OF_REC)-69 FROM pre_audit_sub_profile WHERE PREAMP_ID=2;

SELECT UARD_TIMESTAMP FROM raja_dest.user_admin_report_details;
SELECT *FROM reports_scdb_format WHERE UDATE='2014-10-25';

SELECT CONVERT_TZ('2014-10-25 9.26.06 AM',  "+05:30","+0:00");
SELECT CONVERT_TZ(UARD_TIMESTAMP, "+05:30","+0:00") FROM raja_dest.user_admin_report_details;

UPDATE TEMP_CUSTOMER_SCDB_FORMAT SET UARD_TIMESTAMP=(SELECT CONVERT_TZ(UARD_TIMESTAMP, "+08:00","+0:00"));

UPDATE TEMP_CUSTOMER_SCDB_FORMAT 
   SET UARD_PDID = IF(ULD_ID='jeevitha.thillaigovindan@ssomens.com',(SELECT PD_ID FROM project_details WHERE PD_PROJECT_NAME='MARKETING'),),
       UARD_PDID = IF(ULD_ID='viswanath.n@ssomens.com',,),
       UARD_PDID = IF(ULD_ID='santhi.palanisamy@ssomens.com',,),
       UARD_PDID = IF(ULD_ID='subashcbp8@gmail.com',,),
 WHERE ULD_ID = ;

UPDATE TEMP_USER_ADMIN_REPORT_DETAILS SET UARD_PDID=(SELECT PD_ID FROM PROJECT_DETAILS WHERE PD_PROJECT_NAME="OFFICE MAINTENANCE") WHERE ULD_ID IN (41,66);

SELECT *FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID IN (41,66,42,11);

SELECT *FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=44 LIMIT 147,170;















