-- VERSION 0.2 STARTDATE:15/09/2014 ENDDATE:16/09/2014 ISSUE NO:85 COMMENT NO:7 DESC:CREATED OUTPUT TABLE FOR ABSENT USERS. DONE BY :RAJA
-- VERSION 0.1 STARTDATE:12/09/2014 ENDDATE:13/09/2014 ISSUE NO:85 COMMENT NO:2 DESC:SP FOR INSERT ABSENT FOR USERS IF NOT INSERT REPORT. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TS_REPORT_AUTO_ABSENT_INSERT;
CREATE PROCEDURE SP_TS_REPORT_AUTO_ABSENT_INSERT(
IN USERSTAMP VARCHAR(50),
OUT TEMP_ABSENT_USER TEXT)
BEGIN
	DECLARE COUNT_REPORT INTEGER;
	DECLARE TAU_MIN_ID SMALLINT;
	DECLARE TAU_MAX_ID SMALLINT;
	DECLARE ULDID SMALLINT;
	DECLARE TEMP_ABSENTUSER TEXT;
	DECLARE UNAME VARCHAR(50);
	DECLARE CAPS_UNAME VARCHAR(50);
	DECLARE FULLDATE VARCHAR(50);
	DECLARE LOGINID VARCHAR(50);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
	CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID (USERSTAMP,@ULD_ID);
	SET ULDID=@ULD_ID;
	-- VIEW & TEMP TABLE FOR ACTIVE USERS
	CREATE OR REPLACE VIEW VW_USER_ACCESS_MAXRECVER AS SELECT ULD_ID,MAX(UA_REC_VER) AS RECVER FROM USER_ACCESS GROUP BY ULD_ID;
	DROP TABLE IF EXISTS TEMP_ACTIVE_USER;
	CREATE TABLE TEMP_ACTIVE_USER (ID INT AUTO_INCREMENT PRIMARY KEY,ULD_ID INTEGER,ULD_LOGINID VARCHAR(50),URC_ID INTEGER);
	INSERT INTO TEMP_ACTIVE_USER (ULD_ID,ULD_LOGINID,URC_ID) 
	(SELECT ULD.ULD_ID, ULD.ULD_LOGINID,URCN.URC_ID FROM USER_LOGIN_DETAILS ULD,USER_ACCESS UA, VW_USER_ACCESS_MAXRECVER V,USER_RIGHTS_CONFIGURATION URCN,ROLE_CREATION RC WHERE ULD.ULD_ID=UA.ULD_ID 
	AND UA.UA_REC_VER=V.RECVER AND V.ULD_ID=UA.ULD_ID AND V.ULD_ID=ULD.ULD_ID AND UA.RC_ID=RC.RC_ID AND RC.URC_ID=URCN.URC_ID AND UA.UA_TERMINATE IS NULL AND URCN.URC_DATA !="SUPER ADMIN" GROUP BY ULD.ULD_ID);

	-- FOR COUNTING ENTERED REPORTS
	SELECT COUNT(*) INTO COUNT_REPORT FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID IN(SELECT ULD_ID FROM TEMP_ACTIVE_USER) AND UARD_DATE=CURDATE();
	
	IF(COUNT_REPORT!=0)THEN
		-- TEMP TABLE FOR USER NOT ENTERED REPORT
		SET TEMP_ABSENTUSER=(SELECT CONCAT('TEMP_ABSENT_USER',SYSDATE()));
		SET TEMP_ABSENTUSER=(SELECT REPLACE(TEMP_ABSENTUSER,':',''));
		SET TEMP_ABSENTUSER=(SELECT REPLACE(TEMP_ABSENTUSER,'-',''));
		SET TEMP_ABSENTUSER=(SELECT REPLACE(TEMP_ABSENTUSER,' ',''));
		SET TEMP_ABSENT_USER=(SELECT CONCAT(TEMP_ABSENTUSER,'_',ULDID));
		SET @DROP_TEMP_ABSENT_USER=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_ABSENT_USER));
		PREPARE DROP_TEMP_ABSENT_USER_STMT FROM @DROP_TEMP_ABSENT_USER;
		EXECUTE DROP_TEMP_ABSENT_USER_STMT;
		SET @CREATE_TEMP_ABSENT_USER=(SELECT CONCAT('CREATE TABLE ',TEMP_ABSENT_USER,' (ID INT AUTO_INCREMENT PRIMARY KEY,ULD_ID INTEGER,EMPLOYEE_NAME VARCHAR(50),REPORT_DATE VARCHAR(50))'));
		PREPARE CREATE_TEMP_ABSENT_USER_STMT FROM @CREATE_TEMP_ABSENT_USER;
		EXECUTE CREATE_TEMP_ABSENT_USER_STMT;
		SET @INSERT_TEMP_ABSENT_USER=(SELECT CONCAT('INSERT INTO ',TEMP_ABSENT_USER,' (ULD_ID,EMPLOYEE_NAME) SELECT ULD_ID,ULD_LOGINID FROM TEMP_ACTIVE_USER WHERE ULD_ID NOT IN(SELECT ULD_ID FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_DATE=CURDATE())'));
		PREPARE INSERT_TEMP_ABSENT_USER_STMT FROM @INSERT_TEMP_ABSENT_USER;
		EXECUTE INSERT_TEMP_ABSENT_USER_STMT;

		-- FOR CHECK THE USER ENTER REPORT OR NOT
		SET @TAUMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @TAU_MIN_ID FROM ',TEMP_ABSENT_USER));
		PREPARE TAUMIN_ID_STMT FROM @TAUMINID;
		EXECUTE TAUMIN_ID_STMT;
		SET @TAUMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @TAU_MAX_ID FROM ',TEMP_ABSENT_USER));
		PREPARE TAUMAX_ID_STMT FROM @TAUMAXID;
		EXECUTE TAUMAX_ID_STMT;
		SET TAU_MIN_ID = @TAU_MIN_ID;
		SET TAU_MAX_ID = @TAU_MAX_ID;   

		WHILE(TAU_MIN_ID <= TAU_MAX_ID)DO  
			-- FOR INSERT ABSENT INTO REPORT TABLE
			SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO USER_ADMIN_REPORT_DETAILS(UARD_REASON,UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION,URC_ID,ULD_ID,UARD_BANDWIDTH,UARD_USERSTAMP_ID,ABSENT_FLAG) VALUES 
			(("ABSENT"),(CURDATE()),(SELECT DISTINCT AC_ID FROM ATTENDANCE_CONFIGURATION WHERE AC_DATA="0" AND CGN_ID=5),
			(SELECT DISTINCT AC_ID FROM ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),(SELECT DISTINCT AC_ID FROM ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
			(SELECT DISTINCT RC.URC_ID FROM USER_LOGIN_DETAILS ULD,ROLE_CREATION RC,USER_ACCESS UA WHERE ULD.ULD_ID=',ULDID,' AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID),
			(SELECT DISTINCT ULD_ID FROM ',TEMP_ABSENT_USER,' WHERE ID=',TAU_MIN_ID,'),(0),(',ULDID,'),("X"))'));      
			PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
			EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;

			-- FOR ABSENTEE USERNAME AND DATE
			SET @SELECT_LOGINID=(SELECT CONCAT('SELECT DISTINCT EMPLOYEE_NAME INTO @LOGIN_ID FROM ',TEMP_ABSENT_USER,' WHERE ID=',TAU_MIN_ID));
			PREPARE SELECT_LOGINID_STMT FROM @SELECT_LOGINID;
			EXECUTE SELECT_LOGINID_STMT;
			SET LOGINID=@LOGIN_ID;
			SET UNAME=(SELECT SUBSTRING_INDEX(LOGINID,'.',+1));
			SET CAPS_UNAME=(SELECT UCASE(UNAME));
			SET FULLDATE=(SELECT DATE_FORMAT(CURDATE(),'%W-%d-%M-%Y'));
			SET @UPDATE_TEMP_ABSENT_USER=(SELECT CONCAT('UPDATE ',TEMP_ABSENT_USER,' SET EMPLOYEE_NAME=','"',CAPS_UNAME,'"',',REPORT_DATE=','"',FULLDATE,'"','WHERE ID=',TAU_MIN_ID));
			PREPARE UPDATE_TEMP_ABSENT_USER_STMT FROM @UPDATE_TEMP_ABSENT_USER;
			EXECUTE UPDATE_TEMP_ABSENT_USER_STMT;
			SET TAU_MIN_ID=TAU_MIN_ID+1;
		END WHILE;
	END IF;
	DROP VIEW IF EXISTS VW_USER_ACCESS_MAXRECVER;
	DROP TABLE IF EXISTS TEMP_ACTIVE_USER;
	COMMIT;
END;
/*
CALL SP_TS_REPORT_AUTO_ABSENT_INSERT('safiyullah.mohideen@ssomens.com',@TEMP_ABSENT_USER);
*/