-- VERSION:0.1 --SDATE:05/09/2014 --EDATE:05/09/2014 --ISSUE:84 --COMMENTNO:1 --DESC:TRIGGERS TO UPDATE OLD & NEW VALUE IN TICKLER HISTORY TABLE DONE BY RL

DROP TRIGGER IF EXISTS TRG_TS_USER_ADMIN_REPORT_DETAILS;
CREATE TRIGGER TRG_TS_USER_ADMIN_REPORT_DETAILS  
AFTER UPDATE ON USER_ADMIN_REPORT_DETAILS
FOR EACH ROW
BEGIN 
	
	DECLARE OLD_VALUE TEXT DEFAULT '';
	DECLARE NEW_VALUE TEXT DEFAULT '';
	
	IF ((OLD.UARD_ID!= NEW.UARD_ID) OR (OLD.UARD_DATE!= NEW.UARD_DATE) OR (OLD.URC_ID!= NEW.URC_ID) OR (OLD.ULD_ID!= NEW.ULD_ID) OR 
		(OLD.UARD_ATTENDANCE!= NEW.UARD_ATTENDANCE) OR (OLD.UARD_AM_SESSION!= NEW.UARD_AM_SESSION) OR (OLD.UARD_PM_SESSION!= NEW.UARD_PM_SESSION) OR
		(OLD.UARD_BANDWIDTH!= NEW.UARD_BANDWIDTH) OR
		(OLD.UARD_REPORT IS NULL AND NEW.UARD_REPORT IS NOT NULL) OR (OLD.UARD_REPORT IS NOT NULL AND NEW.UARD_REPORT IS NULL) OR (OLD.UARD_REPORT!= NEW.UARD_REPORT) OR
		(OLD.UARD_REASON IS NULL AND NEW.UARD_REASON IS NOT NULL) OR (OLD.UARD_REASON IS NOT NULL AND NEW.UARD_REASON IS NULL) OR (OLD.UARD_REASON!= NEW.UARD_REASON) OR
		(OLD.UARD_PERMISSION IS NULL AND NEW.UARD_PERMISSION IS NOT NULL) OR (OLD.UARD_PERMISSION IS NOT NULL AND NEW.UARD_PERMISSION IS NULL) OR (OLD.UARD_PERMISSION!= NEW.UARD_PERMISSION) OR
		(OLD.UARD_PDID IS NULL AND NEW.UARD_PDID IS NOT NULL) OR (OLD.UARD_PDID IS NOT NULL AND NEW.UARD_PDID IS NULL) OR (OLD.UARD_PDID!= NEW.UARD_PDID))THEN
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_ID=', OLD.UARD_ID,','); 
	END IF;
	
	IF (OLD.UARD_ID!= NEW.UARD_ID) THEN SET 
		NEW_VALUE = CONCAT(NEW_VALUE,'UARD_ID=', NEW.UARD_ID,','); 
	END IF;
	
	IF (OLD.UARD_REPORT IS NULL AND NEW.UARD_REPORT IS NOT NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_REPORT=','<NULL>,');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_REPORT=',NEW.UARD_REPORT,',');
	ELSEIF(OLD.UARD_REPORT IS NOT NULL AND NEW.UARD_REPORT IS NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_REPORT=',OLD.UARD_REPORT,',');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_REPORT=','<NULL>,');
	ELSEIF (OLD.UARD_REPORT!= NEW.UARD_REPORT) THEN 
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_REPORT=', OLD.UARD_REPORT,','); 
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_REPORT=', NEW.UARD_REPORT,','); 
	END IF;
	
	IF (OLD.UARD_REASON IS NULL AND NEW.UARD_REASON IS NOT NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_REASON=','<NULL>,');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_REASON=',NEW.UARD_REASON,',');
	ELSEIF(OLD.UARD_REASON IS NOT NULL AND NEW.UARD_REASON IS NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_REASON=',OLD.UARD_REASON,',');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_REASON=','<NULL>,');
	ELSEIF (OLD.UARD_REASON!= NEW.UARD_REASON) THEN 
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_REASON=', OLD.UARD_REASON,','); 
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_REASON=', NEW.UARD_REASON,','); 
	END IF;
	
	IF (OLD.UARD_DATE!= NEW.UARD_DATE) THEN 
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_DATE=', OLD.UARD_DATE,','); 
	END IF;
	IF (OLD.UARD_DATE!= NEW.UARD_DATE) THEN   
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_DATE=', NEW.UARD_DATE,','); 
	END IF;
	
	IF (OLD.URC_ID!= NEW.URC_ID) THEN  
		SET OLD_VALUE = CONCAT(OLD_VALUE,'URC_ID=', OLD.URC_ID,','); 
	END IF;
	IF (OLD.URC_ID!= NEW.URC_ID) THEN  
		SET NEW_VALUE = CONCAT(NEW_VALUE,'URC_ID=', NEW.URC_ID,','); 
	END IF;
	
	IF (OLD.ULD_ID!= NEW.ULD_ID) THEN  
		SET OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
	END IF;
	IF (OLD.ULD_ID!= NEW.ULD_ID) THEN  
		SET NEW_VALUE = CONCAT(NEW_VALUE,'ULD_ID=', NEW.ULD_ID,','); 
	END IF;
	
	IF (OLD.UARD_PERMISSION IS NULL AND NEW.UARD_PERMISSION IS NOT NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_PERMISSION=','<NULL>,');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_PERMISSION=',NEW.UARD_PERMISSION,',');
	ELSEIF(OLD.UARD_PERMISSION IS NOT NULL AND NEW.UARD_PERMISSION IS NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_PERMISSION=',OLD.UARD_PERMISSION,',');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_PERMISSION=','<NULL>,');
	ELSEIF (OLD.UARD_PERMISSION!= NEW.UARD_PERMISSION) THEN 
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_PERMISSION=', OLD.UARD_PERMISSION,','); 
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_PERMISSION=', NEW.UARD_PERMISSION,','); 
	END IF;
	
	IF (OLD.UARD_ATTENDANCE!= NEW.UARD_ATTENDANCE) THEN  
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_ATTENDANCE=', OLD.UARD_ATTENDANCE,','); 
	END IF;
	IF (OLD.UARD_ATTENDANCE!= NEW.UARD_ATTENDANCE) THEN  
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_ATTENDANCE=', NEW.UARD_ATTENDANCE,','); 
	END IF;
	
	IF (OLD.UARD_PDID IS NULL AND NEW.UARD_PDID IS NOT NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_PDID=','<NULL>,');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_PDID=',NEW.UARD_PDID,',');
	ELSEIF(OLD.UARD_PDID IS NOT NULL AND NEW.UARD_PDID IS NULL) THEN
		SET OLD_VALUE=CONCAT(OLD_VALUE,'UARD_PDID=',OLD.UARD_PDID,',');
		SET NEW_VALUE=CONCAT(NEW_VALUE,'UARD_PDID=','<NULL>,');
	ELSEIF (OLD.UARD_PDID!= NEW.UARD_PDID) THEN 
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_PDID=', OLD.UARD_PDID,','); 
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_PDID=', NEW.UARD_PDID,','); 
	END IF;
	
	IF (OLD.UARD_AM_SESSION!= NEW.UARD_AM_SESSION) THEN  
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_AM_SESSION=', OLD.UARD_AM_SESSION,','); 
	END IF;
	IF (OLD.UARD_AM_SESSION!= NEW.UARD_AM_SESSION) THEN  
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_AM_SESSION=', NEW.UARD_AM_SESSION,','); 
	END IF;
	
	IF (OLD.UARD_PM_SESSION!= NEW.UARD_PM_SESSION) THEN  
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_PM_SESSION=', OLD.UARD_PM_SESSION,','); 
	END IF;
	IF (OLD.UARD_PM_SESSION!= NEW.UARD_PM_SESSION) THEN  
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_PM_SESSION=', NEW.UARD_PM_SESSION,','); 
	END IF;
	
	IF (OLD.UARD_BANDWIDTH!= NEW.UARD_BANDWIDTH) THEN  
		SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_BANDWIDTH=', OLD.UARD_BANDWIDTH,','); 
	END IF;
	IF (OLD.UARD_BANDWIDTH!= NEW.UARD_BANDWIDTH) THEN  
		SET NEW_VALUE = CONCAT(NEW_VALUE,'UARD_BANDWIDTH=', NEW.UARD_BANDWIDTH,','); 
	END IF;
	
	IF ((OLD.UARD_ID!= NEW.UARD_ID) OR (OLD.UARD_DATE!= NEW.UARD_DATE) OR (OLD.URC_ID!= NEW.URC_ID) OR (OLD.ULD_ID!= NEW.ULD_ID) OR 
		(OLD.UARD_ATTENDANCE!= NEW.UARD_ATTENDANCE) OR (OLD.UARD_AM_SESSION!= NEW.UARD_AM_SESSION) OR (OLD.UARD_PM_SESSION!= NEW.UARD_PM_SESSION) OR
		(OLD.UARD_BANDWIDTH!= NEW.UARD_BANDWIDTH) OR
		(OLD.UARD_REPORT IS NULL AND NEW.UARD_REPORT IS NOT NULL) OR (OLD.UARD_REPORT IS NOT NULL AND NEW.UARD_REPORT IS NULL) OR (OLD.UARD_REPORT!= NEW.UARD_REPORT) OR
		(OLD.UARD_REASON IS NULL AND NEW.UARD_REASON IS NOT NULL) OR (OLD.UARD_REASON IS NOT NULL AND NEW.UARD_REASON IS NULL) OR (OLD.UARD_REASON!= NEW.UARD_REASON) OR
		(OLD.UARD_PERMISSION IS NULL AND NEW.UARD_PERMISSION IS NOT NULL) OR (OLD.UARD_PERMISSION IS NOT NULL AND NEW.UARD_PERMISSION IS NULL) OR (OLD.UARD_PERMISSION!= NEW.UARD_PERMISSION) OR
		(OLD.UARD_PDID IS NULL AND NEW.UARD_PDID IS NOT NULL) OR (OLD.UARD_PDID IS NOT NULL AND NEW.UARD_PDID IS NULL) OR (OLD.UARD_PDID!= NEW.UARD_PDID))THEN
		IF (OLD.UARD_USERSTAMP_ID!= NEW.UARD_USERSTAMP_ID) THEN  
			SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_USERSTAMP_ID=', OLD.UARD_USERSTAMP_ID,','); 
		END IF;
		IF (OLD.UARD_TIMESTAMP!= NEW.UARD_TIMESTAMP) THEN  
			SET OLD_VALUE = CONCAT(OLD_VALUE,'UARD_TIMESTAMP=', OLD.UARD_TIMESTAMP,','); 
		END IF;
	END IF;
	
	IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
		IF(OLD_VALUE!=NEW_VALUE)THEN
			SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
			SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
			SET @A=(SELECT CONCAT('INSERT INTO TICKLER_HISTORY(TP_ID,ULD_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,TH_USERSTAMP_ID) VALUES
			((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE="UPDATION"),
			(SELECT ULD_ID FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=NEW.ULD_ID AND UARD_ID=NEW.UARD_ID),
			(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='USER_ADMIN_REPORT_DETAILS'),OLD_VALUE,NEW_VALUE,
			(SELECT UARD_USERSTAMP_ID FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_ID=NEW.UARD_ID))'));
		END IF;
	END IF;
END;