DROP TRIGGER IF EXISTS TS_TRG_PROJECT_DETAILS_UPDATE_VALIDATION;
CREATE TRIGGER TS_TRG_PROJECT_DETAILS_UPDATE_VALIDATION
BEFORE UPDATE ON PROJECT_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TS_TRG_PROJECT_DETAILS_VALIDATION (NEW.PD_PROJECT_NAME,NEW.PD_PROJECT_DESCRIPTION,'UPDATE');
END;