DROP PROCEDURE IF EXISTS SP_TS_LOGIN_TERMINATE_SAVE;
CREATE PROCEDURE SP_TS_LOGIN_TERMINATE_SAVE(
IN LOGINID VARCHAR(40),
IN ENDDATE DATE,
IN REASON TEXT,
IN USERSTAMP VARCHAR(50),
OUT SUCCESS_FLAG INTEGER)
BEGIN
	DECLARE RECVER INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
  	ROLLBACK;
  	SET SUCCESS_FLAG=0;    
	END;
	SET AUTOCOMMIT = 0;
	IF (LOGINID IS NOT NULL AND ENDDATE IS NOT NULL AND REASON IS NOT NULL AND USERSTAMP IS NOT NULL) THEN
		SET RECVER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID));
		UPDATE USER_ACCESS SET UA_JOIN=NULL,UA_TERMINATE='X',UA_REASON=REASON,UA_END_DATE=ENDDATE,UA_USERSTAMP=USERSTAMP WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID) AND UA_REC_VER=RECVER;
		SET SUCCESS_FLAG=1;		
	END IF;
	COMMIT;
END;
CALL SP_TS_LOGIN_TERMINATE_SAVE(LOGINID,ENDDATE,REASON,USERSTAMP,SUCCESS_FLAG);