-- VERSION 0.1 STARTDATE:25/10/2014 ENDDATE:25/10/2014 ISSUE NO:837 COMMENT NO:68 DESC:PATCH TO UPDATE ERROR_MSG_CONFIG DATA. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_ERROR_MESSAGE_CONFIGURATION_UPDATE_PATCH;
CREATE PROCEDURE SP_ERROR_MESSAGE_CONFIGURATION_UPDATE_PATCH(
IN FILENAME TEXT,
IN USERSTAMP VARCHAR(50),
OUT SUCCESS_MESSAGE TEXT)
BEGIN
	DECLARE SUCCESS_ECNDATA TEXT;
	DECLARE SUCCESSECNDATA TEXT;
	DECLARE FAILURE_ECNDATA TEXT;
	DECLARE FAILUREECNDATA TEXT;
	DECLARE FAILURE_ECN_DATA TEXT;
	DECLARE FAIL_ECNDATA TEXT;
	DECLARE PATCHFILENAME VARCHAR(100);
	DECLARE PHSTATUS TINYINT;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		INSERT INTO PATCH_HISTORY(PO_ID,PH_FILE_NAME,PH_STATUS,ULD_ID) VALUES (1,FILENAME,0,(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=USERSTAMP));
		SET SUCCESS_MESSAGE=FAIL_ECNDATA;
	END;
	SET AUTOCOMMIT=0;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;
	SET SUCCESS_ECNDATA=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=469);
	SET FAILURE_ECNDATA=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=470);
	SET FAILURE_ECN_DATA=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=473);
	SET SUCCESSECNDATA=(SELECT REPLACE(SUCCESS_ECNDATA,'[FILENAME]',FILENAME));
	SET FAILUREECNDATA=(SELECT REPLACE(FAILURE_ECNDATA,'[FILENAME]',FILENAME));
	SET FAIL_ECNDATA=(SELECT REPLACE(FAILURE_ECN_DATA,'[FILENAME]',FILENAME));
	IF EXISTS(SELECT PH_FILE_NAME FROM PATCH_HISTORY WHERE PH_FILE_NAME=FILENAME AND PH_STATUS=1)THEN
		SET SUCCESS_MESSAGE=FAILUREECNDATA;
	END IF;
	SET PATCHFILENAME=(SELECT PH_FILE_NAME FROM PATCH_HISTORY WHERE PH_FILE_NAME=FILENAME);
	SET PHSTATUS=(SELECT PH_STATUS FROM PATCH_HISTORY WHERE PH_FILE_NAME=FILENAME AND PH_STATUS=0);
	IF ((PATCHFILENAME IS NOT NULL) AND (PHSTATUS=0)) OR (PATCHFILENAME IS NULL)THEN
		UPDATE ERROR_MESSAGE_CONFIGURATION SET EMC_DATA='UNIT NO - [UNIT_NO] WITH DUPLICATE CARD [CARD_NO] FOR THE CUSTOMERS [ACTCUSTNAME]',EMC_TIMESTAMP='2014-04-01' WHERE EMC_ID=573;
		IF(PATCHFILENAME IS NULL)THEN
			INSERT INTO PATCH_HISTORY(PO_ID,PH_FILE_NAME,PH_STATUS,ULD_ID) VALUES (1,FILENAME,1,(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=USERSTAMP));
		ELSEIF((PATCHFILENAME IS NOT NULL) AND (PHSTATUS=0))THEN
			UPDATE PATCH_HISTORY SET PH_STATUS=1,ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=USERSTAMP) WHERE PH_FILE_NAME=FILENAME;
		END IF;
		SET SUCCESS_MESSAGE=SUCCESSECNDATA;
		SET FOREIGN_KEY_CHECKS=1;
	END IF;
	COMMIT;
END;
/*
CALL SP_ERROR_MESSAGE_CONFIGURATION_UPDATE_PATCH ('SP_ERROR_MESSAGE_CONFIGURATION_UPDATE_PATCH','expatsintegrated@gmail.com',@SUCCESS_MESSAGE);
SELECT @SUCCESS_MESSAGE;
*/