-- VERSION 0.8 STARTDATE:11/08/2014 ENDDATE:11/08/2014 ISSUE NO:835 COMMENTNO :66 DESC:IMPLEMENTED SET AUTOCOMMIT=0 BEFORE TRANSACTION. DONE BY :RAJA
-- version 0.7 startdate:28/02/2014 --enddate:28/02/2014--- issueno 754 commentno:36-->desc: APPLIED SUB_SP TO REPLACE USERSTAMP AS ID-SAFI
-- version 0.6 --sdate:27/02/2014 --edate:27/02/2014 --issue:754 --comment:22 --doneby:RL
-- VER 0.5 ISSUE NO:659 COMMENT # STARTDATE:03/02/2014 ENDDATE:04/02/2014 DESC: CALLING SUB SP FOR NEW USER CREATION AND GRANT PERMISSION FOR THAT USER. DONE BY: MANIKANDAN.S
-- VER 0.4 ISSUE NO:659 COMMENT #29 STARTDATE:17/12/2013 ENDDATE:17/12/2013 DESC:CHANGED USER_FILE_DETAILS TABLE HEADER NAME AS PER TABLE MODIFICATION DONE BY:DHIVYA.A
-- VER 0.3 ISSUE NO:659  STARTDATE:13/12/2013 ENDDATE:13/12/2013 DESC:CHANGED PASSING VARIABLES MENUNAME AS MENUID DONE BY:DHIVYA.A
-- VER 0.2 ISSUE NO:670  STARTDATE:11/12/2013 ENDDATE:11/12/2013 DESC:CHANGED PASSING VARIABLES AND INSERT QUERY FOR USER_MENU_DETAILS DONE BY:DHIVYA.A
-- VER 0.1 ISSUE NO:659 COMMENT #3 STARTDATE:07/12/2013 ENDDATE:09/12/2013 DESC:SP FOR ROLE CREATION INSERT DONE BY:DHIVYA.A
DROP PROCEDURE IF EXISTS SP_ROLE_CREATION_INSERT;
CREATE PROCEDURE SP_ROLE_CREATION_INSERT(
CUSTOM_ROLE VARCHAR(15),
BASIC_ROLE TEXT,
MENUID TEXT,
FILEID TEXT,
USERSTAMP VARCHAR(50),
DB_NAME VARCHAR(20),
OUT SUCCESS_FLAG INTEGER)
BEGIN
DECLARE MENU_LENGTH INTEGER;
DECLARE TEMP_MENU TEXT;
DECLARE MENU INTEGER;
DECLARE MENU_POSITION INTEGER;
DECLARE TEMP_FILE TEXT;
DECLARE FPID INTEGER;
DECLARE FILE_POSITION INTEGER;
DECLARE FILE_LENGTH INTEGER;
DECLARE GRANT_MP_ID TEXT DEFAULT "'";
DECLARE USER_NAME VARCHAR(50);
DECLARE V_USER_COUNT  SMALLINT(1);
DECLARE V_STRLEN    INT DEFAULT 0;
DECLARE V_SUBSTRLEN INT DEFAULT 0;
DECLARE V_MENU_ID   INT;
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
    SET SUCCESS_FLAG=0;
END;
SET AUTOCOMMIT = 0;
START TRANSACTION;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
	IF CUSTOM_ROLE IS NOT NULL AND BASIC_ROLE IS NOT NULL THEN
      IF NOT EXISTS (SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME = CUSTOM_ROLE) THEN
			  -- INSERT QUERY FOR ROLE_CREATION TABLE
        INSERT INTO ROLE_CREATION(URC_ID,RC_NAME,RC_USERSTAMP) VALUES ((SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA=BASIC_ROLE),CUSTOM_ROLE,USERSTAMP);
              SET SUCCESS_FLAG=1;
      END IF;
		END IF;
IF MENUID IS NOT NULL THEN
  SET TEMP_MENU = MENUID;
  SET MENU_LENGTH = 1;
 loop_label : LOOP
		SET MENU_POSITION=(SELECT LOCATE(',', TEMP_MENU,MENU_LENGTH));
		IF MENU_POSITION<=0 THEN
			SET MENU=TEMP_MENU;
		ELSE
			SELECT SUBSTRING(TEMP_MENU,MENU_LENGTH,MENU_POSITION-1) INTO MENU;
			SET TEMP_MENU=(SELECT SUBSTRING(TEMP_MENU,MENU_POSITION+1));
		END IF;
    -- INSERT QUERY FOR USER_MENU_DETAILS
		INSERT INTO USER_MENU_DETAILS(MP_ID,RC_ID,ULD_ID)VALUES(MENU,(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),USERSTAMP_ID);
        SET SUCCESS_FLAG=1;
		IF MENU_POSITION<=0 THEN
			LEAVE  loop_label;
		END IF;
	END LOOP;
END IF;
IF FILEID IS NOT NULL THEN
	SET TEMP_FILE = FILEID;
	SET FILE_LENGTH=1;
	loop_label:  LOOP
		SET FILE_POSITION=(SELECT LOCATE(',', TEMP_FILE,FILE_LENGTH));
		IF FILE_POSITION<=0 THEN
			SET FPID=TEMP_FILE;
		ELSE
			SELECT SUBSTRING(TEMP_FILE,FILE_LENGTH,FILE_POSITION-1) INTO FPID;
			SET TEMP_FILE=(SELECT SUBSTRING(TEMP_FILE,FILE_POSITION+1));
		END IF;
    -- INSERT QUERY FOR USER_FILE_DETAILS
		INSERT INTO USER_FILE_DETAILS(RC_ID,FP_ID,ULD_ID)VALUES((SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),FPID,USERSTAMP_ID);
        SET SUCCESS_FLAG=1;
		IF FILE_POSITION<=0 THEN
			LEAVE  loop_label;
		END IF;
	END LOOP;
END IF; 
COMMIT;
END;
/*
CALL SP_ROLE_CREATION_INSERT('MANI','ADMIN','1,2,3','1,7,4','EXPATSINTEGRATED@GMAIL.COM','SQL_TEAM',@SUCCESS_FLAG);
SELECT * FROM TEMP;
DELETE FROM TEMP;
*/