-- VERSION 0.1 STARTDATE:26/06/2014 ENDDATE:26/06/2014 ISSUE NO: 593 DESC:THROWING ERROR MSG FOR THE CHECK CONSTRAINS. DONE BY :RAJA
-- TRIGGER FOR BEFORE INSERT ON EXPENSE_FACILITY_USE
DROP TRIGGER IF EXISTS TRG_BIZDLY_FACILITY_USE_INSERT_VALIDATION;
CREATE TRIGGER TRG_BIZDLY_FACILITY_USE_INSERT_VALIDATION
BEFORE INSERT ON EXPENSE_FACILITY_USE
FOR EACH ROW
BEGIN
    CALL SP_TRG_BIZDLY_FACILITY_USE_VALIDATION(NEW.UNIT_ID,NEW.EFU_INVOICE_DATE,NEW.EFU_DEPOSIT,NEW.EFU_AMOUNT,'INSERT');
END;