DROP TRIGGER IF EXISTS TS_TRG_EMPLOYEE_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TS_TRG_EMPLOYEE_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON EMPLOYEE_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TS_TRG_EMPLOYEE_DETAILS_VALIDATION (NEW.EMP_DESIGNATION,NEW.EMP_DOB,NEW.EMP_MOBILE_NUMBER,NEW.EMP_ALT_MOBILE_NO,'INSERT');
END;