SELECT * FROM CUSTOMER_LP_DETAILS WHERE UASD_ID=513;
SELECT * FROM UNIT_ACCESS_STAMP_DETAILS;
SELECT * FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CUSTOMER_ID=156;
DROP TABLE CUSTOMER_ACCESS_CARD_DETAILS;
DROP SCHEMA TEST;
CREATE SCHEMA NEWPROD;

CREATE TABLE PATCH_HISTORY LIKE test_cards.PATCH_HISTORY;
CREATE TABLE PATCH_OBJECTS LIKE test_cards.PATCH_OBJECTS;
INSERT INTO PATCH_HISTORY (SELECT*FROM test_cards.PATCH_HISTORY);
INSERT INTO PATCH_OBJECTS (SELECT*FROM test_cards.PATCH_OBJECTS);
TRUNCATE ERROR_MESSAGE_CONFIGURATION;
INSERT INTO ERROR_MESSAGE_CONFIGURATION SELECT * FROM test_cards.ERROR_MESSAGE_CONFIGURATION;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE UNIT_ACCESS_STAMP_DETAILS;
INSERT INTO UNIT_ACCESS_STAMP_DETAILS SELECT * FROM test_cards.UNIT_ACCESS_STAMP_DETAILS;
TRUNCATE customer ;
INSERT INTO customer SELECT * FROM test_cards.customer;

INSERT INTO TEMP_DUPLICATE_CARDS_20140730221632
(SELECT * FROM TEMP_CARD_20140730221700_223 WHERE UASD_ID=296
AND ((STARTDATE BETWEEN DATE_SUB('2013-05-31', INTERVAL 1 DAY) AND DATE_SUB('2013-06-30', INTERVAL 1 DAY)) 
OR (ENDDATE BETWEEN DATE_SUB('2013-05-31', INTERVAL 1 DAY)
AND DATE_SUB('2013-06-30', INTERVAL 1 DAY))) AND ID > 5);

SELECT ADDDATE( LAST_DAY( SUBDATE('2011-07-07', INTERVAL 1 MONTH)), 1);

SELECT DISTINCT CLD.CLP_ID,CLD.CUSTOMER_ID,CLD.CED_REC_VER,CLD.UASD_ID,CLD.CLP_STARTDATE,CLD.CLP_ENDDATE,CLD.CLP_PRETERMINATE_DATE,CLD.CLP_TERMINATE,CLD.CLP_GUEST_CARD 
FROM CUSTOMER_LP_DETAILS CLD,TEMP_DUPLICATE_CARDS_20140731093155 TDI 
WHERE CLD.CLP_ID=TDI.CLP_ID AND CLD.CUSTOMER_ID=TDI.CUSTOMER_ID AND CLD.UASD_ID=TDI.UASD_ID;









