-- CHARTS
CALL SP_GET_UNIT_RENTAL_PERUNIT(422,'2011-01-01','2012-12-31','ADMIN@EXPATSINT.COM',@TEMP_UNIT_RENTAL_PERUNIT);
CALL SP_GET_UNIT_RENTAL_ALLUNIT('2013-12-01','2013-12-31','ADMIN@EXPATSINT.COM',@TEMPTBL_UNIT_RENTAL_ALLUNIT );
CALL SP_GET_UNIT_RENTAL('2012-08-01','2012-11-30','ADMIN@EXPATSINT.COM',@TEMP_UNIT_RENTAL);
CALL SP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE('APRIL-2013','JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_GROSS_REVENUE_AND_NET_REVENUE);
CALL SP_CHARTS_GROSS_REVENUE_ALLUNIT('NOVEMBER-2013','JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_GROSS_REVENUE_ALLUNIT);
CALL SP_CHARTS_GROSS_REVENUE_PERUNIT(422,'NOVEMBER-2013','JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMPTBL_CHARTS_GROSS_REVENUE_PERUNIT);
CALL SP_CHARTS_GROSS_REVENUE('NOVEMBER-2013' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@CHARTS_GROSS_REVENUE_TMPTBL );
CALL SP_CHARTS_SINGLE_EXPENSE_ALL_UNIT('JUNE-2013','SEPTEMBER-2014','EXPENSE_DETAIL_ELECTRICITY','EXPENSE_ELECTRICITY','EE.EE_AMOUNT','EE.EE_INVOICE_DATE','EDE_ID','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_SINGLE_EXPENSE_ALLUNIT);
CALL SP_CHARTS_SINGLE_EXPENSE_PERUNIT(422,'JANUARY-2012','JANUARY-2014','EXPENSE_DETAIL_ELECTRICITY','EXPENSE_ELECTRICITY','EE.EE_AMOUNT','EE.EE_INVOICE_DATE','EDE_ID','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_SINGLE_EXPENSE_PERUNIT);
CALL SP_CHARTS_SINGLE_PERSONAL_EXPENSE('JANUARY-2013','JANUARY-2014','EXPENSE_CAR','EC_AMOUNT','EC_INVOICE_DATE','EDE_ID','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_SINGLE_PERSONAL_EXPENSE);
CALL SP_CHARTS_SINGLE_PERSONAL_EXPENSE('JANUARY-2009','JANUARY-2014','EXPENSE_STAFF_SALARY','ESS_SALARY_AMOUNT','ESS_INVOICE_DATE','ESS_ID','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_SINGLE_PERSONAL_EXPENSE);
CALL SP_CHARTS_STAFF_EXPENSE('JANUARY-2007' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_STAFF_EXPENSE);
CALL SP_CHARTS_UNIT_GROSS_NET_REVENUE_ALLUNIT('JANUARY-2014','JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_ALLUNIT);
CALL SP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT(422,'JANUARY-2014','JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMP_CHARTS_UNIT_GROSS_AND_NET_REVENUE_PERUNIT);  
CALL SP_CHARTS_BIZ_EXPENSE_ALLUNIT('JANUARY-2014' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@CHARTS_BIZ_EXPENSE_ALLUNIT_TMPTBL);
CALL SP_CHARTS_BIZ_EXPENSE_PERUNIT(216, 'JANUARY-2014' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@MAIN_TEMPTBL_CHARTS_BIZ_EXPENSE_PERUNIT);
CALL SP_CHARTS_BIZ_EXPENSE('APRIL-2013' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@TEMP_MAIN_CHARTS_BIZ_EXPENSE);
CALL SP_CHARTS_BIZ_NET_REVENUE_ALLUNIT('DECEMBER-2013' , 'DECEMBER-2014','ADMIN@EXPATSINT.COM',@CHARTS_BIZ_NET_REVENUE_ALLUNIT_TEMPTBL);
CALL SP_CHARTS_BIZ_NET_REVENUE_PERUNIT(216, 'JANUARY-2014' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@CHARTS_BIZ_NET_REVENUE_PERUNIT_TMPTBL);
CALL SP_CHARTS_PERSONAL_EXPENSE( 'MAR-2013' , 'JAN-2014','ADMIN@EXPATSINT.COM',@CHARTS_PERSONAL_EXPENSE_TEMPTBL);
CALL SP_CHARTS_PERSONAL_NET_REVENUE('APRIL-2013' , 'JANUARY-2014','ADMIN@EXPATSINT.COM',@CHARTS_PERSONAL_NET_REVENUE_TMPTBL);
CALL SP_FORMAT_DATE('JANURARY-2013',NULL,@FD,@TD);

-- COMMEN SP
CALL SP_CHANGE_USERSTAMP_AS_ULDID('ADMIN@EXPATSINT.COM',@ULDID);
CALL SP_SINGLE_TABLE_ROW_DELETION(5,3,'ADMIN@EXPATSINT.COM',@DELETION_FLAG);
CALL SP_CHK_TRANSACTION(42,6,@OUTPUT_FLAG);
CALL SP_CHK_TRANSACTION_AND_DELETION(42,6,'EXPATSINTEGRATED@GMAIL.COM',@OUTPUT_FLAG );
CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES();
CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',','VASANTH,RAJA',@VALUE ,@REMAINING_STRING );

-- CUSTOMER 
CALL SP_CARD_ASSIGN_INVENTORY_CARD_CHECKING(4,422,0,16239,'EXPATSINTEGRATED@GMAIL.COM',@FLAG);
CALL SP_CUSTOMER_SEARCH_CALENDAR_CREATION_DELETION(4,'EXPATSINTEGRATED@GMAIL.COM',@TEMP_CALENDAR_LIST);
CALL SP_REPORT_CURRENT_ACTIVE_CUSTOMER('EXPATSINTEGRATED@GMAIL.COM',@REPORT_CURRENT_ACTIVE_CUSTOMER);

-- EXPENSE
CALL SP_BIZDLY_DIGITAL_VOICE_INSERT(0422,21,'2014-04-10','2011-01-10','2014-12-10',100.00,'OAD','EXPATSINTEGRATED@GMAIL.COM',@DIGITALVOICE_SUCCESSFLAG);
CALL SP_BIZDLY_HOUSEKEEPING_DURATION_AMOUNT_SRCH(1,'2013-03-12',120.00,'EXPATSINTEGRATED@GMAIL.COM',@HOUSEKEEPING_DURATION_AMOUNT);
CALL SP_BIZDLY_UNIT_DELETION(1,1,'EXPATSINTEGRATED@GMAIL.COM',@UPDATE_SUCCESSFLAG);

-- BANK TT
CALL SP_TEMP_TABLE_BANKTT('422','',1,'EXPATSINTEGRATED@GMAIL.COM',@BANKTT_SEARCH_TEMPTBLNAME,@BANKTT_TEMP_TABLE_NAME);
CALL SP_TEMP_TABLE_BANKTT('HAITHAM A H M ABDULKARIM','',4,'EXPATSINTEGRATED@GMAIL.COM',@BANKTT_SEARCH_TEMPTBLNAME,@BANKTT_TEMP_TABLE_NAME);
CALL SP_TEMP_TABLE_BANKTT('1000.00','2000.00',5,'EXPATSINTEGRATED@GMAIL.COM',@BANKTT_SEARCH_TEMPTBLNAME,@BANKTT_TEMP_TABLE_NAME);
CALL SP_TEMP_TABLE_BANKTT('2014-01-01','2014-06-30',3,'EXPATSINTEGRATED@GMAIL.COM',@BANKTT_SEARCH_TEMPTBLNAME,@BANKTT_TEMP_TABLE_NAME);
CALL SP_TEMP_TABLE_BANKTT('JAI ACCOUNTING','',6,'EXPATSINTEGRATED@GMAIL.COM',@BANKTT_SEARCH_TEMPTBLNAME,@BANKTT_TEMP_TABLE_NAME);
CALL SP_TEMP_TABLE_BANKTT('0422','KEN_ARIEFF BIN KAMAL WONG',2,'EXPATSINTEGRATED@GMAIL.COM',@BANKTT_SEARCH_TEMPTBLNAME,@BANKTT_TEMP_TABLE_NAME);

-- PAYMENT
CALL SP_OCBC_PAYMENT_DETAIL_INSERT(2918,1,1,'DEPOSIT',2000,NULL,'JULY-2011','EEEE','EXPATSINTEGRATED@GMAIL.COM',1,@FINAL_MESSAGE);
CALL SP_OUTSTANDING_PAYMENTLIST('JANUARY-2014','EXPATSINTEGRATED@GMAIL.COM',@TEMP_FINAL_NONPAIDCUSTOMER);
CALL SP_PAYMENT_ENTRY_TERMINATED_CUSTOMER('EXPATSINTEGRATED@GMAIL.COM',@PAYMENT_ENTRY_TERMINATED_CUSTOMER);
CALL SP_PAYMENT_SEARCH_TEMP_TABLE(2118,NULL, NULL,NULL,NULL,7,'EXPATSINTEGRATED@GMAIL.COM',@FINALTABLENAME);
SELECT *FROM TEMP_REPORT_CURRENT_ACTIVE_CUSTOMER_20140621171123_2;
-- MIG SP CALL QUERY
-- PAYMENT PART 1
CALL SP_TEMP_RENTAL_CUSTOMER_INSERT('SOURCE_07072014','DEST_07072014');
CALL SP_TEMP_RENTAL_SCDB_FORMAT_INSERT('SOURCE_07072014','DEST_07072014');
CALL SP_TEMP_PAYMENT_DETAILS_INSERT('SOURCE_07072014','DEST_07072014');
CALL SP_PAYMENT_UPDATE_REC_VERSION('DEST_07072014',1,1,75);
-- PAYMENT PART 2
CALL SP_PAYMENT_UPDATE_REC_VERSION('DEST_07072014',2,76,150);
-- PAYMENT PART 3
CALL SP_PAYMENT_UPDATE_REC_VERSION('DEST_07072014',3,151,225);
-- PAYMENT PART 4
CALL SP_PAYMENT_UPDATE_REC_VERSION('DEST_07072014',4,226,300);
-- PAYMENT PART 5
CALL SP_PAYMENT_UPDATE_REC_VERSION('DEST_07072014',5,301,375);
-- PAYMENT PART 6
CALL SP_PAYMENT_UPDATE_REC_VERSION('DEST_07072014',6,376,(SELECT MAX(CUSTOMER_ID) FROM TEMP_PAYMENT_ENTRY_DETAILS));
CALL SP_MIG_PAYMENT_INSERT('SOURCE_07072014','DEST_07072014','EXPATSINTEGRATED@GMAIL.COM');  
  
-- USER RIGHTS
CALL SP_LOGIN_CREATION_INSERT('DEEPANAIDU25@MAIL.COM','ADMIN','2014-09-07','EXPATSINTEGRATED@GMAIL.COM',@UR_FLAG);
CALL SP_LOGIN_TERMINATE_SAVE('DEEPANAIDU25@GMAIL.COM','2014-05-03','NEW USER','EXPATSINTEGRATED@GMAIL.COM',@SUCCESS_FLAG);
CALL SP_LOGIN_UPDATE('DEEPANAIDU25@GMAIL.COM','ADMIN','2014-09-07','EXPATSINTEGRATED@GMAIL.COM',@UR_FLAG);
CALL SP_ROLE_CREATION_INSERT('mani','ADMIN','1,2,3','1,3,4','EXPATSINTEGRATED@GMAIL.com','SQLTEAM');
CALL SP_ROLE_CREATION_UPDATE('user','user','2,48,49,51,50','8,7,6,3','admin@expatsint.com','SQLTEAM',@RC_FLAG);
CALL SP_USER_RIGHTS_BASIC_PROFILE_SAVE('EXPATSINTEGRATED@GMAIL.COM','USER','USER','1,2,3,4,7,8,5',@UR_FLAG);
CALL SP_USER_RIGHTS_BASIC_PROFILE_UPDATE('EXPATSINTEGRATED@GMAIL.COM','admin','admin','3,9,13,34,12',@UR_FLAG);
CALL SP_ACCESS_RIGHTS_SITE_MAINTANENCE('3,9,13,34,12');
CALL SP_PLATFORM_MGMT_DB_USER_RIGHTS_GRANT_REVOKE('DEVELOPMENT','MANI','''1'',''10''');
