-- TO SEE ALL DB SCHEMA'S.
SHOW DATABASES; 

-- TO SEE ALL USER'S
SELECT * FROM MYSQL.USER;

SELECT DISTINCT USER,HOST FROM MYSQL.USER;

REVOKE ALL PRIVILEGES ON *.* FROM 'mani'@'%';

-- GIVE GRANT PERMISSOIN TO USER.
GRANT GRANT OPTION ON *.* TO 'username'@'%';

GRANT SELECT ON *.* TO 'mani'@'%';

SHOW GRANTS; 

CREATE USER 'mani'@'%' IDENTIFIED BY ''; 

GRANT GRANT OPTION ON DEVELOPMENT.* TO 'mani'@'%';

GRANT SELECT ON TABLE DEVELOPMENT.UNIT TO 'mani'@'%';

GRANT INSERT ON TABLE TEST.* TO 'mani'@'%';

GRANT UPDATE ON TABLE TEST.* TO 'mani'@'%';

DROP USER 'MANI'@'%';

-- ALLOW USER TO EXECUTE ALL STORED PROCEDURE 
GRANT EXECUTE ON *.* TO 'user'@'localhost'; 

-- ALLOW USER TO EXECUTE ALL STORED PROCEDURE ATTACHED WITH A SINGLE DATABASE 
GRANT EXECUTE ON DB_NAME.* TO 'user'@'localhost'; 

-- ALLOW USER TO EXECUTE A SINGLE STORED PROCEDURE 
GRANT EXECUTE ON DB_NAME.SP TO 'user'@'localhost';

-- GIVING GRANT PERMISSION TO ROOT
GRANT GRANT OPTION ON *.* TO 'root'@'%';

-- REVOKE ALL THE PERMISSION FROM USER
REVOKE ALL PRIVILEGES,GRANT OPTION FROM 'mani'@'%'; 

-- MOVING TABLE STRUCTURE FROM ONE SCHEMA TO ANOTHER SCHEMA
CREATE TABLE DEVELOPMENT.PLATFORM_MANAGEMENT LIKE SQL_MIG.PLATFORM_MANAGEMENT;

-- MOVING TABLE DATA FROM ONE SCHEMA TABLE TO ANOTHER SCHEMA TABLE
INSERT INTO DEVELOPMENT.PLATFORM_MANAGEMENT (SELECT * FROM SQL_MIG.PLATFORM_MANAGEMENT);

-- REVOKE TABLE PERMISSIONS
REVOKE SELECT,INSERT,UPDATE ON DEVELOPMENT.TICKLER_HISTORY FROM 'mac'@'%';

-- REVOKE PROCEDURE EXECUTION PERMISSION
REVOKE EXECUTE ON PROCEDURE DEVELOPMENT.SP_CUSTOMER_CARDASSIGN_INSERT FROM 'mac'@'%';
