function delete_CAIRON_PATRICK_MCKINLEY_2735() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2735}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_CAIRON_PATRICK_MCKINLEY_2676()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2676});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '3460';
    item.RENTAL_COMMENTS = '130710003316-Ciaron 0618 GIRO-IBG-DBS INTERNET BAN,this customer paid RENT two times in same lp (july-2013). so removed one record and appended that two rent (3250+210),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:30/07/2013';
    db.save(item);
  }
}


function delete_ETSUKO_1654() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1654}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


//function UPDATE_ETSUKO_1655()
//{
//  var db=ScriptDb.getMyDb();
//  var result = db.query({RENTAL_ID:1655});
//  if(result.hasNext())
//  {
//    var item = result.next();
//    item.RENTAL_AMOUNT = '1900';
//    item.RENTAL_COMMENTS = 'customer lease period 08/08/2010 to 31/10/2011 but in payment entry sheet rent forperiod date 1/11/2011,So rent forperiod updated in between customer lease period,This customer paid RENT two times in same lp (OCT-2011). so removed one record and appended that two rent (1550+350),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/08/2013';
//    db.save(item);
//  }
//}


function delete_MIKE_DELA_CUESTA_1171() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1171}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}



function UPDATE_MIKE_DELA_CUESTA_1172()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1172});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '2750';
    item.RENTAL_COMMENTS = 'customer lease period 21/04/2011 to 31/05/2012 but in payment entry sheet rent forperiod date 1/6/2012,So rent forperiod updated in between customer lease period,This customer paid RENT two times in same lp (MAY-2012). so removed one record and appended that two rent (2500+250),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/05/2012';
    db.save(item);
  }
}


function delete_OLIVER_3063() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3063}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function delete_OLIVER_3047() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3047}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_OLIVER_2354()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2354});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '4151';
    item.RENTAL_COMMENTS = 'CASH DEPOSIT-NONREF - WARDROBE REPAIR WORKS,OLIVER JOHN PAUL OS-TT-SGD2750.00 MEPS RECEIPTS OLIVER JOHN PAUL OSBORNE-IM13101100469400,CASH DEPO - FR DEPO CALCULATIONS FROM 2718,This customer paid RENT 3 times in same lp (MAY-2013). so removed one record and appended that 3 rent (722+2750+679),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:22/10/2013,11/10/2013';
    db.save(item);
  }
}


function delete_sapient_consulting_gunjan_1920() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1920}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_sapient_consulting_gunjan_2732()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2732});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '4840';
    item.RENTAL_COMMENTS = 'boa 000185-CLRG CHEQUE DEP-gunjun 1603 to 3, so shortfall $160 which we can deduct frm deposit), Now due is June $4800 plus 3 days rent as he stayed till 3 July,This customer paid RENT 3 times in same lp (MARCH-2013). so removed one record and appended that two rent (2400+2440),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/03/2013';
    db.save(item);
  }
}


function delete_sapient_consulting_gunjan_1919() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1919}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_sapient_consulting_gunjan_2815()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2815});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '6085.71';
    item.RENTAL_COMMENTS = '6085.71 gunjun-CLRG CHEQUE DEP-NONREF,This customer paid RENT 2 times in same lp (FEB-2013). so removed one record and appended that two rent (4800+1285.71),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/02/2013';
    db.save(item);
  }
}



function delete_sapient_consulting_1890() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1890}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}



function UPDATE_sapient_consulting_1892()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1892});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '6723';
    item.RENTAL_COMMENTS = 'CUSTOMER LEASE PERIOD 01/08/2011 TO 30/04/2012 BUT IN PAYMENT ENTRY SHEET RENT FORPERIOD DATE 1/1/2013,SO RENT FORPERIOD UPDATED IN BETWEEN CUSTOMER LP,This customer paid RENT 2 times in same lp (JAN-2012). so removed one record and appended that two rent (1923+4800),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/04/2012';
    db.save(item);
  }
}


function delete_MT_MARINE_457() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:457}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_MT_MARINE_2388()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2388});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '7170.4';
    item.RENTAL_COMMENTS = '1915 car park DNB-CLRG CHEQUE DEP-dnb chq 525968,This customer paid RENT 2 times in same lp (MAY-2013). so removed one record and appended that two rent (770.4+6400),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/05/2013';
    db.save(item);
  }
}


function delete_MATTHEW_KERR_2824() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2824}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function delete_MIKE_5() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:5}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}



function delete_TOMOKO_NASUKO_3021() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3021}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_TOMOKO_NASUKO_3049()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3049});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '2800';
    item.RENTAL_COMMENTS = 'Tomoko door-140429660639 GIRO-IBG--ICH-IBK Funds T,tomoko 1218-070426950768 GIRO-IBG--ICH-IBK Funds T,This customer paid RENT 2 times in same lp (OCT-2013). so removed one record and appended that two rent (1000+1800),deleted record USERSTAMP:sarathbabou.somaya@ssomens.com,PAIDDATE:08/10/2013';
    db.save(item);
  }
}


function delete_RICHARRD_WU_752() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:752}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_RICHARRD_WU_738()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:738});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_PROCESSING_FEE = '1200';
    item.RENTAL_COMMENTS = 'this customer paid PF two times in same lp. so removed one record and appended that two pf (1000+200),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/10/2012';
    db.save(item);
  }
}


function delete_RAJNESSH_JHAWAR_2434() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:2434}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_RAJNESSH_JHAWAR_980()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:980});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_DEPOSIT = '3300';
    item.RENTAL_COMMENTS = 'this customer paid DEPOSIT two times in same lp. so removed one record and appended that two DEPOSIT (2300+1000),deleted record USERSTAMP:expatsintegrated@gmail.com,PAIDDATE:01/12/2012';
    db.save(item);
  }
}

function delete_RAJNEESH_JHAWAR_1879() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:1879}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function delete_NIRAJ_NAGPAL_3395() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3395}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


//function UPDATE_NIRAJ_NAGPAL_3423()
//{
//  var db=ScriptDb.getMyDb();
//  var result = db.query({RENTAL_ID:3423});
//  if(result.hasNext())
//  {
//    var item = result.next();
//    item.RENTAL_AMOUNT = '4297';
//    item.RENTAL_COMMENTS = '140203014361-Niraj 0518 GIRO-IBG-DBS INTERNET BANKIN,140205002728-Nikunj 0518 GIRO-IBG-DBS INTERNET BANKIN,This customer paid RENT 2 times in same lp (MARCH-2013). so removed one record and appended that two rent (1447+2850),deleted record USERSTAMP:sarathbabou.somaya@ssomens.com,PAIDDATE:05/02/2014';
//    db.save(item);
//  }
//}


function delete_ELEONORA_FALCONE_3241() {
    var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3241}); 
  if (result.hasNext()) 
  {
    db.remove(result.next());
  }
}


function UPDATE_ELEONORA_FALCONE_3254()
{
  var db=ScriptDb.getMyDb();
  var result = db.query({RENTAL_ID:3254});
  if(result.hasNext())
  {
    var item = result.next();
    item.RENTAL_AMOUNT = '4980';
    item.RENTAL_COMMENTS = 'Eleanor 5501 - 1/12 to 19/12 $2500 (actual prorata amt shd be just $1873 but it was agreed she will pay $2500) to deduct frm $3k deposit,FALCONE DOTT. FRANC-TT-SGD2480.00 MEPS RECEIPTS FALCONE DOTT. FRANCESCO ELEONORA 5501-IM13121600399100,This customer paid RENT 2 times in same lp (DEC-2013). so removed one record and appended that two rent (2500+2480),deleted record USERSTAMP:sarathbabou.somaya@ssomens.com,PAIDDATE:01/12/2013';
    db.save(item);
  }
}
