DROP PROCEDURE IF EXISTS SP_ACCESS_CARD_STATUS;
CREATE PROCEDURE SP_ACCESS_CARD_STATUS(IN CARD_NUMBER INTEGER(7),USERSTAMP VARCHAR(50),OUT TEMP_ACCESS_CARD_STATUS TEXT)
BEGIN
DECLARE ACCESS_CARD_TEMP_TABLE TEXT;
DECLARE USERSTAMP_ID INTEGER;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
END;
SET @CARDNO=CARD_NUMBER;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID=(SELECT @ULDID);
SET ACCESS_CARD_TEMP_TABLE=(SELECT CONCAT('TEMP_ACCESS_CARD_STATUS','_',SYSDATE()));
SET ACCESS_CARD_TEMP_TABLE=(SELECT REPLACE(ACCESS_CARD_TEMP_TABLE,' ',''));
SET ACCESS_CARD_TEMP_TABLE=(SELECT REPLACE(ACCESS_CARD_TEMP_TABLE,'-',''));
SET ACCESS_CARD_TEMP_TABLE=(SELECT REPLACE(ACCESS_CARD_TEMP_TABLE,':',''));
SET TEMP_ACCESS_CARD_STATUS=(SELECT CONCAT(ACCESS_CARD_TEMP_TABLE,'_',USERSTAMP_ID)); 
SET @CREATE_TEMP_ACCESS_CARD_STATUS=(SELECT CONCAT('CREATE TABLE ',TEMP_ACCESS_CARD_STATUS,'(ACTIVE_ACCESS_CARD TEXT,INVENTORY_ACCESS_CARD INTEGER(7),LOST_ACCESS_CARD TEXT,ACCESS_REASON TEXT,ACCESS_COMMENTS TEXT)'));
PREPARE CREATE_TEMP_ACCESS_CARD_STATUS_STMT FROM @CREATE_TEMP_ACCESS_CARD_STATUS;
EXECUTE CREATE_TEMP_ACCESS_CARD_STATUS_STMT;
IF EXISTS(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARD_NUMBER AND UASD_ACCESS_ACTIVE='X')THEN
	IF EXISTS(SELECT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARD_NUMBER) 
	AND  ACN_ID IS NULL AND CACD_VALID_TILL IS NULL AND CACD_GUEST_CARD IS NOT NULL)THEN
		SET @INSERT_ACTIVE_GUEST=(SELECT CONCAT('INSERT INTO ',TEMP_ACCESS_CARD_STATUS,'(ACTIVE_ACCESS_CARD, ACCESS_COMMENTS)VALUES
		((SELECT CONCAT((SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_ACTIVE="X" AND 
		UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')),"  ",
		(SELECT C.CUSTOMER_FIRST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND (CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL)  AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),"   ",
		(SELECT C.CUSTOMER_LAST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND (CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL)  AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),"  ","GUEST","(",
		(SELECT C.CUSTOMER_ID FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND (CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL)  AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),")")),
		(SELECT CPD.CPD_COMMENTS FROM CUSTOMER_PERSONAL_DETAILS CPD,CUSTOMER_ACCESS_CARD_DETAILS CACD
		WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,') AND CACD.CUSTOMER_ID=CPD.CUSTOMER_ID AND (CACD.ACN_ID!=4 OR CACD.CACD_VALID_TILL IS NULL)))'));
		PREPARE INSERT_ACTIVE_GUEST_STMT FROM @INSERT_ACTIVE_GUEST;
		EXECUTE INSERT_ACTIVE_GUEST_STMT;
	ELSE
		SET @INSERT_ACTIVE_ORGINAL_CUSTOMER=(SELECT CONCAT('INSERT INTO ',TEMP_ACCESS_CARD_STATUS,'(ACTIVE_ACCESS_CARD, ACCESS_COMMENTS)VALUES
		((SELECT CONCAT((SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_ACTIVE="X" AND 
		UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=@CARDNO)),"  ",
		(SELECT C.CUSTOMER_FIRST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=@CARDNO)
		AND (CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL)  AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),"   ",
		(SELECT C.CUSTOMER_LAST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=@CARDNO)
		AND (CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL)  AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),"  ","(",
		(SELECT C.CUSTOMER_ID FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=@CARDNO)
		AND (CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL)  AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),")")),
		(SELECT CPD.CPD_COMMENTS FROM CUSTOMER_PERSONAL_DETAILS CPD,CUSTOMER_ACCESS_CARD_DETAILS CACD
		WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=@CARDNO) AND CACD.CUSTOMER_ID=CPD.CUSTOMER_ID AND (CACD.ACN_ID!=4 OR CACD.CACD_VALID_TILL IS NULL)))'));
		PREPARE INSERT_ACTIVE_ORGINAL_CUSTOMER_STMT FROM @INSERT_ACTIVE_ORGINAL_CUSTOMER;
		EXECUTE INSERT_ACTIVE_ORGINAL_CUSTOMER_STMT;
	END IF;
END IF;
IF EXISTS(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARD_NUMBER AND UASD_ACCESS_INVENTORY='X')THEN
	SET @INSERT_INVENTORY=(SELECT CONCAT('INSERT INTO ',TEMP_ACCESS_CARD_STATUS,'(INVENTORY_ACCESS_CARD)VALUES
	((SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_INVENTORY="X" AND 
	UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')))'));
	PREPARE INSERT_INVENTORY_STMT FROM @INSERT_INVENTORY;
	EXECUTE INSERT_INVENTORY_STMT;
END IF;
IF EXISTS(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARD_NUMBER AND UASD_ACCESS_LOST='X')THEN
	IF NOT EXISTS(SELECT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION WHERE ACN_DATA!='TERMINATED') AND UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARD_NUMBER))THEN
        SET @INSERT_LOST_EMPLOYEE_CARD=(SELECT CONCAT('INSERT INTO ',TEMP_ACCESS_CARD_STATUS,'(LOST_ACCESS_CARD)VALUES
		((SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_LOST="X" AND 
		UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')))'));
		PREPARE INSERT_LOST_EMPLOYEE_CARD_STMT FROM  @INSERT_LOST_EMPLOYEE_CARD;
		EXECUTE INSERT_LOST_EMPLOYEE_CARD_STMT;
	ELSE
	IF EXISTS(SELECT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION WHERE ACN_DATA!='TERMINATED') AND UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARD_NUMBER) AND CACD_GUEST_CARD IS NOT NULL)THEN
		SET @INSERT_LOST_GUEST=(SELECT CONCAT('INSERT INTO ',TEMP_ACCESS_CARD_STATUS,'(LOST_ACCESS_CARD, ACCESS_REASON, ACCESS_COMMENTS)VALUES
		((SELECT CONCAT((SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_LOST="X" AND 
		UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')),"  ",
		(SELECT C.CUSTOMER_FIRST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND CACD.ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION 
		WHERE ACN_DATA!="TERMINATED") AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),"  ",
		(SELECT C.CUSTOMER_LAST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND CACD.ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION
		WHERE ACN_DATA!="TERMINATED") AND C.CUSTOMER_ID=CACD.CUSTOMER_ID)," ","GUEST","(",
		(SELECT C.CUSTOMER_ID FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND CACD.ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION
		WHERE ACN_DATA!="TERMINATED") AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),")")),
		(SELECT AC.ACN_DATA FROM ACCESS_CONFIGURATION AC,CUSTOMER_ACCESS_CARD_DETAILS CACD
		WHERE UASD_ID =(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,') AND CACD.ACN_ID!=4 AND AC.ACN_ID=CACD.ACN_ID ),
		(SELECT CPD.CPD_COMMENTS FROM CUSTOMER_PERSONAL_DETAILS CPD,CUSTOMER_ACCESS_CARD_DETAILS CACD
		WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,') AND CACD.CUSTOMER_ID=CPD.CUSTOMER_ID AND (CACD.ACN_ID!=4 OR CACD.CACD_VALID_TILL IS NULL)))'));
		PREPARE INSERT_LOST_GUEST_STMT FROM @INSERT_LOST_GUEST;
		EXECUTE INSERT_LOST_GUEST_STMT;
	ELSE
		SET @INSERT_LOST_ORIGINAL_CUSTOMER=(SELECT CONCAT('INSERT INTO ',TEMP_ACCESS_CARD_STATUS,'(LOST_ACCESS_CARD, ACCESS_REASON, ACCESS_COMMENTS)VALUES
		((SELECT CONCAT((SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_LOST="X" AND 
		UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')),"  ",
		(SELECT C.CUSTOMER_FIRST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND CACD.ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION 
		WHERE ACN_DATA!="TERMINATED") AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),"  ",
		(SELECT C.CUSTOMER_LAST_NAME FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND CACD.ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION
		WHERE ACN_DATA!="TERMINATED") AND C.CUSTOMER_ID=CACD.CUSTOMER_ID)," ","(",
		(SELECT C.CUSTOMER_ID FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,')
		AND CACD.ACN_ID IN (SELECT ACN_ID FROM ACCESS_CONFIGURATION
		WHERE ACN_DATA!="TERMINATED") AND C.CUSTOMER_ID=CACD.CUSTOMER_ID),")")),
		(SELECT AC.ACN_DATA FROM ACCESS_CONFIGURATION AC,CUSTOMER_ACCESS_CARD_DETAILS CACD
		WHERE UASD_ID =(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,') AND CACD.ACN_ID!=4 AND AC.ACN_ID=CACD.ACN_ID ),
		(SELECT CPD.CPD_COMMENTS FROM CUSTOMER_PERSONAL_DETAILS CPD,CUSTOMER_ACCESS_CARD_DETAILS CACD
		WHERE CACD.UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CARD_NUMBER,') AND CACD.CUSTOMER_ID=CPD.CUSTOMER_ID AND (CACD.ACN_ID!=4 OR CACD.CACD_VALID_TILL IS NULL)))'));
		PREPARE INSERT_LOST_ORIGINAL_CUSTOMER_STMT FROM  @INSERT_LOST_ORIGINAL_CUSTOMER;
		EXECUTE INSERT_LOST_ORIGINAL_CUSTOMER_STMT;
	END IF;
	END IF;
END IF;
COMMIT;
END;