DROP PROCEDURE IF EXISTS SP_TEMP_PERSONAL_SCDB_FORMAT;
CREATE PROCEDURE SP_TEMP_PERSONAL_SCDB_FORMAT()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
	DROP TABLE IF EXISTS TEMP_PERSONAL_SCDB_FORMAT;
	CREATE TABLE TEMP_PERSONAL_SCDB_FORMAT LIKE PERSONAL_SCDB_FORMAT;
	INSERT INTO TEMP_PERSONAL_SCDB_FORMAT SELECT * FROM PERSONAL_SCDB_FORMAT;
	UPDATE TEMP_PERSONAL_SCDB_FORMAT SET PE_CAR_EXP_TYPE = 'CASH CARD' WHERE PE_CAR_EXP_TYPE = 'Cash Card/Coupon';
	UPDATE TEMP_PERSONAL_SCDB_FORMAT SET PE_BABY_EXPENSE = 'HEALTH CARE/HOSPITAL EXPENSES' WHERE PE_BABY_EXPENSE = 'HEALTH CARE/HOSPITAL EXPENSE';
	DELETE FROM TEMP_PERSONAL_SCDB_FORMAT WHERE PE_ID IN(2225,3154);
	UPDATE TEMP_PERSONAL_SCDB_FORMAT SET TIMESTAMP=(SELECT CONVERT_TZ(TIMESTAMP, "+08:00","+0:00"));
COMMIT;
END;