DROP PROCEDURE IF EXISTS SP_MIG_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT;
CREATE PROCEDURE SP_MIG_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT()
BEGIN
	DECLARE DONE INT DEFAULT FALSE;
	DECLARE PEID INTEGER;
	DECLARE CARCOMMENTS TEXT;
	DECLARE ITEMLOCATION INTEGER;
	DECLARE FROMLOCATION INTEGER;
	DECLARE INVOICEITEM TEXT;
	DECLARE INVOICEFROM TEXT;
	DECLARE INVITEM TEXT;
	DECLARE INVFROM TEXT;
	DECLARE FILTER_CURSOR CURSOR FOR 
	SELECT PE_ID,PE_CAR_EXP_COMMENTS,PE_CAR_EXP_INVOICE_ITEMS,PE_CAR_EXP_INVOICE_FROM FROM VW_MIG_TEMP_EXP_CAR_REMAINING_COMMENTS ;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
	DROP TABLE IF EXISTS TEMP_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM;
	CREATE TABLE TEMP_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,PE_ID INT NOT NULL,PE_CAR_EXP_COMMENTS TEXT,PE_INVOICE_ITEM TEXT,PE_INVOICE_FROM TEXT);
	OPEN FILTER_CURSOR;
		read_loop: LOOP
			FETCH FILTER_CURSOR INTO PEID,CARCOMMENTS,INVOICEITEM,INVOICEFROM;
			IF DONE THEN
				LEAVE read_loop;
			END IF;
			SET ITEMLOCATION=(SELECT LOCATE('\n',CARCOMMENTS));
			SET FROMLOCATION=(SELECT LOCATE('\n\n',CARCOMMENTS,ITEMLOCATION+1));
			SET INVITEM=(SELECT SUBSTRING(CARCOMMENTS,ITEMLOCATION+2,FROMLOCATION-(ITEMLOCATION+2)));
			SET INVFROM=(SELECT SUBSTRING(CARCOMMENTS,FROMLOCATION+2));
			IF (ITEMLOCATION!=0) AND (FROMLOCATION!=0)THEN
				INSERT INTO TEMP_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM(PE_ID,PE_CAR_EXP_COMMENTS,PE_INVOICE_ITEM,PE_INVOICE_FROM)VALUES(PEID,CARCOMMENTS,INVITEM,INVFROM);
			END IF;
		END LOOP;
	CLOSE FILTER_CURSOR;
COMMIT;
END;