DROP PROCEDURE IF EXISTS SP_EXPENSE_CAR_BABY_INSERT;
CREATE PROCEDURE SP_EXPENSE_CAR_BABY_INSERT(IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;
	CALL SP_TEMP_PERSONAL_SCDB_FORMAT();
	SET START_TIME=(SELECT CURTIME());
	CALL SP_MIG_EXP_BABY_DOUBLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_BABY_ALL_COMMENTS AS SELECT PE_ID,PE_BABY_COMMENTS,PE_BABY_INVOICE_ITEMS,PE_BABY_INVOICE_FROM 
	FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='BABY';
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_BABY_REMAINING_COMMENTS AS SELECT RC.PE_ID,RC.PE_BABY_COMMENTS,RC.PE_BABY_INVOICE_ITEMS,RC.PE_BABY_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_BABY_ALL_COMMENTS RC LEFT JOIN TEMP_EXP_BABY_DOUBLE_SLASHN_INVOICE_FROM_ITEM BDSIFI 
	ON BDSIFI.PE_ID = RC.PE_ID WHERE BDSIFI.PE_ID IS NULL;
	CALL SP_MIG_EXP_BABY_SINGLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_BABY_SINGLE_SLASHN_REMAINING_COMMENTS AS SELECT RC.PE_ID,RC.PE_BABY_COMMENTS,RC.PE_BABY_INVOICE_ITEMS,RC.PE_BABY_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_BABY_REMAINING_COMMENTS RC LEFT JOIN TEMP_EXP_BABY_SINGLE_SLASHN_INVOICE_FROM_ITEM BIFI ON BIFI.PE_ID = RC.PE_ID
	WHERE BIFI.PE_ID IS NULL;
	CALL SP_MIG_EXP_BABY_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
	CALL SP_BABY_INVOICE_ITEM_FROM_SPLIT(DESTINATIONSCHEMA);
	CALL SP_EXPENSE_BABY_INSERT(DESTINATIONSCHEMA);
	SET END_TIME=(SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @COUNT_SCDB_BABY=(SELECT COUNT(*) FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='BABY');
	SET @COUNT_SPLITTED_BABY=(SELECT CONCAT('SELECT COUNT(*) INTO @SPLITEDBABYCOUNT FROM ',DESTINATIONSCHEMA,'.EXPENSE_BABY'));
	PREPARE COUNT_SPLITTED_BABYSTMT FROM @COUNT_SPLITTED_BABY;
	EXECUTE COUNT_SPLITTED_BABYSTMT;
	SET @REJECTION_COUNT=(@COUNT_SCDB_BABY-@SPLITEDBABYCOUNT);
	SET FOREIGN_KEY_CHECKS = 0;
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_BABY WHERE PREASP_DATA='EXPENSE_BABY';
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
	VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_BABY'),@SPLITEDBABYCOUNT,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_BABY'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='PERSONAL'),DURATION,@REJECTION_COUNT,@ULDID);
	DROP TABLE IF EXISTS TEMP_BABY_INVOICE_ITEM_FROM_SPLITTED_TABLE;
	SET FOREIGN_KEY_CHECKS = 1;
	SET START_TIME=(SELECT CURTIME());
	CALL SP_EXP_MIG_CAR_DOUBLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_CAR_ALL_COMMENTS AS SELECT PE_ID,PE_CAR_EXP_COMMENTS,PE_CAR_EXP_INVOICE_ITEMS,PE_CAR_EXP_INVOICE_FROM FROM PERSONAL_SCDB_FORMAT 
	WHERE PE_TYPE_OF_EXPENSE='CAR EXPENSE';
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_CAR_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_CAR_EXP_COMMENTS,PE_CAR_EXP_INVOICE_ITEMS,PE_CAR_EXP_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_CAR_ALL_COMMENTS t1 LEFT JOIN TEMP_EXP_CAR_DOUBLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
	WHERE t2.PE_ID IS NULL;
	CALL SP_MIG_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
	CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_CAR_SLASHN_REMAINING_COMMENTS  AS SELECT RC.PE_ID,RC.PE_CAR_EXP_COMMENTS,PE_CAR_EXP_INVOICE_ITEMS,PE_CAR_EXP_INVOICE_FROM
	FROM VW_MIG_TEMP_EXP_CAR_REMAINING_COMMENTS RC LEFT JOIN TEMP_EXP_CAR_SINGLE_SLASHN_INVOICE_FROM_ITEM SSIFI ON SSIFI.PE_ID = RC.PE_ID
	WHERE SSIFI.PE_ID IS NULL;
	CALL SP_MIG_EXP_CAR_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
	CALL SP_CAR_INVOICE_ITEM_FROM_SPLITTING(DESTINATIONSCHEMA);
	CALL SP_EXPENSE_CAR_INSERT(DESTINATIONSCHEMA);
	SET END_TIME=(SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @COUNT_SCDB_CAR=(SELECT COUNT(*) FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='CAR EXPENSE');
	SET @COUNT_SPLITTED_CAR=(SELECT CONCAT('SELECT COUNT(*) INTO @SPLITEDCAR FROM ',DESTINATIONSCHEMA,'.EXPENSE_CAR'));
	PREPARE COUNT_SPLITTED_CARSTMT FROM @COUNT_SPLITTED_CAR;
	EXECUTE COUNT_SPLITTED_CARSTMT;
	SET @REJECTION_COUNT=(@COUNT_SCDB_CAR-@SPLITEDCAR);
	SET FOREIGN_KEY_CHECKS = 0;
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_CAR WHERE PREASP_DATA='EXPENSE_CAR';
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
	VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_CAR'),@SPLITEDCAR,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_CAR'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='PERSONAL'),DURATION,@REJECTION_COUNT,@ULDID);
	SET FOREIGN_KEY_CHECKS = 1;
	DROP TABLE IF EXISTS TEMP_CAR_INVOICE_ITEM_FROM_SPLITTED_TABLE;
	SET FOREIGN_KEY_CHECKS = 1;
	SET START_TIME=(SELECT CURTIME());
	CALL SP_CREATE_EXPENSE_CARLOAN_TABLE(DESTINATIONSCHEMA);
	CALL SP_EXPENSE_CARLOAN_INSERT(DESTINATIONSCHEMA);
	SET END_TIME=(SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @COUNT_SCDB_CARLOAN=(SELECT COUNT(*) FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='CAR LOAN');
	SET @COUNT_SPLITTED_CARLOAN=(SELECT CONCAT('SELECT COUNT(*) INTO @SPLITEDCARLOAN FROM ',DESTINATIONSCHEMA,'.EXPENSE_CAR_LOAN'));
	PREPARE COUNT_SPLITTED_CARLOANSTMT FROM @COUNT_SPLITTED_CARLOAN;
	EXECUTE COUNT_SPLITTED_CARLOANSTMT;
	SET @REJECTION_COUNT=(@COUNT_SCDB_CARLOAN-@SPLITEDCARLOAN);
	SET FOREIGN_KEY_CHECKS = 0;
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_CARLOAN WHERE PREASP_DATA='EXPENSE_CAR_LOAN';
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
	VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_CAR_LOAN'),@SPLITEDCARLOAN,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_CAR_LOAN'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='PERSONAL'),DURATION,@REJECTION_COUNT,@ULDID);
	SET FOREIGN_KEY_CHECKS = 1;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_BABY_ALL_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_BABY_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_BABY_SINGLE_SLASHN_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_CAR_ALL_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_CAR_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_CAR_SLASHN_REMAINING_COMMENTS;
	DROP VIEW IF EXISTS VW_BABY_REMAINING_COMMENTS;
COMMIT;
END;	
CALL SP_EXPENSE_CAR_BABY_INSERT(DESTINATIONSCHEMA,MIGUSERSTAMP);