DROP PROCEDURE IF EXISTS SP_EXPENSE_PERSONAL_SPLIITING_INVOICE_ITEM_FROM;
CREATE PROCEDURE SP_EXPENSE_PERSONAL_SPLIITING_INVOICE_ITEM_FROM(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
DECLARE START_TIME TIME;
DECLARE END_TIME TIME;
DECLARE DURATION TIME;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
CALL SP_TEMP_PERSONAL_SCDB_FORMAT();
SET START_TIME=(SELECT CURTIME());
CALL SP_MIG_EXP_PERSONAL_TRIBLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_ALL_COMMENTS AS SELECT PE_ID,PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM FROM PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='PERSONAL' AND PE_PERSONAL_COMMENTS IS NOT NULL AND (PE_PERSONAL_INVOICE_ITEMS IS NULL OR PE_PERSONAL_INVOICE_FROM IS NULL);
CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
FROM VW_MIG_TEMP_EXP_PERSONAL_ALL_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_TRIBLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
WHERE t2.PE_ID IS NULL;
CALL SP_MIG_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
FROM VW_MIG_TEMP_EXP_PERSONAL_REMAINING_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
WHERE t2.PE_ID IS NULL;
CALL SP_MIG_EXP_PERSONAL_SINGLE_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_SINGLE_SLASHN_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
FROM VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_REMAINING_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_SINGLE_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
WHERE t2.PE_ID IS NULL;
CALL SP_MIG_EXP_PERSONAL_SLASHN_INVOICE_FROM_ITEM_SPLIT_INSERT();
CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_SLASHN_REMAINING_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
FROM VW_MIG_TEMP_EXP_PERSONAL_SINGLE_SLASHN_REMAINING_COMMENTS t1 LEFT JOIN TEMP_EXP_PERSONAL_SLASHN_INVOICE_FROM_ITEM t2 ON t2.PE_ID = t1.PE_ID
WHERE t2.PE_ID IS NULL;
CALL SP_MIG_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM_SPLIT_INSERT();
CREATE OR REPLACE VIEW VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM_COMMENTS AS SELECT t1.PE_ID,t1.PE_PERSONAL_COMMENTS,PE_PERSONAL_INVOICE_ITEMS,PE_PERSONAL_INVOICE_FROM
FROM VW_MIG_TEMP_EXP_PERSONAL_SLASHN_REMAINING_COMMENTS t1
LEFT JOIN TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM t2 ON t2.PE_ID = t1.PE_ID
WHERE t2.PE_ID IS NULL;
CALL SP_MIG_EXP_PERSONAL_SINGLE_SLASHN_INVOICE_ITEM_SPLIT_INSERT();
CALL SP_PERSONAL_INVOICE_ITEM_FROM_SPLITTING(DESTINATIONSCHEMA);
SET END_TIME=(SELECT CURTIME());
SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
DROP TABLE IF EXISTS TEMP_DURATION_PERSONAL_INVOICE_ITEM_FROM;
CREATE TABLE TEMP_DURATION_PERSONAL_INVOICE_ITEM_FROM(ID INTEGER PRIMARY KEY AUTO_INCREMENT,SPLITTING_DURATION TIME);
INSERT INTO TEMP_DURATION_PERSONAL_INVOICE_ITEM_FROM(SPLITTING_DURATION)VALUES(DURATION);
DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_ALL_COMMENTS;
DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_REMAINING_COMMENTS;
DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_SINGLE_SLASHN_REMAINING_COMMENTS;
DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_INVOICE_ITEM_COMMENTS;
DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_DOUBLE_SLASHN_REMAINING_COMMENTS;
DROP VIEW IF EXISTS VW_MIG_TEMP_EXP_PERSONAL_SLASHN_REMAINING_COMMENTS;
COMMIT;
END;