DROP TRIGGER IF EXISTS TRG_EMPLOEYEE_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_EMPLOEYEE_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON EMPLOYEE_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TRG_EMPLOEYEE_DETAILS_VALIDATION (NEW.EMP_MOBILE,'INSERT');
END;