-- VERSION 0.1 STARTDATE:15/09/2014 ENDDATE:15/09/2014 ISSUE NO:85 COMMENT NO:2 DESC:SP FOR COUNT ABSENT FLAG ON MONTH WISE. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TS_REPORT_COUNT_ABSENT_FLAG;
CREATE PROCEDURE SP_TS_REPORT_COUNT_ABSENT_FLAG(
IN MONTH_YEAR VARCHAR(20),
IN USERSTAMP VARCHAR(50),
OUT TEMP_USER_ABSENT_COUNT TEXT)
BEGIN
	DECLARE TEMP_USERABSENTCOUNT TEXT;
	DECLARE SHORT_MONTH CHAR(10);
	DECLARE MONTHSTARTDATE DATE;
	DECLARE MONTHENDDATE DATE;
	DECLARE TAU_MIN_ID SMALLINT;
	DECLARE TAU_MAX_ID SMALLINT;
	DECLARE FLAG_COUNT SMALLINT;
	DECLARE ULDID SMALLINT; 
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
	CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULD_ID);
	SET ULDID=@ULD_ID;
	-- VIEW & TABLE FOR ACTIVE USERS
	CREATE OR REPLACE VIEW VW_USER_ACCESS_MAXRECVER AS SELECT ULD_ID,MAX(UA_REC_VER) AS RECVER FROM USER_ACCESS GROUP BY ULD_ID;
	DROP TABLE IF EXISTS TEMP_ACTIVE_USER;
	CREATE TABLE TEMP_ACTIVE_USER (ID INT AUTO_INCREMENT PRIMARY KEY,ULD_ID INTEGER,ULD_LOGINID VARCHAR(50),URC_ID INT,URC_DATA VARCHAR(20));
	INSERT INTO TEMP_ACTIVE_USER (ULD_ID,ULD_LOGINID,URC_ID,URC_DATA) (SELECT ULD.ULD_ID, ULD.ULD_LOGINID,URCN.URC_ID,URCN.URC_DATA 
	FROM USER_LOGIN_DETAILS ULD,USER_ACCESS UA, VW_USER_ACCESS_MAXRECVER V,USER_RIGHTS_CONFIGURATION URCN,ROLE_CREATION RC WHERE ULD.ULD_ID=UA.ULD_ID 
	AND UA.UA_REC_VER=V.RECVER AND V.ULD_ID=UA.ULD_ID AND V.ULD_ID=ULD.ULD_ID AND UA.RC_ID=RC.RC_ID AND RC.URC_ID=URCN.URC_ID AND UA.UA_TERMINATE IS NULL AND URCN.URC_DATA !="SUPER ADMIN" GROUP BY ULD.ULD_ID);
	-- FOR MIN AND MAX ID
	SELECT MIN(ID) INTO TAU_MIN_ID FROM TEMP_ACTIVE_USER;
	SELECT MAX(ID) INTO TAU_MAX_ID FROM TEMP_ACTIVE_USER;  
	-- FOR START DATE AND ENDATE
	SET SHORT_MONTH=(SELECT SUBSTRING(MONTH_YEAR,1,3));
	SET MONTHSTARTDATE=(SELECT CONCAT((SELECT SUBSTRING_INDEX(MONTH_YEAR, '-', -1)),'-',(SELECT MONTH(STR_TO_DATE(SHORT_MONTH,'%b'))),'-','01'));
	SET MONTHENDDATE=(SELECT LAST_DAY(MONTHSTARTDATE));
  
	-- TABLE FOR COUNT ABSNET
	SET TEMP_USERABSENTCOUNT=(SELECT CONCAT('TEMP_USER_ABSENT_COUNT',SYSDATE()));
	SET TEMP_USERABSENTCOUNT=(SELECT REPLACE(TEMP_USERABSENTCOUNT,':',''));
	SET TEMP_USERABSENTCOUNT=(SELECT REPLACE(TEMP_USERABSENTCOUNT,'-',''));
	SET TEMP_USERABSENTCOUNT=(SELECT REPLACE(TEMP_USERABSENTCOUNT,' ',''));
	SET TEMP_USERABSENTCOUNT=(SELECT CONCAT(TEMP_USERABSENTCOUNT,'_',ULDID));
	SET TEMP_USER_ABSENT_COUNT=TEMP_USERABSENTCOUNT;
	SET @DROP_TEMP_USER_ABSENT_COUNT=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_USER_ABSENT_COUNT));
	PREPARE DROP_TEMP_USER_ABSENT_COUNT_STMT FROM @DROP_TEMP_USER_ABSENT_COUNT;
	EXECUTE DROP_TEMP_USER_ABSENT_COUNT_STMT;
	SET @CREATE_TEMP_USER_ABSENT_COUNT=(SELECT CONCAT('CREATE TABLE ',TEMP_USER_ABSENT_COUNT,'(ID INT AUTO_INCREMENT PRIMARY KEY,ULD_ID INTEGER,UNAME VARCHAR(50),ABSENT_COUNT INTEGER)'));
	PREPARE CREATE_TEMP_USER_ABSENT_COUNT_STMT FROM @CREATE_TEMP_USER_ABSENT_COUNT;
	EXECUTE CREATE_TEMP_USER_ABSENT_COUNT_STMT;  
	WHILE(TAU_MIN_ID <= TAU_MAX_ID)DO 
		SET @ABSENTFLAGCOUNT=(SELECT CONCAT('SELECT COUNT(ABSENT_FLAG) INTO @COUNT_ABSENTFLAG FROM USER_ADMIN_REPORT_DETAILS WHERE ULD_ID=(SELECT ULD_ID FROM TEMP_ACTIVE_USER WHERE ID=',TAU_MIN_ID,') 
		AND (UARD_DATE BETWEEN ','"',MONTHSTARTDATE,'"',' AND ','"',MONTHENDDATE,'"',') AND ABSENT_FLAG="X"'));
		PREPARE ABSENTFLAGCOUNT_STMT FROM @ABSENTFLAGCOUNT;
		EXECUTE ABSENTFLAGCOUNT_STMT;
		SET FLAG_COUNT=@COUNT_ABSENTFLAG;
		-- INSERT ABSENT COUNT
		IF(FLAG_COUNT!=0)THEN  	     
			SET @INSERT_TEMP_USER_ABSENT_COUNT=(SELECT CONCAT('INSERT INTO ',TEMP_USER_ABSENT_COUNT,'(ULD_ID,UNAME,ABSENT_COUNT) (SELECT ULD.ULD_ID,ULD.ULD_LOGINID,COUNT(UARD.ABSENT_FLAG) 
			FROM USER_ADMIN_REPORT_DETAILS UARD,USER_LOGIN_DETAILS ULD WHERE UARD.ULD_ID=(SELECT ULD_ID FROM TEMP_ACTIVE_USER WHERE ID=',TAU_MIN_ID,') AND (UARD.UARD_DATE BETWEEN ','"',MONTHSTARTDATE,'"',' AND ','"',MONTHENDDATE,'"',') 
			AND UARD.ABSENT_FLAG="X" AND UARD.ULD_ID = ULD.ULD_ID AND ULD.ULD_ID=(SELECT ULD_ID FROM TEMP_ACTIVE_USER WHERE ID=',TAU_MIN_ID,'))'));
			PREPARE INSERT_TEMP_USER_ABSENT_COUNT_STMT FROM @INSERT_TEMP_USER_ABSENT_COUNT;
			EXECUTE INSERT_TEMP_USER_ABSENT_COUNT_STMT;      
		END IF;
		SET TAU_MIN_ID=TAU_MIN_ID+1;
	END WHILE;
	DROP VIEW IF EXISTS VW_USER_ACCESS_MAXRECVER;
	DROP TABLE IF EXISTS TEMP_ACTIVE_USER;
	COMMIT;
END;
/*
CALL SP_TS_REPORT_COUNT_ABSENT_FLAG('AUGUST-2014','dhandapani.sattanathan@ssomens.com',@TEMP_USER_ABSENT_COUNT);
*/