-- version 0.5 startdate:14/05/2014 --enddate:14/05/2014--- issueno 817 commentno:65-->desc: CHANGED THE SP FOR DYNAMIC PURPOSE BY RAJA
-- version 0.4 startdate:14/03/2014 --enddate:15/03/2014--- issueno 659 commentno:#76-->desc: DONE SOME CHANGES FOR LOGIN REJOIN DONE BY:DHIVYA
-- version 0.3 startdate:28/02/2014 --enddate:28/02/2014--- issueno 754 commentno:36-->desc: APPLIED SUB_SP TO REPLACE USERSTAMP AS ID-SAFI
-- version 0.2 --sdate:27/02/2014 --edate:27/02/2014 --issue:754 --comment:22 --doneby:RL	
-- VER 0.1--->ISSUE NO:659 COMMENT NO:#2 START DATE:12/12/2013 ENDDATE:12/12/2013 DESC:SP FOR LOGIN CREATION INSERT  DONE BY:DHIVYA.A
DROP PROCEDURE IF EXISTS SP_LOGIN_CREATION_INSERT;
CREATE PROCEDURE SP_LOGIN_CREATION_INSERT
(LOGINID VARCHAR(40),
ROLENAME VARCHAR(15),
JOINDATE DATE,
USERSTAMP VARCHAR(50),
OUT UR_FLAG INTEGER)

BEGIN
-- VARIABLE DECLARATION
DECLARE MINID INTEGER;
DECLARE MAXID INTEGER;
DECLARE RECVER INTEGER;
DECLARE ULDID INTEGER;
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE TEMPTABLE_MENU TEXT;
DECLARE TEMPTBL_MENU TEXT;
DECLARE EPID INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
	SET UR_FLAG=0;
END;
START TRANSACTION;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
-- TEMP TABLE NAME START
SET TEMPTBL_MENU=(SELECT CONCAT('TEMPTABLE_MENU',SYSDATE()));
SET TEMPTBL_MENU=(SELECT REPLACE(TEMPTBL_MENU,' ',''));
SET TEMPTBL_MENU=(SELECT REPLACE(TEMPTBL_MENU,'-',''));
SET TEMPTBL_MENU=(SELECT REPLACE(TEMPTBL_MENU,':',''));
SET TEMPTABLE_MENU=(SELECT CONCAT(TEMPTBL_MENU,'_',USERSTAMP_ID));

SET RECVER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID));
SET ULDID=(SELECT DISTINCT ULD_ID FROM USER_ACCESS WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID));

IF NOT EXISTS(SELECT ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID)THEN
	IF LOGINID IS NOT NULL THEN
		-- INSERT QUERY FOR USER_LOGIN_DETAILS TABLE
		INSERT INTO USER_LOGIN_DETAILS(ULD_LOGINID,ULD_USERSTAMP)VALUES(LOGINID,USERSTAMP);
		SET UR_FLAG=1;
	END IF;
END IF;	

IF (LOGINID IS NOT NULL AND ROLENAME IS NOT NULL AND JOINDATE IS NOT NULL AND USERSTAMP IS NOT NULL)THEN
	-- INSERT QUERY FOR USER_ACCESS TABLE
	IF (ULDID IS NOT NULL)THEN
		INSERT INTO USER_ACCESS(RC_ID,ULD_ID,UA_REC_VER,UA_JOIN_DATE,UA_JOIN,UA_USERSTAMP)VALUES((SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=ROLENAME),
		(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID),(RECVER+1),JOINDATE,'X',USERSTAMP);
		SET UR_FLAG=1;
	ELSE
		INSERT INTO USER_ACCESS(RC_ID,ULD_ID,UA_REC_VER,UA_JOIN_DATE,UA_JOIN,UA_USERSTAMP)VALUES((SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=ROLENAME),
		(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID),1,JOINDATE,'X',USERSTAMP);
		SET UR_FLAG=1;
	END IF;   
END IF;
  
	-- TEMP TABLE FOR GETTING MENU_ID AND ITS EMAIL_PROFILE ID
	-- DROP TABLE IF EXISTS TEMPTBL_MENU;
	SET @CREATE_TEMPTABLE_MENU=(SELECT CONCAT('CREATE TABLE ',TEMPTABLE_MENU,'(ID INTEGER PRIMARY KEY AUTO_INCREMENT,MP_ID INTEGER,EP_ID INTEGER)'));
  PREPARE CREATE_TEMPTABLE_MENU_STMT FROM @CREATE_TEMPTABLE_MENU;
  EXECUTE CREATE_TEMPTABLE_MENU_STMT;
  
	SET @INSERT_TEMPTABLE_MENU=(SELECT CONCAT('INSERT INTO ',TEMPTABLE_MENU,'(MP_ID,EP_ID) SELECT M.MP_ID,M.EP_ID FROM USER_MENU_DETAILS U,MENU_PROFILE M WHERE U.RC_ID=(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=','"',ROLENAME,'"',')AND U.MP_ID=M.MP_ID'));
	PREPARE INSERT_TEMPTABLE_MENU_STMT FROM @INSERT_TEMPTABLE_MENU;
  EXECUTE INSERT_TEMPTABLE_MENU_STMT;
  
	SET @MIN_ID=NULL;
  SET @SELECT_MINID=(SELECT CONCAT('SELECT MIN(ID) INTO @MIN_ID FROM ',TEMPTABLE_MENU));
  PREPARE SELECT_MINID_STMT FROM @SELECT_MINID;
  EXECUTE SELECT_MINID_STMT;
	SET MINID=@MIN_ID;
  
  SET @MAX_ID=NULL;
  SET @SELECT_MAXID=(SELECT CONCAT('SELECT MAX(ID) INTO @MAX_ID FROM ',TEMPTABLE_MENU));
  PREPARE SELECT_MAXID_STMT FROM @SELECT_MAXID;
  EXECUTE SELECT_MAXID_STMT;
	SET MAXID=@MAX_ID;
  
	WHILE (MINID<=MAXID)DO
    SET @T_EPID=NULL;
    SET @SELECT_EPID=(SELECT CONCAT('SELECT EP_ID INTO @T_EPID FROM ',TEMPTABLE_MENU,' WHERE ID=',MINID,' AND EP_ID IS NOT NULL'));
    PREPARE SELECT_EPID_STMT FROM @SELECT_EPID;
    EXECUTE SELECT_EPID_STMT;
    SET EPID=@T_EPID;
    
  	IF (EPID IS NOT NULL)THEN		
      -- INSERT QUERY FOR EMAIL_LIST TABLE
      SET @INSERT_EMAIL_LIST=(SELECT CONCAT('INSERT INTO EMAIL_LIST (EP_ID,EL_EMAIL_ID,ULD_ID)VALUES((SELECT EP_ID FROM ',TEMPTABLE_MENU,' WHERE ID=',MINID,'),','"',LOGINID,'"',',',USERSTAMP_ID,')'));
      PREPARE INSERT_EMAIL_LIST_STMT FROM @INSERT_EMAIL_LIST;
      EXECUTE INSERT_EMAIL_LIST_STMT;
      SET UR_FLAG=1;
		END IF;
		SET MINID=MINID+1;
	END WHILE;
  SET @DROP_TEMPTABLE_MENU=(SELECT CONCAT('DROP TABLE ',TEMPTABLE_MENU));
  PREPARE DROP_TEMPTABLE_MENU_STMT FROM @DROP_TEMPTABLE_MENU;
  EXECUTE DROP_TEMPTABLE_MENU_STMT;
	
COMMIT;
END;
/*
CALL SP_LOGIN_CREATION_INSERT('bhavani.rajagopalagopal@ssomens.com','ADMIN','2013-09-08','sarathbabou.somaya@ssomens.com',@UR_FLAG);
*/