-- VERSION 0.1 STARTDATE:16/09/2014 ENDDATE:16/09/2014 ISSUE NO:84 COMMENT NO:10 DESC:CHECK CONSTRAINTS FOR THE EMPLOYEE DETAILS. DONE BY :RAJA
DROP PROCEDURE IF EXISTS SP_TS_TRG_EMPLOYEE_DETAILS_VALIDATION;
CREATE PROCEDURE SP_TS_TRG_EMPLOYEE_DETAILS_VALIDATION(
IN DESIGNATION VARCHAR(20),
IN DOB DATE,
IN MOBILE_NO VARCHAR(10),
IN ALT_MOBILE_NO VARCHAR(10),
IN PROCESS VARCHAR(10))
BEGIN
	DECLARE ERROR_MSG TEXT;
	DECLARE MESSAGE_TEXT TEXT;
	IF((PROCESS='INSERT') OR (PROCESS='UPDATE'))THEN

		IF (DESIGNATION IS NOT NULL) THEN
			IF (DESIGNATION REGEXP BINARY '[a-z]') THEN
				SET ERROR_MSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=34);
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT=ERROR_MSG;
			END IF;
		END IF;
		IF (DOB IS NOT NULL) THEN
			IF (DOB<CURDATE())THEN
				IF (DOB>DATE_ADD(CURDATE(),INTERVAL -18 YEAR)) THEN
					SET ERROR_MSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=35);
					SET ERROR_MSG=(SELECT REPLACE(ERROR_MSG,'[DOB]',DOB));
					SIGNAL SQLSTATE '45000'
					SET MESSAGE_TEXT=ERROR_MSG;
				END IF;
			END IF;
			IF(DOB>CURDATE())THEN
				IF (DOB>CURDATE()) THEN
					SET ERROR_MSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=36);
					SET ERROR_MSG=(SELECT REPLACE(ERROR_MSG,'[DOB]',DOB));
					SET ERROR_MSG=(SELECT REPLACE(ERROR_MSG,'[CURDATE]',CURDATE()));
					SIGNAL SQLSTATE '45000'
					SET MESSAGE_TEXT=ERROR_MSG;
				END IF;
			END IF;
		END IF;
		IF (MOBILE_NO IS NOT NULL) THEN
			IF (LENGTH(MOBILE_NO)!=10) THEN
				SET ERROR_MSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=37);
				SET ERROR_MSG=(SELECT REPLACE(ERROR_MSG,'[MOB NO]',MOBILE_NO));
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT=ERROR_MSG;
			END IF;
		END IF;
		IF (ALT_MOBILE_NO IS NOT NULL) THEN
			IF (LENGTH(ALT_MOBILE_NO)!=10) THEN
				SET ERROR_MSG=(SELECT EMC_DATA FROM ERROR_MESSAGE_CONFIGURATION WHERE EMC_ID=37);
				SET ERROR_MSG=(SELECT REPLACE(ERROR_MSG,'[MOB NO]',ALT_MOBILE_NO));
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT=ERROR_MSG;
			END IF;
		END IF;

	END IF;
END;
/*
CALL SP_TS_TRG_EMPLOYEE_DETAILS_VALIDATION ('DEVELOPER','1991-03-04','8608502941','8608502941','INSERT');
*/