-- VERSION 0.1 STARTDATE:16/09/2014 ENDDATE:16/09/2014 ISSUE NO:84 DESC:IMPLEMENTED CONSTRAINTS TRIGGER FOR INSERT. DONE BY :RAJA
DROP TRIGGER IF EXISTS TS_TRG_EMPLOYEE_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TS_TRG_EMPLOYEE_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON EMPLOYEE_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TS_TRG_EMPLOYEE_DETAILS_VALIDATION (NEW.EMP_DESIGNATION,NEW.EMP_DOB,NEW.EMP_MOBILE_NUMBER,NEW.EMP_ALT_MOBILE_NO,'INSERT');
END;