DROP TRIGGER IF EXISTS TRG_STAFFDTL_SALARY_INSERT_VALIDATION;
CREATE TRIGGER TRG_STAFFDTL_SALARY_INSERT_VALIDATION
BEFORE INSERT ON EXPENSE_DETAIL_STAFF_SALARY
FOR EACH ROW
BEGIN
	CALL SP_TRG_STAFFDTL_SALARY_VALIDATION (NEW.EDSS_CPF_NUMBER,'INSERT');
END;