DROP PROCEDURE IF EXISTS SP_LOGIN_UPDATE;
CREATE PROCEDURE SP_LOGIN_UPDATE(
LOGINID VARCHAR(40),
ROLENAME VARCHAR(15),
JOINDATE DATE,
USERSTAMP VARCHAR(50),
OUT UR_FLAG INTEGER)
BEGIN
DECLARE OLDROLENAME VARCHAR(15);
DECLARE MINID INTEGER;
DECLARE MAXID INTEGER;
DECLARE RECVER INTEGER;
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE TEMPTBL_MENU TEXT;
DECLARE TMP_MENU TEXT;
DECLARE EPID INT;
DECLARE EMAILLIST INT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
IF(TEMPTBL_MENU IS NOT NULL)THEN
  SET @DROP_TEMPTBL_MENU=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMPTBL_MENU));
  PREPARE DROP_TEMPTBL_MENU_STMT FROM @DROP_TEMPTBL_MENU;
  EXECUTE DROP_TEMPTBL_MENU_STMT;
END IF;
END;
START TRANSACTION;
SET FOREIGN_KEY_CHECKS=0;
SET UR_FLAG=0;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
SET TMP_MENU=(SELECT CONCAT('TEMPTBL_MENU',SYSDATE()));
SET TMP_MENU=(SELECT REPLACE(TMP_MENU,' ',''));
SET TMP_MENU=(SELECT REPLACE(TMP_MENU,'-',''));
SET TMP_MENU=(SELECT REPLACE(TMP_MENU,':',''));
SET TEMPTBL_MENU=(SELECT CONCAT(TMP_MENU,'_',USERSTAMP_ID));
SET RECVER=(SELECT MAX(UA_REC_VER) FROM USER_ACCESS WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID));
SET OLDROLENAME=(SELECT R.RC_NAME FROM USER_ACCESS U,ROLE_CREATION R WHERE R.RC_ID=U.RC_ID AND U.ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID)AND U.UA_REC_VER=RECVER);
	IF (ROLENAME IS NOT NULL AND JOINDATE IS NOT NULL AND USERSTAMP IS NOT NULL)THEN
		UPDATE USER_ACCESS SET RC_ID=(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=ROLENAME),UA_JOIN_DATE=JOINDATE,UA_USERSTAMP=USERSTAMP WHERE ULD_ID=(SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=LOGINID)AND UA_REC_VER=RECVER;
      SET UR_FLAG=1;
	END IF;
	IF (OLDROLENAME!=ROLENAME)THEN
  DELETE FROM EMAIL_LIST WHERE EL_EMAIL_ID=LOGINID;
	SET @CREATE_TEMPTBL_MENU=(SELECT CONCAT('CREATE TABLE ',TEMPTBL_MENU,'(ID INTEGER PRIMARY KEY AUTO_INCREMENT,MP_ID INTEGER,EP_ID INTEGER)'));
  PREPARE CREATE_TEMPTBL_MENU_STMT FROM @CREATE_TEMPTBL_MENU;
  EXECUTE CREATE_TEMPTBL_MENU_STMT;
	SET @INSERT_TEMPTBL_MENU=(SELECT CONCAT('INSERT INTO ',TEMPTBL_MENU,'(MP_ID,EP_ID) SELECT M.MP_ID,M.EP_ID FROM USER_MENU_DETAILS U,MENU_PROFILE M WHERE U.RC_ID=(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=','"',ROLENAME,'"',')AND U.MP_ID=M.MP_ID'));
	PREPARE INSERT_TEMPTBL_MENU_STMT FROM @INSERT_TEMPTBL_MENU;
  EXECUTE INSERT_TEMPTBL_MENU_STMT;
  SET @MIN_ID=NULL; 
  SET @SELECT_MINID=(SELECT CONCAT('SELECT MIN(ID) INTO @MIN_ID FROM ',TEMPTBL_MENU));
  PREPARE SELECT_MINID_STMT FROM @SELECT_MINID;
  EXECUTE SELECT_MINID_STMT;
	SET MINID=@MIN_ID;
  SET @MAX_ID=NULL;
  SET @SELECT_MAXID=(SELECT CONCAT('SELECT MAX(ID) INTO @MAX_ID FROM ',TEMPTBL_MENU));
  PREPARE SELECT_MAXID_STMT FROM @SELECT_MAXID;
  EXECUTE SELECT_MAXID_STMT;
	SET MAXID=@MAX_ID;
	WHILE (MINID<=MAXID)DO 
    SET @T_EPID=NULL;
    SET @SELECT_EPID=(SELECT CONCAT('SELECT EP_ID INTO @T_EPID FROM ',TEMPTBL_MENU,' WHERE ID=',MINID,' AND EP_ID IS NOT NULL'));
    PREPARE SELECT_EPID_STMT FROM @SELECT_EPID;
    EXECUTE SELECT_EPID_STMT;
    SET EPID=(SELECT @T_EPID);
  		IF (EPID IS NOT NULL)THEN
       SET @SELECT_EMAIL_LIST=(SELECT CONCAT('SELECT COUNT(*) INTO @T_EMAILLIST FROM EMAIL_LIST WHERE EP_ID=(SELECT EP_ID FROM ',TEMPTBL_MENU,' WHERE ID=',MINID,')AND EL_EMAIL_ID=','"',LOGINID,'"'));
       PREPARE SELECT_EMAIL_LIST_STMT FROM @SELECT_EMAIL_LIST;
       EXECUTE SELECT_EMAIL_LIST_STMT;
       SET EMAILLIST=(SELECT @T_EMAILLIST);
	        IF (EMAILLIST=0)THEN 
      			SET @INSERT_EMAIL_LIST=(SELECT CONCAT('INSERT INTO EMAIL_LIST(EP_ID,EL_EMAIL_ID,ULD_ID)VALUES((SELECT EP_ID FROM ',TEMPTBL_MENU,' WHERE ID=',MINID,'),','"',LOGINID,'"',',',USERSTAMP_ID,')'));
            PREPARE INSERT_EMAIL_LIST_STMT FROM @INSERT_EMAIL_LIST;
            EXECUTE INSERT_EMAIL_LIST_STMT;
              SET UR_FLAG=1;
		      END IF;
		  END IF;
		SET MINID=MINID+1;
	END WHILE;
  SET @DROP_TEMPTBL_MENU=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMPTBL_MENU));
  PREPARE DROP_TEMPTBL_MENU_STMT FROM @DROP_TEMPTBL_MENU;
  EXECUTE DROP_TEMPTBL_MENU_STMT;
	END IF;
    SET FOREIGN_KEY_CHECKS=1;
COMMIT;
END;