DROP PROCEDURE IF EXISTS SP_CONFIG_SQL_FORMAT;
CREATE PROCEDURE SP_CONFIG_SQL_FORMAT() 
BEGIN 
DROP TABLE IF EXISTS CONFIG_SQL_FORMAT;
CREATE TABLE `CONFIG_SQL_FORMAT` (
`ID` VARCHAR(10) NULL,
`CNP_ID` VARCHAR(50) NULL,
`CNP_DATA` VARCHAR(255) NULL,
`CGN_ID` VARCHAR(50) NULL,
`CGN_DATA` VARCHAR(255) NULL,
`DATA` TEXT NULL,
`TP_ID` VARCHAR(50) NULL,
`TP_TYPE` VARCHAR(255) NULL,
`TTIP_ID` VARCHAR(50) NULL,
`TTIP_DATA` VARCHAR(255) NULL,
`EMC_CODE` VARCHAR(50) NULL,
`EMC_DATA` TEXT NULL,
`PD_DATA` VARCHAR(255) NULL,
`PD_DESCRIPTION` TEXT NULL,
`PD_ID` VARCHAR(20) NULL,
`PC_ID` VARCHAR(20) NULL,
`PS_REC_VER` VARCHAR(20) NULL,
`PS_START_DATE` VARCHAR(255) NULL,
`PS_END_DATE` VARCHAR(255) NULL,
`USER_STAMP` VARCHAR(100) NULL,
`TIMESTAMP` VARCHAR(100) NULL);
END;
/*
CALL SP_CONFIG_SQL_FORMAT;
*/