DROP PROCEDURE IF EXISTS SP_TS_REPORT_COUNT_ABSENT_FLAG;
CREATE PROCEDURE SP_TS_REPORT_COUNT_ABSENT_FLAG(
IN MONTH_YEAR VARCHAR(20),
IN USERSTAMP INTEGER,
OUT TEMP_USER_ABSENT_COUNT TEXT)
BEGIN
	DECLARE TEMP_USERABSENTCOUNT TEXT;
	DECLARE SHORT_MONTH CHAR(10);
	DECLARE MONTHSTARTDATE DATE;
	DECLARE MONTHENDDATE DATE;
	DECLARE TAU_MIN_ID SMALLINT;
	DECLARE TAU_MAX_ID SMALLINT;
	DECLARE FLAG_COUNT SMALLINT;
	DECLARE ULDID SMALLINT; 
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		DROP TABLE IF EXISTS TEMP_ABSENT_ULDID;
	END;
	START TRANSACTION;
	SET ULDID=USERSTAMP;
	SET SHORT_MONTH=(SELECT SUBSTRING(MONTH_YEAR,1,3));
	SET MONTHSTARTDATE=(SELECT CONCAT((SELECT SUBSTRING_INDEX(MONTH_YEAR, '-', -1)),'-',(SELECT MONTH(STR_TO_DATE(SHORT_MONTH,'%b'))),'-','01'));
	SET MONTHENDDATE=(SELECT LAST_DAY(MONTHSTARTDATE));
	DROP TABLE IF EXISTS TEMP_ABSENT_ULDID;
	CREATE TABLE TEMP_ABSENT_ULDID(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ULD_ID INTEGER);
	SET @INSERT_ABSENTFLAGULDID=(SELECT CONCAT('INSERT INTO TEMP_ABSENT_ULDID(ULD_ID) SELECT DISTINCT ULD_ID FROM USER_ADMIN_REPORT_DETAILS WHERE UARD_DATE BETWEEN ','"',MONTHSTARTDATE,'"',' AND ','"',MONTHENDDATE,'"',' AND ABSENT_FLAG="X"'));
	PREPARE INSERT_ABSENTFLAGULDID_STMT FROM @INSERT_ABSENTFLAGULDID;
	EXECUTE INSERT_ABSENTFLAGULDID_STMT;
	SELECT MIN(ID) INTO TAU_MIN_ID FROM TEMP_ABSENT_ULDID;
	SELECT MAX(ID) INTO TAU_MAX_ID FROM TEMP_ABSENT_ULDID;
	SET TEMP_USERABSENTCOUNT=(SELECT CONCAT('TEMP_USER_ABSENT_COUNT',SYSDATE()));
	SET TEMP_USERABSENTCOUNT=(SELECT REPLACE(TEMP_USERABSENTCOUNT,':',''));
	SET TEMP_USERABSENTCOUNT=(SELECT REPLACE(TEMP_USERABSENTCOUNT,'-',''));
	SET TEMP_USERABSENTCOUNT=(SELECT REPLACE(TEMP_USERABSENTCOUNT,' ',''));
	SET TEMP_USERABSENTCOUNT=(SELECT CONCAT(TEMP_USERABSENTCOUNT,'_',ULDID));
	SET TEMP_USER_ABSENT_COUNT=TEMP_USERABSENTCOUNT;
	SET @DROP_TEMP_USER_ABSENT_COUNT=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_USER_ABSENT_COUNT));
	PREPARE DROP_TEMP_USER_ABSENT_COUNT_STMT FROM @DROP_TEMP_USER_ABSENT_COUNT;
	EXECUTE DROP_TEMP_USER_ABSENT_COUNT_STMT;
	SET @CREATE_TEMP_USER_ABSENT_COUNT=(SELECT CONCAT('CREATE TABLE ',TEMP_USER_ABSENT_COUNT,'(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ULD_ID INTEGER,
	UNAME VARCHAR(50),
	ABSENT_COUNT INTEGER)'));
	PREPARE CREATE_TEMP_USER_ABSENT_COUNT_STMT FROM @CREATE_TEMP_USER_ABSENT_COUNT;
	EXECUTE CREATE_TEMP_USER_ABSENT_COUNT_STMT;  
	WHILE(TAU_MIN_ID <= TAU_MAX_ID)DO  
		SET @INSERT_TEMP_USER_ABSENT_COUNT=(SELECT CONCAT('INSERT INTO ',TEMP_USER_ABSENT_COUNT,'(ULD_ID,UNAME,ABSENT_COUNT) (SELECT ULD.ULD_ID,ULD.EMPLOYEE_NAME,COUNT(UARD.ABSENT_FLAG) 
		FROM USER_ADMIN_REPORT_DETAILS UARD,VW_TS_ALL_EMPLOYEE_DETAILS ULD WHERE (UARD.UARD_DATE BETWEEN ','"',MONTHSTARTDATE,'"',' AND ','"',MONTHENDDATE,'"',') 
		AND UARD.ABSENT_FLAG="X" AND UARD.ULD_ID = ULD.ULD_ID AND ULD.ULD_ID=(SELECT ULD_ID FROM TEMP_ABSENT_ULDID WHERE ID=',TAU_MIN_ID,'))'));
		PREPARE INSERT_TEMP_USER_ABSENT_COUNT_STMT FROM @INSERT_TEMP_USER_ABSENT_COUNT;
		EXECUTE INSERT_TEMP_USER_ABSENT_COUNT_STMT;
		SET TAU_MIN_ID=TAU_MIN_ID+1;
	END WHILE;
	DROP TABLE IF EXISTS TEMP_ABSENT_ULDID;
	COMMIT;
END;
