DROP PROCEDURE IF EXISTS SP_REPORT_SCDB_FORMAT;
CREATE PROCEDURE SP_REPORT_SCDB_FORMAT() 
BEGIN 
  CREATE TABLE `REPORTS_SCDB_FORMAT` (
  `siloId` VARCHAR(255) NULL,
  `timeStamp` VARCHAR(255) NULL,
  `Uname` VARCHAR(255) NULL,
  `Udate` VARCHAR(255) NULL,
  `Ureport` TEXT NULL, 
  `Uid` INT NULL,
  `userStamp` VARCHAR(255) NULL);

  CREATE TABLE `TEMP_EMP_REPORT_SCDB_FORMAT` (
  `siloId` VARCHAR(255) NULL,
  `timeStamp` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `Uname` VARCHAR(255) NULL,
  `Udate` VARCHAR(255) NULL,
  `Ureport` TEXT NULL,
  `Uid` VARCHAR(255) NULL,
`userStamp` VARCHAR(255) NULL);
END;
/*
CALL SP_REPORT_SCDB_FORMAT;
*/