DROP PROCEDURE IF EXISTS SP_TS_MIG_REPORT_DETAILS_INSERT;
CREATE PROCEDURE SP_TS_MIG_REPORT_DETAILS_INSERT(
IN SOURCESCHEMA VARCHAR(40),
IN DESTINATIONSCHEMA VARCHAR(40))
BEGIN
  DECLARE OD_TIMESTAMP TIMESTAMP; 
  DECLARE OD_USERSTAMP VARCHAR(50);
  DECLARE ABS_TIMESTAMP TIMESTAMP; 
  DECLARE ABS_USERSTAMP VARCHAR(50);
  DECLARE TRSF_TIMESTAMP TIMESTAMP;
  DECLARE TRSF_USERSTAMP VARCHAR(50);
  DECLARE TEMP_USERADMINREPORTDETAILS TEXT;
  DECLARE TEMP_USER_ADMIN_REPORT_DETAILS TEXT; 
  DECLARE TEMP_ABSENT TEXT;
  DECLARE TEMPABSENT TEXT;
  DECLARE TEMP_HALF_DAY_LEAVE TEXT;
  DECLARE TEMHALFDAYLEAVE TEXT;
  DECLARE TEMP_HALF_DAY_MORNG TEXT;
  DECLARE TEMHALFDAYMORNG TEXT;
  DECLARE TEMP_HALF_DAY_AFTN TEXT;
  DECLARE TEMHALFDAYAFTN TEXT;
  DECLARE TEMP_ONDUTY TEXT;
  DECLARE TEMPONDUTY TEXT;
  DECLARE TEMP_PERMISSION TEXT;
  DECLARE TEMPPERMISSION TEXT;
  DECLARE TEMP_REPORTS TEXT;
  DECLARE TEMPREPORTS TEXT;
  DECLARE PDMAX_ID INT;
  DECLARE UARDMAX_ID INT;
  DECLARE ABS_MIN_ID INT;
  DECLARE ABS_MAX_ID INT;
  DECLARE TRSF_MIN_ID INT;
  DECLARE TRSF_MAX_ID INT;
  DECLARE OD_MIN_ID INT;
  DECLARE OD_MAX_ID INT;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;
    SET @DROP_TEMP_REPORTSSCDBFORMAT=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT'));
  	PREPARE DROP_TEMP_REPORTS_SCDB_FORMAT_STMT FROM @DROP_TEMP_REPORTSSCDBFORMAT;
    EXECUTE DROP_TEMP_REPORTS_SCDB_FORMAT_STMT;
  	SET @CREATE_TEMP_REPORTSSCDBFORMAT=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT(
    UID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SILOID VARCHAR(255) DEFAULT NULL,
    TIMESTAMP VARCHAR(255) DEFAULT NULL,
    UNAME VARCHAR(255) DEFAULT NULL,
    UDATE VARCHAR(255) DEFAULT NULL,
    UREPORT TEXT,
    USERSTAMP VARCHAR(255) DEFAULT NULL)'));
    PREPARE CREATE_TEMP_REPORTS_SCDB_FORMAT_STMT FROM @CREATE_TEMP_REPORTSSCDBFORMAT;
    EXECUTE CREATE_TEMP_REPORTS_SCDB_FORMAT_STMT;
    SET @INSERT_TEMP_REPORTSSCDBFORMAT=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT(SILOID,TIMESTAMP,UNAME,UDATE,UREPORT,USERSTAMP) 
    (SELECT SILOID,TIMESTAMP,UNAME,UDATE,UREPORT,USERSTAMP FROM ',SOURCESCHEMA,'.REPORTS_SCDB_FORMAT)'));
  	PREPARE INSERT_TEMP_REPORTS_SCDB_FORMAT_STMT FROM @INSERT_TEMP_REPORTSSCDBFORMAT;
    EXECUTE INSERT_TEMP_REPORTS_SCDB_FORMAT_STMT;
    SET @UPDATE_TEMP_REPORTSSCDBFORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT SET UNAME="bhavani.rajagopal@ssomens.com",USERSTAMP="bhavani.rajagopal@ssomens.com" WHERE UNAME="bhavani.rajagopalagopal@ssomens.com"'));
   	PREPARE UPDATE_TEMP_REPORTS_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_REPORTSSCDBFORMAT;
    EXECUTE UPDATE_TEMP_REPORTS_SCDB_FORMAT_STMT;
    
    -- TABLE FOR PROJECT DETAILS
    SET @DROP_PROJECTDTLS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.PROJECT_DETAILS'));
  	PREPARE DROP_PROJECT_DETAILS_STMT FROM @DROP_PROJECTDTLS;
    EXECUTE DROP_PROJECT_DETAILS_STMT;    
    SET @CREATE_PROJECT_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.PROJECT_DETAILS(
    PD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
    PD_PROJECT_NAME	VARCHAR(50)	NOT NULL,
    PD_PROJECT_DESCRIPTION	VARCHAR(100)	NOT NULL,
    ULD_ID	INTEGER(2)	NOT NULL,
    PD_TIMESTAMP	TIMESTAMP		NOT NULL,
    PRIMARY KEY (PD_ID),
    UNIQUE (PD_PROJECT_NAME),
    FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
    PREPARE CREATE_PROJECT_DETAILS_STMT FROM @CREATE_PROJECT_DETAILS;
    EXECUTE CREATE_PROJECT_DETAILS_STMT;
    SET @INSERT_PROJECTDTLS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.PROJECT_DETAILS(PD_PROJECT_NAME,PD_PROJECT_DESCRIPTION,ULD_ID) VALUES ("EI","EXPATSINTEGRATED",1)'));
  	PREPARE INSERT_PROJECT_DETAILS_STMT FROM @INSERT_PROJECTDTLS;
    EXECUTE INSERT_PROJECT_DETAILS_STMT;
    -- QUERY FOR ALTER AUTO_INCREMENT 
    SET @PDMAXID = (SELECT CONCAT('SELECT MAX(PD_ID) INTO @PD_MAX_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS'));
    PREPARE PD_MAX_ID_STMT FROM @PDMAXID;
    EXECUTE PD_MAX_ID_STMT;
    SET PDMAX_ID=@PD_MAX_ID;
    IF (PDMAX_ID IS NOT NULL) THEN    
      SET @ALTER_PROJECT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.PROJECT_DETAILS AUTO_INCREMENT=',PDMAX_ID));
      PREPARE ALTER_PROJECT_DETAILS_STMT FROM @ALTER_PROJECT_DETAILS;
      EXECUTE ALTER_PROJECT_DETAILS_STMT;
    END IF;
    
    -- TABLE FOR USER ADMIN REPORT DETAILS
    SET @DROP_USERADMINREPORTDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS'));
  	PREPARE DROP_USER_ADMIN_REPORT_DETAILS_STMT FROM @DROP_USERADMINREPORTDETAILS;
    EXECUTE DROP_USER_ADMIN_REPORT_DETAILS_STMT;
  	SET @CREATE_USERADMINREPORTDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS(
  	UARD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
    UARD_REPORT	TEXT NULL,
    UARD_REASON	TEXT NULL,
    UARD_DATE	DATE NOT NULL,
    URC_ID INTEGER(2) NOT NULL,
    ULD_ID INTEGER(2) NOT NULL,
    UARD_PERMISSION	INTEGER	NULL,
    UARD_ATTENDANCE	INTEGER	NOT NULL,
    UARD_FULLDAY_PDID	INTEGER	NULL,
    UARD_AM_PDID INTEGER	NULL,
    UARD_PM_PDID INTEGER	NULL,
    UARD_AM_SESSION	INTEGER NOT NULL,
    UARD_PM_SESSION	INTEGER	NOT NULL,
    UARD_BANDWIDTH DECIMAL(5,2) NOT NULL,
    UARD_USERSTAMP_ID	INTEGER	NOT NULL,
    UARD_TIMESTAMP TIMESTAMP	NOT NULL,
    PRIMARY KEY(UARD_ID),
    FOREIGN KEY(URC_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID),
    FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID),
    FOREIGN KEY(UARD_USERSTAMP_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
  	PREPARE CREATE_USER_ADMIN_REPORT_DETAILS_STMT FROM @CREATE_USERADMINREPORTDETAILS;
    EXECUTE CREATE_USER_ADMIN_REPORT_DETAILS_STMT;       
    
    --  TEMP TABLE NAME TEMP_USER_ADMIN_REPORT_DETAILS
    SET @DROP_TEMP_USERADMINREPORTDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
  	PREPARE DROP_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @DROP_TEMP_USERADMINREPORTDETAILS;
    EXECUTE DROP_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;
    SET @CREATE_TEMP_USERADMINREPORTDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(
  	UARD_ID	INTEGER	NOT NULL AUTO_INCREMENT,
    UARD_REPORT	TEXT NULL,
    UARD_REASON	TEXT NULL,
    UARD_DATE	DATE NOT NULL,
    URC_ID INTEGER(2) NOT NULL,
    ULD_ID INTEGER(2) NOT NULL,
    UARD_PERMISSION	INTEGER	NULL,
    UARD_ATTENDANCE	INTEGER	NOT NULL,
    UARD_FULLDAY_PDID	INTEGER	NULL,
    UARD_AM_PDID INTEGER	NULL,
    UARD_PM_PDID INTEGER	NULL,
    UARD_AM_SESSION	INTEGER NOT NULL,
    UARD_PM_SESSION	INTEGER	NOT NULL,
    UARD_BANDWIDTH DECIMAL(5,2) NOT NULL,
    UARD_USERSTAMP_ID	INTEGER	NOT NULL,
    UARD_TIMESTAMP TIMESTAMP	NOT NULL,
    PRIMARY KEY(UARD_ID),
    FOREIGN KEY(URC_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION (CGN_ID),
    FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID),
    FOREIGN KEY(UARD_USERSTAMP_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
  	PREPARE CREATE_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @CREATE_TEMP_USERADMINREPORTDETAILS;
    EXECUTE CREATE_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;
    
    -- TEMP TABLE FOR ABSENTIES
        SET @DROP_TEMP_ABSENT=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_ABSENT'));
      	PREPARE DROP_TEMP_ABSENT_STMT FROM @DROP_TEMP_ABSENT;
        EXECUTE DROP_TEMP_ABSENT_STMT;
        SET @CREATE_TEMP_ABSENT=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_ABSENT(
        ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
        UID INT(11) NOT NULL ,
        UNAME VARCHAR(255) DEFAULT NULL,
        UDATE VARCHAR(255) DEFAULT NULL,
        UREPORT TEXT,
        USERSTAMP VARCHAR(255) DEFAULT NULL,
        TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
        PREPARE CREATE_TEMP_ABSENT_STMT FROM @CREATE_TEMP_ABSENT;
        EXECUTE CREATE_TEMP_ABSENT_STMT;
        SET @INSERT_TEMPABSENT=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_ABSENT(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
        (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE (UREPORT NOT LIKE "%Ha%day%Absent%" AND UREPORT NOT LIKE "%Absent not%"
        AND UREPORT NOT LIKE "%ABSENT record del%" AND UREPORT NOT LIKE "%AFT%ABSENT%" AND UREPORT NOT LIKE "%present%absent%"
        AND UREPORT NOT LIKE "%absentee%" AND UREPORT NOT LIKE "%0.5%D%"  AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%absent trigger%"
        AND UREPORT NOT LIKE "%Absent Radio%" AND UREPORT NOT LIKE "%Absent option%" AND UREPORT NOT LIKE "%Absent in%" AND UREPORT NOT LIKE "%Absent for%"
        AND UREPORT NOT LIKE "%ABSENT MAIL%" AND UREPORT NOT LIKE "%ABSENT(AFTERNOON)%" AND UREPORT NOT LIKE "%ABSENT record%"
        AND UREPORT NOT LIKE "%ABSENT%ON%DUTY%" AND UREPORT NOT LIKE "%morning Absent%" AND UREPORT NOT LIKE "%ABSENT: (half%") 
        AND (UREPORT LIKE "%went chennai%" OR UREPORT LIKE "off%" OR UREPORT LIKE "on leave%" OR UREPORT LIKE "%took leave%" OR UREPORT LIKE "%ABSENT%" OR UREPORT LIKE "%today%leave%" OR UREPORT LIKE "leave%"))'));
      	PREPARE INSERT_TEMP_ABSENT_STMT FROM @INSERT_TEMPABSENT;
        EXECUTE INSERT_TEMP_ABSENT_STMT;  
        SET @DELETE_TEMPABSENT=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT)'));
        PREPARE DELETE_TEMPABSENT_STMT FROM @DELETE_TEMPABSENT;
        EXECUTE DELETE_TEMPABSENT_STMT;
        
        SET @ABSMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @ABSMIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT'));
        PREPARE ABSMIN_ID_STMT FROM @ABSMINID;
        EXECUTE ABSMIN_ID_STMT;
        SET @ABSMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @ABSMAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT'));
        PREPARE ABSMAX_ID_STMT FROM @ABSMAXID;
        EXECUTE ABSMAX_ID_STMT;
        SET ABS_MIN_ID = @ABSMIN_ID;
        SET ABS_MAX_ID = @ABSMAX_ID;
        WHILE(ABS_MIN_ID <= ABS_MAX_ID)DO         
          SET @SELECT_ABSENT_USERSTAMP_TIMESTAMP=(SELECT CONCAT('SELECT USERSTAMP, `TIMESTAMP` INTO @RUSERSTAMP, @RTIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID));
        	PREPARE SELECT_ABSENT_USERSTAMP_TIMESTAMP_STMT FROM @SELECT_ABSENT_USERSTAMP_TIMESTAMP;
          EXECUTE SELECT_ABSENT_USERSTAMP_TIMESTAMP_STMT;
          SET ABS_USERSTAMP=@RUSERSTAMP;
          SET ABS_TIMESTAMP=@RTIMESTAMP;          
            -- FOR USERSTAMP AND TIMESTAMP
          IF (ABS_USERSTAMP IS NOT NULL OR ABS_TIMESTAMP IS NOT NULL) THEN
            SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REASON,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
            ((SELECT UREPORT FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,'),    
            (SELECT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
            (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,'),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0" AND CGN_ID=5),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
            (SELECT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_ABSENT RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',ABS_MIN_ID,'),
            (SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,')),
            (150.00),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,')),
            (SELECT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,'))'));      
          	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
            EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;      
            -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
          END IF;   
          IF (ABS_USERSTAMP IS NULL OR ABS_TIMESTAMP IS NULL) THEN
            SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REASON,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
            ((SELECT UREPORT FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,'),    
            (SELECT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
            (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,'),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="0" AND CGN_ID=5),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ABSENT"),
            (SELECT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_ABSENT RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',ABS_MIN_ID,'),
            (SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,')),
            (150.00),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,')),
            (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_ABSENT WHERE ID=',ABS_MIN_ID,'))'));      
          	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
            EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT; 
            -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
          END IF;
          SET ABS_MIN_ID = ABS_MIN_ID+1;
        END WHILE;
--         SET @DROP_TEMPABSENT=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.',TEMP_ABSENT));
--       	PREPARE DROP_TEMPABSENT_STMT FROM @DROP_TEMPABSENT;
--         EXECUTE DROP_TEMPABSENT_STMT;
        -- TEMP TABLE FOR ONDUTY          
          SET @DROP_TEMP_ONDUTY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_ONDUTY'));
      	  PREPARE DROP_DROP_TEMP_ONDUTY_STMT FROM @DROP_TEMP_ONDUTY;
          EXECUTE DROP_DROP_TEMP_ONDUTY_STMT;
          SET @CREATE_TEMP_ONDUTY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_ONDUTY(
          ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
          UID INT(11) NOT NULL ,
          UNAME VARCHAR(255) DEFAULT NULL,
          UDATE VARCHAR(255) DEFAULT NULL,
          UREPORT TEXT,
          USERSTAMP VARCHAR(255) DEFAULT NULL,
          TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
          PREPARE CREATE_TEMP_ONDUTY_STMT FROM @CREATE_TEMP_ONDUTY;
          EXECUTE CREATE_TEMP_ONDUTY_STMT;
          SET @INSERT_TEMPONDUTY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_ONDUTY(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UREPORT LIKE "%on-duty%" 
          OR UREPORT LIKE "%onduty%" OR UREPORT LIKE "%on duty%" OR UREPORT LIKE "%worked in new year%" 
          OR UREPORT LIKE "%on_duty%" OR  UREPORT LIKE "OD" OR  UREPORT LIKE "%We went%" OR  UREPORT LIKE "Worked in Christmas%")'));
          PREPARE INSERT_TEMP_ONDUTY_STMT FROM @INSERT_TEMPONDUTY;
          EXECUTE INSERT_TEMP_ONDUTY_STMT; 
          SET @DELETE_TEMPONDUTY=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY)'));
          PREPARE DELETE_TEMPONDUTY_STMT FROM @DELETE_TEMPONDUTY;
          EXECUTE DELETE_TEMPONDUTY_STMT; 
          
          SET @ONDUTYMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @ODMIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY'));
          PREPARE ONDUTYMIN_ID_STMT FROM @ONDUTYMINID;
          EXECUTE ONDUTYMIN_ID_STMT;
          SET @ONDUTYMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @ODMAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY'));
          PREPARE ONDUTYMAX_ID_STMT FROM @ONDUTYMAXID;
          EXECUTE ONDUTYMAX_ID_STMT;
          SET OD_MIN_ID = @ODMIN_ID;
          SET OD_MAX_ID = @ODMAX_ID;
          WHILE(OD_MIN_ID <= OD_MAX_ID)DO         
            SET @SELECT_ONDUTY_USERSTAMP_TIMESTAMP=(SELECT CONCAT('SELECT USERSTAMP, `TIMESTAMP` INTO @ODUSERSTAMP, @ODTIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID));
          	PREPARE SELECT_ONDUTY_USERSTAMP_TIMESTAMP_STMT FROM @SELECT_ONDUTY_USERSTAMP_TIMESTAMP;
            EXECUTE SELECT_ONDUTY_USERSTAMP_TIMESTAMP_STMT;
            SET OD_USERSTAMP=@ODUSERSTAMP;
            SET OD_TIMESTAMP=@ODTIMESTAMP;
            IF (OD_USERSTAMP IS NOT NULL OR OD_TIMESTAMP IS NOT NULL) THEN
              SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REASON,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
              ((SELECT UREPORT FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,'),    
              (SELECT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
              (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,'),
              (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="OD" AND CGN_ID=5),
              (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ONDUTY"),
              (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ONDUTY"),
              (SELECT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_ONDUTY RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',OD_MIN_ID,'),
              (SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,')),
              (150.00),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,')),
              (SELECT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,'))'));      
            	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
              EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;     
              -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
            END IF; 
            IF (OD_USERSTAMP IS NULL OR OD_TIMESTAMP IS NULL) THEN
              SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REASON,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
              ((SELECT UREPORT FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,'),    
              (SELECT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
              (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,'),
              (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="OD" AND CGN_ID=5),
              (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ONDUTY"),
              (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="ONDUTY"),
              (SELECT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_ONDUTY RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',OD_MIN_ID,'),
              (SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,')),
              (150.00),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,')),
              (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_ONDUTY WHERE ID=',OD_MIN_ID,'))'));      
            	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
              EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;   
              -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
            END IF; 
            SET OD_MIN_ID=OD_MIN_ID+1;
          END WHILE;
--         SET @DROP_TEMPONDUTY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.',TEMP_ONDUTY));
--       	PREPARE DROP_TEMPONDUTY_STMT FROM @DROP_TEMPONDUTY;
--         EXECUTE DROP_TEMPONDUTY_STMT;
        
        -- TEMP TABLE FOR HALF DAY LEAVE
        SET @DROP_TEMP_HALF_DAY_LEAVE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE'));
  	    PREPARE DROP_TEMP_HALF_DAY_LEAVE_STMT FROM @DROP_TEMP_HALF_DAY_LEAVE;
        EXECUTE DROP_TEMP_HALF_DAY_LEAVE_STMT;
        SET @CREATE_TEMP_HALF_DAY_LEAVE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE(
        ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
        UID INT(11) NOT NULL ,
        UNAME VARCHAR(255) DEFAULT NULL,
        UDATE VARCHAR(255) DEFAULT NULL,
        UREPORT TEXT,
        USERSTAMP VARCHAR(255) DEFAULT NULL,
        TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
        PREPARE CREATE_TEMP_ABSENT_STMT FROM @CREATE_TEMP_HALF_DAY_LEAVE;
        EXECUTE CREATE_TEMP_ABSENT_STMT;
        SET @INSERT_TEMPHALFDAYLEAVE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
        (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%HALF%day%" OR UREPORT LIKE "%half%day%absent%"
        OR UREPORT LIKE "morning%absent%"  OR UREPORT LIKE "%half%leave%"  OR UREPORT LIKE "%morning%leave%" OR UREPORT LIKE "%AFTERNOON%LEAVE%"
        OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "Came at  8.30am%" 
        OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%" OR UREPORT LIKE "%AFT%ABSENT%" OR UREPORT LIKE "Came office at 4%" OR UREPORT LIKE "Came office at 1%"
        OR UREPORT LIKE "1.came at 1.30%" OR UREPORT LIKE "1.Came at 11 am n%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%"
        OR UREPORT LIKE "1.Came office at 4.20%" OR UREPORT LIKE "come to office at 1%" OR UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%ABSENT%" OR UREPORT LIKE "%2 pm - to 4 pm%")
        AND UREPORT NOT LIKE "%after  half day%" AND UREPORT NOT LIKE "%half day but there%" AND UREPORT NOT LIKE "%half day%full day%")'));
        PREPARE INSERT_TEMP_HALF_DAY_LEAVE_STMT FROM @INSERT_TEMPHALFDAYLEAVE;
        EXECUTE INSERT_TEMP_HALF_DAY_LEAVE_STMT;  
        SET @DELETE_TEMPHALFDAYLEAVE=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE)'));
        PREPARE DELETE_TEMPHALFDAYLEAVE_STMT FROM @DELETE_TEMPHALFDAYLEAVE;
        EXECUTE DELETE_TEMPHALFDAYLEAVE_STMT;
          -- TABLE FOR MORNG LEAVE
          SET @DROP_TEMP_HALF_DAY_MORNG=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MORNG'));
    	    PREPARE DROP_TEMP_HALF_DAY_MORNG_STMT FROM @DROP_TEMP_HALF_DAY_MORNG;
          EXECUTE DROP_TEMP_HALF_DAY_MORNG_STMT; 
          SET @CREATE_TEMP_HALF_DAY_MORNG=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MORNG(
          ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
          UID INT(11) NOT NULL ,
          UNAME VARCHAR(255) DEFAULT NULL,
          UDATE VARCHAR(255) DEFAULT NULL,
          UREPORT TEXT,
          USERSTAMP VARCHAR(255) DEFAULT NULL,
          TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
          PREPARE CREATE_TEMP_ABSENT_STMT FROM @CREATE_TEMP_HALF_DAY_MORNG;
          EXECUTE CREATE_TEMP_ABSENT_STMT;
          SET @INSERT_TEMPHALFDAYMORNG=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MORNG(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "came at 1%PM%" OR UREPORT LIKE "%morn%" OR UREPORT LIKE "%2 pm - to 4 pm%" 
          OR UREPORT LIKE "CAME TO OFFICE BY 1:%" OR UREPORT LIKE "came to office by 12.30%" OR UREPORT LIKE "%Come to office at 1.%" OR UREPORT LIKE "%(half a day - AM)%"
          OR UREPORT LIKE "come to office at 1%" OR UREPORT LIKE "%OFFICE AT 1.15%" OR UREPORT LIKE "Came office at 1%" OR UREPORT LIKE "Came office at 4%"
          OR UREPORT LIKE "1.came at 1.30%" OR UREPORT LIKE "1.Came office at 4.20%" )AND UREPORT not LIKE "%ernoon%" AND UREPORT not LIKE "1.CAME TO OFFICE FOR MORNING%")'));
          PREPARE INSERT_TEMP_HALF_DAY_MORNG_STMT FROM @INSERT_TEMPHALFDAYMORNG;
          EXECUTE INSERT_TEMP_HALF_DAY_MORNG_STMT;  
          SET @INSERT_TEMPHALFDAYMORNG=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MORNG(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "%HALF%day%"  OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
          AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%"
          AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
          AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%"
          AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND TIME(TIMESTAMP)>"03:00:00")'));
          PREPARE INSERT_TEMP_HALF_DAY_MORNG_STMT FROM @INSERT_TEMPHALFDAYMORNG;
          EXECUTE INSERT_TEMP_HALF_DAY_MORNG_STMT;
          SET @INSERT_TEMPHALFDAYMORNG=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_MORNG(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "%HALF%day%"  OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
          AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%"
          AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
          AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%"
          AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND TIMESTAMP IS NULL)'));
          PREPARE INSERT_TEMP_HALF_DAY_MORNG_STMT FROM @INSERT_TEMPHALFDAYMORNG;
          EXECUTE INSERT_TEMP_HALF_DAY_MORNG_STMT;
          
          -- TABLE FOR AFTN LEAVE
          SET @DROP_TEMP_HALF_DAY_AFTN=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_AFTN'));
    	    PREPARE DROP_TEMP_HALF_DAY_AFTN_STMT FROM @DROP_TEMP_HALF_DAY_AFTN;
          EXECUTE DROP_TEMP_HALF_DAY_AFTN_STMT;
          SET @CREATE_TEMP_HALF_DAY_AFTN=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_AFTN(
          ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
          UID INT(11) NOT NULL ,
          UNAME VARCHAR(255) DEFAULT NULL,
          UDATE VARCHAR(255) DEFAULT NULL,
          UREPORT TEXT,
          USERSTAMP VARCHAR(255) DEFAULT NULL,
          TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
          PREPARE CREATE_TEMP_ABSENT_STMT FROM @CREATE_TEMP_HALF_DAY_AFTN;
          EXECUTE CREATE_TEMP_ABSENT_STMT;
          SET @INSERT_TEMPHALFDAYAFTN=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_AFTN(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "%AFTERN%" OR UREPORT LIKE "%leave%1%pm%" or UREPORT LIKE "Afternoon half day%" OR UREPORT LIKE "%AFTRN ABSENT%"
          OR UREPORT LIKE "Came at  8.30am%" OR UREPORT LIKE "%AN%session%" OR UREPORT LIKE "%After noon%" OR UREPORT LIKE "%Left at 1PM%" OR UREPORT LIKE "%LEFT%AT%1:30%" OR UREPORT LIKE "%day Absent(AN)%" 
          OR UREPORT LIKE "1.Came at 11 am%" OR UREPORT LIKE "1.Came to office at 11 %" OR UREPORT LIKE "1.CAME TO OFFICE FOR MORNING%" OR UREPORT LIKE "Went at%" OR UREPORT LIKE "Left office at%") AND UREPORT NOT LIKE "%(Morning)%")'));
          PREPARE INSERT_TEMP_HALF_DAY_AFTN_STMT FROM @INSERT_TEMPHALFDAYAFTN;
          EXECUTE INSERT_TEMP_HALF_DAY_AFTN_STMT;  
          SET @INSERT_TEMPHALFDAYAFTN=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_AFTN(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_HALF_DAY_LEAVE WHERE (UREPORT LIKE "%HALF%day%"  OR UREPORT LIKE "%HALF a leave%"  OR UREPORT LIKE "%ABSENT( NOT%") 
          AND UREPORT NOT LIKE "%morning%" AND UREPORT NOT LIKE "%(half a day - AM)%" AND UREPORT NOT LIKE "%After noon%"
          AND UREPORT NOT LIKE "%AFTERN%" AND UREPORT NOT LIKE "%Left at 1PM%" AND UREPORT NOT LIKE "%2 pm - to 4 pm%"
          AND UREPORT NOT LIKE "%AN%session%" AND UREPORT NOT LIKE "%day Absent(AN)%" AND UREPORT NOT LIKE "%LEFT%AT%1:30%"
          AND UREPORT NOT LIKE "%leave%from%1%" AND UREPORT NOT LIKE "%Come to office at 1.%" AND  TIME(timestamp)<"03:00:00")'));
          PREPARE INSERT_TEMP_HALF_DAY_AFTN_STMT FROM @INSERT_TEMPHALFDAYAFTN;
          EXECUTE INSERT_TEMP_HALF_DAY_AFTN_STMT;          
--           SET @DROP_TEMP_HALF_DAY_LEAVE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.',TEMP_HALF_DAY_LEAVE));
--       	  PREPARE DROP_TEMP_HALF_DAY_LEAVE_STMT FROM @DROP_TEMP_HALF_DAY_LEAVE;
--           EXECUTE DROP_TEMP_HALF_DAY_LEAVE_STMT;
          
          -- TEMP TABLE FOR PERMISSIONS
          SET @DROP_TEMP_PERMISSION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_PERMISSION'));
      	  PREPARE DROP_TEMP_PERMISSION_STMT FROM @DROP_TEMP_PERMISSION;
          EXECUTE DROP_TEMP_PERMISSION_STMT;
          SET @CREATE_TEMP_PERMISSION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_PERMISSION (
          ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
          UID INT(11) NOT NULL ,
          UNAME VARCHAR(255) DEFAULT NULL,
          UDATE VARCHAR(255) DEFAULT NULL,
          UREPORT TEXT,
          USERSTAMP VARCHAR(255) DEFAULT NULL,
          TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
          PREPARE CREATE_TEMP_PERMISSION_STMT FROM @CREATE_TEMP_PERMISSION;
          EXECUTE CREATE_TEMP_PERMISSION_STMT;
          SET @INSERT_TEMPPERMISSION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_PERMISSION(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP) 
          (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE (UREPORT LIKE "%PERMISSION%" OR UREPORT LIKE "%PERSMISSION%" 
          OR UREPORT LIKE "%HR PERMISSON%" OR UREPORT LIKE "Came at 12%" OR UREPORT LIKE "Came to office at 1%" OR UREPORT LIKE "come to office by 12%"
          OR UREPORT LIKE "went out at%" OR UREPORT LIKE "worked till 3.30 pm%" OR UREPORT LIKE "1.Came to office at 10.%" OR UREPORT LIKE "1.came at 12%o clock%"
          OR UREPORT LIKE "1.came at 11.%") AND UREPORT NOT LIKE "%Half day permission%" AND UREPORT NOT LIKE "%the permission%" AND UREPORT NOT LIKE "%provide permission%"
          AND UREPORT NOT LIKE "%Select permission%" AND UREPORT NOT LIKE "%GRANT%permission%" AND UREPORT NOT LIKE "%Revoke permissioin%" 
          AND UREPORT NOT LIKE "%Access permission%" AND UREPORT NOT LIKE "%view permission%" AND UREPORT NOT LIKE "%need permission%" 
          AND UREPORT NOT LIKE "%GIVE PERMISSION%" AND UREPORT NOT LIKE "%GIVEn PERMISSION%" AND UREPORT NOT LIKE "%employee permission%" 
          AND UREPORT NOT LIKE "%CHECKING PERMISSION%" AND UREPORT NOT LIKE "%edit PERMISSION%" AND UREPORT NOT LIKE "%permission cant%"
          AND UREPORT NOT LIKE "%an permission%" AND UREPORT NOT LIKE "%& permission%")'));
          PREPARE INSERT_TEMP_PERMISSION_STMT FROM @INSERT_TEMPPERMISSION;
          EXECUTE INSERT_TEMP_PERMISSION_STMT; 
          SET @DELETE_TEMPPERMISSION=(SELECT CONCAT('DELETE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT WHERE UID IN (SELECT UID FROM ',DESTINATIONSCHEMA,'.TEMP_PERMISSION)'));
          PREPARE DELETE_TEMPPERMISSION_STMT FROM @DELETE_TEMPPERMISSION;
          EXECUTE DELETE_TEMPPERMISSION_STMT;
          
        -- TEMP TABLE FOR REPORTS    
        SET @DROP_TEMP_REPORTS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_REPORTS'));
    	  PREPARE DROP_TEMP_REPORTS_STMT FROM @DROP_TEMP_REPORTS;
        EXECUTE DROP_TEMP_REPORTS_STMT;
        SET @CREATE_TEMP_REPORTS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_REPORTS(
        ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
        UID INT(11) NOT NULL ,
        UNAME VARCHAR(255) DEFAULT NULL,
        UDATE VARCHAR(255) DEFAULT NULL,
        UREPORT TEXT,
        USERSTAMP VARCHAR(255) DEFAULT NULL,
        TIMESTAMP VARCHAR(255) DEFAULT NULL)'));
        PREPARE CREATE_TEMP_REPORTS_STMT FROM @CREATE_TEMP_REPORTS;
        EXECUTE CREATE_TEMP_REPORTS_STMT;
        SET @INSERT_TEMP_REPORTS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_REPORTS(UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP)
        (SELECT UID,UNAME,UDATE,UREPORT,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS_SCDB_FORMAT)'));
      	PREPARE INSERT_TEMP_REPORTS_SCDB_FORMAT_STMT FROM @INSERT_TEMP_REPORTS;
        EXECUTE INSERT_TEMP_REPORTS_SCDB_FORMAT_STMT;
        SET @TRSFMINID = (SELECT CONCAT('SELECT MIN(ID) INTO @TRSFMIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS'));
        PREPARE TRSFMIN_ID_STMT FROM @TRSFMINID;
        EXECUTE TRSFMIN_ID_STMT;
        SET @TRSFMAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @TRSFMAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS'));
        PREPARE TRSFMAX_ID_STMT FROM @TRSFMAXID;
        EXECUTE TRSFMAX_ID_STMT;
        SET TRSF_MIN_ID = @TRSFMIN_ID;
        SET TRSF_MAX_ID = @TRSFMAX_ID;
        WHILE(TRSF_MIN_ID <= TRSF_MAX_ID)DO         
          SET @SELECT_TRSF_USERSTAMP_TIMESTAMP=(SELECT CONCAT('SELECT USERSTAMP, `TIMESTAMP` INTO @TRSFUSERSTAMP, @TRSFTIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID));
        	PREPARE SELECT_TRSF_USERSTAMP_TIMESTAMP_STMT FROM @SELECT_TRSF_USERSTAMP_TIMESTAMP;
          EXECUTE SELECT_TRSF_USERSTAMP_TIMESTAMP_STMT;
          SET TRSF_USERSTAMP=@TRSFUSERSTAMP;
          SET TRSF_TIMESTAMP=@TRSFTIMESTAMP;          
            -- FOR USERSTAMP AND TIMESTAMP
          IF (TRSF_USERSTAMP IS NOT NULL OR TRSF_TIMESTAMP IS NOT NULL) THEN
            SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
            ((SELECT UREPORT FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,'),    
            (SELECT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
            (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,'),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="1" AND CGN_ID=5),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
            (SELECT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_REPORTS RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',TRSF_MIN_ID,'),
            (SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,')),
            (150.00),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,')),
            (SELECT TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,'))'));      
          	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
            EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;      
            -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
          END IF;   
          IF (TRSF_USERSTAMP IS NULL OR TRSF_TIMESTAMP IS NULL) THEN
            SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS(UARD_REPORT,UARD_FULLDAY_PDID, UARD_DATE,UARD_ATTENDANCE,UARD_AM_SESSION,UARD_PM_SESSION, URC_ID, ULD_ID, UARD_BANDWIDTH, UARD_USERSTAMP_ID, UARD_TIMESTAMP) VALUES 
            ((SELECT UREPORT FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,'),    
            (SELECT PD_ID FROM ',DESTINATIONSCHEMA,'.PROJECT_DETAILS WHERE PD_PROJECT_NAME="EI"),
            (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,'),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="1" AND CGN_ID=5),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
            (SELECT AC_ID FROM ',DESTINATIONSCHEMA,'.ATTENDANCE_CONFIGURATION WHERE AC_DATA="PRESENT"),
            (SELECT RC.URC_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.ROLE_CREATION RC,',DESTINATIONSCHEMA,'.USER_ACCESS UA,',DESTINATIONSCHEMA,'.TEMP_REPORTS RSF WHERE ULD.ULD_LOGINID= RSF.UNAME AND ULD.ULD_ID = UA.ULD_ID AND UA.RC_ID = RC.RC_ID AND RSF.ID=',TRSF_MIN_ID,'),
            (SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,')),
            (150.00),(SELECT DISTINCT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT UNAME FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,')),
            (SELECT UDATE FROM ',DESTINATIONSCHEMA,'.TEMP_REPORTS WHERE ID=',TRSF_MIN_ID,'))'));      
          	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
            EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT; 
            -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
          END IF;
          SET TRSF_MIN_ID = TRSF_MIN_ID+1;
        END WHILE;
--         SET @DROP_TEMP_REPORT=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.',TEMP_REPORTS));
--   	    PREPARE DROP_TEMP_REPORT_STMT FROM @DROP_TEMP_REPORT;
--         EXECUTE DROP_TEMP_REPORT_STMT;

--         SET @DROP_TEMP_USER_ADMIN_REPORT_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.',TEMP_USER_ADMIN_REPORT_DETAILS));
--   	    PREPARE DROP_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @DROP_TEMP_USER_ADMIN_REPORT_DETAILS;
--         EXECUTE DROP_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;

        SET @INSERT_USERADMINREPORTDETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS (UARD_REPORT,UARD_REASON,UARD_DATE,URC_ID,ULD_ID,UARD_PERMISSION,UARD_ATTENDANCE,UARD_FULLDAY_PDID,UARD_AM_PDID,UARD_PM_PDID,UARD_AM_SESSION,UARD_PM_SESSION,UARD_BANDWIDTH,UARD_USERSTAMP_ID,UARD_TIMESTAMP)
        SELECT UARD_REPORT,UARD_REASON,UARD_DATE,URC_ID,ULD_ID,UARD_PERMISSION,UARD_ATTENDANCE,UARD_FULLDAY_PDID,UARD_AM_PDID,UARD_PM_PDID,UARD_AM_SESSION,UARD_PM_SESSION,UARD_BANDWIDTH,UARD_USERSTAMP_ID,UARD_TIMESTAMP
        FROM ',DESTINATIONSCHEMA,'.TEMP_USER_ADMIN_REPORT_DETAILS ORDER BY UARD_DATE'));      
      	PREPARE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT FROM @INSERT_USERADMINREPORTDETAILS;
        EXECUTE INSERT_TEMP_USER_ADMIN_REPORT_DETAILS_STMT;
        
        -- QUERY FOR ALTER AUTO_INCREMENT 
              SET @UARDMAXID = (SELECT CONCAT('SELECT MAX(UARD_ID) INTO @UARD_MAX_ID FROM ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS'));
              PREPARE UARD_MAX_ID_STMT FROM @UARDMAXID;
              EXECUTE UARD_MAX_ID_STMT;
              SET UARDMAX_ID=@UARD_MAX_ID;
              IF (UARDMAX_ID IS NOT NULL) THEN    
                SET @ALTER_USER_ADMIN_REPORT_DETAILS =(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.USER_ADMIN_REPORT_DETAILS AUTO_INCREMENT=',UARDMAX_ID));
                PREPARE ALTER_USER_ADMIN_REPORT_DETAILS_STMT FROM @ALTER_USER_ADMIN_REPORT_DETAILS;
                EXECUTE ALTER_USER_ADMIN_REPORT_DETAILS_STMT;
              END IF;
    SET FOREIGN_KEY_CHECKS=1;
  COMMIT;
END;
CALL SP_TS_MIG_REPORT_DETAILS_INSERT('SOURCE_RAJA','DEST_RAJA');
