DROP PROCEDURE IF EXISTS SP_TS_CHANGE_USERSTAMP_AS_ULDID;
CREATE PROCEDURE SP_TS_CHANGE_USERSTAMP_AS_ULDID(
IN USERSTAMP VARCHAR(50),
OUT ULDID INTEGER)
BEGIN
   SET ULDID = (SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID = USERSTAMP);
END;