DROP PROCEDURE IF EXISTS SP_TS_USER_ADMIN_REPORT_DETAILS_TICKLER_DATA;
CREATE PROCEDURE SP_TS_USER_ADMIN_REPORT_DETAILS_TICKLER_DATA(IN ULDID INTEGER,IN USERSTAMP VARCHAR(50),OUT TEMP_UARD_TICKLER_HISTORY TEXT)
BEGIN
	DECLARE UARD_TICKLER_HISTORY TEXT;
	DECLARE TEMP_TICKLER_HISTORY TEXT;
	DECLARE TEMP_TICKLERHISTORY TEXT;
	DECLARE USERSTAMP_ID INT;
	DECLARE TH_MINID INTEGER;
	DECLARE TH_MAXID INTEGER;
	DECLARE TEMP_TH_OLDVALUE TEXT;
	DECLARE TEMP_TH_NEWVALUE TEXT;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		IF (TEMP_TICKLER_HISTORY IS NOT NULL) THEN
			SET @DROP_TEMP_TICKLER_HISTORY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_TICKLER_HISTORY));
			PREPARE DROP_TEMP_TICKLER_HISTORY_STMT FROM @DROP_TEMP_TICKLER_HISTORY;
			EXECUTE DROP_TEMP_TICKLER_HISTORY_STMT;
		END IF;
	END;
	CALL SP_TS_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULD_ID);
	SET USERSTAMP_ID=@ULD_ID;
	SET UARD_TICKLER_HISTORY=(SELECT CONCAT('TEMP_UARD_TICKLER_HISTORY',SYSDATE()));
	SET UARD_TICKLER_HISTORY=(SELECT REPLACE(UARD_TICKLER_HISTORY,' ',''));
	SET UARD_TICKLER_HISTORY=(SELECT REPLACE(UARD_TICKLER_HISTORY,'-',''));
	SET UARD_TICKLER_HISTORY=(SELECT REPLACE(UARD_TICKLER_HISTORY,':',''));
	SET TEMP_UARD_TICKLER_HISTORY=(SELECT CONCAT(UARD_TICKLER_HISTORY,'_',USERSTAMP_ID));  
	SET @CREATE_TEMP_UARD_TICKLER_HISTORY=(SELECT CONCAT('CREATE TABLE ',TEMP_UARD_TICKLER_HISTORY,'(
	TH_ID INT NOT NULL,
	ULD_ID INT,
	ULD_LOGINID VARCHAR(50),
	EVENT_TYPE VARCHAR(10)NOT NULL,
	TABLE_NAME VARCHAR(70)NOT NULL,
	TH_OLD_VALUE TEXT NOT NULL,
	TH_NEW_VALUE TEXT,
	TH_USERSTAMP VARCHAR(50)NOT NULL,
	TH_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)'));
	PREPARE CREATE_TEMP_UARD_TICKLER_HISTORY_STMT FROM @CREATE_TEMP_UARD_TICKLER_HISTORY;
	EXECUTE CREATE_TEMP_UARD_TICKLER_HISTORY_STMT;
  	SET TEMP_TICKLERHISTORY=(SELECT CONCAT('TEMP_TICKLER_HISTORY',SYSDATE()));
	SET TEMP_TICKLERHISTORY=(SELECT REPLACE(TEMP_TICKLERHISTORY,' ',''));
	SET TEMP_TICKLERHISTORY=(SELECT REPLACE(TEMP_TICKLERHISTORY,'-',''));
	SET TEMP_TICKLERHISTORY=(SELECT REPLACE(TEMP_TICKLERHISTORY,':',''));
	SET TEMP_TICKLER_HISTORY=(SELECT CONCAT(TEMP_TICKLERHISTORY,'_',USERSTAMP_ID));
	SET @CREATE_TEMP_TICKLER_HISTORY=(SELECT CONCAT('CREATE TABLE ',TEMP_TICKLER_HISTORY,' (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TH_ID INT(11) NOT NULL,
	TP_ID INT(11) NOT NULL,
	ULD_ID INT(11) DEFAULT NULL,
	TTIP_ID INT(11) NOT NULL,
	TH_OLD_VALUE TEXT NOT NULL,
	TH_NEW_VALUE TEXT,
	TH_USERSTAMP_ID INT(2) NOT NULL,
	TH_TIMESTAMP TIMESTAMP NOT NULL)'));
	PREPARE CREATE_TEMP_TICKLER_HISTORY_STMT FROM @CREATE_TEMP_TICKLER_HISTORY;
	EXECUTE CREATE_TEMP_TICKLER_HISTORY_STMT;
	SET @INSERT_TEMP_TICKLER_HISTORY=(SELECT CONCAT('INSERT INTO ',TEMP_TICKLER_HISTORY,' 
	(TH_ID,TP_ID,ULD_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,TH_USERSTAMP_ID,TH_TIMESTAMP)(SELECT * FROM TICKLER_HISTORY WHERE  ULD_ID=',ULDID,')'));
	PREPARE INSERT_TEMP_TICKLER_HISTORY_STMT FROM @INSERT_TEMP_TICKLER_HISTORY;
	EXECUTE INSERT_TEMP_TICKLER_HISTORY_STMT;
	SET @THMINID=(SELECT CONCAT('SELECT MIN(ID) INTO @MINID FROM ',TEMP_TICKLER_HISTORY));
	PREPARE THMINID_STMT FROM @THMINID;
	EXECUTE THMINID_STMT;
	SET @THMAXID=(SELECT CONCAT('SELECT MAX(ID) INTO @MAXID FROM ',TEMP_TICKLER_HISTORY));
	PREPARE THMAXID_STMT FROM @THMAXID;
	EXECUTE THMAXID_STMT;
	SET TH_MINID=@MINID;
	SET TH_MAXID=@MAXID;
	WHILE(TH_MINID<=TH_MAXID)DO  
		SET @SELECT_TICKLER_VALUES=(SELECT CONCAT('SELECT TH_ID,ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,TH_USERSTAMP_ID,TH_TIMESTAMP 
		INTO @THID,@ULDID,@TPID,@TTIPID,@TH_OLDVALUE,@TH_NEWVALUE,@THUSERSTAMP,@THTIMESTAMP FROM ',TEMP_TICKLER_HISTORY,' WHERE ID=',TH_MINID));
		PREPARE SELECT_TICKLER_VALUES_STMT FROM @SELECT_TICKLER_VALUES;
		EXECUTE SELECT_TICKLER_VALUES_STMT;
		SET TEMP_TH_OLDVALUE=@TH_OLDVALUE;
		SET TEMP_TH_NEWVALUE=@TH_NEWVALUE;
		IF (@TTIPID=2) THEN
		SET @COUNT=1;
			IF (@TH_OLDVALUE IS NOT NULL) THEN
				UARD_OLD_LOOP : LOOP
					SET @VALUE=NULL;
					SET @REMAINING_STRING=NULL;
					SET @COLUMN_NAME=NULL;
					SET @COLUMN_VALUE=NULL;
					CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',',@TH_OLDVALUE,@VALUE,@REMAINING_STRING);
					SELECT @REMAINING_STRING INTO @TH_OLDVALUE;
					CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=',@VALUE,@COLUMN_NAME,@COLUMN_VALUE);
					IF (@VALUE REGEXP '^[0-9]') THEN
						SET @PROJECTFLAG=5;
						IF (@COLUMN_NAME REGEXP '^[0-9]' AND @COLUMN_VALUE IS NULL) THEN              
							SELECT PD.PD_PROJECT_NAME ,PS.PS_REC_VER INTO @PROJECTNAME,@RECVER  FROM PROJECT_DETAILS PD,PROJECT_STATUS PS WHERE PS.PD_ID=PD.PD_ID AND PS.PS_ID=@COLUMN_NAME;
							SET @REPLACE_STRING=(SELECT CONCAT(',',@PROJECTNAME,'-', @RECVER));
							SET @VALUE=(SELECT CONCAT(',',@VALUE));
							SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
							SET @PROJECTNAME=NULL;
						END IF;
					END IF;
					IF(@COLUMN_VALUE='<NULL>' OR @COLUMN_VALUE='')THEN
						SET @URCDATA='<NULL>';
						SET @LOGINID='<NULL>';
						SET @PERMISSION='<NULL>';
						SET @ATTENDANCE='<NULL>';
						SET @PROJECTNAME='<NULL>';
						SET @AMSESSION='<NULL>';
						SET @AMSESSION='<NULL>';
						SET @USERID='<NULL>';
					END IF;
					IF (UPPER(@COLUMN_NAME)='URC_ID') THEN
						SELECT URC_DATA INTO @URCDATA FROM USER_RIGHTS_CONFIGURATION WHERE URC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('URC_DATA=',@URCDATA);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='ULD_ID') THEN
						SELECT ULD_LOGINID INTO @LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('ULD_LOGINID=',@LOGINID);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_PERMISSION') THEN
						SELECT AC_DATA INTO @PERMISSION FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_PERMISSION=',@PERMISSION);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_ATTENDANCE') THEN
						SELECT AC_DATA INTO @ATTENDANCE FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_ATTENDANCE=',@ATTENDANCE);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_PSID') THEN
						IF @COLUMN_VALUE!='<NULL>' THEN
						SELECT PD.PD_PROJECT_NAME ,PS.PS_REC_VER INTO @PROJECTNAME,@RECVER  FROM PROJECT_DETAILS PD,PROJECT_STATUS PS WHERE PS.PD_ID=PD.PD_ID AND PS.PS_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('PD_PROJECT_NAME=',@PROJECTNAME,'-',@RECVER);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
						END IF;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_AM_SESSION') THEN
						SELECT AC_DATA INTO @AMSESSION FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_AM_SESSION=',@AMSESSION);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_PM_SESSION') THEN
						SELECT AC_DATA INTO @PMSESSION FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_PM_SESSION=',@PMSESSION);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='CIORL_ID') THEN
						SELECT CIORL_LOCATION INTO @LOCATION FROM CLOCK_IN_OUT_REPORT_LOCATION WHERE CIORL_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('CIORL_LOCATION=',@LOCATION);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_USERSTAMP_ID') THEN
						SELECT ULD_LOGINID INTO @USERID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('ULD_LOGINID=',@USERID);
						SELECT REPLACE(TEMP_TH_OLDVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_OLDVALUE;
						LEAVE UARD_OLD_LOOP;
					END IF;
					IF @TH_OLDVALUE IS NULL THEN
						LEAVE UARD_OLD_LOOP;
					END IF;
						SET @COUNT=	 @COUNT+1;
				END LOOP; 
			END IF;
			IF (@TH_NEWVALUE IS NOT NULL) THEN
				UARD_NEW_LOOP : LOOP
					SET @VALUE=NULL;
					SET @REMAINING_STRING=NULL;
					SET @COLUMN_NAME=NULL;
					SET @COLUMN_VALUE=NULL;
					CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',',@TH_NEWVALUE,@VALUE,@REMAINING_STRING);
					SELECT @REMAINING_STRING INTO @TH_NEWVALUE;          
					CALL SP_TS_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=',@VALUE,@COLUMN_NAME,@COLUMN_VALUE);
					IF (@VALUE REGEXP '^[0-9]') THEN
						IF (@COLUMN_NAME REGEXP '^[0-9]' AND @COLUMN_VALUE IS NULL) THEN              
						SELECT PD.PD_PROJECT_NAME ,PS.PS_REC_VER INTO @PROJECTNAME,@RECVER  FROM PROJECT_DETAILS PD,PROJECT_STATUS PS WHERE PS.PD_ID=PD.PD_ID AND PS.PS_ID=@COLUMN_NAME;
							SET @REPLACE_STRING=(SELECT CONCAT(',',@PROJECTNAME,'-',@RECVER));
							SET @VALUE=(SELECT CONCAT(',',@VALUE));
							SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
							SET @PROJECTNAME=NULL;
						END IF;
					END IF;
					IF(@COLUMN_VALUE='<NULL>' OR @COLUMN_VALUE='')THEN
						SET @URCDATA='<NULL>';
						SET @LOGINID='<NULL>';
						SET @PERMISSION='<NULL>';
						SET @ATTENDANCE='<NULL>';
						SET @PROJECTNAME='<NULL>';
						SET @AMSESSION='<NULL>';
						SET @AMSESSION='<NULL>';
						SET @USERID='<NULL>';
					END IF;
					IF (UPPER(@COLUMN_NAME)='URC_ID') THEN
						SELECT URC_DATA INTO @URCDATA FROM USER_RIGHTS_CONFIGURATION WHERE URC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('URC_DATA=',@URCDATA);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='ULD_ID') THEN
						SELECT ULD_LOGINID INTO @LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('ULD_LOGINID=',@LOGINID);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_PERMISSION') THEN
						SELECT AC_DATA INTO @PERMISSION FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_PERMISSION=',@PERMISSION);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_ATTENDANCE') THEN
						SELECT AC_DATA INTO @ATTENDANCE FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_ATTENDANCE=',@ATTENDANCE);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_PSID') THEN
						IF @COLUMN_VALUE!='<NULL>' THEN

						SELECT PD.PD_PROJECT_NAME ,PS.PS_REC_VER INTO @PROJECTNAME,@RECVER  FROM PROJECT_DETAILS PD,PROJECT_STATUS PS WHERE PS.PD_ID=PD.PD_ID AND PS.PS_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('PD_PROJECT_NAME=',@PROJECTNAME,'-',@RECVER);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
						END IF;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_AM_SESSION') THEN
						SELECT AC_DATA INTO @AMSESSION FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_AM_SESSION=',@AMSESSION);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_PM_SESSION') THEN
						SELECT AC_DATA INTO @PMSESSION FROM ATTENDANCE_CONFIGURATION WHERE AC_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('UARD_PM_SESSION=',@PMSESSION);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='CIORL_ID') THEN
						SELECT CIORL_LOCATION INTO @LOCATION FROM CLOCK_IN_OUT_REPORT_LOCATION WHERE CIORL_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('CIORL_LOCATION=',@LOCATION);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
					END IF;
					IF (UPPER(@COLUMN_NAME)='UARD_USERSTAMP_ID') THEN
						SELECT ULD_LOGINID INTO @USERID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@COLUMN_VALUE;
						SET @REPLACE_STRING=CONCAT('ULD_LOGINID=',@USERID);
						SELECT REPLACE(TEMP_TH_NEWVALUE,@VALUE,@REPLACE_STRING) INTO TEMP_TH_NEWVALUE;
						LEAVE UARD_NEW_LOOP;
					END IF;
					IF @TH_NEWVALUE IS NULL THEN
						LEAVE UARD_NEW_LOOP;
					END IF;
				END LOOP;  
			END IF;
		END IF;    
		IF(@TPID=1)THEN
			SET @INSERT_TEMP_UARD_TICKLER_HISTORY=(SELECT CONCAT('INSERT INTO ',TEMP_UARD_TICKLER_HISTORY,' VALUES (@THID,@ULDID,(SELECT ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@ULDID),
			(SELECT TP_TYPE FROM TICKLER_PROFILE WHERE TP_ID=@TPID),(SELECT TTIP_DATA FROM TICKLER_TABID_PROFILE WHERE TTIP_ID=@TTIPID),','"',TEMP_TH_OLDVALUE,'"',',','"',TEMP_TH_NEWVALUE,'"',',(SELECT ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@THUSERSTAMP),@THTIMESTAMP)'));
			PREPARE INSERT_TEMP_UARD_TICKLER_HISTORY_STMT FROM @INSERT_TEMP_UARD_TICKLER_HISTORY;
			EXECUTE INSERT_TEMP_UARD_TICKLER_HISTORY_STMT;
		END IF;
		IF(@TPID=2)THEN
			SET @INSERT_TEMP_UARD_TICKLER_HISTORY=(SELECT CONCAT('INSERT INTO ',TEMP_UARD_TICKLER_HISTORY,'(TH_ID,ULD_ID,ULD_LOGINID,EVENT_TYPE,TABLE_NAME,TH_OLD_VALUE,TH_USERSTAMP,TH_TIMESTAMP) VALUES (@THID,@ULDID,(SELECT ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@ULDID),
			(SELECT TP_TYPE FROM TICKLER_PROFILE WHERE TP_ID=@TPID),(SELECT TTIP_DATA FROM TICKLER_TABID_PROFILE WHERE TTIP_ID=@TTIPID),','"',TEMP_TH_OLDVALUE,'"',',(SELECT ULD_LOGINID FROM USER_LOGIN_DETAILS WHERE ULD_ID=@THUSERSTAMP),@THTIMESTAMP)'));
			PREPARE INSERT_TEMP_UARD_TICKLER_HISTORY_STMT FROM @INSERT_TEMP_UARD_TICKLER_HISTORY;
			EXECUTE INSERT_TEMP_UARD_TICKLER_HISTORY_STMT;
		END IF;
		SET TH_MINID=TH_MINID + 1;
	END WHILE;
	SET @DROP_TEMP_TICKLER_HISTORY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_TICKLER_HISTORY));
	PREPARE DROP_TEMP_TICKLER_HISTORY_STMT FROM @DROP_TEMP_TICKLER_HISTORY;
	EXECUTE DROP_TEMP_TICKLER_HISTORY_STMT;
	COMMIT;
END;
call SP_TS_USER_ADMIN_REPORT_DETAILS_TICKLER_DATA(44, 'raja.gunasekaran@ssomens.com', @TEMP_UARD_TICKLER_HISTORY)
