-- CHEQUE

-- ALL THE VALUES ARE MATCHED IN CHEQUE_ENTRY_DETAILS

SELECT*FROM CHEQUE_ENTRY_DETAILS;

SELECT*FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.*
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_AMOUNT=CED.CHEQUE_AMOUNT;

-- 

SELECT DISTINCT CHEQUE_DATE FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_DATE FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_DATE,CED.CHEQUE_DATE 
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_DATE=CED.CHEQUE_DATE;

-- 

SELECT DISTINCT CHEQUE_AMOUNT FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_AMOUNT FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_AMOUNT,CED.CHEQUE_AMOUNT 
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_AMOUNT=CED.CHEQUE_AMOUNT;

--

SELECT DISTINCT CHEQUE_NO FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_NO FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_NO,CED.CHEQUE_NO
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_NO=CED.CHEQUE_NO;

--

SELECT DISTINCT CHEQUE_TO FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_TO FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_TO,CED.CHEQUE_TO
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_TO=CED.CHEQUE_TO ;

--

SELECT DISTINCT CHEQUE_FOR FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_FOR FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_FOR,CED.CHEQUE_FOR
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_FOR=CED.CHEQUE_FOR;

--

SELECT DISTINCT CHEQUE_UNIT_NO FROM CHEQUE_ENTRY_DETAILS WHERE CHEQUE_UNIT_NO IS NOT NULL;

SELECT DISTINCT CHEQUE_UNIT_NO FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS  WHERE CHEQUE_UNIT_NO IS NOT NULL;

SELECT DISTINCT MCED.CHEQUE_UNIT_NO,CED.CHEQUE_UNIT_NO
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_UNIT_NO=CED.CHEQUE_UNIT_NO;

--

SELECT DISTINCT CHEQUE_TIMESTAMP FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_TIMESTAMP FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_TIMESTAMP ,CED.CHEQUE_TIMESTAMP
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_TIMESTAMP=CED.CHEQUE_TIMESTAMP;

--

SELECT CED.BCN_ID , BC.BCN_ID
FROM CHEQUE_ENTRY_DETAILS CED
INNER JOIN BANKTT_CONFIGURATION BC ON CED.BCN_ID = BC.BCN_ID;

SELECT MCED.CS_ID,MCSD.CS_DATA,BC.BCN_DATA,CED.BCN_ID 
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED
INNER JOIN SOURCE_28062014.MIG_CHEQUE_STATUS_DETAILS MCSD ON MCED.CS_ID=MCSD.CS_ID
INNER JOIN BANKTT_CONFIGURATION BC ON MCSD.CS_DATA=BC.BCN_DATA
INNER JOIN CHEQUE_ENTRY_DETAILS CED ON BC.BCN_ID = CED.BCN_ID GROUP BY MCED.CHEQUE_SNO;

--

SELECT DISTINCT CHEQUE_DEBITED_RETURNED_DATE FROM CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT CHEQUE_DEBITED_RETURNED_DATE FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS;

SELECT DISTINCT MCED.CHEQUE_DEBITED_RETURNED_DATE ,CED.CHEQUE_DEBITED_RETURNED_DATE
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_DEBITED_RETURNED_DATE=CED.CHEQUE_DEBITED_RETURNED_DATE;

--

SELECT DISTINCT CHEQUE_COMMENTS FROM CHEQUE_ENTRY_DETAILS WHERE CHEQUE_COMMENTS IS NOT NULL;

SELECT DISTINCT CHEQUE_COMMENTS FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS WHERE CHEQUE_COMMENTS IS NOT NULL;

SELECT DISTINCT MCED.CHEQUE_COMMENTS ,CED.CHEQUE_COMMENTS
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS MCED, CHEQUE_ENTRY_DETAILS CED 
WHERE MCED.CHEQUE_COMMENTS=CED.CHEQUE_COMMENTS;

--

SELECT DISTINCT ULD_ID FROM CHEQUE_ENTRY_DETAILS ORDER BY CHEQUE_NO;

SELECT DISTINCT CHEQUE_USERSTAMP FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS WHERE CHEQUE_NO;

SELECT DISTINCT A.CHEQUE_USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_28062014.MIG_CHEQUE_ENTRY_DETAILS A
INNER JOIN USER_LOGIN_DETAILS B ON A.CHEQUE_USERSTAMP= B.ULD_LOGINID
INNER JOIN CHEQUE_ENTRY_DETAILS C ON B.ULD_ID=C.ULD_ID;

-- SELECT * COUNT(CHEQUE_NO) CNT FROM CHEQUE_ENTRY_DETAILS GROUP BY SOUNDEX(CHEQUE_NO) HAVING COUNT(SOUNDEX(CHEQUE_NO)) > 1;

SELECT *  
FROM CHEQUE_ENTRY_DETAILS  
GROUP BY CHEQUE_NO  
HAVING COUNT(CHEQUE_NO) >1;

SELECT * FROM CHEQUE_ENTRY_DETAILS WHERE CHEQUE_NO=957526;

SELECT * FROM CHEQUE_ENTRY_DETAILS WHERE CHEQUE_NO=957552;

-- ALL THE VALUE ARE MATCHED
-- CHEQUE_CONFIGURATION

SELECT* FROM CHEQUE_CONFIGURATION;

SELECT *FROM CONFIGURATION;

SELECT DISTINCT CGN_ID FROM CHEQUE_CONFIGURATION;

SELECT * FROM SOURCE_28062014.CONFIG_SQL_FORMAT WHERE CGN_ID=57 AND DATA IS NOT NULL;
