-- CONFIGURATION_PROFILE

SELECT*FROM SOURCE_12072014.CONFIG_SQL_FORMAT;

SELECT *FROM SOURCE_12072014.CONFIG_SCDB_FORMAT;

SELECT CNP_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE CNP_DATA IS NOT NULL;

SELECT * FROM CONFIGURATION_PROFILE;

-- CONFIGURATION

SELECT DISTINCT CGN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE CGN_DATA IS NOT NULL;

SELECT DISTINCT CF_TYPE FROM SOURCE_12072014.CONFIG_SCDB_FORMAT WHERE CF_TYPE IS NOT NULL;

SELECT DISTINCT CGN_DATA,CNP_ID,CGN_NON_IP_FLAG
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL ,SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB
WHERE CSQL.CGN_DATA IS NOT NULL AND CSQL.CGN_DATA = TCSCDB.CF_TYPE ;

--

SELECT DISTINCT CGN_DATA,CNP_ID,CGN_NON_IP_FLAG
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.CGN_DATA = TCSCDB.CF_TYPE 
WHERE CSQL.CGN_DATA IS NOT NULL;

SELECT * FROM CONFIGURATION;

--

SELECT DISTINCT CGN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE CGN_DATA IS NOT NULL;

SELECT DISTINCT CGN_TYPE FROM CONFIGURATION WHERE CGN_TYPE IS NOT NULL;

SELECT DISTINCT(CSQL.CGN_DATA),D.CGN_TYPE 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.CGN_DATA = TCSCDB.CF_TYPE, CONFIGURATION D
WHERE CSQL.CGN_DATA IS NOT NULL AND D.CGN_TYPE=CSQL.CGN_DATA;

-- CUSTOMER_CONFIGURATION

SELECT DISTINCT(DATA)
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76,81);

SELECT * FROM CUSTOMER_CONFIGURATION;

--

SELECT DISTINCT DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT
WHERE DATA IS NOT NULL AND CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76,81);

SELECT DISTINCT CCN_DATA FROM CUSTOMER_CONFIGURATION WHERE CCN_DATA IS NOT NULL;

SELECT DISTINCT(CSQL.DATA),D.CCN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA, CUSTOMER_CONFIGURATION D
WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76,81)AND CSQL.DATA=D.CCN_DATA;

-- TIME STAMP IS GET FROM CONF SCDB AND DATA IS UPDATED IN CONF SCDB

SELECT TCSCDB.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA 
WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76,81) AND TCSCDB.TIMESTAMP IS NOT NULL;

SELECT ADDTIME(CCN_TIMESTAMP,'8:00')FROM CUSTOMER_CONFIGURATION;

-- USERSTAMP IS GET FROM CONF SCDB AND DATA IS UPDATED IN CONF SCDB

SELECT DISTINCT USER_STAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT
WHERE DATA IS NOT NULL AND CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76,81);

SELECT DISTINCT ULD_ID FROM CUSTOMER_CONFIGURATION WHERE CCN_DATA IS NOT NULL;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID 
INNER JOIN CUSTOMER_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- UNIT_CONFIGURATION

SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,CSQL.TIMESTAMP,ULD.ULD_ID
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,USER_LOGIN_DETAILS ULD
WHERE  CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=32 AND CSQL.USER_STAMP=ULD.ULD_LOGINID;

SELECT * FROM UNIT_CONFIGURATION;

--

SELECT DISTINCT DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT 
WHERE DATA IS NOT NULL AND CGN_ID=32;

SELECT  UCN_DATA FROM UNIT_CONFIGURATION ;

SELECT CSQL.DATA,D.UCN_DATA 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,UNIT_CONFIGURATION D 
WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=32 AND D.UCN_DATA=CSQL.DATA;

-- 

SELECT TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT 
WHERE DATA IS NOT NULL AND CGN_ID=32;

SELECT UCN_TIMESTAMP FROM UNIT_CONFIGURATION;

SELECT CSF.TIMESTAMP,UC.UCN_TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSF
INNER JOIN UNIT_CONFIGURATION UC ON CSF.TIMESTAMP=UC.UCN_TIMESTAMP
WHERE CSF.DATA IS NOT NULL AND CSF.CGN_ID=32 GROUP BY DATA;

--

SELECT DISTINCT USER_STAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT
WHERE DATA IS NOT NULL AND CGN_ID=32 GROUP BY DATA;

SELECT DISTINCT ULD_ID FROM UNIT_CONFIGURATION WHERE UCN_DATA IS NOT NULL;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_12072014.CONFIG_SQL_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID
INNER JOIN UNIT_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- PAYMENT_CONFIGURATION

SELECT DISTINCT(DATA),CGN_ID,INITIALIZE_FLAG,USER_STAMP,TIMESTAMP
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL  
WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (28,49,58);

SELECT * FROM PAYMENT_CONFIGURATION;

--

SELECT DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE DATA IS NOT NULL AND CGN_ID IN (28,49,58);

SELECT PCN_DATA FROM PAYMENT_CONFIGURATION;

SELECT CSQL.DATA,D.PCN_DATA
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,PAYMENT_CONFIGURATION D 
WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN (28,49,58) AND D.PCN_DATA=CSQL.DATA;

--

SELECT ADDTIME(PCN_TIMESTAMP,'8:00')FROM PAYMENT_CONFIGURATION;

--

SELECT DISTINCT USER_STAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT
WHERE DATA IS NOT NULL AND CGN_ID IN (28,49,58) GROUP BY DATA;

SELECT DISTINCT ULD_ID FROM PAYMENT_CONFIGURATION WHERE PCN_DATA IS NOT NULL;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID
INNER JOIN PAYMENT_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- ACCESS_CONFIGURATION

SELECT DISTINCT(CSQL.DATA),CSQL.CGN_ID,CSQL.INITIALIZE_FLAG,USERSTAMP,TCSCDB.TIMESTAMP 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA ,USER_LOGIN_DETAILS ULD 
WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (16,17) AND ULD.ULD_LOGINID=TCSCDB.USERSTAMP ORDER BY CGN_ID;

SELECT * FROM ACCESS_CONFIGURATION;

SELECT CSQL.DATA,D.ACN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,ACCESS_CONFIGURATION D
WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN (16,17) AND D.ACN_DATA=CSQL.DATA;

SELECT ADDTIME(ACN_TIMESTAMP,'8:00')FROM ACCESS_CONFIGURATION;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_12072014.CONFIG_SQL_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID 
INNER JOIN ACCESS_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- OCBC_CONFIGURATION

SELECT DISTINCT(CSQL.DATA),CSQL.CGN_ID,CSQL.INITIALIZE_FLAG,USERSTAMP,TCSCDB.TIMESTAMP 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA , USER_LOGIN_DETAILS ULD 
WHERE CSQL.DATA IS NOT NULL AND CGN_ID=29 AND ULD.ULD_LOGINID=TCSCDB.USERSTAMP;

SELECT * FROM OCBC_CONFIGURATION;

SELECT CSQL.DATA,D.OCN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,OCBC_CONFIGURATION D
WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=29 AND D.OCN_DATA=CSQL.DATA;

SELECT ADDTIME(OCN_TIMESTAMP,'8:00')FROM OCBC_CONFIGURATION;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_12072014.CONFIG_SQL_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID
INNER JOIN OCBC_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- EXPENSE_CONFIGURATION

SELECT DISTINCT(DATA),CGN_ID,INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP
FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL 
LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA 
WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN(18,19,27,20,26,21,22,23,24,25) AND DATA!="MIGRATED";

SELECT * FROM EXPENSE_CONFIGURATION WHERE CGN_ID IN(18,19,27,20,26,21,22,23,24,25) AND ECN_DATA!="MIGRATED";

SELECT DATA,CGN_ID,INITIALIZE_FLAG,USER_STAMP,TIMESTAMP 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT 
WHERE DATA IS NOT NULL AND CGN_ID IN(34,35,36,37,38,40,20,41,51,52) AND (DATA!="COMMON" AND DATA!="CUSTOMER" AND DATA!="GENERAL");

SELECT * FROM EXPENSE_CONFIGURATION 
WHERE CGN_ID IN(34,35,36,37,38,40,20,41,51,52) AND (ECN_DATA!="COMMON" AND ECN_DATA!="CUSTOMER" AND ECN_DATA!="GENERAL");

SELECT ADDTIME(ECN_TIMESTAMP,'8:00')FROM EXPENSE_CONFIGURATION;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_12072014.CONFIG_SQL_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID 
INNER JOIN EXPENSE_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- DEPOSIT_DEDUCTION_CONFIGURATION
SELECT CGN_ID,DATA,SUB_DATA,INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL  LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN(30,42);
SELECT * FROM DEPOSIT_DEDUCTION_CONFIGURATION;
SELECT CSQL.DATA,D.DDC_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,DEPOSIT_DEDUCTION_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN(30,42) AND D.DDC_DATA=CSQL.DATA;
SELECT ADDTIME(DDC_TIMESTAMP,'8:00')FROM DEPOSIT_DEDUCTION_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN DEPOSIT_DEDUCTION_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- ERROR_MESSAGE_CONFIGURATION
SELECT CSQL.CNP_ID,CSQL.EMC_CODE,CSQL.EMC_DATA,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.EMC_DATA = TCSCDB.CF_DATA WHERE CSQL.EMC_DATA IS NOT NULL;
SELECT * FROM ERROR_MESSAGE_CONFIGURATION;
SELECT ADDTIME(EMC_TIMESTAMP,'8:00')FROM ERROR_MESSAGE_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN ERROR_MESSAGE_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;
-- TRIGGER_CONFIGURATION
SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,TCSCDB.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL  LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA ,USER_LOGIN_DETAILS ULD WHERE CSQL.CGN_ID IN(31,74) AND CSQL.DATA IS NOT NULL AND ULD.ULD_LOGINID = CSQL.USER_STAMP;
SELECT * FROM TRIGGER_CONFIGURATION;
SELECT CSQL.DATA,D.TC_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,TRIGGER_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN(31,74) AND D.TC_DATA=CSQL.DATA;
SELECT ADDTIME(TC_TIMESTAMP,'8:00')FROM TRIGGER_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN TRIGGER_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;


-- NATIONALITY_CONFIGURATION
SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL  LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.CGN_ID=15 AND CSQL.DATA IS NOT NULL;
SELECT * FROM NATIONALITY_CONFIGURATION;
SELECT ADDTIME(NC_TIMESTAMP,'8:00')FROM NATIONALITY_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN NATIONALITY_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- USER_RIGHTS_CONFIGURATION
SELECT CGN_ID,CSQL.DATA,INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL  LEFT JOIN SOURCE_12072014.CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.CGN_ID IN (43,66,67,68) AND CSQL.DATA IS NOT NULL;
SELECT * FROM USER_RIGHTS_CONFIGURATION;
SELECT CSQL.DATA,D.URC_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,USER_RIGHTS_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN (43,66,67,68) AND D.URC_DATA=CSQL.DATA;
SELECT ADDTIME(URC_TIMESTAMP,'8:00')FROM USER_RIGHTS_CONFIGURATION;
SELECT DISTINCT(A.USER_STAMP),C.URC_USERSTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT A,USER_RIGHTS_CONFIGURATION C WHERE A.USER_STAMP=C.URC_USERSTAMP AND A.CGN_ID IN (43,66,67,68) AND A.DATA IS NOT NULL;

-- ERM_CONFIGURATION
SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL, USER_LOGIN_DETAILS ULD WHERE CSQL.CGN_ID=55 AND CSQL.DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP;
SELECT * FROM ERM_CONFIGURATION;
SELECT CSQL.DATA,D.ERMCN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,ERM_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=55 AND D.ERMCN_DATA=CSQL.DATA;
SELECT ADDTIME(ERMCN_TIMESTAMP,'8:00')FROM ERM_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN ERM_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- BANKTT_CONFIGURATION
SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL, USER_LOGIN_DETAILS ULD WHERE CSQL.CGN_ID IN (56,69,70,71,72) AND CSQL.DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP;
SELECT * FROM BANKTT_CONFIGURATION;
SELECT CSQL.DATA,D.BCN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,BANKTT_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN (56,69,70,71,72) AND D.BCN_DATA=CSQL.DATA;
SELECT ADDTIME(BCN_TIMESTAMP,'8:00')FROM BANKTT_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN BANKTT_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;


-- CHEQUE_CONFIGURATION
SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL, USER_LOGIN_DETAILS ULD WHERE CSQL.CGN_ID=57 AND CSQL.DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP;
SELECT * FROM CHEQUE_CONFIGURATION;
SELECT CSQL.DATA,D.CQCN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,CHEQUE_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=57 AND D.CQCN_DATA=CSQL.DATA;
SELECT ADDTIME(CQCN_TIMESTAMP,'8:00')FROM CHEQUE_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN CHEQUE_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- REPORT_CONFIGURATION
SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL, USER_LOGIN_DETAILS ULD WHERE CSQL.CGN_ID IN (59,60,61,62,63,64,65,73,48) AND CSQL.DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP;
SELECT * FROM REPORT_CONFIGURATION;
SELECT CSQL.DATA,D.RCN_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,REPORT_CONFIGURATION D WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID IN (59,60,61,62,63,64,65,73,48) AND D.RCN_DATA=CSQL.DATA;
SELECT ADDTIME(RCN_TIMESTAMP,'8:00')FROM REPORT_CONFIGURATION;
SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_12072014.CONFIG_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID INNER JOIN REPORT_CONFIGURATION C ON B.ULD_ID=C.ULD_ID;

-- CUSTOMER_PAYMENT_PROFILE
SELECT CSQL.CPP_DATA,ULD.ULD_ID,CSQL.TIMESTAMP FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,USER_LOGIN_DETAILS ULD WHERE CSQL.CPP_DATA IS NOT NULL AND ULD.ULD_LOGINID=CSQL.USER_STAMP;
SELECT * FROM CUSTOMER_PAYMENT_PROFILE;
SELECT CSQL.CPP_DATA,D.CPP_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT CSQL,CUSTOMER_PAYMENT_PROFILE D WHERE CSQL.CPP_DATA IS NOT NULL AND D.CPP_DATA=CSQL.CPP_DATA;


-- CUSTOMER_TIME_PROFILE
SELECT CTP_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE CTP_DATA IS NOT NULL;
SELECT * FROM CUSTOMER_TIME_PROFILE;

-- PAYMENT_PROFILE
SELECT PP_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE PP_DATA IS NOT NULL;
SELECT * FROM PAYMENT_PROFILE;
SELECT S.PP_DATA,D.PP_DATA FROM SOURCE_12072014.CONFIG_SQL_FORMAT S,PAYMENT_PROFILE D WHERE S.PP_DATA IS NOT NULL AND S.PP_DATA=D.PP_DATA;

-- TICKLER_PROFILE
SELECT TP_TYPE FROM SOURCE_12072014.CONFIG_SQL_FORMAT WHERE TP_TYPE IS NOT NULL;
SELECT * FROM TICKLER_PROFILE;
SELECT S.TP_TYPE,D.TP_TYPE FROM SOURCE_12072014.CONFIG_SQL_FORMAT S,TICKLER_PROFILE D WHERE S.TP_TYPE IS NOT NULL AND S.TP_TYPE=D.TP_TYPE;
