-- EXPENCE STAR HUB

SELECT * FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE = 'STAR HUB';

SELECT * FROM EXPENSE_DETAIL_STARHUB;

-- UNIT_ID
SELECT DISTINCT UNIT_ID FROM EXPENSE_DETAIL_STARHUB;

SELECT DISTINCT EXPD_UNIT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_UNIT_NO IS NOT NULL;

SELECT EDS.UNIT_ID ,BDSF.EXPD_UNIT_NO 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_STARHUB EDS, UNIT U
WHERE BDSF.EXPD_UNIT_NO=U.UNIT_NO AND U.UNIT_ID = EDS.UNIT_ID GROUP BY EXPD_UNIT_NO;

-- ECN_ID
SELECT DISTINCT ECN_ID FROM EXPENSE_DETAIL_STARHUB;

SELECT DISTINCT EXPD_INVOICE_TO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_UNIT_NO IS NOT NULL;

SELECT DISTINCT A.EXPD_INVOICE_TO,B.ECN_DATA,B.ECN_ID,C.ECN_ID 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT A  
INNER JOIN EXPENSE_CONFIGURATION B ON A.EXPD_INVOICE_TO=B.ECN_DATA 
INNER JOIN EXPENSE_DETAIL_STARHUB C ON B.ECN_ID=C.ECN_ID;

-- ACCOUNT NO
SELECT DISTINCT EXPD_STAR_HUB_ACCOUNT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_STAR_HUB_ACCOUNT_NO IS NOT NULL;

SELECT DISTINCT EDSH_ACCOUNT_NO FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_ACCOUNT_NO IS NOT NULL;

SELECT DISTINCT EDSH.EDSH_ACCOUNT_NO,BDSF.EXPD_STAR_HUB_ACCOUNT_NO
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH
WHERE EDSH.EDSH_ACCOUNT_NO=BDSF.EXPD_STAR_HUB_ACCOUNT_NO AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- APPL DATE
SELECT DISTINCT EDSH_APPL_DATE FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_APPL_DATE IS NOT NULL;

SELECT DISTINCT EXPD_APPL_DATE FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_APPL_DATE IS NOT NULL;

SELECT DISTINCT EDSH.EDSH_APPL_DATE,BDSF.EXPD_APPL_DATE 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH
WHERE EDSH.EDSH_APPL_DATE=BDSF.EXPD_APPL_DATE AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- CABLE START DATE
SELECT DISTINCT EDSH_CABLE_START_DATE FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_CABLE_START_DATE IS NOT NULL;

SELECT DISTINCT EXPD_CABLE_START_DATE FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_CABLE_START_DATE IS NOT NULL;

SELECT DISTINCT EDSH.EDSH_CABLE_START_DATE,BDSF.EXPD_CABLE_START_DATE 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE EDSH.EDSH_CABLE_START_DATE=BDSF.EXPD_CABLE_START_DATE AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- CABLE END DATE
SELECT DISTINCT EDSH_CABLE_END_DATE FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_CABLE_END_DATE IS NOT NULL;

SELECT DISTINCT EXPD_CABLE_END_DATE FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_CABLE_END_DATE IS NOT NULL;

SELECT DISTINCT EDSH.EDSH_CABLE_END_DATE ,BDSF.EXPD_CABLE_END_DATE 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE EDSH.EDSH_CABLE_END_DATE=BDSF.EXPD_CABLE_END_DATE AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- INTERNET START DATE
SELECT DISTINCT EDSH_INTERNET_START_DATE FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_INTERNET_START_DATE IS NOT NULL;

SELECT DISTINCT EXPD_INTERNET_START_DATE FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_INTERNET_START_DATE IS NOT NULL;

SELECT DISTINCT EDSH.EDSH_INTERNET_START_DATE,BDSF.EXPD_INTERNET_START_DATE 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE EDSH.EDSH_INTERNET_START_DATE=BDSF.EXPD_INTERNET_START_DATE AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- INTERNET END DATE
SELECT DISTINCT EDSH_INTERNET_END_DATE FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_INTERNET_END_DATE IS NOT NULL;

SELECT DISTINCT EXPD_INTERNET_END_DATE FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_INTERNET_END_DATE IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_INTERNET_END_DATE , EDSH.EDSH_INTERNET_END_DATE
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.EXPD_INTERNET_END_DATE= EDSH.EDSH_INTERNET_END_DATE AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- SSID
SELECT DISTINCT EDSH_SSID FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_SSID IS NOT NULL;

SELECT DISTINCT EXPD_SSID FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_SSID IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_SSID,EDSH_SSID 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.EXPD_SSID=EDSH_SSID AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- PWD
SELECT DISTINCT EDSH_PWD FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_PWD IS NOT NULL;

SELECT DISTINCT EXPD_PWD FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_PWD IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_PWD,EDSH_PWD
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH  
WHERE BDSF.EXPD_PWD=EDSH_PWD AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB'; 

-- CABLE BOX SERIAL NO
SELECT DISTINCT EDSH_CABLE_BOX_SERIAL_NO FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_CABLE_BOX_SERIAL_NO IS NOT NULL;

SELECT DISTINCT EXPD_CABLE_BOX_SERIAL_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_CABLE_BOX_SERIAL_NO IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_CABLE_BOX_SERIAL_NO , EDSH.EDSH_CABLE_BOX_SERIAL_NO 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.EXPD_CABLE_BOX_SERIAL_NO = EDSH.EDSH_CABLE_BOX_SERIAL_NO AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- MODEM SERIAL NO
SELECT DISTINCT EDSH_MODEM_SERIAL_NO FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_MODEM_SERIAL_NO IS NOT NULL;

SELECT DISTINCT EXPD_MODEM_SERIAL_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_MODEM_SERIAL_NO IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_MODEM_SERIAL_NO , EDSH.EDSH_MODEM_SERIAL_NO 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.EXPD_MODEM_SERIAL_NO= EDSH.EDSH_MODEM_SERIAL_NO AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- BASIC GROUP
SELECT DISTINCT EDSH_BASIC_GROUP FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_BASIC_GROUP IS NOT NULL;

SELECT DISTINCT EXPD_BASIC_GROUP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND  EXPD_BASIC_GROUP IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_BASIC_GROUP,EDSH_BASIC_GROUP 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_STARHUB
WHERE BDSF.EXPD_BASIC_GROUP=EDSH_BASIC_GROUP AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- ADDTNL_CH
SELECT DISTINCT EDSH_ADDTNL_CH FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_ADDTNL_CH IS NOT NULL;

SELECT DISTINCT EXPD_ADDTNL_CH FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_ADDTNL_CH IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_ADDTNL_CH , EDSH.EDSH_ADDTNL_CH
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.EXPD_ADDTNL_CH = EDSH.EDSH_ADDTNL_CH AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- COMMENTS
SELECT DISTINCT EDSH_COMMENTS FROM EXPENSE_DETAIL_STARHUB WHERE EDSH_COMMENTS IS NOT NULL;

SELECT DISTINCT EXPD_COMMENTS FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB' AND EXPD_COMMENTS IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_COMMENTS , EDSH.EDSH_COMMENTS 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.EXPD_COMMENTS = EDSH.EDSH_COMMENTS AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- TIMESTAMP
SELECT DISTINCT EDSH_TIMESTAMP FROM EXPENSE_DETAIL_STARHUB;

SELECT DISTINCT `TIMESTAMP` FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB';

SELECT DISTINCT SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') , EDSH.EDSH_TIMESTAMP 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE (SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = EDSH.EDSH_TIMESTAMP )AND BDSF.EXPD_TYPE_OF_EXPENSE ='STAR HUB';

-- ULD ID
SELECT DISTINCT ULD_ID FROM EXPENSE_DETAIL_STARHUB;

SELECT DISTINCT USERSTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='STAR HUB';

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID 
INNER JOIN EXPENSE_DETAIL_STARHUB C ON B.ULD_ID=C.ULD_ID;

-- ELECTRICITY

SELECT * FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='ELECTRICITY';

SELECT *FROM EXPENSE_DETAIL_ELECTRICITY;

-- UNIT_ID
SELECT DISTINCT UNIT_ID FROM EXPENSE_DETAIL_ELECTRICITY;

SELECT DISTINCT EXPD_UNIT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='ELECTRICITY' AND EXPD_UNIT_NO IS NOT NULL;

SELECT DISTINCT EDE.UNIT_ID,BDSF.EXPD_UNIT_NO,U.UNIT_ID,U.UNIT_NO 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF 
INNER JOIN UNIT U ON BDSF.EXPD_UNIT_NO=U.UNIT_NO 
INNER JOIN EXPENSE_DETAIL_ELECTRICITY EDE ON U.UNIT_ID = EDE.UNIT_ID ORDER BY U.UNIT_ID;

-- ECN_ID

SELECT ECN_ID FROM EXPENSE_DETAIL_ELECTRICITY;

SELECT EXPD_INVOICE_TO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='ELECTRICITY' AND EXPD_UNIT_NO IS NOT NULL;

SELECT EDE.ECN_ID ,BDSF.EXPD_INVOICE_TO
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF
INNER JOIN EXPENSE_CONFIGURATION EC ON BDSF.EXPD_INVOICE_TO=EC.ECN_DATA 
INNER JOIN EXPENSE_DETAIL_ELECTRICITY EDE ON  EC.ECN_ID = EDE.ECN_ID
WHERE BDSF.EXPD_TYPE_OF_EXPENSE='ELECTRICITY' GROUP BY EDE.EDE_ID;


-- EDE COMMENTS
SELECT DISTINCT EDE_COMMENTS FROM EXPENSE_DETAIL_ELECTRICITY WHERE EDE_COMMENTS IS NOT NULL;

SELECT DISTINCT EXPD_COMMENTS FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='ELECTRICITY' AND EXPD_COMMENTS IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_COMMENTS,EDE.EDE_COMMENTS 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_ELECTRICITY EDE
WHERE BDSF.EXPD_COMMENTS=EDE.EDE_COMMENTS AND EXPD_TYPE_OF_EXPENSE='ELECTRICITY';

-- ULD_ID
SELECT DISTINCT ULD_ID FROM EXPENSE_DETAIL_ELECTRICITY;

SELECT DISTINCT USERSTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='ELECTRICITY';

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN EXPENSE_DETAIL_ELECTRICITY C ON B.ULD_ID=C.ULD_ID;

--  TIMESTAMP
SELECT DISTINCT EDE_TIMESTAMP FROM EXPENSE_DETAIL_ELECTRICITY;

SELECT DISTINCT TIMESTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='ELECTRICITY'; 

SELECT DISTINCT SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') , EDE.EDE_TIMESTAMP 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_ELECTRICITY EDE
WHERE (SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = EDE.EDE_TIMESTAMP  )AND BDSF.EXPD_TYPE_OF_EXPENSE ='ELECTRICITY';

-- DIGITAL VOICE

SELECT * FROM EXPENSE_DETAIL_DIGITAL_VOICE;

SELECT * FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE';

-- UNIT_ID
SELECT DISTINCT UNIT_ID FROM EXPENSE_DETAIL_DIGITAL_VOICE;

SELECT DISTINCT EXPD_UNIT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE' AND EXPD_UNIT_NO IS NOT NULL;

SELECT DISTINCT EDDV.UNIT_ID,BDSF.EXPD_UNIT_NO,U.UNIT_ID,U.UNIT_NO
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF 
INNER JOIN UNIT U ON BDSF.EXPD_UNIT_NO=U.UNIT_NO 
INNER JOIN EXPENSE_DETAIL_DIGITAL_VOICE EDDV ON U.UNIT_ID = EDDV.UNIT_ID; 

-- ECN_ID
SELECT DISTINCT ECN_ID FROM EXPENSE_DETAIL_DIGITAL_VOICE;

SELECT DISTINCT EXPD_INVOICE_TO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE' AND EXPD_UNIT_NO IS NOT NULL;

SELECT DISTINCT A.EXPD_INVOICE_TO,B.ECN_DATA,B.ECN_ID,C.ECN_ID FROM 
SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT A  INNER JOIN
EXPENSE_CONFIGURATION B ON A.EXPD_INVOICE_TO=B.ECN_DATA INNER JOIN
EXPENSE_DETAIL_DIGITAL_VOICE C ON B.ECN_ID=C.ECN_ID;

-- DIGITAL VOICE NO
SELECT DISTINCT EDDV_DIGITAL_VOICE_NO FROM EXPENSE_DETAIL_DIGITAL_VOICE WHERE EDDV_DIGITAL_VOICE_NO IS NOT NULL;

SELECT DISTINCT EXPD_DIGITAL_VOICE_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE' AND EXPD_DIGITAL_VOICE_NO IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_DIGITAL_VOICE_NO,EDDV.EDDV_DIGITAL_VOICE_NO
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_DIGITAL_VOICE EDDV 
WHERE BDSF.EXPD_DIGITAL_VOICE_NO=EDDV.EDDV_DIGITAL_VOICE_NO AND EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE';

-- DIGITAL ACCOUNT NO
SELECT DISTINCT EDDV_DIGITAL_ACCOUNT_NO FROM EXPENSE_DETAIL_DIGITAL_VOICE WHERE EDDV_DIGITAL_ACCOUNT_NO IS NOT NULL;

SELECT DISTINCT EXPD_DIGITAL_ACCOUNT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE' AND EXPD_DIGITAL_ACCOUNT_NO IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_DIGITAL_ACCOUNT_NO,EDDV.EDDV_DIGITAL_ACCOUNT_NO
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_DIGITAL_VOICE EDDV 
WHERE BDSF.EXPD_DIGITAL_ACCOUNT_NO=EDDV.EDDV_DIGITAL_ACCOUNT_NO AND EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE';

-- EDDV_COMMENTS
SELECT DISTINCT EDDV_COMMENTS FROM EXPENSE_DETAIL_DIGITAL_VOICE WHERE EDDV_COMMENTS IS NOT NULL;

SELECT DISTINCT EXPD_COMMENTS FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE' AND EXPD_COMMENTS IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_COMMENTS,EDDV.EDDV_COMMENTS
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_DIGITAL_VOICE EDDV 
WHERE BDSF.EXPD_COMMENTS=EDDV.EDDV_COMMENTS AND EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE';

-- ULDID
SELECT DISTINCT ULD_ID FROM EXPENSE_DETAIL_AIRCON_SERVICE;

SELECT DISTINCT USERSTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='AIRCON SERVICES';

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN EXPENSE_DETAIL_AIRCON_SERVICE C ON B.ULD_ID=C.ULD_ID;

-- TIMESTAMP
SELECT DISTINCT  EDDV_TIMESTAMP FROM EXPENSE_DETAIL_DIGITAL_VOICE;

SELECT DISTINCT TIMESTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='DIGITAL VOICE';

SELECT DISTINCT SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') ,EDDV.EDDV_TIMESTAMP 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_DIGITAL_VOICE EDDV 
WHERE SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = EDDV.EDDV_TIMESTAMP;

--

SELECT DISTINCT EDDV_TIMESTAMP, EDDV_DIGITAL_VOICE_NO, EDDV_DIGITAL_ACCOUNT_NO FROM EXPENSE_DETAIL_DIGITAL_VOICE;

SELECT DISTINCT EDDV.*
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF
INNER JOIN UNIT U ON BDSF.EXPD_UNIT_NO=U.UNIT_NO
INNER JOIN EXPENSE_CONFIGURATION EC ON BDSF.EXPD_INVOICE_TO=EC.ECN_DATA
INNER JOIN EXPENSE_DETAIL_DIGITAL_VOICE EDDV ON U.UNIT_ID = EDDV.UNIT_ID AND EC.ECN_ID = EDDV.ECN_ID GROUP BY EDDV.EDDV_ID;

-- EXPENSE_AIRCON SERVICE BY

SELECT*FROM EXPENSE_AIRCON_SERVICE_BY;

-- EASB_ID
SELECT EASB_ID FROM EXPENSE_AIRCON_SERVICE_BY WHERE EASB_ID IN(SELECT EDAS_ID FROM EXPENSE_DETAIL_AIRCON_SERVICE);

-- EASB_DATA
SELECT DISTINCT EXPD_AIRCON_SERVICED_BY FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_AIRCON_SERVICED_BY IS NOT NULL AND EXPD_AIRCON_SERVICED_BY!='BCS AIRCON ENGINEERING';

SELECT DISTINCT EASB_DATA FROM EXPENSE_AIRCON_SERVICE_BY;

SELECT DISTINCT BDSF.EXPD_AIRCON_SERVICED_BY,EASB.EASB_DATA
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_AIRCON_SERVICE_BY EASB
WHERE BDSF.EXPD_AIRCON_SERVICED_BY=EASB.EASB_DATA;

-- ULDID
SELECT DISTINCT ULD_ID FROM EXPENSE_AIRCON_SERVICE_BY;

SELECT DISTINCT ULD_ID FROM EXPENSE_AIRCON_SERVICE_BY WHERE ULD_ID IN (SELECT ULD_ID FROM EXPENSE_DETAIL_AIRCON_SERVICE);

-- TIMESTAMP
SELECT DISTINCT SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') , DAS.EASB_TIMESTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_AIRCON_SERVICE_BY DAS WHERE SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = DAS.EASB_TIMESTAMP;

-- AIRCON SERVICE

SELECT * FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='AIRCON SERVICES';

SELECT * FROM EXPENSE_DETAIL_AIRCON_SERVICE;

-- UNIT_ID
SELECT DISTINCT UNIT_ID FROM EXPENSE_DETAIL_AIRCON_SERVICE;

SELECT DISTINCT EXPD_UNIT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='AIRCON SERVICES' AND EXPD_UNIT_NO IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_UNIT_NO,U.UNIT_NO,U.UNIT_ID,EDAS.UNIT_ID 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF
INNER JOIN UNIT U ON BDSF.EXPD_UNIT_NO=U.UNIT_NO 
INNER JOIN EXPENSE_DETAIL_AIRCON_SERVICE EDAS ON U.UNIT_ID = EDAS.UNIT_ID ORDER BY U.UNIT_ID;

-- EASB_ID
SELECT DISTINCT EASB_ID FROM EXPENSE_DETAIL_AIRCON_SERVICE;

SELECT DISTINCT EASB_ID FROM EXPENSE_AIRCON_SERVICE_BY;

-- EDAS_COMMENTS
SELECT DISTINCT EDAS_COMMENTS FROM EXPENSE_DETAIL_AIRCON_SERVICE WHERE EDAS_COMMENTS IS NOT NULL;

SELECT DISTINCT EXPD_COMMENTS FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='AIRCON SERVICES' AND EXPD_COMMENTS IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_COMMENTS,EDAS.EDAS_COMMENTS 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_AIRCON_SERVICE EDAS 
WHERE BDSF.EXPD_COMMENTS=EDAS.EDAS_COMMENTS AND EXPD_TYPE_OF_EXPENSE='AIRCON SERVICES';

-- TIMESTAMP
SELECT DISTINCT  EDAS_TIMESTAMP FROM EXPENSE_DETAIL_AIRCON_SERVICE;

SELECT DISTINCT TIMESTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='AIRCON SERVICES';

SELECT DISTINCT SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') , DAS.EDAS_TIMESTAMP 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_AIRCON_SERVICE DAS 
WHERE SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = DAS.EDAS_TIMESTAMP;

-- CAR PARK

SELECT * FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='CAR PARK';

SELECT * FROM EXPENSE_DETAIL_CARPARK;

-- UNIT_ID
SELECT DISTINCT UNIT_ID FROM EXPENSE_DETAIL_CARPARK;

SELECT DISTINCT EXPD_UNIT_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT 
WHERE EXPD_TYPE_OF_EXPENSE='CAR PARK' AND EXPD_UNIT_NO IS NOT NULL;

SELECT DISTINCT EDC.UNIT_ID,U.UNIT_ID,BDSF.EXPD_UNIT_NO,U.UNIT_NO 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF
INNER JOIN UNIT U ON BDSF.EXPD_UNIT_NO=U.UNIT_NO
INNER JOIN EXPENSE_DETAIL_CARPARK EDC ON U.UNIT_ID = EDC.UNIT_ID GROUP BY EDC.EDCP_ID;

-- CAR NO
SELECT DISTINCT EDCP_CAR_NO FROM EXPENSE_DETAIL_CARPARK WHERE EDCP_CAR_NO IS NOT NULL;

SELECT DISTINCT EXPD_CAR_NO FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT
WHERE EXPD_TYPE_OF_EXPENSE='CAR PARK' AND EXPD_CAR_NO IS NOT NULL;

SELECT DISTINCT BDSF.EXPD_CAR_NO,EDCP.EDCP_CAR_NO
FROM  SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF,EXPENSE_DETAIL_CARPARK EDCP
WHERE BDSF.EXPD_CAR_NO=EDCP.EDCP_CAR_NO AND EXPD_TYPE_OF_EXPENSE='CAR PARK';

-- ULDID
SELECT DISTINCT ULD_ID FROM EXPENSE_DETAIL_CARPARK;

SELECT DISTINCT USERSTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='CAR PARK';

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID 
INNER JOIN EXPENSE_DETAIL_CARPARK C ON B.ULD_ID=C.ULD_ID;


-- TIMESTAMP
SELECT DISTINCT EDCP_TIMESTAMP FROM EXPENSE_DETAIL_CARPARK;

SELECT DISTINCT TIMESTAMP FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE='CAR PARK';

SELECT  DISTINCT SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') , EC.EDCP_TIMESTAMP
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_CARPARK EC
WHERE EXPD_TYPE_OF_EXPENSE='CAR PARK' AND SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = EC.EDCP_TIMESTAMP;

SELECT  BDSF.EXPD_CAR_NO,EC.EDCP_CAR_NO, SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') , EC.EDCP_TIMESTAMP
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_CARPARK EC 
WHERE BDSF.EXPD_CAR_NO=EC.EDCP_CAR_NO  AND SUBTIME( BDSF.`TIMESTAMP`,'08:00:00') = EC.EDCP_TIMESTAMP;

SELECT DISTINCT EDC.*
FROM SOURCE_12072014.BIZ_DETAIL_SCDB_FORMAT BDSF
INNER JOIN UNIT U ON BDSF.EXPD_UNIT_NO=U.UNIT_NO
INNER JOIN EXPENSE_DETAIL_CARPARK EDC ON U.UNIT_ID = EDC.UNIT_ID GROUP BY EDC.EDCP_ID;
