-- EMAIL_TEMPLATE

SELECT ESQL.SCRIPT_NAME 
FROM SOURCE_28062014.EMAIL_SQL_FORMAT ESQL  
LEFT JOIN TEMP_CONFIG_SCDB_FORMAT TCSCDB ON ESQL.SCRIPT_NAME = TCSCDB.CF_TYPE 
WHERE ESQL.SCRIPT_NAME IS NOT NULL;

SELECT * FROM EMAIL_TEMPLATE;

SELECT ESQL.SCRIPT_NAME,S.ET_EMAIL_SCRIPT 
FROM SOURCE_28062014.EMAIL_SQL_FORMAT ESQL  
LEFT JOIN TEMP_CONFIG_SCDB_FORMAT TCSCDB ON ESQL.SCRIPT_NAME = TCSCDB.CF_TYPE, EMAIL_TEMPLATE S 
WHERE ESQL.SCRIPT_NAME IS NOT NULL AND ESQL.SCRIPT_NAME=S.ET_EMAIL_SCRIPT;

-- EMAIL_TEMPLATE_DETAILS

SELECT * FROM EMAIL_TEMPLATE_DETAILS;

SELECT ET.ET_ID,ESQL.SUBJECT,ESQL.BODY,ULD.ULD_ID,ESQL.TIMESTAMP 
FROM  EMAIL_TEMPLATE ET 
LEFT JOIN SOURCE_28062014.EMAIL_SQL_FORMAT ESQL ON ET.ET_EMAIL_SCRIPT = ESQL.SCRIPT_NAME 
LEFT JOIN SOURCE_28062014.EMAIL_SCDB_FORMAT ESCDB ON ESQL.BODY=ESCDB.BODY,USER_LOGIN_DETAILS ULD 
WHERE ESQL.SUBJECT IS NOT NULL AND ESQL.BODY IS NOT NULL AND  ULD.ULD_LOGINID=ESQL.USER_STAMP;

SELECT ET.ET_ID,S.ET_ID,ESQL.SUBJECT,S.ETD_EMAIL_SUBJECT,ESQL.BODY,S.ETD_EMAIL_BODY 
FROM  EMAIL_TEMPLATE ET
LEFT JOIN SOURCE_28062014.EMAIL_SQL_FORMAT ESQL ON ET.ET_EMAIL_SCRIPT = ESQL.SCRIPT_NAME 
LEFT JOIN SOURCE_28062014.EMAIL_SCDB_FORMAT ESCDB ON ESQL.BODY=ESCDB.BODY,EMAIL_TEMPLATE_DETAILS S 
WHERE ESQL.SUBJECT IS NOT NULL AND ESQL.BODY IS NOT NULL AND ET.ET_ID=S.ET_ID AND ESQL.SUBJECT=S.ETD_EMAIL_SUBJECT AND ESQL.BODY=S.ETD_EMAIL_BODY;

--

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_28062014.EMAIL_SQL_FORMAT A INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID 
INNER JOIN EMAIL_TEMPLATE_DETAILS C ON B.ULD_ID=C.ULD_ID;

SELECT DISTINCT ULD_ID FROM EMAIL_TEMPLATE_DETAILS;

--

SELECT ESQL.TIMESTAMP FROM  EMAIL_TEMPLATE ET 
LEFT JOIN SOURCE_28062014.EMAIL_SQL_FORMAT ESQL ON ET.ET_EMAIL_SCRIPT = ESQL.SCRIPT_NAME 
LEFT JOIN SOURCE_28062014.EMAIL_SCDB_FORMAT ESCDB ON ESQL.BODY=ESCDB.BODY,USER_LOGIN_DETAILS ULD 
WHERE ESQL.SUBJECT IS NOT NULL AND ESQL.BODY IS NOT NULL AND  ULD.ULD_LOGINID=ESQL.USER_STAMP;

SELECT ETD_TIMESTAMP FROM EMAIL_TEMPLATE_DETAILS;

SELECT ESQL.TIMESTAMP,ETD.ETD_TIMESTAMP FROM  EMAIL_TEMPLATE ET 
LEFT JOIN SOURCE_28062014.EMAIL_SQL_FORMAT ESQL ON ET.ET_EMAIL_SCRIPT = ESQL.SCRIPT_NAME 
LEFT JOIN SOURCE_28062014.EMAIL_SCDB_FORMAT ESCDB ON ESQL.BODY=ESCDB.BODY,USER_LOGIN_DETAILS ULD 
INNER JOIN EMAIL_TEMPLATE_DETAILS ETD
WHERE ESQL.SUBJECT IS NOT NULL AND ESQL.BODY IS NOT NULL AND  ULD.ULD_LOGINID=ESQL.USER_STAMP AND ESQL.TIMESTAMP=ETD.ETD_TIMESTAMP GROUP BY ETD.ETD_ID;


-- EMAIL_PROFILE

SELECT DISTINCT EMAIL_DOMAIN,FLAG FROM SOURCE_28062014.EMAIL_SQL_FORMAT WHERE EMAIL_DOMAIN IS NOT NULL;

SELECT * FROM EMAIL_PROFILE;

SELECT DISTINCT S.EMAIL_DOMAIN,S.FLAG ,D.EP_EMAIL_DOMAIN,D.EP_NON_IP_FLAG
FROM SOURCE_28062014.EMAIL_SQL_FORMAT S,EMAIL_PROFILE D 
WHERE S.EMAIL_DOMAIN=D.EP_EMAIL_DOMAIN AND S.EMAIL_DOMAIN IS NOT NULL;

-- EMAIL_LIST

SELECT EP.EP_ID, ESQL.EMAIL_ID, ULD.ULD_ID,ESQL.TIMESTAMP
FROM SOURCE_28062014.EMAIL_SQL_FORMAT ESQL 
INNER JOIN EMAIL_PROFILE EP , USER_LOGIN_DETAILS ULD
WHERE EP.EP_EMAIL_DOMAIN = ESQL.EMAIL_DOMAIN AND ULD.ULD_LOGINID=ESQL.USER_STAMP;

SELECT * FROM EMAIL_LIST;

--

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_28062014.EMAIL_SQL_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID
INNER JOIN EMAIL_LIST C ON B.ULD_ID=C.ULD_ID;

SELECT DISTINCT ULD_ID FROM EMAIL_LIST;

--

SELECT ESQL.TIMESTAMP FROM SOURCE_28062014.EMAIL_SQL_FORMAT ESQL 
INNER JOIN EMAIL_PROFILE EP , USER_LOGIN_DETAILS ULD 
WHERE EP.EP_EMAIL_DOMAIN = ESQL.EMAIL_DOMAIN AND ULD.ULD_LOGINID=ESQL.USER_STAMP;

SELECT EL_TIMESTAMP FROM EMAIL_LIST;

SELECT ESQL.TIMESTAMP,EL.EL_TIMESTAMP FROM SOURCE_28062014.EMAIL_SQL_FORMAT ESQL 
INNER JOIN EMAIL_PROFILE EP , USER_LOGIN_DETAILS ULD 
INNER JOIN EMAIL_LIST EL
WHERE EP.EP_EMAIL_DOMAIN = ESQL.EMAIL_DOMAIN AND ULD.ULD_LOGINID=ESQL.USER_STAMP AND ESQL.TIMESTAMP=EL.EL_TIMESTAMP GROUP BY EL.EL_ID ;
