-- STAFF EXPENCE

SELECT* FROM SOURCE_28062014. STAFF_DAILY_SCDB_FORMAT

-- EXPENSE STAFF SALARY
-- TOTAL SOURCE: 146 DEST:146

SELECT* FROM EXPENSE_STAFF_SALARY;

SELECT * FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY'

-- VALUES ARE MATCHED IN EXPENSE STAFF SALARY AND STAFF DIALY
-- SOURCE:5 DEST:5 MATCHED:5

SELECT DISTINCT ESS_SALARY_AMOUNT FROM EXPENSE_STAFF_SALARY

SELECT DISTINCT SE_SALARY_AMOUNT FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT ESS.ESS_SALARY_AMOUNT,SASF.SE_SALARY_AMOUNT 
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SASF , EXPENSE_STAFF_SALARY ESS
WHERE ESS.ESS_SALARY_AMOUNT=SASF.SE_SALARY_AMOUNT 

-- ALL ARE MATCHED 
-- SOURCE:35 DEST:35 MATCHED:35

SELECT DISTINCT ESS_INVOICE_DATE FROM EXPENSE_STAFF_SALARY

SELECT DISTINCT SE_SALARY_INVOICE_DATE FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT ESS.ESS_INVOICE_DATE , SASF.SE_SALARY_INVOICE_DATE
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SASF , EXPENSE_STAFF_SALARY ESS
WHERE ESS.ESS_INVOICE_DATE = SASF.SE_SALARY_INVOICE_DATE

SELECT DISTINCT A.SE_SALARY_AMOUNT ,A.SE_SALARY_FIRST_NAME,B.EMP_FIRST_NAME,B.EMP_ID , C.EMP_ID,A.SE_SALARY_LAST_NAME,B.EMP_LAST_NAME,A.SE_SALARY_AMOUNT,C.EDSS_SALARY_AMOUNT,C.EDSS_ID , D.EDSS_ID,C.EDSS_SALARY_AMOUNT,D.ESS_SALARY_AMOUNT,A.SE_LEVY_AMOUNT,C.EDSS_LEVY_AMOUNT , A.SE_CPF_AMOUNT,C.EDSS_CPF_AMOUNT,C.EDSS_LEVY_AMOUNT,D.ESS_LEVY_AMOUNT ,C.EDSS_CPF_AMOUNT,D.ESS_CPF_AMOUNT 
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT A 
INNER JOIN EMPLOYEE_DETAILS B ON ((A.SE_SALARY_FIRST_NAME=B.EMP_FIRST_NAME)AND(A.SE_SALARY_LAST_NAME=B.EMP_LAST_NAME)) 
INNER JOIN EXPENSE_DETAIL_STAFF_SALARY C ON ((B.EMP_ID = C.EMP_ID) AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )
INNER JOIN EXPENSE_STAFF_SALARY D ON ((C.EDSS_ID = D.EDSS_ID) AND (C.EDSS_SALARY_AMOUNT=D.ESS_SALARY_AMOUNT)) OR ((C.EDSS_LEVY_AMOUNT=D.ESS_LEVY_AMOUNT AND C.EDSS_CPF_AMOUNT=D.ESS_CPF_AMOUNT ))

SELECT DISTINCT B.*
FROM SOURCE_28062014.BIZ_DAILY_SCDB_FORMAT BD
INNER JOIN EMPLOYEE_DETAILS B ON BD.EXP_HK_CLEANER_NAME=B.EMP_FIRST_NAME
INNER JOIN EXPENSE_HOUSEKEEPING EH ON B.EMP_ID=EH.EMP_ID

-- ALL ARE MATCHED 

SELECT DISTINCT ESS_TIMESTAMP FROM EXPENSE_STAFF_SALARY

SELECT DISTINCT TIMESTAMP FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY' -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT ESS.ESS_TIMESTAMP , SUBTIME(SASF.TIMESTAMP,'08:00:00')
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SASF , EXPENSE_STAFF_SALARY ESS
WHERE ESS.ESS_TIMESTAMP= SUBTIME(SASF.TIMESTAMP,'08:00:00') AND  SE_TYPE_OF_EXPENSE='SALARY ENTRY'

-- EXPENSE STAFF
-- TOTAL SOURCE: 388 DEST:388

SELECT  * FROM EXPENSE_STAFF;

SELECT * FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF'

-- ALL THE VALUES ARE MATCHED IN EXPENCE STAFF AND STAFF DAILY SCDB
-- SOURCE:145 DEST:137 MATCHED:145

SELECT DISTINCT ES_INVOICE_AMOUNT FROM EXPENSE_STAFF

SELECT DISTINCT SE_STAFF_INVOICE_AMOUNT FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF' -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT   SFF.ES_INVOICE_AMOUNT,SCAI.SE_STAFF_INVOICE_AMOUNT
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SCAI, EXPENSE_STAFF SFF
WHERE  SFF.ES_INVOICE_AMOUNT=SCAI.SE_STAFF_INVOICE_AMOUNT AND SE_TYPE_OF_EXPENSE='STAFF'

-- ALL ARE MATCHED
-- SOURCE:317 DEST:317 MATCHED:317

SELECT DISTINCT ES_INVOICE_DATE FROM EXPENSE_STAFF

SELECT DISTINCT SE_STAFF_INVOICE_DATE FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT   SFF.ES_INVOICE_DATE,SCAI.SE_STAFF_INVOICE_DATE
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SCAI, EXPENSE_STAFF SFF
WHERE  SFF.ES_INVOICE_DATE=SCAI.SE_STAFF_INVOICE_DATE 

SELECT DISTINCT A.SE_STAFF_EXPENSE ,EC.ECN_DATA, EC.ECN_ID , SFF.ECN_ID
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT A
INNER JOIN EXPENSE_CONFIGURATION EC ON A.SE_STAFF_EXPENSE =EC.ECN_DATA 
INNER JOIN EXPENSE_STAFF SFF ON EC.ECN_ID = SFF.ECN_ID WHERE A.SE_TYPE_OF_EXPENSE ='STAFF'

-- INVOICE FROM ALSO MATCHED

-- ALL ARE MATCHED 
-- SOURCE: 233 DEST:233 MATCHED:232( SOURCE HAS NULL SO IN DEST MENTIONED AS 'NO ITEM')

SELECT DISTINCT ES_INVOICE_ITEMS FROM EXPENSE_STAFF

SELECT DISTINCT SE_STAFF_INVOICE_ITEMS FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT   SFF.ES_INVOICE_ITEMS,SCAI.SE_STAFF_INVOICE_ITEMS
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SCAI RIGHT JOIN EXPENSE_STAFF SFF
ON  SFF.ES_INVOICE_ITEMS=SCAI.SE_STAFF_INVOICE_ITEMS 

SELECT DISTINCT   SFF.ES_INVOICE_ITEMS,SCAI.SE_STAFF_INVOICE_ITEMS
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SCAI, EXPENSE_STAFF SFF
WHERE  SFF.ES_INVOICE_ITEMS=SCAI.SE_STAFF_INVOICE_ITEMS 

-- ALL ARE MATCHED ( SOURCE HAS NULL SO IN DEST MENTIONED AS 'NO ITEM')

SELECT DISTINCT ES_INVOICE_FROM FROM EXPENSE_STAFF

SELECT DISTINCT SE_STAFF_INVOICE_FROM FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT   SFF.ES_INVOICE_FROM,SCAI.SE_STAFF_INVOICE_FROM
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SCAI RIGHT JOIN EXPENSE_STAFF SFF
ON  SFF.ES_INVOICE_FROM=SCAI.SE_STAFF_INVOICE_FROM 

SELECT DISTINCT   SFF.ES_INVOICE_FROM,SCAI.SE_STAFF_INVOICE_FROM
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT SCAI, EXPENSE_STAFF SFF
WHERE  SFF.ES_INVOICE_FROM=SCAI.SE_STAFF_INVOICE_FROM 

-- ALL ARE MATCHED 

SELECT DISTINCT ES_TIMESTAMP FROM EXPENSE_STAFF

SELECT DISTINCT TIMESTAMP FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF' -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT ES.ES_TIMESTAMP , SUBTIME(SASF.TIMESTAMP,'08:00:00')
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SASF , EXPENSE_STAFF ES
WHERE ES.ES_TIMESTAMP= SUBTIME(SASF.TIMESTAMP,'08:00:00') AND  SE_TYPE_OF_EXPENSE='STAFF'

-- EXPENSE AGENT 

SELECT * FROM EXPENSE_AGENT;

SELECT * FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION'

-- ALL THE VALUES ARE MATCHED IN EXPENCSE STAFF AGENT AND STAFF DAILY SCDB
-- SOURCE: 9 DEST: 9 MATCHED 9

SELECT DISTINCT EA_COMM_AMOUNT FROM EXPENSE_AGENT 

SELECT DISTINCT SE_AGENT_COMM_AMOUNT FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION'

SELECT DISTINCT SDSF.SE_AGENT_COMM_AMOUNT,EA.EA_COMM_AMOUNT 
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT SDSF, EXPENSE_AGENT EA 
WHERE EA.EA_COMM_AMOUNT= SDSF.SE_AGENT_COMM_AMOUNT 

-- ALL ARE MATCHED

SELECT DISTINCT EA_DATE FROM EXPENSE_AGENT 

SELECT DISTINCT SE_AGENT_DATE FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION'

SELECT DISTINCT SDSF.SE_AGENT_DATE,EA.EA_DATE 
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT SDSF, EXPENSE_AGENT EA 
WHERE SDSF.SE_AGENT_DATE=EA.EA_DATE

-- ALL ARE MATCHED

SELECT DISTINCT EA_TIMESTAMP FROM EXPENSE_AGENT

SELECT DISTINCT TIMESTAMP FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION' -- WHERE SE_STAFF_INVOICE_DATE IS NOT NULL

SELECT DISTINCT EA.EA_TIMESTAMP , SUBTIME(SASF.TIMESTAMP,'08:00:00')
FROM SOURCE_28062014.STAFF_DAILY_SCDB_FORMAT   SASF , EXPENSE_AGENT EA
WHERE EA.EA_TIMESTAMP= SUBTIME(SASF.TIMESTAMP,'08:00:00') AND  SE_TYPE_OF_EXPENSE='AGENT COMMISSION'

