-- PERSONAL SCDB

SELECT*FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT;

-- PERSONAL TABLE
-- TOTAL:SOURCE:5275 DEST:5275

SELECT*FROM EXPENSE_PERSONAL;

SELECT * FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='PERSONAL';

-- ALL THE VALUES ARE MATCHED WITH THE SOURCE PERSONAL SCDB FORMAT AND PERSONAL EXPENC
-- SOURCE: 233 DEST:1191 MATCHING:233

SELECT * FROM EXPENSE_PERSONAL;

SELECT DISTINCT EP.EP_INVOICE_ITEMS,PSF.PE_PERSONAL_INVOICE_ITEMS 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_PERSONAL EP 
WHERE  EP.EP_INVOICE_ITEMS=PSF.PE_PERSONAL_INVOICE_ITEMS;

SELECT DISTINCT EP_INVOICE_ITEMS FROM EXPENSE_PERSONAL

SELECT DISTINCT PE_PERSONAL_INVOICE_ITEMS FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- SOURCE: 1377 DEST:1377 MATCHING:1377

SELECT DISTINCT EP.EP_INVOICE_DATE,PSF.PE_PERSONAL_INVOICE_DATE 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_PERSONAL EP
WHERE EP.EP_INVOICE_DATE=PSF.PE_PERSONAL_INVOICE_DATE 

SELECT DISTINCT EP_INVOICE_DATE FROM EXPENSE_PERSONAL

SELECT DISTINCT PE_PERSONAL_INVOICE_DATE FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- 1 AMOUNT IS CHANGED: 7.354 AS 7.35
-- SOURCE: 1809 DEST:1632 MATCHING:1809

SELECT DISTINCT EP.EP_AMOUNT,PSF.PE_PERSONAL_AMOUNT 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_PERSONAL EP
WHERE  EP.EP_AMOUNT=PSF.PE_PERSONAL_AMOUNT 

SELECT DISTINCT PE_PERSONAL_AMOUNT
FROM SOURCE_28062014. PERSONAL_SCDB_FORMAT
WHERE PE_PERSONAL_AMOUNT NOT IN      
(        
SELECT  EP_AMOUNT
FROM EXPENSE_PERSONAL     
);

SELECT DISTINCT PSF.PE_PERSONAL_EXPENSE,EC.ECN_DATA, EC.ECN_ID , EP.ECN_ID
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF INNER JOIN EXPENSE_CONFIGURATION EC ON PSF.PE_PERSONAL_EXPENSE=EC.ECN_DATA
INNER JOIN EXPENSE_PERSONAL EP ON EC.ECN_ID = EP.ECN_ID WHERE PSF.PE_TYPE_OF_EXPENSE='PERSONAL'

SELECT DISTINCT * FROM EXPENSE_PERSONAL WHERE EP_AMOUNT = 7.354

SELECT DISTINCT EP_AMOUNT FROM EXPENSE_PERSONAL

SELECT DISTINCT PE_PERSONAL_AMOUNT FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATHCED
-- 1 ITEM IS CHENGED BY BY: MOS BURGER BY: AS BY: MOS BURGER
-- SOURCE: 386 DEST:1556 MATCHING:386

SELECT DISTINCT  EP. EP_INVOICE_FROM,PSF.PE_PERSONAL_INVOICE_FROM 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_PERSONAL EP WHERE  EP. EP_INVOICE_FROM=PSF.PE_PERSONAL_INVOICE_FROM

SELECT DISTINCT  EP. EP_INVOICE_FROM,PSF.PE_PERSONAL_INVOICE_FROM 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF 
RIGHT JOIN EXPENSE_PERSONAL EP ON  EP. EP_INVOICE_FROM=PSF.PE_PERSONAL_INVOICE_FROM

SELECT DISTINCT EP_INVOICE_FROM FROM EXPENSE_PERSONAL

SELECT DISTINCT PE_PERSONAL_INVOICE_FROM FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- BABY
-- TOTAL:  SOURCE: 330 DEST:330

SELECT*FROM EXPENSE_BABY;

SELECT * FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='BABY';

-- ALL ARE MATCH
-- AMOUNT 6.504 IS CHANGED AS 6.50
-- SOURCE:284 DEST:273 MATCHED:284

SELECT DISTINCT EB.EB_AMOUNT,PSF.PE_BABY_AMOUNT FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_BABY EB 
WHERE EB.EB_AMOUNT=PSF.PE_BABY_AMOUNT  

SELECT DISTINCT PE_BABY_AMOUNT
FROM SOURCE_28062014. PERSONAL_SCDB_FORMAT
WHERE PE_BABY_AMOUNT NOT IN (SELECT  EB_AMOUNT FROM EXPENSE_BABY);

SELECT *FROM EXPENSE_BABY WHERE EB_AMOUNT=6.50

SELECT DISTINCT EB_AMOUNT FROM EXPENSE_BABY

SELECT DISTINCT PE_BABY_AMOUNT FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

SELECT DISTINCT EB.EB_AMOUNT,PSF.PE_BABY_AMOUNT FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF
LEFT JOIN EXPENSE_BABY EB  ON EB.EB_AMOUNT=PSF.PE_BABY_AMOUNT  

SELECT DISTINCT PPE.PE_BABY_EXPENSE ,EC.ECN_DATA ,EC.ECN_ID , EB.ECN_ID
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PPE
INNER JOIN EXPENSE_CONFIGURATION EC ON PPE.PE_BABY_EXPENSE =EC.ECN_DATA 
INNER JOIN EXPENSE_BABY EB ON EC.ECN_ID = EB.ECN_ID WHERE PPE.PE_TYPE_OF_EXPENSE='BABY'

-- ALL ARE MATCH
-- SOURCE:83 DEST:264 MATCHED:83

SELECT DISTINCT EB.EB_INVOICE_ITEMS,PSF.PE_BABY_INVOICE_ITEMS 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_BABY EB  WHERE EB.EB_INVOICE_ITEMS=PSF.PE_BABY_INVOICE_ITEMS  

SELECT DISTINCT EB_INVOICE_ITEMS FROM EXPENSE_BABY

SELECT DISTINCT PE_BABY_INVOICE_ITEMS FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- SOURCE:64 DEST:185 MATCHED:64

SELECT DISTINCT PSF.PE_BABY_INVOICE_FROM,EB.EB_INVOICE_FROM 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_BABY EB  WHERE PSF.PE_BABY_INVOICE_FROM=EB.EB_INVOICE_FROM 

SELECT DISTINCT EB_INVOICE_FROM FROM EXPENSE_BABY

SELECT DISTINCT PE_BABY_INVOICE_FROM FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- SOURCE:246 DEST:246 MATCHED:246

SELECT DISTINCT PSF.PE_BABY_INVOICE_DATE,EB.EB_INVOICE_DATE  
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_BABY EB  WHERE PSF.PE_BABY_INVOICE_DATE=EB.EB_INVOICE_DATE 

SELECT DISTINCT EB_INVOICE_DATE FROM EXPENSE_BABY

SELECT DISTINCT PE_BABY_INVOICE_DATE FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- CAR 
-- TOTAL SOURCE:118 DEST:118

SELECT *FROM EXPENSE_CAR;

SELECT * FROM SOURCE_28062014. PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='CAR EXPENSE';

SELECT DISTINCT PPE.PE_CAR_EXP_TYPE ,EC.ECN_DATA ,EC.ECN_ID , ECA.ECN_ID
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PPE
INNER JOIN EXPENSE_CONFIGURATION EC ON PPE.PE_CAR_EXP_TYPE =EC.ECN_DATA 
INNER JOIN EXPENSE_CAR ECA ON EC.ECN_ID = ECA.ECN_ID WHERE PPE.PE_TYPE_OF_EXPENSE ='CAR EXPENSE'

-- ALL ARE MATCHED
-- SOURCE:80 DEST:76 MATCHED:80

SELECT DISTINCT  PSF.PE_CAR_EXP_AMOUNT ,EC.EC_AMOUNT 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR EC  WHERE PSF.PE_CAR_EXP_AMOUNT = EC.EC_AMOUNT

SELECT DISTINCT EC_AMOUNT FROM EXPENSE_CAR

SELECT DISTINCT PE_CAR_EXP_AMOUNT FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

SELECT  PE_CAR_EXP_AMOUNT
FROM SOURCE_28062014. PERSONAL_SCDB_FORMAT
WHERE PE_CAR_EXP_AMOUNT NOT IN      
(        
SELECT  EC_AMOUNT
FROM EXPENSE_CAR     
);

SELECT DISTINCT PSF.PE_CAR_EXP_AMOUNT , ECA.EC_AMOUNT FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF
LEFT JOIN EXPENSE_CAR ECA  ON ECA.EC_AMOUNT=PSF.PE_CAR_EXP_AMOUNT  

-- ALL ARE MATCHED
-- SOURCE:82 DEST:82 MATCHED:82

SELECT DISTINCT  PSF.PE_CAR_EXP_INVOICE_DATE ,EC.EC_INVOICE_DATE  
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR EC  WHERE PSF.PE_CAR_EXP_INVOICE_DATE =EC.EC_INVOICE_DATE

SELECT DISTINCT EC_INVOICE_DATE FROM EXPENSE_CAR

SELECT DISTINCT PE_CAR_EXP_INVOICE_DATE FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- SOURCE:8 DEST:96 MATCHED:8

SELECT DISTINCT  PSF.PE_CAR_EXP_INVOICE_ITEMS ,EC.EC_INVOICE_ITEMS
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR EC  WHERE PSF.PE_CAR_EXP_INVOICE_ITEMS =EC.EC_INVOICE_ITEMS 

SELECT DISTINCT EC_INVOICE_ITEMS FROM EXPENSE_CAR

SELECT DISTINCT PE_CAR_EXP_INVOICE_ITEMS FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL VALUES ARE MATCHED
-- SOURCE:8 DEST:80 MATCHED:8

SELECT DISTINCT  PSF.PE_CAR_EXP_INVOICE_FROM ,EC.EC_INVOICE_FROM 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR EC  WHERE PSF.PE_CAR_EXP_INVOICE_FROM =EC.EC_INVOICE_FROM 

SELECT DISTINCT EC_INVOICE_FROM FROM EXPENSE_CAR

SELECT DISTINCT PE_CAR_EXP_INVOICE_FROM FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- CAR LOAN
-- TOTAL SOURCE:17 DEST:17

SELECT*FROM EXPENSE_CAR_LOAN;

SELECT*FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE='CAR LOAN';

-- ALL ARE MATCHED
-- SOURCE:16 DEST:16 MATCHED:16

SELECT DISTINCT  PSF.PE_CARLOAN_PAID_DATE ,ECL.ECL_PAID_DATE 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR_LOAN ECL  WHERE PSF.PE_CARLOAN_PAID_DATE =ECL.ECL_PAID_DATE  

SELECT DISTINCT ECL_PAID_DATE FROM EXPENSE_CAR_LOAN

SELECT DISTINCT PE_CARLOAN_PAID_DATE FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- SOURCE:16 DEST:16 MATCHED:16

SELECT DISTINCT  PSF.PE_CARLOAN_FROM_PERIOD ,ECL.ECL_FROM_PERIOD 
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR_LOAN ECL  WHERE PSF.PE_CARLOAN_FROM_PERIOD=ECL.ECL_FROM_PERIOD   

SELECT DISTINCT ECL_FROM_PERIOD FROM EXPENSE_CAR_LOAN

SELECT DISTINCT PE_CARLOAN_FROM_PERIOD FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT

-- ALL ARE MATCHED
-- SOURCE:16 DEST:16 MATCHED:16

SELECT DISTINCT  PSF.PE_CARLOAN_TO_PERIOD ,ECL.ECL_TO_PERIOD
FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT PSF, EXPENSE_CAR_LOAN ECL  WHERE   PSF.PE_CARLOAN_TO_PERIOD =ECL.ECL_TO_PERIOD  

SELECT DISTINCT ECL_TO_PERIOD FROM EXPENSE_CAR_LOAN

SELECT DISTINCT PE_CARLOAN_TO_PERIOD FROM SOURCE_28062014.PERSONAL_SCDB_FORMAT WHERE PE_TYPE_OF_EXPENSE= 'CAR LOAN'


