-- UNIT
SELECT*FROM UNIT
SELECT * FROM SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
SELECT unit_room_type,unit_no, userstamp FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE unit_room_type IS NOT NULL; 
-- ACCESS STAMP DETAILS AND UNIT SCDB
-- ALL THE VALUES ARE MATCHED

SELECT*FROM UNIT_ACCESS_STAMP_DETAILS;

SELECT DISTINCT UNIT_ACCESS_CARD FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE UNIT_ACCESS_CARD IS NOT NULL;

SELECT DISTINCT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD IS NOT NULL;

SELECT DISTINCT SCU.UNIT_ACCESS_CARD,UAS.UASD_ACCESS_CARD 
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD;

-- UNIT ID AND ACCESS CARD MATCHED

SELECT SCU.UNIT_ACCESS_CARD,UAS.UASD_ACCESS_CARD,UAS.UNIT_ID , U.UNIT_ID,U.UNIT_NO, SCU.UNIT_NO
FROM UNIT_ACCESS_STAMP_DETAILS UAS
INNER JOIN UNIT U ON UAS.UNIT_ID = U.UNIT_ID
INNER JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU ON U.UNIT_NO= SCU.UNIT_NO AND UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD
WHERE SCU.UNIT_ACCESS_CARD IS NOT NULL AND UAS.UASD_ACCESS_CARD IS NOT NULL
GROUP BY UAS.UASD_ACCESS_CARD

--

SELECT DISTINCT UNIT_STAMPDUTYDATE FROM SOURCE_13062014.UNIT_SCDB_FORMAT -- WHERE UNIT_ACCESS_CARD IS NOT NULL 

SELECT DISTINCT UASD_STAMPDUTYDATE FROM UNIT_ACCESS_STAMP_DETAILS

SELECT DISTINCT SCU.UNIT_STAMPDUTYDATE,UAS.UASD_STAMPDUTYDATE
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE SCU.UNIT_STAMPDUTYDATE =UAS.UASD_STAMPDUTYDATE

--

SELECT DISTINCT UNIT_STAMPDUTYAMT FROM SOURCE_13062014.UNIT_SCDB_FORMAT -- WHERE UNIT_ACCESS_CARD IS NOT NULL 

SELECT DISTINCT UASD_STAMPDUTYAMT FROM UNIT_ACCESS_STAMP_DETAILS

SELECT DISTINCT SCU.UNIT_STAMPDUTYAMT,UAS.UASD_STAMPDUTYAMT
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE SCU.UNIT_STAMPDUTYAMT =UAS.UASD_STAMPDUTYAMT

--

SELECT DISTINCT UNIT_ID FROM UNIT_ACCESS_STAMP_DETAILS

SELECT DISTINCT UNIT_NO FROM SOURCE_13062014.UNIT_SCDB_FORMAT

SELECT U.UNIT_ID
FROM UNIT U 
WHERE NOT EXISTS     
(        
SELECT UAS.UNIT_ID
FROM UNIT_ACCESS_STAMP_DETAILS UAS 
WHERE U.UNIT_ID=UAS.UNIT_ID
);

SELECT DISTINCT(U.UNIT_NO),U1.UNIT_NO,U1.UNIT_ID,UAS.UNIT_ID
FROM SOURCE_13062014.UNIT_SCDB_FORMAT U , UNIT U1,UNIT_ACCESS_STAMP_DETAILS UAS 
WHERE U.UNIT_NO=U1.UNIT_NO AND U1.UNIT_ID = UAS.UNIT_ID ORDER BY U1.UNIT_NO;

SELECT DISTINCT UAS.UASD_ID, UAS.UNIT_ID, UAS.UASD_STAMPDUTYAMT,UAS.UASD_STAMPDUTYDATE,UAS.UASD_ACCESS_CARD
FROM  UNIT_ACCESS_STAMP_DETAILS UAS,SOURCE_13062014.UNIT_SCDB_FORMAT SCU,UNIT U
WHERE UAS.UNIT_ID=U.UNIT_ID OR SCU.UNIT_STAMPDUTYAMT =UAS.UASD_STAMPDUTYAMT OR 
SCU.UNIT_STAMPDUTYDATE =UAS.UASD_STAMPDUTYDATE OR UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD;

SELECT DISTINCT UAS.*
FROM UNIT_ACCESS_STAMP_DETAILS UAS
INNER JOIN UNIT U ON (UAS.UNIT_ID=U.UNIT_ID)
INNER JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU ON ((U.UNIT_NO=SCU.UNIT_NO)AND (SCU.UNIT_STAMPDUTYAMT=UAS.UASD_STAMPDUTYAMT )) OR ((SCU.UNIT_ACCESS_CARD=UAS.UASD_ACCESS_CARD AND SUBTIME(SCU.`TIMESTAMP`,'08:00:00')=UAS.UASD_TIMESTAMP ) )

-- TIMESTAMP ARE CHANGED 

SELECT DISTINCT UASD_TIMESTAMP FROM UNIT_ACCESS_STAMP_DETAILS

SELECT DISTINCT TIMESTAMP FROM SOURCE_13062014.UNIT_SCDB_FORMAT SCU 

SELECT DISTINCT  UAS.UASD_TIMESTAMP,SUBTIME(SCU.`TIMESTAMP`,'08:00:00')
FROM UNIT_ACCESS_STAMP_DETAILS UAS , SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =UAS.UASD_TIMESTAMP

SELECT DISTINCT  UAS.UASD_TIMESTAMP,SUBTIME(SCU.`TIMESTAMP`,'08:00:00')
FROM UNIT_ACCESS_STAMP_DETAILS UAS LEFT JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
ON SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =UAS.UASD_TIMESTAMP

SELECT DISTINCT UAS.UASD_TIMESTAMP,SUBTIME(SCU.`TIMESTAMP`,'08:00:00')
FROM UNIT_ACCESS_STAMP_DETAILS UAS right JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
ON SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =UAS.UASD_TIMESTAMP

SELECT *
FROM SOURCE_13062014.UNIT_SCDB_FORMAT 
WHERE SUBTIME(`TIMESTAMP`,'08:00:00') NOT IN      
(        
SELECT  UASD_TIMESTAMP
FROM UNIT_ACCESS_STAMP_DETAILS     
);

-- UNIT ACCOUT DETAIL AND UNIT SCDB
-- ALL THE VALUES ARE MATCHED

SELECT*FROM UNIT_ACCOUNT_DETAILS

SELECT DISTINCT UACD_ACC_NO FROM UNIT_ACCOUNT_DETAILS

SELECT DISTINCT UNIT_ACC_NO FROM SOURCE_13062014.UNIT_SCDB_FORMAT

SELECT DISTINCT  UAD.UACD_ACC_NO,SCU.UNIT_ACC_NO 
FROM UNIT_ACCOUNT_DETAILS UAD, SOURCE_13062014.UNIT_SCDB_FORMAT SCU
WHERE UAD.UACD_ACC_NO=SCU.UNIT_ACC_NO

-- 3 NAMES ARE SAME BUT NOT ISSUE

SELECT DISTINCT UACD_ACC_NAME FROM UNIT_ACCOUNT_DETAILS

SELECT  UNIT_ACC_NAME FROM SOURCE_13062014.UNIT_SCDB_FORMAT GROUP BY UNIT_ACC_NO

SELECT DISTINCT  UAD.UACD_ACC_NAME ,SCU.UNIT_ACC_NAME
FROM UNIT_ACCOUNT_DETAILS UAD, SOURCE_13062014.UNIT_SCDB_FORMAT SCU
WHERE UAD.UACD_ACC_NAME =SCU.UNIT_ACC_NAME

--

SELECT DISTINCT UACD_BANK_CODE FROM UNIT_ACCOUNT_DETAILS

SELECT DISTINCT UNIT_BANKCODE FROM SOURCE_13062014.UNIT_SCDB_FORMAT

SELECT DISTINCT  UAD.UACD_BANK_CODE ,SCU.UNIT_BANKCODE 
FROM UNIT_ACCOUNT_DETAILS UAD, SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE  UAD.UACD_BANK_CODE =SCU.UNIT_BANKCODE 

--

SELECT DISTINCT UAD.*
FROM UNIT_ACCOUNT_DETAILS UAD
INNER JOIN UNIT U ON (UAD.UNIT_ID=U.UNIT_ID)
INNER JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU ON (U.UNIT_NO=SCU.UNIT_NO) -- AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )

-- UNIT DETAILS AND UNIT SCDB
-- ALL THE VALUES ARE MATCHED 

SELECT *FROM UNIT_DETAILS

SELECT DISTINCT UD_START_DATE FROM UNIT_DETAILS

SELECT DISTINCT UNIT_START_DATE FROM SOURCE_13062014.UNIT_SCDB_FORMAT

SELECT DISTINCT UD.UD_START_DATE,UD.UD_END_DATE FROM UNIT_DETAILS UD

SELECT  DISTINCT UD.UNIT_ID, UD.UD_START_DATE,SCU.UNIT_START_DATE , UD.UD_END_DATE,SCU.UNIT_END_DATE 
FROM UNIT_DETAILS UD , SOURCE_13062014.UNIT_SCDB_FORMAT SCU
WHERE UD.UD_START_DATE=SCU.UNIT_START_DATE AND UD.UD_END_DATE=SCU.UNIT_END_DATE

SELECT  UD.UNIT_ID, UD.UD_START_DATE,SCU.UNIT_START_DATE , UD.UD_END_DATE,SCU.UNIT_END_DATE , UD.UD_OBSOLETE,SCU.UNIT_OBSOLETE
FROM UNIT_DETAILS UD , SOURCE_13062014.UNIT_SCDB_FORMAT SCU
WHERE UD.UD_START_DATE=SCU.UNIT_START_DATE AND UD.UD_END_DATE=SCU.UNIT_END_DATE AND UD.UD_OBSOLETE=SCU.UNIT_OBSOLETE

--

SELECT DISTINCT UD_TIMESTAMP FROM UNIT_DETAILS

SELECT DISTINCT TIMESTAMP FROM SOURCE_13062014.UNIT_SCDB_FORMAT

SELECT DISTINCT SCU.`TIMESTAMP` ,UD.UD_TIMESTAMP
FROM UNIT_DETAILS UD  , SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =UD.UD_TIMESTAMP 

SELECT DISTINCT UD.*
FROM UNIT_DETAILS UD
INNER JOIN UNIT U ON (UD.UNIT_ID=U.UNIT_ID)
INNER JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU ON (U.UNIT_NO=SCU.UNIT_NO) -- AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )

-- UNIT STAMP DUTY DETAILS AND UNIT SCDB
-- ALL THE THREE VALUES ARE MATCHED

SELECT*FROM UNIT_STAMP_DUTY_TYPE

SELECT DISTINCT SCU.`TIMESTAMP` ,USD.USDT_TIMESTAMP
FROM  UNIT_STAMP_DUTY_TYPE USD ,SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =USD.USDT_TIMESTAMP

-- UNIT LOGIN DETAIL, UNIT SCDB
-- ALL THE VALUES ARE MATCHED 

SELECT*FROM UNIT_LOGIN_DETAILS

SELECT DISTINCT ULDTL_WEBPWD FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBPWD IS NOT NULL

SELECT DISTINCT UNIT_WEBPWD FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE UNIT_WEBPWD IS NOT NULL 

SELECT DISTINCT SCU.UNIT_WEBPWD, LD.ULDTL_WEBPWD 
FROM SOURCE_13062014.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD WHERE SCU.UNIT_WEBPWD=LD.ULDTL_WEBPWD

--

SELECT DISTINCT ULDTL_DOORCODE FROM UNIT_LOGIN_DETAILS WHERE ULDTL_DOORCODE IS NOT NULL

SELECT DISTINCT UNIT_DOORCODE FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE UNIT_DOORCODE IS NOT NULL 
 
SELECT DISTINCT SCU.UNIT_DOORCODE, LD.ULDTL_DOORCODE
FROM SOURCE_13062014.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD WHERE SCU.UNIT_DOORCODE =LD.ULDTL_DOORCODE

-- WENLOGIN ID ARE WRONGLY MIGED

SELECT DISTINCT ULDTL_WEBLOGIN FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBLOGIN IS NOT NULL

SELECT DISTINCT UNIT_WEBLOGIN FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE UNIT_WEBLOGIN IS NOT NULL 
 
SELECT DISTINCT LD.ULDTL_WEBLOGIN,SCU.UNIT_WEBLOGIN
FROM SOURCE_13062014.UNIT_SCDB_FORMAT SCU , UNIT_LOGIN_DETAILS LD WHERE (SCU.UNIT_WEBLOGIN = LD.ULDTL_WEBLOGIN)

--

SELECT *FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE  CHAR_LENGTH(UNIT_WEBLOGIN)>8 

SELECT *
FROM UNIT_LOGIN_DETAILS
WHERE ULDTL_WEBLOGIN NOT IN      
(        
SELECT UNIT_WEBLOGIN
FROM SOURCE_13062014.UNIT_SCDB_FORMAT 
);

--

SELECT DISTINCT ULDTL_TIMESTAMP FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBLOGIN IS NOT NULL

SELECT DISTINCT SUBTIME(SCU.`TIMESTAMP`,'08:00:00') ,LD.ULDTL_TIMESTAMP
FROM  UNIT_LOGIN_DETAILS LD , SOURCE_13062014.UNIT_SCDB_FORMAT SCU 
WHERE SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =LD.ULDTL_TIMESTAMP AND LD.ULDTL_DOORCODE=SCU.UNIT_DOORCODE;

SELECT DISTINCT LD.*
FROM UNIT_LOGIN_DETAILS LD 
INNER JOIN UNIT U ON (LD.UNIT_ID=U.UNIT_ID)
INNER JOIN SOURCE_13062014.UNIT_SCDB_FORMAT SCU ON (U.UNIT_NO=SCU.UNIT_NO) -- AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )

-- UNIT ROOM TYPE 
-- ALL THE VALUES ARE MATCHED 

SELECT*FROM UNIT_ROOM_TYPE_DETAILS

SELECT DISTINCT URTD_ROOM_TYPE FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ROOM_TYPE IS NOT NULL 

SELECT DISTINCT UNIT_ROOM_TYPE FROM SOURCE_13062014.UNIT_SCDB_FORMAT WHERE UNIT_ROOM_TYPE IS NOT NULL 

SELECT DISTINCT SCU.UNIT_ROOM_TYPE , RM.URTD_ROOM_TYPE 
FROM SOURCE_13062014.UNIT_SCDB_FORMAT SCU, UNIT_ROOM_TYPE_DETAILS RM
WHERE SCU.UNIT_ROOM_TYPE = RM.URTD_ROOM_TYPE

-- UNIT CONFIG

SELECT*FROM UNIT_CONFIGURATION

SELECT SCU.`TIMESTAMP`,UC.UCN_TIMESTAMP
FROM SASI_TEST_SOURCE.UNIT_SCDB_FORMAT SCU, UNIT_CONFIGURATION UC 
WHERE SCU.TIMESTAMP =UC.UCN_TIMESTAMP
