-- ERM

SELECT*FROM ERM_ENTRY_DETAILS;

SELECT*FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS;

-- ERM ENTRY DETAILS
-- ONE NAME IS WRONG - RAPHAËL IN SOURCE

SELECT DISTINCT ERM.ERM_CUST_NAME FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT  MERM.ERM_CUST_NAME FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT MERM.ERM_CUST_NAME,ERM.ERM_CUST_NAME 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_CUST_NAME=ERM.ERM_CUST_NAME;

SELECT DISTINCT MERM.ERM_CUST_NAME,ERM.ERM_CUST_NAME 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM LEFT JOIN ERM_ENTRY_DETAILS ERM ON MERM.ERM_CUST_NAME=ERM.ERM_CUST_NAME;

SELECT ERM_CUST_NAME
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS
WHERE ERM_CUST_NAME NOT IN      
(        
SELECT ERM_CUST_NAME
FROM ERM_ENTRY_DETAILS
);

--

SELECT DISTINCT  MERM.ERM_RENT FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_RENT FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_RENT,ERM.ERM_RENT 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_RENT=ERM.ERM_RENT;

--

SELECT DISTINCT  MERM.ERM_MOVING_DATE FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_MOVING_DATE FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_MOVING_DATE,ERM.ERM_MOVING_DATE 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_MOVING_DATE=ERM.ERM_MOVING_DATE;

--

SELECT DISTINCT  MERM.ERM_MIN_STAY FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_MIN_STAY FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_MIN_STAY,ERM.ERM_MIN_STAY 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_MIN_STAY=ERM.ERM_MIN_STAY;

--

SELECT DISTINCT  MERM.ERMO_ID FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERMO_ID FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERMO_ID,ERM.ERMO_ID 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERMO_ID=ERM.ERMO_ID;

SELECT DISTINCT  MERM.ERMO_ID,ERM.ERMO_ID 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM LEFT JOIN  ERM_ENTRY_DETAILS ERM ON MERM.ERMO_ID=ERM.ERMO_ID;

SELECT DISTINCT EOD.ERMO_ID , MERM.ERMO_ID
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM ,ERM_OCCUPATION_DETAILS EOD
WHERE MERM.ERMO_ID=EOD.ERMO_DATA; -- OR MERM.ERMO_ID = EOD.ERMO_ID AND ERM.ERMO_ID = EOD.ERMO_ID;

SELECT DISTINCT MERM.ERMO_ID,EOD.ERMO_DATA , MERM.ERMO_ID , MERM.ERMO_ID -- ,ERM.ERMO_ID -- , EOD.ERMO_ID
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM ,ERM_OCCUPATION_DETAILS EOD , ERM_ENTRY_DETAILS ERM
WHERE MERM.ERMO_ID=EOD.ERMO_DATA OR MERM.ERMO_ID = EOD.ERMO_ID AND ERM.ERMO_ID = EOD.ERMO_ID;

SELECT ERMO_ID
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS
WHERE ERMO_ID NOT IN      
(        
SELECT ERMO_ID
FROM ERM_ENTRY_DETAILS
);

--

SELECT DISTINCT  MERM.NC_SNO FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.NC_ID FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.NC_SNO,ERM.NC_ID 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.NC_SNO=ERM.NC_ID;

--

SELECT DISTINCT MERM.ERM_NO_OF_GUESTS FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_NO_OF_GUESTS FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_NO_OF_GUESTS,ERM.ERM_NO_OF_GUESTS 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_NO_OF_GUESTS=ERM.ERM_NO_OF_GUESTS;

--

SELECT DISTINCT MERM.ERM_AGE FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_AGE FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_AGE,ERM.ERM_AGE 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_AGE=ERM.ERM_AGE;

--

SELECT DISTINCT MERM.ERM_CONTACT_NO FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_CONTACT_NO FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_CONTACT_NO,ERM.ERM_CONTACT_NO 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_CONTACT_NO=ERM.ERM_CONTACT_NO;

--

SELECT DISTINCT MERM.ERM_EMAIL_ID FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_EMAIL_ID FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_EMAIL_ID,ERM.ERM_EMAIL_ID
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_EMAIL_ID=ERM.ERM_EMAIL_ID;

--

SELECT DISTINCT MERM.ERM_COMMENTS FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_COMMENTS FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_COMMENTS,ERM.ERM_COMMENTS 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM WHERE MERM.ERM_COMMENTS=ERM.ERM_COMMENTS;

-- NEW TIMESTAMPS ARE UPDATED FOR NEW ERM ID IN DEST

SELECT DISTINCT MERM.ERM_TIMESTAMP FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

SELECT DISTINCT ERM.ERM_TIMESTAMP FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT  MERM.ERM_TIMESTAMP,ERM.ERM_TIMESTAMP
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM,ERM_ENTRY_DETAILS ERM
WHERE MERM.ERM_TIMESTAMP=ERM.ERM_TIMESTAMP ;

SELECT DISTINCT  MERM.ERM_TIMESTAMP,ERM.ERM_TIMESTAMP
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM LEFT JOIN ERM_ENTRY_DETAILS ERM
ON MERM.ERM_TIMESTAMP=ERM.ERM_TIMESTAMP;

SELECT DISTINCT MERM.ERM_TIMESTAMP,ERM.ERM_TIMESTAMP
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM RIGHT JOIN ERM_ENTRY_DETAILS ERM
ON MERM.ERM_TIMESTAMP=ERM.ERM_TIMESTAMP ;

SELECT *
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS
WHERE ERM_TIMESTAMP NOT IN      
(        
SELECT ERM_TIMESTAMP
FROM ERM_ENTRY_DETAILS
);

SELECT *
FROM ERM_ENTRY_DETAILS
WHERE ERM_TIMESTAMP NOT IN      
(        
SELECT ERM_TIMESTAMP 
FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS
);

--

SELECT DISTINCT ERM.ULD_ID FROM ERM_ENTRY_DETAILS ERM;

SELECT DISTINCT MERM.ERM_USERSTAMP FROM SOURCE_28062014.MIG_ERM_ENTRY_DETAILS MERM;

-- ERM OCCUPATION DETAILS

SELECT DISTINCT ERMO_ID FROM SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS;

SELECT DISTINCT ERMO_ID FROM ERM_OCCUPATION_DETAILS;

SELECT DISTINCT MERM.ERMO_ID , ERM.ERMO_ID 
FROM ERM_OCCUPATION_DETAILS ERM LEFT JOIN SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS MERM  ON  ERM.ERMO_ID = MERM.ERMO_ID ;

SELECT DISTINCT MEOD.ERMO_ID,EOD.ERMO_ID 
FROM SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS MEOD,ERM_OCCUPATION_DETAILS EOD WHERE MEOD.ERMO_ID=EOD.ERMO_ID;

--

SELECT DISTINCT ERMO_DATA FROM SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS;

SELECT DISTINCT ERMO_DATA FROM ERM_OCCUPATION_DETAILS;

SELECT DISTINCT MEOD.ERMO_DATA,EOD.ERMO_DATA 
FROM SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS MEOD,ERM_OCCUPATION_DETAILS EOD WHERE MEOD.ERMO_DATA=EOD.ERMO_DATA;

--

SELECT EOD.ULD_ID FROM ERM_OCCUPATION_DETAILS EOD;

SELECT MEOD.ERMO_USERSTAMP FROM SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS MEOD;

SELECT DISTINCT EOD.ERMO_TIMESTAMP FROM ERM_OCCUPATION_DETAILS EOD;

SELECT DISTINCT MEOD.ERMO_TIMESTAMP FROM SOURCE_28062014.MIG_ERM_OCCUPATION_DETAILS MEOD;

-- ERM CONFIGURATION

SELECT * FROM ERM_CONFIGURATION;

SELECT * FROM SOURCE_28062014.CONFIG_SQL_FORMAT WHERE CGN_ID=55 AND DATA IS NOT NULL;

SELECT EC.ULD_ID, ULD.ULD_USERSTAMP
FROM ERM_CONFIGURATION EC INNER JOIN USER_LOGIN_DETAILS ULD ON EC.ULD_ID = ULD.ULD_ID;

SELECT DISTINCT EC.CGN_ID,EC.ERMCN_DATA,EC.ERMCN_INITIALIZE_FLAG,EC.ULD_ID,EC.ERMCN_TIMESTAMP
FROM ERM_CONFIGURATION EC
INNER JOIN SOURCE_28062014.CONFIG_SQL_FORMAT  CSF ON CSF. CGN_ID=EC.CGN_ID;
