---- EXPENCE DETAIL TABLE

-- THIS EXPENCE DETAIL STARHUB AND  BIZ DETAIL SCDB FORMAT TABLE MATCH EVERYTHING TIMESTAMP REC BUT NOT MATCHED EVEN ONE RECODR IN REC_VERSION

SELECT DISTINCT BDSF.`TIMESTAMP` , EDSH.EDSH_TIMESTAMP , BDSF.EXPD_REC_VER , EDSH.EDSH_REC_VER 
FROM SASI_SOURCE_SCHEMA .BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_STARHUB EDSH 
WHERE BDSF.`TIMESTAMP` = EDSH.EDSH_TIMESTAMP OR BDSF.EXPD_REC_VER = EDSH.EDSH_REC_VER

-- ALL RECORD MATCHED IN EXPENSE DETAIL ELECTRICITY AND BIZ DETAIL NOT MATCHED IN REC_VERSION

SELECT DISTINCT BDSF.`TIMESTAMP`,EDE.EDE_TIMESTAMP , BDSF.EXPD_REC_VER, EDE.EDE_REC_VER 
FROM SASI_SOURCE_SCHEMA.BIZ_DETAIL_SCDB_FORMAT BDSF , EXPENSE_DETAIL_ELECTRICITY EDE 
WHERE BDSF.`TIMESTAMP`=EDE.EDE_TIMESTAMP OR BDSF.EXPD_REC_VER= EDE.EDE_REC_VER

SELECT DISTINCT  EDSH_TIMESTAMP FROM EXPENSE_DETAIL_STARHUB

SELECT DISTINCT  EDE_TIMESTAMP FROM EXPENSE_DETAIL_ELECTRICITY

-- ALL VALUES ARE MATCHED ON EXPENCE DIGITAL VOICE AND BIZ DETAIL 

SELECT DISTINCT BDSF.`TIMESTAMP`, EDDV.EDDV_TIMESTAMP ,BDSF.EXPD_DIGITAL_ACCOUNT_NO , EDDV.EDDV_DIGITAL_ACCOUNT_NO , BDSF.EXPD_DIGITAL_VOICE_NO,EDDV.EDDV_DIGITAL_VOICE_NO FROMSASI_SOURCE_SCHEMA.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_DIGITAL_VOICE EDDV WHERE BDSF.`TIMESTAMP` = EDDV.EDDV_TIMESTAMP AND BDSF.EXPD_DIGITAL_ACCOUNT_NO = EDDV.EDDV_DIGITAL_ACCOUNT_NO AND BDSF.EXPD_DIGITAL_VOICE_NO=EDDV.EDDV_DIGITAL_VOICE_NO

SELECT DISTINCT EDDV_TIMESTAMP, EDDV_DIGITAL_VOICE_NO, EDDV_DIGITAL_ACCOUNT_NO FROM EXPENSE_DETAIL_DIGITAL_VOICE

-- BIZ DETAIL HAVE 65 RECORDS.BUT HERE ONLY 29 RECORD ARE PRESENTED IN EXPENCE_DETAIL_AIRCON_SERVICE REMAIN 34 RECORD MISING .

SELECT DISTINCT BDSF.`TIMESTAMP`, DAS.EDAS_TIMESTAMP FROMSASI_SOURCE_SCHEMA.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_AIRCON_SERVICE DAS WHERE BDSF.`TIMESTAMP` = DAS.EDAS_TIMESTAMP

SELECT DISTINCT EDAS_TIMESTAMP FROM EXPENSE_DETAIL_AIRCON_SERVICE WHERE EDAS_TIMESTAMP='2014-02-13 11:18:57'

-- HERE MATCHING CAR NO FROM EXPENSE_DETAIL_CARPARK AND ONLY 6 DISTINCT RECORD MATCHING IN  BIZ_DETAIL_SCDB_FORMAT

SELECT  BDSF.EXPD_CAR_NO,EC.EDCP_CAR_NO, BDSF.`TIMESTAMP` , EC.EDCP_TIMESTAMP FROMSASI_SOURCE_SCHEMA.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_CARPARK EC WHERE BDSF.EXPD_CAR_NO=EC.EDCP_CAR_NO  AND BDSF.`TIMESTAMP` = EC.EDCP_TIMESTAMP

-- THE EXPENCE DETAIL STAFF SALAY VALUES NOT MATCHED WITH BIZ DETAIL 

SELECT DISTINCT BDSF.`TIMESTAMP`,DSS.EDSS_TIMESTAMP FROMSASI_SOURCE_SCHEMA.BIZ_DETAIL_SCDB_FORMAT BDSF, EXPENSE_DETAIL_STAFF_SALARY DSS WHERE BDSF.`TIMESTAMP`=DSS.EDSS_TIMESTAMP

-- EXPENSE DAILY TABLE

SELECT *FROM EXPENSE_AIRCON_SERVICE_BY

SELECT DISTINCT BIZ.`TIMESTAMP`,ESB.EASB_TIMESTAMP 
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BIZ , EXPENSE_AIRCON_SERVICE_BY ESB
WHERE BIZ.`TIMESTAMP`=ESB.EASB_TIMESTAMP

SELECT  `TIMESTAMP` FROMSASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT WHERE `TIMESTAMP`='2012-03-17 09:04:00'

-- 91 VALUES ARE MATCHED WITH EXPENSE AIRCON SERVICE AND BIZ DAILY 

SELECT DISTINCT BLSF.`TIMESTAMP`, EASE.EAS_TIMESTAMP 
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_AIRCON_SERVICE EASE 
WHERE BLSF.`TIMESTAMP` = EASE.EAS_TIMESTAMP

-- ALL VALUES ARE MATCHED

SELECT DISTINCT BLSF.EXP_AIRCON_SERVICED_DATE , EASE.EAS_DATE 
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_AIRCON_SERVICE EASE 
WHERE BLSF.EXP_AIRCON_SERVICED_DATE = EASE.EAS_DATE 

SELECT DISTINCT EAS_TIMESTAMP FROM EXPENSE_AIRCON_SERVICE

-- IN THE EXPENSE ELECTRICITY DATAS FROM PERIOD DATA AND INVOICE DATA ARE SAME IN BIZ DAILY TABLE

SELECT DISTINCT EE.EE_INVOICE_DATE,BLSF.EXP_ELC_INVOICE_DATE , EE.EE_FROM_PERIOD, BLSF.EXP_ELC_FROM_PERIOD -- ,EE.EE_COMMENTS,BLSF.EXP_ELC_COMMENTS
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_ELECTRICITY EE
WHERE EE.EE_INVOICE_DATE=BLSF.EXP_ELC_INVOICE_DATE OR EE.EE_FROM_PERIOD= BLSF.EXP_ELC_FROM_PERIOD -- OR EE.EE_COMMENTS=BLSF.EXP_ELC_COMMENTS

SELECT DISTINCT EE.EE_COMMENTS,BLSF.EXP_ELC_COMMENTS
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_ELECTRICITY EE
WHERE  EE.EE_COMMENTS=BLSF.EXP_ELC_COMMENTS


-- ALL THE VALUES ARE MATCHED WITH BIZ DAILY AND EXPENCE DIGITAL VOICE

SELECT DISTINCT  EDV.EDV_INVOICE_DATE,BLSF.EXP_DIGITAL_INVOICE_DATE , EDV.EDV_FROM_PERIOD,BLSF.EXP_DIGITAL_FROM_PERIOD ,EDV.EDV_AMOUNT,BLSF.EXP_DIGITAL_AMOUNT
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_DIGITAL_VOICE EDV 
WHERE EDV.EDV_INVOICE_DATE=BLSF.EXP_DIGITAL_INVOICE_DATE AND EDV.EDV_FROM_PERIOD=BLSF.EXP_DIGITAL_FROM_PERIOD OR EDV.EDV_AMOUNT=BLSF.EXP_DIGITAL_AMOUNT

-- ALL THE VALUES ARE MATCHED WITH BIZ DAILY AND EXPENSE FACULTY USE

SELECT DISTINCT  BLSF.EXP_FACILITY_INVOICE_DATE,EFU.EFU_INVOICE_DATE , BLSF.EXP_FACILITY_AMOUNT,EFU.EFU_AMOUNT , BLSF.`TIMESTAMP` , EFU.EFU_TIMESTAMP 
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_FACILITY_USE EFU 
WHERE BLSF.EXP_FACILITY_INVOICE_DATE=EFU.EFU_INVOICE_DATE AND BLSF.EXP_FACILITY_AMOUNT=EFU.EFU_AMOUNT AND BLSF.`TIMESTAMP` = EFU.EFU_TIMESTAMP

-- ALL THE VALUES ARE MATCHED WITH BIZ DAILY AND EXPENSE CARPARK

SELECT DISTINCT ECP.ECP_INVOICE_DATE,BLSF.EXP_CAR_INVOICE_DATE , ECP.ECP_AMOUNT,BLSF.EXP_CAR_AMOUNT
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_CARPARK ECP 
WHERE ECP.ECP_INVOICE_DATE=BLSF.EXP_CAR_INVOICE_DATE AND ECP.ECP_AMOUNT=BLSF.EXP_CAR_AMOUNT

-- RECORD MATCHED WITH EXPENSE HOUSEKEEPING WITH SOURCE TABLE BIZ DAILY

SELECT DISTINCT EHK.EHK_WORK_DATE,BLSF.EXP_HK_WORK_DATE , EHK.EHK_DURATION,BLSF.EXP_HK_DURATION  
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_HOUSEKEEPING EHK 
WHERE EHK.EHK_WORK_DATE=BLSF.EXP_HK_WORK_DATE AND EHK.EHK_DURATION=BLSF.EXP_HK_DURATION

SELECT DISTINCT  EHK_DURATION FROM EXPENSE_HOUSEKEEPING

-- RECORDS ARE MATCHED WITH THE EXPENSE HOUSEKEEPING PAYMENT AND DAILY BIZ

SELECT DISTINCT  EHKP.EHKP_PAID_DATE,BLSF.EXP_HKP_PAID_DATE 
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_HOUSEKEEPING_PAYMENT EHKP
WHERE EHKP.EHKP_PAID_DATE=BLSF.EXP_HKP_PAID_DATE

SELECT DISTINCT EHKP_PAID_DATE,EHKP_FOR_PERIOD FROM EXPENSE_HOUSEKEEPING_PAYMENT 

-- ALL THE RECORDS ARE MATCHED WITH THE EXENSE HOUSEKEEPING UNIT AND BIZ DAILY

SELECT DISTINCT BLSF.EXP_HKP_UNIT_NO, EHKU.EHKU_UNIT_NO , BLSF.`TIMESTAMP`,EHKU.EHKU_TIMESTAMP 
FROM EXPENSE_HOUSEKEEPING_UNIT EHKU ,SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF 
WHERE BLSF.EXP_HKP_UNIT_NO = EHKU.EHKU_UNIT_NO AND BLSF.`TIMESTAMP`=EHKU.EHKU_TIMESTAMP

-- ONLY ALL 358 RECORDS ARE MATCHED ON BIZ DAILY AND EXPENCE PITTY CASH

SELECT*FROM EXPENSE_PETTY_CASH

SELECT DISTINCT BLSF.EXP_PETTY_DATE,EPC.EPC_DATE , EPC.EPC_BALANCE,BLSF.EXP_PETTY_CURRENT_BAL
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT BLSF, EXPENSE_PETTY_CASH EPC 
WHERE BLSF.EXP_PETTY_DATE=EPC.EPC_DATE AND EPC.EPC_BALANCE=BLSF.EXP_PETTY_CURRENT_BAL

-- ALL RECORDS ARE MATCHED WITH BIZ DAILY AND EXPENSE PURCHASE NEW CARD

SELECT DISTINCT EPNC.EPNC_NUMBER,SRCC.EXP_CARD_NUMBER ,  EPNC.EPNC_AMOUNT ,SRCC.EXP_CARD_AMOUNT
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT SRCC, EXPENSE_PURCHASE_NEW_CARD EPNC 
WHERE EPNC.EPNC_NUMBER=SRCC.EXP_CARD_NUMBER AND EPNC.EPNC_AMOUNT =SRCC.EXP_CARD_AMOUNT

-- ALL VALUES ARE MATCHED WITH BIZ DAILY AND EXPENSE MOVING IN AND OUT

SELECT DISTINCT EMIO.EMIO_AMOUNT,STC.EXP_MOVI_IN_OUT_AMOUNT, EMIO.EMIO_INVOICE_DATE,STC.EXP_MOVI_IN_OUT_INVOICE_DATE
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT STC, EXPENSE_MOVING_IN_AND_OUT EMIO 
WHERE EMIO.EMIO_AMOUNT=STC.EXP_MOVI_IN_OUT_AMOUNT
AND EMIO.EMIO_INVOICE_DATE=STC.EXP_MOVI_IN_OUT_INVOICE_DATE

-- ALL VALUES ARE MATCHED WITH BIZ DAILY AND EXPENSE STARHUB

SELECT DISTINCT ESH.ESH_AMOUNT,STCB.EXP_SHB_AMOUNT ,ESH.ESH_INVOICE_DATE,STCB.EXP_SHB_INVOICE_DATE 
FROM SASI_SOURCE_SCHEMA.BIZ_DAILY_SCDB_FORMAT STCB, EXPENSE_STARHUB ESH 
WHERE ESH.ESH_AMOUNT=STCB.EXP_SHB_AMOUNT AND ESH.ESH_INVOICE_DATE=STCB.EXP_SHB_INVOICE_DATE

SELECT DISTINCT ESH_AMOUNT, ESH_INVOICE_DATE FROM EXPENSE_STARHUB

-- UNIT

-- ALL THE VALUES ARE MATCHED IN ACCESS STAM DETAILS AND UNIT SCDB

SELECT*FROM UNIT_ACCESS_STAMP_DETAILS

SELECT DISTINCT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS

SELECT DISTINCT SCU.UNIT_ACCESS_CARD,UAS.UASD_ACCESS_CARD 
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU 
WHERE UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD

-- ALL THE VALUES ARE MATCHED IN UNIT ACCOUT DETAIL AND UNIT SCDB

SELECT DISTINCT UACD_ACC_NO FROM UNIT_ACCOUNT_DETAILS

SELECT DISTINCT  UAD.UACD_ACC_NO,SCU.UNIT_ACC_NO 
FROM UNIT_ACCOUNT_DETAILS UAD, SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU WHERE UAD.UACD_ACC_NO=SCU.UNIT_ACC_NO

-- ALL THE VALUES ARE MATCHED IN UNIT DETAILS AND UNIT SCDB

SELECT *FROM UNIT_DETAILS

SELECT DISTINCT UD_START_DATE FROM UNIT_DETAILS

SELECT DISTINCT UD.UD_START_DATE,UD.UD_END_DATE FROM UNIT_DETAILS UD

SELECT  DISTINCT UD.UD_START_DATE,SCU.UNIT_START_DATE , UD.UD_END_DATE,SCU.UNIT_END_DATE 
FROM UNIT_DETAILS UD , SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU
WHERE UD.UD_START_DATE=SCU.UNIT_START_DATE AND UD.UD_END_DATE=SCU.UNIT_END_DATE

-- ALL THE THREE VALUES ARE MATCHED WITH UNIT DUTY DETAILS AND UNIT SCDB

SELECT*FROM UNIT_STAMP_DUTY_TYPE

SELECT SCU.`TIMESTAMP`,USD.USDT_TIMESTAMP 
FROM SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU, UNIT_STAMP_DUTY_TYPE USD WHERE SCU.`TIMESTAMP`=USD.USDT_TIMESTAMP

-- ALL THE VALUES ARE MATCHED IN UNIT LOGIN DETAIL, UNIT SCDB

SELECT DISTINCT ULDTL_WEBPWD FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBPWD IS NOT NULL
SELECT DISTINCT ULDTL_WEBLOGIN FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBLOGIN IS NOT NULL

SELECT DISTINCT SCU.UNIT_WEBLOGIN, LD.ULDTL_WEBLOGIN 
FROM SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD WHERE SCU.UNIT_WEBLOGIN=LD.ULDTL_WEBLOGIN

SELECT DISTINCT SCU.UNIT_WEBPWD, LD.ULDTL_WEBPWD 
FROM SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD WHERE SCU.UNIT_WEBPWD=LD.ULDTL_WEBPWD

SELECT DISTINCT SCU.`TIMESTAMP`,ULD.ULDTL_TIMESTAMP
FROM SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS ULD WHERE SCU.`TIMESTAMP`=ULD.ULDTL_TIMESTAMP

--  ALL THE VALUES ARE MATCHED WITH UNIT SCDB AND UNIT ROOM TYPE 

SELECT DISTINCT URTD_ROOM_TYPE FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ROOM_TYPE IS NOT NULL 

SELECT DISTINCT SCU.UNIT_ROOM_TYPE , RM.URTD_ROOM_TYPE 
FROM SASI_SOURCE_SCHEMA.UNIT_SCDB_FORMAT SCU, UNIT_ROOM_TYPE_DETAILS RM WHERE SCU.UNIT_ROOM_TYPE = RM.URTD_ROOM_TYPE

-- STAFF EXPENCE

-- ALL THE VALUES ARE MATCHED

SELECT * FROM EXPENSE_DETAIL_STAFF_SALARY

SELECT DISTINCT EDSS.EDSS_SALARY_AMOUNT ,SFSF.SED_SALARY_AMOUNT 
FROM SASI_SOURCE_SCHEMA.STAFF_DETAIL_SCDB_FORMAT SFSF, EXPENSE_DETAIL_STAFF_SALARY EDSS 
WHERE EDSS.EDSS_SALARY_AMOUNT = SFSF.SED_SALARY_AMOUNT

-- VALUES ARE MATCHED IN EXPENSE STAFF SALARY AND STAFF DIALY

SELECT* FROM EXPENSE_STAFF_SALARY

SELECT DISTINCT ESS_SALARY_AMOUNT FROM EXPENSE_STAFF_SALARY

SELECT DISTINCT ESS.ESS_SALARY_AMOUNT,SASF.SE_SALARY_AMOUNT 
FROM SASI_SOURCE_SCHEMA.STAFF_DAILY_SCDB_FORMAT SASF , EXPENSE_STAFF_SALARY ESS
WHERE ESS.ESS_SALARY_AMOUNT=SASF.SE_SALARY_AMOUNT 

SELECT DISTINCT ESS.ESS_INVOICE_DATE , SASF.SE_STAFF_INVOICE_DATE
FROM SASI_SOURCE_SCHEMA.STAFF_DAILY_SCDB_FORMAT SASF , EXPENSE_STAFF_SALARY ESS
WHERE ESS.ESS_INVOICE_DATE = SASF.SE_STAFF_INVOICE_DATE

-- ALL THE VALUES ARE MATCHED IN EXPENCE STAFF AND STAFF DAILY SCDB

SELECT  * FROM EXPENSE_STAFF

SELECT DISTINCT ES_INVOICE_AMOUNT FROM EXPENSE_STAFF

SELECT DISTINCT   SFF.ES_INVOICE_AMOUNT,SCAI.SE_STAFF_INVOICE_AMOUNT
FROM SASI_SOURCE_SCHEMA.STAFF_DAILY_SCDB_FORMAT SCAI, EXPENSE_STAFF SFF
WHERE  SFF.ES_INVOICE_AMOUNT=SCAI.SE_STAFF_INVOICE_AMOUNT 

SELECT DISTINCT   SFF.ES_INVOICE_DATE,SCAI.SE_STAFF_INVOICE_DATE
FROM SASI_SOURCE_SCHEMA.STAFF_DAILY_SCDB_FORMAT SCAI, EXPENSE_STAFF SFF
WHERE  SFF.ES_INVOICE_DATE=SCAI.SE_STAFF_INVOICE_DATE 

-- ALL THE VALUES ARE MATCHED IN EXPENCSE STAFF AGENT AND STAFF DAILY SCDB

SELECT DISTINCT EA_COMM_AMOUNT FROM EXPENSE_AGENT 

SELECT * FROM EXPENSE_AGENT

SELECT DISTINCT SDSF.SE_AGENT_COMM_AMOUNT,EA.EA_COMM_AMOUNT 
FROM SASI_SOURCE_SCHEMA.STAFF_DAILY_SCDB_FORMAT SDSF, EXPENSE_AGENT EA 
WHERE SDSF.SE_AGENT_COMM_AMOUNT=EA.EA_COMM_AMOUNT

SELECT DISTINCT SDSF.SE_AGENT_DATE,EA.EA_DATE 
FROM SASI_SOURCE_SCHEMA.STAFF_DAILY_SCDB_FORMAT SDSF, EXPENSE_AGENT EA 
WHERE SDSF.SE_AGENT_DATE=EA.EA_DATE

-- BANK 
SELECT *FROM BANK_TRANSFER_MODELS
-- ALL ARE MATCH IN BANK MODELS.
SELECT MBTM.BTM_DATA,BTM.BTM_DATA FROM SASI_SOURCE_SCHEMA.MIG_BANK_TRANSFER_MODELS MBTM, BANK_TRANSFER_MODELS BTM WHERE MBTM.BTM_DATA=BTM.BTM_DATA

SELECT DISTINCT MBTM.BTM_TIMESTAMP,BTM.BTM_TIMESTAMP FROM SASI_SOURCE_SCHEMA.MIG_BANK_TRANSFER_MODELS MBTM, BANK_TRANSFER_MODELS BTM WHERE MBTM.BTM_TIMESTAMP=BTM.BTM_TIMESTAMP

SELECT DISTINCT BTM_TIMESTAMP FROM BANK_TRANSFER_MODELS

SELECT * FROM BANK_TRANSFER_STATUS_DETAILS
SELECT DISTINCT BT_DATE FROM BANK_TRANSFER
SELECT DISTINCT MBT.BT_DATE,BT.BT_DATE FROM SASI_SOURCE_SCHEMA.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_DATE=BT.BT_DATE


SELECT DISTINCT BT_AMOUNT FROM BANK_TRANSFER
-- 3(RECORDS)-> 6300,7200,764 RECORDS ARE NOT AVAILABLE AND 127 RECORD PRESENT IN DESTIONATION SOURCE HAVE 130 RECORD
SELECT DISTINCT MBT.BT_AMOUNT,BT.BT_AMOUNT FROM SASI_SOURCE_SCHEMA.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_AMOUNT=BT.BT_AMOUNT
SELECT DISTINCT MBT.BT_AMOUNT , BT.BT_AMOUNT FROM SASI_SOURCE_SCHEMA.MIG_BANK_TRANSFER MBT LEFT JOIN  BANK_TRANSFER BT ON MBT.BT_AMOUNT = BT.BT_AMOUNT

SELECT*FROM BANK_TRANSFER

SELECT DISTINCT BT_AMOUNT FROM BANK_TRANSFER

SELECT DISTINCT  BT_DATE FROM BANK_TRANSFER

SELECT DISTINCT MBT.BT_AMOUNT , BT.BT_AMOUNT FROM SASI_SOURCE_SCHEMA.MIG_BANK_TRANSFER MBT LEFT JOIN  BANK_TRANSFER BT ON MBT.BT_AMOUNT = BT.BT_AMOUNT
 
SELECT DISTINCT ULD_ID,BTM_ID FROM BANK_TRANSFER_MODELS
SELECT DISTINCT ULD_ID FROM BANK_TRANSFER

SELECT DISTINCT BTM.ULD_ID,BT.ULD_ID ,BTM.BTM_ID,BT.BTM_ID FROM BANK_TRANSFER_MODELS BTM
INNER JOIN BANK_TRANSFER BT ON BTM.ULD_ID=BT.ULD_ID AND BTM.BTM_ID=BT.BTM_ID

SELECT DISTINCT AA.BT_ID , BT.BT_ID,BB.BT_ID,AA.BT_ID FROM BANK_TRANSFER_STATUS_DETAILS AA 
INNER JOIN BANK_TRANSFER BT ON AA.BT_ID = BT.BT_ID
INNER JOIN BANK_TRANSFER_DETAIL BB ON BB.BT_ID=AA.BT_ID 


SELECT *FROM BANKTT_CONFIGURATION
SELECT DISTINCT CGN_ID FROM BANKTT_CONFIGURATION

SELECT DISTINCT CGN_ID FROM BANKTT_CONFIGURATION


ALL THE VALUE ARE MATCHED

SELECT * FROM SASI_SOURCE_SCHEMA.CONFIG_SQL_FORMAT WHERE CGN_ID=56;

SELECT * FROM SASI_SOURCE_SCHEMA.CONFIG_SQL_FORMAT WHERE CGN_ID=69;

SELECT * FROM SASI_SOURCE_SCHEMA.CONFIG_SQL_FORMAT WHERE CGN_ID=70;

SELECT * FROM SASI_SOURCE_SCHEMA.CONFIG_SQL_FORMAT WHERE CGN_ID=72;

SELECT *FROM BANK_TRANSFER_STATUS_DETAILS
