-- UNIT --46

SELECT*FROM UNIT;

SELECT * FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU;

-- UNIT ID, UNIT NO

SELECT UNIT_NO FROM UNIT;

SELECT UNIT_NO FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT GROUP BY UNIT_NO ORDER BY UNIT_NO;

SELECT DISTINCT(U.UNIT_NO),U1.UNIT_NO 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT U , UNIT U1 
WHERE U.UNIT_NO=U1.UNIT_NO ORDER BY U.UNIT_NO;

-- UNIT_ROOM_TYPE_DETAILS --15

SELECT * FROM UNIT_ROOM_TYPE_DETAILS;

SELECT DISTINCT USF.UNIT_ROOM_TYPE,ULD.ULD_ID,USF.TIMESTAMP 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,USER_LOGIN_DETAILS ULD 
WHERE USF.UNIT_ROOM_TYPE IS NOT NULL AND USF.USERSTAMP=ULD.ULD_LOGINID GROUP BY USF.UNIT_ROOM_TYPE;

--

SELECT DISTINCT URTD_ROOM_TYPE FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ROOM_TYPE IS NOT NULL ;

SELECT DISTINCT UNIT_ROOM_TYPE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ROOM_TYPE IS NOT NULL ;

SELECT DISTINCT(USF.UNIT_ROOM_TYPE),URTD.URTD_ROOM_TYPE 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,UNIT_ROOM_TYPE_DETAILS URTD
WHERE USF.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND USF.UNIT_ROOM_TYPE IS NOT NULL;

-- 

SELECT URTD_TIMESTAMP FROM UNIT_ROOM_TYPE_DETAILS;

SELECT USF.TIMESTAMP 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,USER_LOGIN_DETAILS ULD
WHERE USF.UNIT_ROOM_TYPE IS NOT NULL AND USF.USERSTAMP=ULD.ULD_LOGINID GROUP BY USF.UNIT_ROOM_TYPE;

SELECT SUBTIME(USF.TIMESTAMP,'08:00:00'),URTD.URTD_TIMESTAMP
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,UNIT_ROOM_TYPE_DETAILS URTD,USER_LOGIN_DETAILS ULD
WHERE  USF.UNIT_ROOM_TYPE IS NOT NULL AND USF.USERSTAMP=ULD.ULD_LOGINID AND SUBTIME(USF.TIMESTAMP,'08:00:00')=URTD.URTD_TIMESTAMP GROUP BY USF.UNIT_ROOM_TYPE;

-- 

SELECT DISTINCT ULD_ID FROM UNIT_ROOM_TYPE_DETAILS;

SELECT DISTINCT USERSTAMP FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ROOM_TYPE IS NOT NULL AND
UNIT_ROOM_TYPE!='STUDIO 2' OR UNIT_ROOM_TYPE!='STUDIO1' ;

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID 
INNER JOIN UNIT_ROOM_TYPE_DETAILS C ON B.ULD_ID=C.ULD_ID;

-- UNIT_STAMP_DUTY_TYPE --3

SELECT * FROM UNIT_STAMP_DUTY_TYPE;

SELECT DISTINCT T.UNIT_STAMPDUTYTYPE,ULD.ULD_ID,T.TIMESTAMP 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT T,USER_LOGIN_DETAILS ULD 
WHERE T.UNIT_STAMPDUTYTYPE IS NOT NULL AND T.USERSTAMP=ULD.ULD_LOGINID GROUP BY T.UNIT_STAMPDUTYTYPE;

--

SELECT DISTINCT USDT_DATA FROM UNIT_STAMP_DUTY_TYPE;

SELECT DISTINCT UNIT_STAMPDUTYTYPE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_STAMPDUTYTYPE IS NOT NULL;

SELECT DISTINCT(USF.UNIT_STAMPDUTYTYPE),USDT.USDT_DATA 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,UNIT_STAMP_DUTY_TYPE USDT
WHERE USF.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND USF.UNIT_STAMPDUTYTYPE IS NOT NULL;

--

SELECT USDT_TIMESTAMP FROM UNIT_STAMP_DUTY_TYPE;

SELECT USF.TIMESTAMP FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,USER_LOGIN_DETAILS ULD 
WHERE USF.UNIT_STAMPDUTYTYPE IS NOT NULL AND USF.USERSTAMP=ULD.ULD_LOGINID GROUP BY USF.UNIT_STAMPDUTYTYPE;

SELECT SUBTIME(USF.TIMESTAMP,'08:00:00'),USDT.USDT_TIMESTAMP
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,UNIT_STAMP_DUTY_TYPE USDT,USER_LOGIN_DETAILS ULD
WHERE  USF.UNIT_STAMPDUTYTYPE IS NOT NULL AND USF.USERSTAMP=ULD.ULD_LOGINID AND SUBTIME(USF.TIMESTAMP,'08:00:00')=USDT.USDT_TIMESTAMP GROUP BY USF.UNIT_STAMPDUTYTYPE;

--

SELECT DISTINCT ULD_ID FROM UNIT_STAMP_DUTY_TYPE;

SELECT DISTINCT USERSTAMP FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_STAMPDUTYTYPE IS NOT NULL;

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT A
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN UNIT_STAMP_DUTY_TYPE C ON B.ULD_ID=C.ULD_ID;

-- UNIT_DETAILS --46

SELECT * FROM UNIT_DETAILS;

SELECT DISTINCT(U.UNIT_ID),TUSF.UNIT_START_DATE,TUSF.UNIT_END_DATE,TUSF.UNIT_RENTAL,TUSF.UNIT_OBSOLETE,TUSF.UD_NON_EI,TUSF.UNIT_COMMENTS,ULD.ULD_ID,TUSF.TIMESTAMP
FROM UNIT U INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF ON U.UNIT_NO= TUSF.UNIT_NO JOIN USER_LOGIN_DETAILS ULD 
WHERE TUSF.UNIT_START_DATE IS NOT NULL AND TUSF.UNIT_END_DATE IS NOT NULL AND TUSF.UNIT_RENTAL IS NOT NULL AND ULD.ULD_LOGINID=TUSF.USERSTAMP GROUP BY UNIT_ID;

-- 
 
SELECT DISTINCT UNIT_ID FROM UNIT_DETAILS;

SELECT DISTINCT UNIT_NO FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT

SELECT DISTINCT (U.UNIT_NO),U1.UNIT_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT U,UNIT_DETAILS U1,UNIT U2
WHERE U.UNIT_NO=U2.UNIT_NO AND U2.UNIT_ID=U1.UNIT_ID ORDER BY U2.UNIT_ID;

--

SELECT UD_START_DATE,UD_END_DATE FROM UNIT_DETAILS GROUP BY UNIT_ID;

SELECT UNIT_START_DATE,UNIT_END_DATE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT 
WHERE UNIT_START_DATE IS NOT NULL AND UNIT_END_DATE IS NOT NULL ORDER BY UNIT_NO;

SELECT (UD.UNIT_ID),UD.UD_START_DATE,SCU.UNIT_START_DATE , UD.UD_END_DATE,SCU.UNIT_END_DATE
FROM UNIT_DETAILS UD , SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU 
WHERE UD.UD_START_DATE=SCU.UNIT_START_DATE AND UD.UD_END_DATE=SCU.UNIT_END_DATE GROUP BY UD.UNIT_ID;

--

SELECT UD_PAYMENT,UNIT_ID FROM UNIT_DETAILS GROUP BY UNIT_ID;

SELECT UNIT_RENTAL,UNIT_NO FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_RENTAL IS NOT NULL ORDER BY UNIT_NO;

SELECT (UD.UNIT_ID),TUSF.UNIT_RENTAL,UD.UD_PAYMENT 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF,UNIT_DETAILS UD 
WHERE TUSF.UNIT_RENTAL=UD.UD_PAYMENT GROUP BY UD.UNIT_ID;

-- 

SELECT UD_OBSOLETE FROM UNIT_DETAILS WHERE UD_OBSOLETE IS NOT NULL ORDER BY UNIT_ID;

SELECT  UNIT_OBSOLETE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_OBSOLETE IS NOT NULL ORDER BY UNIT_NO;

SELECT DISTINCT(UD.UNIT_ID),TUSF.UNIT_OBSOLETE,UD.UD_OBSOLETE
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF,UNIT_DETAILS UD 
WHERE TUSF.UNIT_OBSOLETE=UD.UD_OBSOLETE ORDER BY UD.UNIT_ID;

SELECT  UD.UNIT_ID, UD.UD_START_DATE,SCU.UNIT_START_DATE , UD.UD_END_DATE,SCU.UNIT_END_DATE , UD.UD_OBSOLETE,SCU.UNIT_OBSOLETE
FROM UNIT_DETAILS UD , SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU
WHERE UD.UD_START_DATE=SCU.UNIT_START_DATE AND UD.UD_END_DATE=SCU.UNIT_END_DATE AND UD.UD_OBSOLETE=SCU.UNIT_OBSOLETE

--

SELECT UD_NON_EI FROM UNIT_DETAILS WHERE UD_COMMENTS IS NOT NULL GROUP BY UNIT_ID;

SELECT UD_NON_EI FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT 
WHERE UNIT_COMMENTS IS NOT NULL AND UNIT_RENTAL IS NOT NULL AND UNIT_START_DATE IS NOT NULL AND UNIT_END_DATE IS NOT NULL ORDER BY UNIT_NO;

SELECT DISTINCT(UD.UNIT_ID),TUSF.UD_NON_EI,UD.UD_NON_EI 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF,UNIT_DETAILS UD
WHERE TUSF.UD_NON_EI=UD.UD_NON_EI AND UNIT_COMMENTS IS NOT NULL AND UNIT_RENTAL IS NOT NULL AND UNIT_START_DATE IS NOT NULL AND UNIT_END_DATE IS NOT NULL ORDER BY UNIT_NO;

--

SELECT UD_COMMENTS FROM UNIT_DETAILS WHERE UD_COMMENTS IS NOT NULL GROUP BY UNIT_ID;

SELECT UNIT_COMMENTS FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT 
WHERE UNIT_COMMENTS IS NOT NULL AND UNIT_RENTAL IS NOT NULL AND UNIT_START_DATE IS NOT NULL AND UNIT_END_DATE IS NOT NULL ORDER BY UNIT_NO;

SELECT (UD.UNIT_ID),TUSF.UNIT_COMMENTS,UD.UD_COMMENTS
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF,UNIT_DETAILS UD 
WHERE TUSF.UNIT_COMMENTS=UD.UD_COMMENTS AND  UNIT_RENTAL IS NOT NULL AND UNIT_START_DATE IS NOT NULL AND UNIT_END_DATE IS NOT NULL ORDER BY UD.UNIT_ID;

--

SELECT DISTINCT ULD_ID FROM UNIT_DETAILS;

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN UNIT_DETAILS C ON B.ULD_ID=C.ULD_ID;

--

SELECT UD_TIMESTAMP FROM UNIT_DETAILS ORDER BY UNIT_ID;

SELECT TUSF.TIMESTAMP FROM UNIT U 
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF ON U.UNIT_NO= TUSF.UNIT_NO 
INNER JOIN USER_LOGIN_DETAILS ULD ON ULD.ULD_LOGINID=TUSF.USERSTAMP
WHERE TUSF.UNIT_START_DATE IS NOT NULL AND TUSF.UNIT_END_DATE IS NOT NULL AND TUSF.UNIT_RENTAL IS NOT NULL GROUP BY U.UNIT_ID;

SELECT SUBTIME(TUSF.TIMESTAMP,'08:00:00'),UD.UD_TIMESTAMP FROM UNIT U 
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF ON U.UNIT_NO= TUSF.UNIT_NO 
INNER JOIN UNIT_DETAILS UD ON SUBTIME(TUSF.TIMESTAMP,'08:00:00')=UD.UD_TIMESTAMP
INNER JOIN USER_LOGIN_DETAILS ULD ON ULD.ULD_LOGINID=TUSF.USERSTAMP
WHERE TUSF.UNIT_START_DATE IS NOT NULL AND TUSF.UNIT_END_DATE IS NOT NULL AND TUSF.UNIT_RENTAL IS NOT NULL  GROUP BY U.UNIT_ID;

--

SELECT DISTINCT UD.*
FROM UNIT_DETAILS UD
INNER JOIN UNIT U ON (UD.UNIT_ID=U.UNIT_ID)
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU ON (U.UNIT_NO=SCU.UNIT_NO) -- AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )

-- UNIT_LOGIN_DETAILS --38

SELECT * FROM UNIT_LOGIN_DETAILS;

SELECT U.UNIT_ID,TUSF.UNIT_DOORCODE,TUSF.UNIT_WEBLOGIN,TUSF.UNIT_WEBPWD,ULD.ULD_ID,TUSF.TIMESTAMP 
FROM UNIT U INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF ON U.UNIT_NO= TUSF.UNIT_NO JOIN USER_LOGIN_DETAILS ULD 
WHERE (TUSF.UNIT_DOORCODE IS NOT NULL OR TUSF.UNIT_WEBLOGIN IS NOT NULL OR TUSF.UNIT_WEBPWD) AND ULD.ULD_LOGINID=TUSF.USERSTAMP GROUP BY TUSF.UNIT_DOORCODE;

--

SELECT DISTINCT ULDTL_WEBPWD FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBPWD IS NOT NULL;

SELECT DISTINCT UNIT_WEBPWD FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_WEBPWD IS NOT NULL;

SELECT DISTINCT SCU.UNIT_WEBPWD, LD.ULDTL_WEBPWD 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD
WHERE SCU.UNIT_WEBPWD=LD.ULDTL_WEBPWD;

--

SELECT DISTINCT ULDTL_DOORCODE FROM UNIT_LOGIN_DETAILS WHERE ULDTL_DOORCODE IS NOT NULL;

SELECT DISTINCT UNIT_DOORCODE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_DOORCODE IS NOT NULL; 

SELECT DISTINCT SCU.UNIT_DOORCODE, LD.ULDTL_DOORCODE 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD
WHERE SCU.UNIT_DOORCODE =LD.ULDTL_DOORCODE;

--

SELECT DISTINCT ULDTL_WEBLOGIN FROM UNIT_LOGIN_DETAILS WHERE ULDTL_WEBLOGIN IS NOT NULL;

SELECT DISTINCT UNIT_WEBLOGIN FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_WEBLOGIN IS NOT NULL ;

SELECT DISTINCT SCU.UNIT_WEBLOGIN, LD.ULDTL_WEBLOGIN
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU, UNIT_LOGIN_DETAILS LD 
WHERE SCU.UNIT_WEBLOGIN =LD.ULDTL_WEBLOGIN;

SELECT *FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE  CHAR_LENGTH(UNIT_WEBLOGIN)>8 

SELECT *
FROM UNIT_LOGIN_DETAILS
WHERE ULDTL_WEBLOGIN NOT IN      
(        
SELECT UNIT_WEBLOGIN
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT 
);

--

SELECT DISTINCT ULD_ID FROM UNIT_LOGIN_DETAILS;

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN UNIT_LOGIN_DETAILS C ON B.ULD_ID=C.ULD_ID;

--

SELECT ULDTL_TIMESTAMP FROM UNIT_LOGIN_DETAILS;

SELECT TUSF.TIMESTAMP FROM UNIT U 
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF ON U.UNIT_NO= TUSF.UNIT_NO 
INNER JOIN USER_LOGIN_DETAILS ULD 
WHERE (TUSF.UNIT_DOORCODE IS NOT NULL OR TUSF.UNIT_WEBLOGIN IS NOT NULL OR TUSF.UNIT_WEBPWD) AND ULD.ULD_LOGINID=TUSF.USERSTAMP GROUP BY TUSF.UNIT_DOORCODE;

SELECT SUBTIME(USF.TIMESTAMP,'08:00:00'),ULOD.ULDTL_TIMESTAMP 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT USF,UNIT_LOGIN_DETAILS ULOD,USER_LOGIN_DETAILS ULD
WHERE  USF.UNIT_DOORCODE IS NOT NULL AND USF.USERSTAMP=ULD.ULD_LOGINID AND SUBTIME(USF.TIMESTAMP,'08:00:00')=ULOD.ULDTL_TIMESTAMP GROUP BY USF.UNIT_DOORCODE;

--

SELECT DISTINCT LD.*
FROM UNIT_LOGIN_DETAILS LD 
INNER JOIN UNIT U ON (LD.UNIT_ID=U.UNIT_ID)
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU ON (U.UNIT_NO=SCU.UNIT_NO) -- AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )

-- UNIT_ACCOUNT_DETAILS --27

SELECT * FROM UNIT_ACCOUNT_DETAILS;

SELECT DISTINCT(U.UNIT_ID),TUSF.UNIT_ACC_NO,TUSF.UNIT_ACC_NAME,TUSF.UNIT_BANKCODE,TUSF.UNIT_BRANCHCODE,TUSF.UNIT_BANKADDR
FROM UNIT U 
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF ON U.UNIT_NO= TUSF.UNIT_NO 
WHERE TUSF.UNIT_ACC_NO IS NOT NULL OR TUSF.UNIT_ACC_NAME IS NOT NULL OR TUSF.UNIT_BANKCODE IS NOT NULL OR
TUSF.UNIT_BRANCHCODE IS NOT NULL OR TUSF.UNIT_BANKADDR IS NOT NULL ORDER BY TUSF.UNIT_ACC_NO;

-- 

SELECT  UACD_ACC_NO FROM UNIT_ACCOUNT_DETAILS;

SELECT  UNIT_ACC_NO FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ACC_NO IS NOT NULL;

SELECT   UAD.UACD_ACC_NO,SCU.UNIT_ACC_NO 
FROM UNIT_ACCOUNT_DETAILS UAD, SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU
WHERE UAD.UACD_ACC_NO=SCU.UNIT_ACC_NO GROUP BY SCU.UNIT_NO;

--

SELECT  UACD_ACC_NAME FROM UNIT_ACCOUNT_DETAILS;

SELECT  UNIT_ACC_NAME FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ACC_NAME IS NOT NULL GROUP BY UNIT_NO;

SELECT UAD.UACD_ACC_NAME ,SCU.UNIT_ACC_NAME 
FROM UNIT_ACCOUNT_DETAILS UAD, SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU
WHERE UAD.UACD_ACC_NAME =SCU.UNIT_ACC_NAME GROUP BY UNIT_NO;

--

SELECT UACD_BANK_CODE FROM UNIT_ACCOUNT_DETAILS;

SELECT UNIT_BANKCODE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_BANKCODE IS NOT NULL;

SELECT UAD.UACD_BANK_CODE ,SCU.UNIT_BANKCODE 
FROM UNIT_ACCOUNT_DETAILS UAD, SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU
WHERE  UAD.UACD_BANK_CODE =SCU.UNIT_BANKCODE  GROUP BY UNIT_NO; 

--

SELECT UACD_BRANCH_CODE FROM UNIT_ACCOUNT_DETAILS;

SELECT UNIT_BRANCHCODE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_BRANCHCODE IS NOT NULL;

SELECT UAD.UACD_BRANCH_CODE ,SCU.UNIT_BRANCHCODE 
FROM UNIT_ACCOUNT_DETAILS UAD, SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU 
WHERE  UAD.UACD_BRANCH_CODE =SCU.UNIT_BRANCHCODE  GROUP BY UNIT_NO; 

--

SELECT UACD_BANK_ADDRESS FROM UNIT_ACCOUNT_DETAILS;

SELECT UNIT_BANKADDR FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_BANKADDR IS NOT NULL;

SELECT UAD.UACD_BANK_ADDRESS ,SCU.UNIT_BANKADDR 
FROM UNIT_ACCOUNT_DETAILS UAD , SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU
WHERE  UAD.UACD_BANK_ADDRESS =SCU.UNIT_BANKADDR GROUP BY UNIT_NO; 

SELECT * FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_BANKADDR ='UOB NORTH BRIDGE';
SELECT * FROM UNIT_ACCOUNT_DETAILS WHERE UACD_BANK_ADDRESS ='UOB NORTH BRIDGE';

SELECT DISTINCT UAD.*
FROM UNIT_ACCOUNT_DETAILS UAD
INNER JOIN UNIT U ON (UAD.UNIT_ID=U.UNIT_ID)
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU ON (U.UNIT_NO=SCU.UNIT_NO) -- AND (A.SE_SALARY_AMOUNT=C.EDSS_SALARY_AMOUNT)) OR ((A.SE_LEVY_AMOUNT=C.EDSS_LEVY_AMOUNT AND A.SE_CPF_AMOUNT=C.EDSS_CPF_AMOUNT) )

-- UNIT_ACCESS_STAMP_DETAILS --290

SELECT * FROM UNIT_ACCESS_STAMP_DETAILS;

SELECT U.UNIT_ID, USDT.USDT_ID, TUSF.UNIT_STAMPDUTYDATE, TUSF.UNIT_STAMPDUTYAMT, TUSF.UNIT_ACCESS_CARD,
TUSF.UNIT_ACCESS_ACTIVE, TUSF.UNIT_ACCESS_INVENTORY,TUSF.UNIT_ACCESS_LOST, URTD.URTD_ID,
TUSF.UNIT_COMMENTS,TUSF.USERSTAMP,TUSF.TIMESTAMP 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF 
LEFT JOIN UNIT U ON U.UNIT_NO=TUSF.UNIT_NO 
LEFT JOIN UNIT_ROOM_TYPE_DETAILS URTD ON URTD.URTD_ROOM_TYPE=TUSF.UNIT_ROOM_TYPE
LEFT JOIN UNIT_STAMP_DUTY_TYPE USDT ON USDT.USDT_DATA=TUSF.UNIT_STAMPDUTYTYPE 
WHERE TUSF.UNIT_ACCESS_CARD IS NOT NULL OR TUSF.UNIT_STAMPDUTYDATE IS NOT NULL OR TUSF.UNIT_STAMPDUTYTYPE IS NOT NULL 
OR TUSF.UNIT_STAMPDUTYAMT IS NOT NULL OR TUSF.UNIT_ROOM_TYPE IS NOT NULL OR TUSF.UNIT_COMMENTS IS NOT NULL;

--

SELECT DISTINCT UNIT_ACCESS_CARD FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ACCESS_CARD IS NOT NULL;

SELECT DISTINCT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD IS NOT NULL;

SELECT DISTINCT SCU.UNIT_ACCESS_CARD,UAS.UASD_ACCESS_CARD 
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU 
WHERE UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD;

-- 264=79+65+120

SELECT DISTINCT UNIT_ACCESS_CARD,UNIT_ACCESS_LOST,UNIT_ACCESS_ACTIVE,UNIT_ACCESS_INVENTORY 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ACCESS_CARD IS NOT NULL;

SELECT DISTINCT UASD_ACCESS_CARD,UASD_ACCESS_LOST,UASD_ACCESS_ACTIVE,UASD_ACCESS_INVENTORY
FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD IS NOT NULL;

SELECT U.UNIT_ACCESS_CARD,U.UNIT_ACCESS_LOST,UASD.UASD_ACCESS_CARD,UASD.UASD_ACCESS_LOST 
FROM  SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT U,UNIT_ACCESS_STAMP_DETAILS UASD 
WHERE U.UNIT_ACCESS_CARD=UASD.UASD_ACCESS_CARD AND U.UNIT_ACCESS_LOST=UASD.UASD_ACCESS_LOST AND U.UNIT_ACCESS_CARD IS NOT NULL;

SELECT U.UNIT_ACCESS_CARD,U.UNIT_ACCESS_ACTIVE,UASD.UASD_ACCESS_CARD,UASD.UASD_ACCESS_ACTIVE 
FROM  SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT U,UNIT_ACCESS_STAMP_DETAILS UASD 
WHERE U.UNIT_ACCESS_CARD=UASD.UASD_ACCESS_CARD AND U.UNIT_ACCESS_ACTIVE=UASD.UASD_ACCESS_ACTIVE AND U.UNIT_ACCESS_CARD IS NOT NULL;

SELECT U.UNIT_ACCESS_CARD,U.UNIT_ACCESS_INVENTORY,UASD.UASD_ACCESS_CARD,UASD.UASD_ACCESS_INVENTORY 
FROM  SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT U,UNIT_ACCESS_STAMP_DETAILS UASD 
WHERE U.UNIT_ACCESS_CARD=UASD.UASD_ACCESS_CARD AND U.UNIT_ACCESS_INVENTORY=UASD.UASD_ACCESS_INVENTORY AND U.UNIT_ACCESS_CARD IS NOT NULL ;

--

SELECT DISTINCT UNIT_STAMPDUTYDATE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_STAMPDUTYDATE IS NOT NULL;

SELECT DISTINCT UASD_STAMPDUTYDATE FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_STAMPDUTYDATE IS NOT NULL;

SELECT DISTINCT SCU.UNIT_STAMPDUTYDATE,UAS.UASD_STAMPDUTYDATE 
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU 
WHERE SCU.UNIT_STAMPDUTYDATE =UAS.UASD_STAMPDUTYDATE;

--

SELECT DISTINCT UNIT_STAMPDUTYAMT FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_STAMPDUTYAMT IS NOT NULL;

SELECT DISTINCT UASD_STAMPDUTYAMT FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_STAMPDUTYAMT IS NOT NULL;

SELECT DISTINCT SCU.UNIT_STAMPDUTYAMT,UAS.UASD_STAMPDUTYAMT
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU 
WHERE SCU.UNIT_STAMPDUTYAMT =UAS.UASD_STAMPDUTYAMT;

--

SELECT DISTINCT UNIT_COMMENTS FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_COMMENTS IS NOT NULL;

SELECT DISTINCT UASD_COMMENTS FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_COMMENTS IS NOT NULL;

SELECT DISTINCT SCU.UNIT_COMMENTS,UAS.UASD_COMMENTS 
FROM UNIT_ACCESS_STAMP_DETAILS UAS ,SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU
WHERE SCU.UNIT_COMMENTS =UAS.UASD_COMMENTS;

--

SELECT DISTINCT UNIT_ID FROM UNIT_ACCESS_STAMP_DETAILS;

SELECT DISTINCT UNIT_NO FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT;

SELECT U.UNIT_ID
FROM UNIT U 
WHERE NOT EXISTS     
(        
SELECT UAS.UNIT_ID
FROM UNIT_ACCESS_STAMP_DETAILS UAS 
WHERE U.UNIT_ID=UAS.UNIT_ID
);

SELECT DISTINCT(U.UNIT_NO),U1.UNIT_NO,U1.UNIT_ID,UAS.UNIT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT U , UNIT U1,UNIT_ACCESS_STAMP_DETAILS UAS 
WHERE U.UNIT_NO=U1.UNIT_NO AND U1.UNIT_ID = UAS.UNIT_ID ORDER BY U1.UNIT_NO;

SELECT SCU.UNIT_ACCESS_CARD,UAS.UASD_ACCESS_CARD,UAS.UNIT_ID , U.UNIT_ID,U.UNIT_NO, SCU.UNIT_NO
FROM UNIT_ACCESS_STAMP_DETAILS UAS
INNER JOIN UNIT U ON UAS.UNIT_ID = U.UNIT_ID
INNER JOIN SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU ON U.UNIT_NO= SCU.UNIT_NO AND UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD
WHERE SCU.UNIT_ACCESS_CARD IS NOT NULL AND UAS.UASD_ACCESS_CARD IS NOT NULL
GROUP BY UAS.UASD_ACCESS_CARD;

SELECT DISTINCT UAS.UASD_ID, UAS.UNIT_ID, UAS.UASD_STAMPDUTYAMT,UAS.UASD_STAMPDUTYDATE,UAS.UASD_ACCESS_CARD
FROM  UNIT_ACCESS_STAMP_DETAILS UAS,SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU,UNIT U
WHERE UAS.UNIT_ID=U.UNIT_ID OR SCU.UNIT_STAMPDUTYAMT =UAS.UASD_STAMPDUTYAMT OR 
SCU.UNIT_STAMPDUTYDATE =UAS.UASD_STAMPDUTYDATE OR UAS.UASD_ACCESS_CARD=SCU.UNIT_ACCESS_CARD;
 
--

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE URTD_ID IS NOT NULL ORDER BY UNIT_ID;

SELECT UNIT_NO,UNIT_ROOM_TYPE FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT WHERE UNIT_ROOM_TYPE IS NOT NULL ORDER BY UNIT_NO;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=422 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 3 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=518 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 4 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=618
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 5 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=718
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 6 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=1108
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 10 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=1118 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 11 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=1218 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 13 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=1410
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 14 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=1415
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 15 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=1915 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 17 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2018 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 18 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2118 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 19 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2218 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 21 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2317 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 22 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2318 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 23 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2718 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 25 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2818 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 26 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=2918 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 27 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3001 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 28 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3006 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 29 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3209
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 30 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3215 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 31 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3708
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 32 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3715 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 33 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3718
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 34 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3821
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 35 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3822
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 36 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=3906 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 37 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=4001 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 38 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=4101
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 39 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=5307
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 40 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=5410 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 42 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD 
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=5501
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 43 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,URTD.URTD_ROOM_TYPE,URTD.URTD_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD
WHERE S.UNIT_ROOM_TYPE IS NOT NULL AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_ROOM_TYPE=URTD.URTD_ROOM_TYPE AND S.UNIT_NO=5522 
ORDER BY URTD.URTD_ID;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 44 AND URTD_ID IS NOT NULL ORDER BY URTD_ID ;

SELECT DISTINCT(S.UNIT_ROOM_TYPE),S.UNIT_NO
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S
WHERE S.UNIT_NO=5618 AND S.UNIT_ROOM_TYPE IS NOT NULL;

SELECT UNIT_ID,URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 45 AND URTD_ID IS NOT NULL ORDER BY URTD_ID;

SELECT S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,S.UNIT_STAMPDUTYTYPE,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=216  ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 1 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=618 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 5 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=718 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 6 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=1118 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 11 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=1415 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 15 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2018 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 18 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2118 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 19 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2218 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 21 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2318 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 23 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2718 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 25 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2818 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 26 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=2918 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 27 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=3209 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 30 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=3215 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 31 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=3708 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 32 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=3715 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 33 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=3822 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 36 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=3906 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 37 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=5307 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 40 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=5501 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 43 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

SELECT DISTINCT(S.UNIT_STAMPDUTYTYPE),S.UNIT_NO,U.UNIT_NO,U.UNIT_ID,USDT.USDT_DATA,USDT.USDT_ID
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT S,UNIT U,UNIT_STAMP_DUTY_TYPE USDT WHERE S.UNIT_STAMPDUTYTYPE IS NOT NULL 
AND S.UNIT_NO=U.UNIT_NO AND S.UNIT_STAMPDUTYTYPE=USDT.USDT_DATA AND S.UNIT_NO=5618 ORDER BY USDT.USDT_ID;
SELECT UNIT_ID,USDT_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UNIT_ID = 45 AND USDT_ID IS NOT NULL ORDER BY USDT_ID;

--

SELECT DISTINCT UASD_TIMESTAMP FROM UNIT_ACCESS_STAMP_DETAILS;

SELECT DISTINCT TUSF.TIMESTAMP FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT TUSF 
WHERE TUSF.UNIT_ACCESS_CARD IS NOT NULL OR TUSF.UNIT_STAMPDUTYDATE IS NOT NULL OR TUSF.UNIT_STAMPDUTYTYPE IS NOT NULL OR
TUSF.UNIT_STAMPDUTYAMT IS NOT NULL OR TUSF.UNIT_ROOM_TYPE IS NOT NULL OR TUSF.UNIT_COMMENTS IS NOT NULL;

SELECT DISTINCT  UAS.UASD_TIMESTAMP,SUBTIME(SCU.`TIMESTAMP`,'08:00:00')
FROM UNIT_ACCESS_STAMP_DETAILS UAS , SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT SCU 
WHERE SUBTIME(SCU.`TIMESTAMP`,'08:00:00') =UAS.UASD_TIMESTAMP;

--

SELECT DISTINCT ULD_ID FROM UNIT_ACCESS_STAMP_DETAILS;

SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SCDB_SOURCE_17062014.UNIT_SCDB_FORMAT A 
INNER JOIN USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID 
INNER JOIN UNIT_ACCESS_STAMP_DETAILS C ON B.ULD_ID=C.ULD_ID;

