
-- BANK 

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS;

SELECT *FROM BANK_TRANSFER_MODELS;

-- BANK TRANSFER MODELS --34

-- SOURCE AND DESTINATION HAVE THE SPACE IN FRONT OF THIS DATA -- WENDY SALARY - 2800 BUT NOT ISSUE

SELECT  BTM_DATA FROM BANK_TRANSFER_MODELS;

SELECT  BTM_DATA FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS;

SELECT MBTM.BTM_DATA,BTM.BTM_DATA
FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS MBTM, BANK_TRANSFER_MODELS BTM 
WHERE MBTM.BTM_DATA=BTM.BTM_DATA;

--

SELECT  BTM_TIMESTAMP FROM BANK_TRANSFER_MODELS;

SELECT  BTM_TIMESTAMP FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS;

SELECT MBTM.BTM_TIMESTAMP,BTM.BTM_TIMESTAMP
FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS MBTM, BANK_TRANSFER_MODELS BTM
WHERE MBTM.BTM_DATA=BTM.BTM_DATA;

--

SELECT DISTINCT ULD_ID FROM BANK_TRANSFER_MODELS ORDER BY BTM_ID;

SELECT DISTINCT BTM_USERSTAMP FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS WHERE BTM_DATA IS NOT NULL;

SELECT DISTINCT A.BTM_USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS A
INNER JOIN USER_LOGIN_DETAILS B ON A.BTM_USERSTAMP= B.ULD_LOGINID
INNER JOIN BANK_TRANSFER_MODELS C ON B.ULD_ID=C.ULD_ID;

-- BANK TRANSFER 3 CUSTOMER ARE NOT PRESENTED -- 165

SELECT * FROM BANK_TRANSFER;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER ;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

SELECT * FROM BANK_TRANSFER 
WHERE BT_ACC_NAME IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- MATCHED

SELECT BTM.BTM_ID,BT.BT_DATE,BT.BT_AMOUNT,BT.BT_ACC_NAME, BT.BT_ACC_NO,BT.BT_BANK_CODE, BT.BT_BRANCH_CODE, BT.BT_BANK_ADDRESS,BT.BT_SWIFT_CODE,BT.BT_CUST_REF,BT.BT_INV_DETAILS,BT.BT_DEBITED_ON,BT.BT_COMMENTS, ULD.ULD_ID,BT.BT_TIME_STAMP
FROM SOURCE_17072014.MIG_BANK_TRANSFER BT
INNER JOIN USER_LOGIN_DETAILS ULD   
LEFT JOIN BANK_TRANSFER_MODELS BTM ON BT.BT_TRANSACTION_TYPE=BTM.BTM_ID
WHERE BT.BT_TRANSACTION_TYPE IS NOT NULL AND BT.BT_USER_STAMP=ULD.ULD_LOGINID GROUP BY BT.BT_SNO;

--

SELECT BT_DATE FROM BANK_TRANSFER;

SELECT BT_DATE FROM SOURCE_17072014.MIG_BANK_TRANSFER ;

SELECT MBT.BT_DATE,BT.BT_DATE 
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_DATE=BT.BT_DATE GROUP BY MBT.BT_SNO;

-- 3(RECORDS)-> 6300,7200,764 RECORDS ARE NOT AVAILABLE AND 152 RECORD PRESENT IN DESTIONATION SOURCE HAVE 155 RECORD

SELECT BT_AMOUNT FROM BANK_TRANSFER;

SELECT BT_AMOUNT FROM SOURCE_17072014.MIG_BANK_TRANSFER ;

SELECT MBT.BT_AMOUNT,BT.BT_AMOUNT
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_AMOUNT=BT.BT_AMOUNT GROUP BY MBT.BT_SNO;

SELECT MBT.BT_AMOUNT , BT.BT_AMOUNT 
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN  BANK_TRANSFER BT ON MBT.BT_AMOUNT = BT.BT_AMOUNT GROUP BY MBT.BT_SNO;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- 3(RECORDS)->MAUNG KHIN MAUNG WIN,RIN NAN YOONG,LEONG KIAN SHIANG RECORDS ARE NOT AVAILABLE AND 152 RECORD PRESENT IN DESTIONATION SOURCE HAVE 155 RECORD

SELECT BT_ACC_NAME FROM BANK_TRANSFER WHERE BT_ACC_NAME IS NOT NULL;

SELECT BT_ACC_NAME FROM SOURCE_17072014.MIG_BANK_TRANSFER WHERE BT_ACC_NAME IS NOT NULL;

SELECT MBT.BT_ACC_NAME ,BT.BT_ACC_NAME
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT  ,BANK_TRANSFER BT WHERE MBT.BT_ACC_NAME =BT.BT_ACC_NAME GROUP BY MBT.BT_SNO;

SELECT MBT.BT_ACC_NAME ,BT.BT_ACC_NAME
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN  BANK_TRANSFER BT ON MBT.BT_ACC_NAME =BT.BT_ACC_NAME
WHERE MBT.BT_ACC_NAME IS NOT NULL GROUP BY MBT.BT_SNO;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- 3723023260,18128223,247677895 ARE MISSED

SELECT BT_ACC_NO FROM BANK_TRANSFER WHERE BT_ACC_NO IS NOT NULL;

SELECT BT_ACC_NO FROM SOURCE_17072014.MIG_BANK_TRANSFER WHERE BT_ACC_NO IS NOT NULL;

SELECT MBT.BT_ACC_NO,BT.BT_ACC_NO
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_ACC_NO=BT.BT_ACC_NO GROUP BY MBT.BT_SNO;

SELECT MBT.BT_ACC_NO,BT.BT_ACC_NO
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN  BANK_TRANSFER BT ON MBT.BT_ACC_NO=BT.BT_ACC_NO 
WHERE MBT.BT_ACC_NO IS NOT NULL GROUP BY MBT.BT_SNO;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- ALL R MATCHED

SELECT DISTINCT BT_BANK_CODE FROM BANK_TRANSFER WHERE BT_BANK_CODE IS NOT NULL;

SELECT DISTINCT BT_BANK_CODE FROM SOURCE_17072014.MIG_BANK_TRANSFER WHERE BT_BANK_CODE IS NOT NULL;

SELECT DISTINCT MBT.BT_BANK_CODE ,BT.BT_BANK_CODE
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_BANK_CODE =BT.BT_BANK_CODE;

-- 046 IS DELETED IN THAT 3 RECORD

SELECT DISTINCT BT_BRANCH_CODE FROM BANK_TRANSFER WHERE BT_BRANCH_CODE IS NOT NULL;

SELECT DISTINCT BT_BRANCH_CODE FROM SOURCE_17072014.MIG_BANK_TRANSFER WHERE BT_BRANCH_CODE IS NOT NULL;

SELECT DISTINCT MBT.BT_BRANCH_CODE ,BT.BT_BRANCH_CODE
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_BRANCH_CODE =BT.BT_BRANCH_CODE;

SELECT DISTINCT MBT.BT_BRANCH_CODE ,BT.BT_BRANCH_CODE
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN BANK_TRANSFER BT ON MBT.BT_BRANCH_CODE =BT.BT_BRANCH_CODE;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- UOB Â€“ SINGAPORE AND 3 RECORD DELETED UOB BANK - COLEMAN STREET,DBS BANK LTD - DBS SHENTON WAY,DBS BANK LTD

SELECT DISTINCT BT_BANK_ADDRESS FROM BANK_TRANSFER WHERE BT_BANK_ADDRESS IS NOT NULL;

SELECT DISTINCT BT_BANK_ADDRESS FROM SOURCE_17072014.MIG_BANK_TRANSFER WHERE BT_BANK_ADDRESS IS NOT NULL;

SELECT DISTINCT MBT.BT_BANK_ADDRESS ,BT.BT_BANK_ADDRESS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_BANK_ADDRESS =BT.BT_BANK_ADDRESS;

SELECT DISTINCT MBT.BT_BANK_ADDRESS ,BT.BT_BANK_ADDRESS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN BANK_TRANSFER BT ON MBT.BT_BANK_ADDRESS =BT.BT_BANK_ADDRESS;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- MATCHED

SELECT DISTINCT BT_SWIFT_CODE FROM BANK_TRANSFER WHERE BT_SWIFT_CODE IS NOT NULL;

SELECT DISTINCT BT_SWIFT_CODE FROM SOURCE_17072014.MIG_BANK_TRANSFER  WHERE BT_SWIFT_CODE IS NOT NULL;

SELECT DISTINCT MBT.BT_SWIFT_CODE ,BT.BT_SWIFT_CODE
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_SWIFT_CODE =BT.BT_SWIFT_CODE;

-- 2 DELETED ITEM SAIL 0518 ,3708 STAMP DUTY

SELECT DISTINCT BT_CUST_REF FROM BANK_TRANSFER;

SELECT DISTINCT BT_CUST_REF FROM SOURCE_17072014.MIG_BANK_TRANSFER ;

SELECT DISTINCT MBT.BT_CUST_REF ,BT.BT_CUST_REF
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_CUST_REF =BT.BT_CUST_REF;

SELECT DISTINCT MBT.BT_CUST_REF ,BT.BT_CUST_REF
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN BANK_TRANSFER BT ON MBT.BT_CUST_REF =BT.BT_CUST_REF;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- 3 RCD DELETED ITEMS  0518 FEB RENT, SAIL 5522 FEB RENT + DEPO, REFUND OF STAMP DUTY 3708

SELECT DISTINCT BT_INV_DETAILS FROM BANK_TRANSFER  WHERE BT_INV_DETAILS IS NOT NULL;

SELECT DISTINCT BT_INV_DETAILS FROM SOURCE_17072014.MIG_BANK_TRANSFER WHERE BT_INV_DETAILS IS NOT NULL;

SELECT DISTINCT MBT.BT_INV_DETAILS ,BT.BT_INV_DETAILS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_INV_DETAILS =BT.BT_INV_DETAILS;

SELECT DISTINCT MBT.BT_INV_DETAILS ,BT.BT_INV_DETAILS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN BANK_TRANSFER BT ON MBT.BT_INV_DETAILS =BT.BT_INV_DETAILS;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- 1 DATE IS DELETED ITEM 08-02-2013 00:00:00

SELECT DISTINCT BT_DEBITED_ON FROM BANK_TRANSFER WHERE BT_DEBITED_ON IS NOT NULL;

SELECT DISTINCT BT_DEBITED_ON FROM SOURCE_17072014.MIG_BANK_TRANSFER   WHERE BT_DEBITED_ON IS NOT NULL;

SELECT DISTINCT MBT.BT_DEBITED_ON ,BT.BT_DEBITED_ON
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_DEBITED_ON =BT.BT_DEBITED_ON;

SELECT DISTINCT MBT.BT_DEBITED_ON ,BT.BT_DEBITED_ON
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN  BANK_TRANSFER BT ON MBT.BT_DEBITED_ON =BT.BT_DEBITED_ON;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- 5 CMT WRONG BY SPACE

SELECT DISTINCT BT_COMMENTS FROM BANK_TRANSFER  WHERE BT_COMMENTS IS NOT NULL;

SELECT DISTINCT BT_COMMENTS FROM SOURCE_17072014.MIG_BANK_TRANSFER  WHERE BT_COMMENTS IS NOT NULL; 

SELECT DISTINCT MBT.BT_COMMENTS ,BT.BT_COMMENTS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_COMMENTS =BT.BT_COMMENTS;

SELECT DISTINCT MBT.BT_COMMENTS ,BT.BT_COMMENTS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN BANK_TRANSFER BT ON MBT.BT_COMMENTS =BT.BT_COMMENTS;

SELECT DISTINCT MBT.BT_COMMENTS ,BT.BT_COMMENTS
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT RIGHT JOIN BANK_TRANSFER BT ON MBT.BT_COMMENTS =BT.BT_COMMENTS;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- 

SELECT DISTINCT ULD_ID FROM BANK_TRANSFER ;

SELECT DISTINCT BT_USER_STAMP FROM SOURCE_17072014.MIG_BANK_TRANSFER;

SELECT DISTINCT A.BTM_USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_17072014.MIG_BANK_TRANSFER_MODELS A
INNER JOIN USER_LOGIN_DETAILS B ON A.BTM_USERSTAMP= B.ULD_LOGINID
INNER JOIN BANK_TRANSFER_MODELS C ON B.ULD_ID=C.ULD_ID;

--

SELECT DISTINCT BT_TIMESTAMP FROM BANK_TRANSFER;

SELECT DISTINCT BT_TIME_STAMP FROM SOURCE_17072014.MIG_BANK_TRANSFER ;

SELECT DISTINCT MBT.BT_TIME_STAMP ,BT.BT_TIMESTAMP
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT, BANK_TRANSFER BT WHERE MBT.BT_TIME_STAMP =BT.BT_TIMESTAMP;

SELECT DISTINCT MBT.BT_TIME_STAMP ,BT.BT_TIMESTAMP
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT LEFT JOIN BANK_TRANSFER BT ON MBT.BT_TIME_STAMP =BT.BT_TIMESTAMP;

SELECT * FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IN('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

-- BANK TRANSFER DETAILS --144
-- PROBLEM IN UNIT 36-KARAN, UNIT 46-KLEINER ANDREAS, 19-THOMAS

SELECT*FROM BANK_TRANSFER_DETAIL;

SELECT BT.BT_SNO, U.UNIT_ID ,BT.BT_UNIT,CSF.CC_UNIT_NO,BT.BT_CUSTOMER,CSF.CC_CUST_ID
FROM SOURCE_17072014.MIG_BANK_TRANSFER BT
INNER JOIN SOURCE_17072014.CUSTOMER_SCDB_FORMAT CSF
INNER JOIN UNIT U ON  BT.BT_UNIT=U.UNIT_NO AND CSF.CC_UNIT_NO=U.UNIT_NO
WHERE (BT.BT_UNIT=CSF.CC_UNIT_NO AND BT.BT_CUSTOMER=CONCAT(CSF.CC_FIRST_NAME,' ', CSF.CC_LAST_NAME))
OR (BT.BT_UNIT=CSF.CC_UNIT_NO AND BT.BT_CUSTOMER=CSF.CC_FIRST_NAME AND CSF.CC_LAST_NAME IS NULL ) GROUP BY BT.BT_SNO;

-- SP FOR CUSTOMER NAME UPDATION FOR BANK TRANSFER DETAILS 

CALL SP_MIG_BANK_TRANSFER_CUSTOMER ('DEST_17072014','SOURCE_17072014');

SELECT*FROM TEMP_FINAL_CUSTOMER;

--

SELECT  BT_UNIT,BT_CUSTOMER,BT_SNO 
FROM SOURCE_17072014.MIG_BANK_TRANSFER 
WHERE BT_CUSTOMER IS NOT NULL AND BT_UNIT IS NOT NULL AND BT_CUSTOMER NOT IN ('LEONG KIAN SHIANG','RIN NAN YOONG','MAUNG KHIN MAUNG WIN');

SELECT UNIT_ID,CUST_ID,BT_SNO FROM TEMP_FINAL_CUSTOMER;

SELECT BTD.BT_ID,TFC.BT_SNO,BTD.UNIT_ID,TFC.UNIT_ID,BTD.CUSTOMER_ID,TFC.CUST_ID 
FROM BANK_TRANSFER_DETAIL BTD, TEMP_FINAL_CUSTOMER TFC 
WHERE BTD.UNIT_ID = TFC.UNIT_ID AND BTD.BT_ID=TFC.BT_SNO AND BTD.CUSTOMER_ID=TFC.CUST_ID;

SELECT BTD.BT_ID,TFC.BT_SNO,BTD.UNIT_ID,TFC.UNIT_ID,BTD.CUSTOMER_ID,TFC.CUST_ID 
FROM BANK_TRANSFER_DETAIL BTD LEFT JOIN TEMP_FINAL_CUSTOMER TFC ON BTD.UNIT_ID = TFC.UNIT_ID 
AND BTD.BT_ID=TFC.BT_SNO AND BTD.CUSTOMER_ID=TFC.CUST_ID;

SELECT BTD.BT_ID,TFC.BT_SNO,BTD.UNIT_ID,TFC.UNIT_ID,BTD.CUSTOMER_ID,TFC.CUST_ID 
FROM BANK_TRANSFER_DETAIL BTD RIGHT JOIN TEMP_FINAL_CUSTOMER TFC ON BTD.UNIT_ID = TFC.UNIT_ID 
AND BTD.BT_ID=TFC.BT_SNO AND BTD.CUSTOMER_ID=TFC.CUST_ID;

-- BANK TRANSFER STATUS DETAIL --479

SELECT * FROM BANK_TRANSFER_STATUS_DETAILS;

SELECT DISTINCT BT_ID FROM BANK_TRANSFER_DETAIL;

SELECT DISTINCT BT_ID FROM BANK_TRANSFER_STATUS_DETAILS;

SELECT AA.BT_ID , BT.BT_ID, BB.BT_ID
FROM BANK_TRANSFER_STATUS_DETAILS AA 
INNER JOIN BANK_TRANSFER BT ON AA.BT_ID = BT.BT_ID
INNER JOIN BANK_TRANSFER_DETAIL BB ON BB.BT_ID=AA.BT_ID GROUP BY BT.BT_ID;

--
DROP TABLE IF EXISTS CONF;
CREATE TABLE CONF(BTID INT, BCNID INT, CGNID INT);

INSERT INTO CONF(BTID,BCNID,CGNID)
(SELECT BT.BT_ID,BC.BCN_ID,BC.CGN_ID
FROM SOURCE_17072014.MIG_BANK_TRANSFER MBT
INNER JOIN SOURCE_17072014.MIG_BANK_TRANSFER_CREATED_BY BTCB ON MBT.BTCB_ID=BTCB.BTCB_ID
INNER JOIN SOURCE_17072014.MIG_BANK_TRANSFER_CHARGES_TO BTCT ON MBT.BTCT_ID=BTCT.BTCT_ID 
INNER JOIN SOURCE_17072014.MIG_BANK_TRANSFER_STATUS BTS ON MBT.BTS_ID = BTS.BTS_ID  
INNER JOIN SOURCE_17072014.MIG_BANK_TRANSFER_TYPE BTT ON MBT.BT_TRANSACTION_TYPE = BTT.BTT_DATA
INNER JOIN BANKTT_CONFIGURATION BC ON BTCB.BTCB_DATA=BC.BCN_DATA OR BTCT.BTCT_DATA=BC.BCN_DATA OR BTS.BTS_DATA=BC.BCN_DATA OR BTT.BTT_DATA=BC.BCN_DATA
INNER JOIN BANK_TRANSFER_STATUS_DETAILS BTSD ON BC.BCN_ID = BTSD.BCN_ID AND BC.CGN_ID = BTSD.CGN_ID
INNER JOIN BANK_TRANSFER BT ON BTSD.BT_ID = BT.BT_ID GROUP BY BTSD.BTSD_ID);
SELECT *FROM CONF;

SELECT AA.BT_ID,CNF.BTID,AA.BCN_ID,CNF.BCNID,AA.CGN_ID,CNF.CGNID
FROM BANK_TRANSFER_STATUS_DETAILS AA
INNER JOIN CONF CNF
WHERE AA.BT_ID=CNF.BTID AND AA.BCN_ID=CNF.BCNID AND AA.CGN_ID=CNF.CGNID;

-- ALL THE VALUE ARE MATCHED IN BANKTT_CONFIGURATION

SELECT * FROM BANKTT_CONFIGURATION;

SELECT * FROM CONFIGURATION;

SELECT DISTINCT CGN_ID FROM BANKTT_CONFIGURATION;

SELECT CGN_ID, DATA, INITIALIZE_FLAG, USER_STAMP,`TIMESTAMP`
FROM SOURCE_17072014.CONFIG_SQL_FORMAT
WHERE CGN_ID IN (56,69,70,71,72) AND DATA IS NOT NULL;

--

SELECT DISTINCT  BCN_TIMESTAMP FROM BANKTT_CONFIGURATION;

SELECT DISTINCT `TIMESTAMP`
FROM SOURCE_17072014.CONFIG_SQL_FORMAT 
WHERE CGN_ID IN (56,69,70,71,72) AND DATA IS NOT NULL;

SELECT DISTINCT CSF.`TIMESTAMP`, BC.BCN_TIMESTAMP
FROM SOURCE_17072014.CONFIG_SQL_FORMAT CSF , BANKTT_CONFIGURATION BC
WHERE CSF.`TIMESTAMP`= BC.BCN_TIMESTAMP AND CSF.CGN_ID IN (56,69,70,71,72) AND CSF.DATA IS NOT NULL;

-- 

SELECT DISTINCT ULD_ID FROM BANKTT_CONFIGURATION ;

SELECT DISTINCT USER_STAMP FROM SOURCE_17072014.CONFIG_SQL_FORMAT WHERE USER_STAMP IS NOT NULL;

SELECT DISTINCT A.USER_STAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID 
FROM SOURCE_17072014.CONFIG_SQL_FORMAT A
INNER JOIN USER_LOGIN_DETAILS B ON A.USER_STAMP= B.ULD_LOGINID
INNER JOIN BANKTT_CONFIGURATION C ON B.ULD_ID=C.ULD_ID
WHERE A.CGN_ID IN (56,69,70,71,72) AND A.DATA IS NOT NULL;

--

SELECT * FROM SOURCE_17072014.CONFIG_SQL_FORMAT WHERE CGN_ID=56 AND DATA IS NOT NULL;

SELECT * FROM SOURCE_17072014.CONFIG_SQL_FORMAT WHERE CGN_ID=69 AND DATA IS NOT NULL;

SELECT * FROM SOURCE_17072014.CONFIG_SQL_FORMAT WHERE CGN_ID=70 AND DATA IS NOT NULL;

SELECT * FROM SOURCE_17072014.CONFIG_SQL_FORMAT WHERE CGN_ID=71 AND DATA IS NOT NULL;

SELECT * FROM SOURCE_17072014.CONFIG_SQL_FORMAT WHERE CGN_ID=72 AND DATA IS NOT NULL;

