
-- CUSTOMER

SELECT * FROM SOURCE_28062014.CUSTOMER_SCDB_FORMAT;

-- CUSTOMER_ACCESS_CARD_DETAILS

SELECT * FROM CUSTOMER_ACCESS_CARD_DETAILS;

SELECT DISTINCT CC_FIRST_NAME,CC_LAST_NAME FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT;

SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_ACCESS_CARD_DETAILS;

SELECT DISTINCT CACD.CUSTOMER_ID
FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF
INNER JOIN CUSTOMER C ON (CSF.CC_FIRST_NAME=C.CUSTOMER_FIRST_NAME ) AND CSF.CC_LAST_NAME=C.CUSTOMER_LAST_NAME
INNER JOIN CUSTOMER_ACCESS_CARD_DETAILS CACD ON C.CUSTOMER_ID = CACD.CUSTOMER_ID;

SELECT DISTINCT CSF.CC_CUST_ID,CACD.CUSTOMER_ID
FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_ACCESS_CARD_DETAILS CACD 
WHERE CSF.CC_CUST_ID=CACD.CUSTOMER_ID ;

SELECT DISTINCT AC_CARD FROM SOURCE_11062014.ACCESS_SCDB_FORMAT;

SELECT DISTINCT CSF.CC_CUST_ID FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

SELECT DISTINCT CACD.CUSTOMER_ID FROM CUSTOMER_ACCESS_CARD_DETAILS CACD;

SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER;

SELECT DISTINCT CSF.CC_CUST_ID,CACD.CUSTOMER_ID 
FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_ACCESS_CARD_DETAILS CACD 
WHERE CSF.CC_CUST_ID=CACD.CUSTOMER_ID;

SELECT DISTINCT CSF.TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

SELECT DISTINCT CACD.CACD_TIMESTAMP FROM CUSTOMER_ACCESS_CARD_DETAILS CACD;

SELECT DISTINCT ASF.TIMESTAMP,CACD.CACD_TIMESTAMP FROM SOURCE_11062014.ACCESS_SCDB_FORMAT ASF,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE ASF.TIMESTAMP=CACD.CACD_TIMESTAMP;

SELECT DISTINCT CSF.TIMESTAMP,CACD.CACD_TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE  CSF.TIMESTAMP!=CACD.CACD_TIMESTAMP;

SELECT * FROM SOURCE_11062014.ACCESS_SCDB_FORMAT;

SELECT * FROM CUSTOMER_ACCESS_CARD_DETAILS;

SELECT * FROM CUSTOMER;

SELECT DISTINCT AC_FIRST_NAME FROM SOURCE_11062014.ACCESS_SCDB_FORMAT;

SELECT DISTINCT CUSTOMER_FIRST_NAME FROM CUSTOMER;

SELECT DISTINCT C.CUSTOMER_ID,CACD.CUSTOMER_ID FROM CUSTOMER C,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE C.CUSTOMER_ID=CACD.CUSTOMER_ID

SELECT AC_VALID_TILL FROM SOURCE_11062014.ACCESS_SCDB_FORMAT WHERE AC_VALID_TILL IS NOT NULL;

SELECT CACD_VALID_TILL FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CACD_VALID_TILL IS NOT NULL;

SELECT DISTINCT ASF.AC_VALID_TILL,CACD.CACD_VALID_TILL FROM SOURCE_11062014.ACCESS_SCDB_FORMAT ASF,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE ASF.AC_VALID_TILL=CACD.CACD_VALID_TILL

-- CUSTOMER_COMPANY_DETAILS

SELECT DISTINCT CSF.CC_CUST_ID FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF WHERE CSF.CC_COMPANY_NAME IS NOT NULL;

SELECT DISTINCT CCD.CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS CCD WHERE CCD.CCD_COMPANY_NAME IS NOT NULL;

SELECT DISTINCT  CSF.CC_COMPANY_NAME FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

SELECT DISTINCT CCD.CCD_COMPANY_NAME  FROM CUSTOMER_COMPANY_DETAILS CCD;

SELECT DISTINCT CSF.CC_COMPANY_NAME,CCD.CCD_COMPANY_NAME FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_COMPANY_DETAILS CCD WHERE CSF.CC_COMPANY_NAME=CCD.CCD_COMPANY_NAME

SELECT DISTINCT CSF.CC_COMPANY_ADDR FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF

SELECT DISTINCT CCD.CCD_COMPANY_ADDR FROM CUSTOMER_COMPANY_DETAILS CCD

SELECT DISTINCT CSF.CC_COMPANY_ADDR,CCD.CCD_COMPANY_ADDR FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_COMPANY_DETAILS CCD WHERE CSF.CC_COMPANY_ADDR=CCD.CCD_COMPANY_ADDR;

-- CUSTOMER_ENTRY_DETAILS

SELECT DISTINCT CSF.CC_REC_VER FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

SELECT DISTINCT CED.CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS CED;

SELECT DISTINCT CSF.CC_REC_VER,CED.CED_REC_VER FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_ENTRY_DETAILS CED WHERE CSF.CC_REC_VER=CED.CED_REC_VER

SELECT  CSF.CC_PRETERMINATE FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF WHERE CSF.CC_PRETERMINATE IS NOT NULL

SELECT CED.CED_PRETERMINATE FROM CUSTOMER_ENTRY_DETAILS CED WHERE CED.CED_PRETERMINATE IS NOT NULL

SELECT  CSF.CC_PRETERMINATE,CED.CED_PRETERMINATE FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_ENTRY_DETAILS CED WHERE CSF.CC_PRETERMINATE=CED.CED_PRETERMINATE

-- CUSTOMER_FEE_DETAILS

SELECT DISTINCT CSF.CC_REC_VER FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF

SELECT DISTINCT CFD.CED_REC_VER FROM CUSTOMER_FEE_DETAILS CFD ;

SELECT DISTINCT CSF.CC_REC_VER, CFD.CED_REC_VER FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_FEE_DETAILS CFD WHERE  CSF.CC_REC_VER= CFD.CED_REC_VER

-- CUSTOMER PAYMENT PROFILE

SELECT DISTINCT CPP.CPP_TIMESTAMP FROM CUSTOMER_PAYMENT_PROFILE CPP;

SELECT DISTINCT CSF.TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF

SELECT DISTINCT CSF.TIMESTAMP,CPP.CPP_TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_PAYMENT_PROFILE CPP WHERE CSF.TIMESTAMP=CPP.CPP_TIMESTAMP

-- CUSTOMER_PERSONAL_DETAILS

SELECT DISTINCT CSF.CC_CUST_ID,CSF.CC_EMAIL  FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF WHERE CSF.CC_EMAIL IS NOT NULL;

SELECT DISTINCT CPD.CUSTOMER_ID,CPD.CPD_EMAIL FROM CUSTOMER_PERSONAL_DETAILS CPD

-- CUSTOMER _TERMINATION_DETAILS

SELECT DISTINCT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS;

SELECT DISTINCT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS;

SELECT DISTINCT CTD.CLP_ENDDATE,CSF.CC_ENDDATE FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_LP_DETAILS CTD WHERE CSF.CC_ENDDATE=CTD.CLP_ENDDATE;

SELECT DISTINCT CUSTOMER_ID,CLP_STARTDATE,CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CLP_STARTDATE=CLP_ENDDATE;

SELECT DISTINCT CSF.CC_STARTDATE FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

SELECT DISTINCT CSF.CC_ENDDATE FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

-- CUSTOMER_CONFIGURATION

SELECT DISTINCT CCN_TIMESTAMP FROM CUSTOMER_CONFIGURATION;

SELECT DISTINCT CSF.TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF;

SELECT DISTINCT CCN.CCN_TIMESTAMP,CSF.TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_CONFIGURATION CCN WHERE CCN.CCN_TIMESTAMP=CSF.TIMESTAMP

SELECT DISTINCT CSF.CC_REC_VER,CED.CED_REC_VER FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT CSF, CUSTOMER_ENTRY_DETAILS CED WHERE CSF.CC_REC_VER=CED.CED_REC_VER

-- CHECKING CUSTOMER _SCDB_FORMAT AND CUSTOMER_PAYMENT_PROFILE HERE CUSTOMER PAYMENT PROFILE NOT MATCHING ANY DATA

SELECT DISTINCT SCF.`TIMESTAMP`,CPP.CPP_TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT SCF, CUSTOMER_PAYMENT_PROFILE CPP WHERE SCF.`TIMESTAMP`=CPP.CPP_TIMESTAMP

-- CHK FOR THE CUSTOMER SCDB FORMAT WITH CUSTOMER FEE DETAIL (ONLY 12 RECORDS ARE SAME IN BOTH RECORD)

SELECT DISTINCT SCF.CC_REC_VER, CFD.CED_REC_VER FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT SCF, CUSTOMER_FEE_DETAILS CFD WHERE SCF.CC_REC_VER=CFD.CED_REC_VER

SELECT DISTINCT CACD_TIMESTAMP FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE  CACD_TIMESTAMP IS NOT NULL

-- ONLY  37 RECORD MATCHING IN SOURCE TABLE 127 NOT MATCHING IN DESTINATION TABLE 

SELECT DISTINCT  SCF.`TIMESTAMP`,ACD.CACD_TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT SCF, CUSTOMER_ACCESS_CARD_DETAILS ACD WHERE SCF.`TIMESTAMP`=ACD.CACD_TIMESTAMP

-- TO CHECK CUSTOMER_TERMINATION_DETAIL AND CUSTOMER_SCDB STARTDATE AND ENDDATE AND RECVER AND TIMESTAMP.

SELECT DISTINCT SCF.CC_STARTDATE , CTD.CTD_STARTDATE , SCF.CC_ENDDATE,CTD.CTD_ENDDATE , SCF.CC_REC_VER,CTD.CED_REC_VER , SCF.`TIMESTAMP`,CTD.CTD_TIMESTAMP FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT SCF, CUSTOMER_TERMINATION_DETAILS CTD WHERE SCF.CC_STARTDATE = CTD.CTD_STARTDATE AND SCF.CC_ENDDATE=CTD.CTD_ENDDATE AND SCF.CC_REC_VER=CTD.CED_REC_VER AND SCF.`TIMESTAMP`=CTD.CTD_TIMESTAMP

-- CUSTOMER_TIME _PROFILE THERE IS NO DATA IN TABLE

SELECT DISTINCT C.CUSTOMER_ID , SCF.CC_FIRST_NAME, C.CUSTOMER_FIRST_NAME FROM SOURCE_11062014.CUSTOMER_SCDB_FORMAT SCF, CUSTOMER C WHERE SCF.CC_FIRST_NAME= C.CUSTOMER_FIRST_NAME ORDER BY C.CUSTOMER_ID 

-- PAYMENT

-- 1.CHECK A RENTAL_SCDB_FORMAT AND PAYMENT_CONFIGURATION 

-- NOT MATCHING ANY DATA IN BOTH TABLES

SELECT  RF.TIMESTAMP, PC.PCN_TIMESTAMP FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RF, PAYMENT_CONFIGURATION PC WHERE RF.`TIMESTAMP`= PC.PCN_TIMESTAMP

-- HERE WE CHECK A PAYMENT DETAIL AND RENTAL_SCDB_FORMAT MATCHING EACH DATA IN BOTH TABLE

SELECT DISTINCT RF.RENTAL_AMOUNT,PD.PD_AMOUNT , RF.RENTAL_PAID_DATE,PD.PD_PAID_DATE FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RF, PAYMENT_DETAILS PD WHERE RF.RENTAL_AMOUNT=PD.PD_AMOUNT AND RF.RENTAL_PAID_DATE=PD.PD_PAID_DATE

SELECT * FROM PAYMENT_PROFILE

SELECT * FROM CUSTOMER

SELECT * FROM PAYMENT_DETAILS

SELECT * FROM SOURCE_11062014.RENTAL_SCDB_FORMAT;

-- PAYMENT CONFIGURATION

SELECT RSF.TIMESTAMP,PCN.PCN_TIMESTAMP FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RSF,PAYMENT_CONFIGURATION PCN WHERE RSF.TIMESTAMP=PCN.PCN_TIMESTAMP;

-- PAYMENT_DETAILS

SELECT DISTINCT CED_REC_VER FROM PAYMENT_DETAILS

SELECT DISTINCT CTD.CED_REC_VER,PD.CED_REC_VER FROM CUSTOMER_LP_DETAILS CTD, PAYMENT_DETAILS PD WHERE CTD.CED_REC_VER=PD.CED_REC_VER

SELECT DISTINCT PD.PD_TIMESTAMP FROM PAYMENT_DETAILS PD;

SELECT DISTINCT RSF.TIMESTAMP FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RSF;

SELECT DISTINCT PD.PD_TIMESTAMP,RSF.TIMESTAMP FROM PAYMENT_DETAILS PD,SOURCE_11062014.RENTAL_SCDB_FORMAT RSF WHERE PD.PD_TIMESTAMP=RSF.TIMESTAMP

SELECT DISTINCT PD.PD_AMOUNT FROM PAYMENT_DETAILS PD;

SELECT DISTINCT RSF.RENTAL_AMOUNT FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RSF WHERE RSF.RENTAL_AMOUNT IS NOT NULL;

SELECT DISTINCT PD.PD_AMOUNT,RSF.RENTAL_AMOUNT FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RSF,PAYMENT_DETAILS PD WHERE PD.PD_AMOUNT=RSF.RENTAL_AMOUNT

SELECT DISTINCT RSF.RENTAL_PAID_DATE FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RSF

SELECT DISTINCT PD.PD_PAID_DATE FROM PAYMENT_DETAILS PD

SELECT DISTINCT RSF.RENTAL_PAID_DATE,PD.PD_PAID_DATE FROM SOURCE_11062014.RENTAL_SCDB_FORMAT RSF,PAYMENT_DETAILS PD WHERE  RSF.RENTAL_PAID_DATE=PD.PD_PAID_DATE
