SELECT * FROM SASI_SOURCE_SCHEMA.CUSTOMER_SCDB_FORMAT

SELECT DISTINCT CC_COMPANY_ADDR FROM CUSTOMER_SCDB_FORMAT WHERE CC_COMPANY_ADDR IS NOT NULL

SELECT DISTINCT CC_LEASE_PERIOD FROM CUSTOMER_SCDB_FORMAT WHERE CC_LEASE_PERIOD IS NOT NULL 

SELECT DISTINCT CC_RENT_AMOUNT FROM CUSTOMER_SCDB_FORMAT WHERE CC_RENT_AMOUNT IS NOT NULL 

SELECT *FROM BIZ_DETAIL_SCDB_FORMAT

SELECT DISTINCT EXPD_STAR_HUB_ACCOUNT_NO FROM BIZ_DETAIL_SCDB_FORMAT

SELECT DISTINCT SED_SALARY_AMOUNT FROM STAFF_DETAIL_SCDB_FORMAT

SELECT DISTINCT `TIMESTAMP` FROM BIZ_DETAIL_SCDB_FORMAT

SELECT * FROM UNIT_SCDB_FORMAT

SELECT DISTINCT UNIT_START_DATE FROM UNIT_SCDB_FORMAT

SELECT DISTINCT UNIT_WEBPWD FROM UNIT_SCDB_FORMAT WHERE UNIT_WEBPWD IS NOT NULL 

SELECT DISTINCT UNIT_ACCESS_CARD FROM UNIT_SCDB_FORMAT WHERE UNIT_ACCESS_CARD IS NOT NULL 

SELECT DISTINCT UNIT_ACC_NO FROM UNIT_SCDB_FORMAT

SELECT* FROM STAFF_DAILY_SCDB_FORMAT

SELECT * FROM STAFF_DAILY_SCDB_FORMAT

SELECT DISTINCT SE_AGENT_COMM_AMOUNT SE_STAFF_INVOICE_AMOUNT FROM STAFF_DAILY_SCDB_FORMAT WHERE SE_STAFF_INVOICE_AMOUNT IS NOT NULL

SELECT DISTINCT SE_AGENT_COMM_AMOUNT  FROM STAFF_DAILY_SCDB_FORMAT WHERE SE_AGENT_COMM_AMOUNT IS NOT NULL

SELECT DISTINCT PE_PERSONAL_INVOICE_DATE,PE_PERSONAL_INVOICE_ITEMS FROM PERSONAL_SCDB_FORMAT WHERE PE_PERSONAL_INVOICE_DATE IS NOT NULL AND PE_PERSONAL_INVOICE_ITEMS IS NOT NULL

SELECT *FROM RENTAL_SCDB_FORMAT

SELECT DISTINCT RENTAL_AMOUNT,RENTAL_PAID_DATE FROM RENTAL_SCDB_FORMAT  



