USE source_raja;

insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (1,1,'CONFIGURATION_PROFILE',4);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (2,1,'CONFIGURATION',6);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (3,1,'ERROR_MESSAGE_CONFIGURATION',63);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (4,1,'USER_RIGHTS_CONFIGURATION',3);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (5,1,'REPORT_CONFIGURATION',9);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (6,1,'ATTENDANCE_CONFIGURATION',14);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (7,1,'TICKLER_PROFILE',2);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (8,1,'TICKLER_TABID_PROFILE',21);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (9,2,'MENU_PROFILE',13);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (10,2,'ROLE_CREATION',3);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (11,2,'USER_LOGIN_DETAILS',43);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (12,2,'USER_ACCESS',43);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (13,2,'USER_MENU_DETAILS',28);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (14,2,'PUBLIC_HOLIDAY',17);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (15,3,'USER_ADMIN_REPORT_DETAILS',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (16,3,'ADMIN_WEEKLY_REPORT_DETAILS',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (17,3,'ONDUTY_ENTRY_DETAILS',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (18,3,'EMPLOYEE_DETAILS',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (19,3,'COMPANY_PROPERTIES_DETAILS',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (20,3,'PROJECT_DETAILS',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (21,2,'BASIC_ROLE_PROFILE',null);
insert into `pre_audit_sub_profile`(`PREASP_ID`,`PREAMP_ID`,`PREASP_DATA`,`PREASP_NO_OF_REC`) values (22,2,'BASIC_MENU_PROFILE',null);
