USE source_raja;

insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:15:24','dhandapani.sattanathan@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'1','Admin','2012-07-02',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:29:37','srinivasan.gopal@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-07-31','4','User','2012-05-23','Hike salary ',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:30:50','thamizh.sindu@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-07-21','6','User','2012-06-04','Higher Education',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-07-05 18:39:12','loganathan.annamalai@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-06-21','33','User','2013-02-04','FAMILY ISSUE',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:30:06','suresh.k@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-07-31','14','User','2012-07-23','Need guide in the PHP',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-09-18 13:52:57','bhuvaneswari.p@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-09-17','9','User','2012-07-02','WENT TO HIGHER STUDY.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 20:45:00','sarathbabou.somaya@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'2','SPCLAdmin','2012-05-23',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:28:11','nandhini.k@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-08-14','18','User','2012-08-09','Higher Education',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-12-03 08:37:39','pradab.v@ssomens.com','dhandapani.sattanathan@ssomens.com','2','X','2013-11-30','38','User','2013-07-04','GOT JOB ',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-04-09 12:57:30','pradab.v@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-04-02','10','User','2012-07-04','HE TOLD SOME PERSONAL PROBLEM,IT MAY BE FAKE.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-07-30 18:22:08','saradambal.munusamy@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'36','User','2013-07-23',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-07-30 18:20:09','dhivya.arjunan@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'35','User','2013-07-17',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-05-25 14:46:56','gopikrishnan.shankaran@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-05-18','21','User','2012-09-14','GOT ANOTHER JOB',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-04-01 18:08:02','bhavani.rajagopal@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'41','User','2014-02-10',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-07-21 12:53:33','santhi.palanisamy@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2014-07-16','42','User','2014-04-03','FAULT OF REGULAR DUTIES',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-12-01 15:23:02','sudhagar.sundaramoorthy@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-12-01','26','User','2012-11-19','Difficult to understand script, Our guys helped more.But he did not give any output.He doesnot know basics.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-02-14 22:08:13','chockalingam.r@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2014-02-14','12','User','2012-07-11','Performance very poor.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 20:50:36','viswanath.n@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'11','User','2012-07-04',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-09-03 19:10:05','manikandan.arumugam@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-09-03','30','User','2013-01-18','He got offer from some company',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-07-14 18:05:14','thamizh.sindu@ssomens.com','dhandapani.sattanathan@ssomens.com','2',null,null,'43','User','2014-07-13',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-04-01 15:33:26','pratibha.nadarajan@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-03-31','32','User','2013-01-24','Marriage fixed',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-02-07 22:16:36','elango.sanmugaraj@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2014-02-07','25','User','2012-11-05','GOT ANOTHER JOB',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-01-03 18:43:37','m.premkumar@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-12-23','34','User','2013-07-08','WILL START OWN BUSINESS',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:27:32','kamalam.sampath@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-08-28','17','User','2012-08-09','She got job in chenai,i think her friend hema not willing to work here So, hema took kamalam',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-12-28 19:07:00','safiyullah.mohideen@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'29','User','2012-12-24',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-07-30 18:23:45','lalitha.rajendiran@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'37','User','2013-07-19',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2014-03-06 08:46:46','manikandan.s@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2014-02-24','40','User','2014-01-05','GOT JOB! BUT FAKE REASON TOLD',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-12-13 11:30:06','dinesh.kumar@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-12-11','39','User','2013-11-06','NO INFORMATION',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-09-16 21:01:05','logasundari.moganadasse@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2013-09-14','31','User','2013-01-24','WENT TO HIGHER STUDIES',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:33:02','prabakaran.subramaniyan@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-10-10','22','User','2012-10-08','he hasn''t like the work environment n got job in chennai',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-12-29 12:34:33','sathiamoorthy.muthu@ssomens.com','sarathbabou.somaya@ssomens.com','1','X','2012-12-08','28','User','2012-11-26','He got another job',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:31:48','marimuthu.r@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-07-25','3','User','2012-05-23','He hasn''t  interested in web site creation .',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-11-23 18:46:14','suresh.madhappan@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-11-23','24','User','2012-10-29','We gave time to learn more than 20 days but he did not prove himself.
',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:24:03','duraimurugan.veloumourougane@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-08-24','15','User','2012-08-09','Past one year he worked in 4 company.So he hasn''t stable mind.
',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:34:41','shameer.viyas@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-10-22','23','User','2012-10-10','Difficult to understand validation, need more time to finish his task, n he did not like the ssomens rules',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 20:48:54','kumar.r@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'8','User','2012-06-19',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:09:40','boopathy.v@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-07-05','5','User','2012-05-29','I don''t know the reason, but he has liked easy task,
without pressure frm lead',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-12-01 15:25:20','sundaravadivel.shanmugam@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-12-01','27','User','2012-11-23','He did Java course. But he did not prove himself.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2013-01-04 17:42:06','bavidha.jayaraman@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-12-31','7','User','2012-06-05','1.performance not good , so management reduce the salary. She need previous month salary n hike.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 20:51:44','rajalakshmi.r@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'13','User','2012-07-16',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:26:52','hema.kovarthanan@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-08-28','16','User','2012-08-09','She hasn''t know how to handle the pressure frm lead, 
She has interested to work in Java n not in web design.',null,null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:17:54','punitha.shanmugam@ssomens.com','dhandapani.sattanathan@ssomens.com','1',null,null,'19','User','2012-08-31',null,'X',null,null,null);
insert into `userrights_scdb_format`(`siloId`,`timeStamp`,`Uname`,`userStamp`,`URecVer`,`UTerminate`,`UEDate`,`Rid`,`roles`,`UJDate`,`UReason`,`UJoin`,`Udate`,`Ureport`,`Uid`) values ('role','2012-10-24 21:20:02','arulkumar.alagappan@ssomens.com','dhandapani.sattanathan@ssomens.com','1','X','2012-09-06','20','User','2012-09-04','He has expected to work in Java, GAS was difficult to learn for him',null,null,null,null);
